### ISSUE TITLE
`update()` a model fit with `glmmTMB::fitTMB()`

### ISSUE THREAD

**Issue by grcatlin** [glmmTMB/glmmTMB#1003]
Hi there, I'm working a project that requires some manual manipulation of the TMBStruc. It seems that `update()` does not work as I would expect on a model object output by `fitTMB()`.

```r
# don't fit
TMBStruc <- glmmTMB(
    count ~
        mined +
        (1 | site),
    family = poisson,
    data = Salamanders,
    doFit = FALSE
)

# assume making some edits here...

# when ready
fit <- glmmTMB::fitTMB(TMBStruc = TMBStruc)

# update w/ new data
fit_k <- update(fit, data = Salamanders[1:500, ])
```

Yet, `fit_k` is just a list and doesn't seem to run anything. However if I:

```r
fit_k_expected <- update(fit, data = Salamanders[1:500, ], doFit = TRUE)
```

it produces the expected result. Alternatively, the below seems to work which bypasses `fitTMB` entirely:

```r
# however, this also (I think) works
fit_2 <- update(TMBStruc, doFit = TRUE)

# update w/ new data
fit_k_2 <- update(fit_2, data = Salamanders[1:500, ])
```

```r
> all.equal(fit_k_expected, fit_k_2)
[1] TRUE
```

Is this behavior expected? I would've thought that running `fitTMB` would set `doFit = TRUE` in the model object.

**Comment by bbolker** [comment]
I'll take a look. `update()` is in pretty naive, it just looks at the stored `call` object. If we thought it made sense we could manipulate the call after capturing it with `match.call()` ...

**Comment by bbolker** [comment]
It would be easy enough to add `fit$call$doFit <- TRUE` somewhere in `fitTMB`, presumably right at the end ([here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L1695) ?)  I don't know if this would have any potential unintended consequences?

**Comment by grcatlin** [comment]
That's what I was thinking - though I'm not sure if it would affect any tests in place. It may affect [here](https://github.com/glmmTMB/glmmTMB/blob/38ef467de3c9898fa04b48cf3341797e3600d62c/glmmTMB/R/utils.R#L648) perhaps?

**Comment by grcatlin** [comment]
Actually I'm not so sure that would solve it. I didn't know about specifying the `map` and `start` arguments in `glmmTMB()` which is all I needed to change. Originally I was using the above method where `doFit = FALSE` but just found examples of using map and start arguments [here](https://github.com/jfieberg/ISEC_HSF_Workshop/blob/main/CodedExamples/Otters_SSF.r). In order to have `fitTMB()` do what I was hoping to achieve, it seems it would also need to edit the `call$start` and `call$map` (for my intended use):

```r
# get struct
str <- glmmTMB::glmmTMB(
    case ~ dist +
        log(dist) +
        DEM_30m_target +
        (1 | strata) +
        (0 + DEM_30m_target | id),
    family = poisson,
    data = dat,
    doFit = FALSE
)

# make edits to struct
str$parameters$theta[1] <- log(1e3)
str$mapArg <- list(theta = factor(c(NA, 1)))

# fit and get varcorr
x <- glmmTMB::fitTMB(str)
xv <- glmmTMB::VarCorr(x)

# update to doFit = TRUE, get VarCorr
x$call$doFit <- TRUE
y <- update(x, data = dat)
yv <- glmmTMB::VarCorr(y)

# edit again to include start, map
x$call$start <- list(theta = c(log(1e3), rep(0, 1)))
x$call$map <- list(theta = factor(c(NA, 1:1)))

# run again
z <- update(x, data = dat)
zv <- glmmTMB::VarCorr(z)

# check
isTRUE(all.equal(xv, yv))
isTRUE(all.equal(xv, zv))
```

```r
> isTRUE(all.equal(xv, yv))
[1] FALSE
```

```r
> isTRUE(all.equal(xv, zv))
[1] TRUE
```

Anyway, now that I know I can just do it all in one go, I suppose the point is moot. This will `update()` as expected just fine:

```r
# run model
fit <- glmmTMB::glmmTMB(
    case ~ dist +
        log(dist) +
        DEM_30m_target +
        (1 | strata) +
        (0 + DEM_30m_target | id),
    family = poisson,
    data = dat,
    start = list(theta = c(log(1e3), rep(0, 1))), 
    map = list(theta = factor(c(NA, 1:1)))
)
```

I will go ahead and close the issue since the above is a simpler approach. I really appreciate you looking into this though and all your work in general!
