### ISSUE TITLE
Feature request: Add range parameter for `beta` model

### ISSUE THREAD

**Issue by roaldarbol** [glmmTMB/glmmTMB#1035]
First of all, thanks for maintaining this great package! Hope this request makes sense - if not, feel free to close.

Currently, the data I fit beta models to is *not* between 0 and 1, so I need to transform it in order to fit a beta model, and then back-transform it afterwards to get the outcome in the original scale. 

Could it be possible to add a parameter to apply alternative range with min/max values for a beta model, and then have the results reported on the original scale? (e.g.  `range: c(min,max)` with `c(0,1)` as default). My understanding that the important feature of beta models is that they are bounded - of course the [0,1] is needed for the computations, but I'm not sure the user needs to meet this requirement, and having the transformation happen implicitly could be quite useful.

**Comment by bbolker** [comment]
I'm not completely convinced that this is worth the additional complexity. If you define a scaling function, e.g. `myscale <- function(x, min = 0, max = 100) (x-min)/(max-min)`, then you should be able to use `myscale(p) ~ ...` in your formula, e.g.:

```r
myscale <- function(x, min = 0, max = 100) (x-min)/(max-min)
set.seed(101)
dd <- data.frame(x = 100*rbeta(100, shape1 = 2, shape2 = 3))
library(glmmTMB)
glmmTMB(myscale(x) ~ 1, data = dd, family = beta_family)
```

**Comment by bbolker** [comment]
I'm going to close this, feel free to re-open if you want to pursue this further.

**Comment by roaldarbol** [comment]
Just remembered about this issue! Yeah no worries - I completely get that it's worth prioritising efforts. Thanks for the suggestion, I'll take that. :-)
