### ISSUE TITLE
Feature request: Allow use of LAPACK in Matrix::qr in .adjustX

### ISSUE THREAD

**Issue by BajczA475** [glmmTMB/glmmTMB#1037]
I have a colleague I've been assisting who has a model that is 34 million records. When he attempts to use glmmTMB() on his data, he gets an error that the matrix being created via qr() [in the .adjustX function] is too large for LINPACK. I'm not totally sure what all that means, but I do know that LAPACK can apparently handle larger objects, and that there is a toggle in qr() that allows use of LAPACK instead. 

So, I had him change .adjustX to have LAPACK = TRUE, changed the name, changed .checkRankX() to use the new version of .adjustX, did the same upstream with fitTMB(), and then the same with glmmTMB(), propagating that one change up through new versions of each of those functions. Then, I did:

environment(glmmTMB2) <- asNamespace('glmmTMB')
environment(fitTMB2) <- asNamespace('glmmTMB')

Where glmmTMB2 is "our" version that uses the renamed versions of all those nested functions. Seems to work ok...except he keeps running out of memory, but I assume we'll solve that issue eventually!

However, I suspect it would be easier/more elegant to just propagate down the LAPACK = TRUE, toggle through the ...s of each function, but I'm not smart enough to do that :).

**Comment by bbolker** [comment]
This seems reasonable, but alternately you could use `control = glmmTMBControl(rank_check = "skip")` to skip the rank-checking step entirely ... ???

**Comment by bbolker** [comment]
Since I haven't heard anything back, I'm closing this. If you have a use case for which you need/want to do the rank checking on a really big X matrix (and were not just overlooking the possibility of skipping the rank check entirely), feel free to re-open this ...
