### ISSUE TITLE
VarCorr() - unfinished ... but I'll take it

### ISSUE THREAD

**Issue by mmaechler** [glmmTMB/glmmTMB#104]

**Comment by bbolker** [comment]
82df7764e gets some of the basics right now, I think.  Still more examples and testing needed, esp. of models with/without scale parameters (right now Gaussian is only scale-estimating family that works in `sigma()` -- need to go back and check how scales are parameterized in other cases

**Comment by bbolker** [comment]
I'm going to say this is done -- scale-handling improved in 89ef782c73f8015da99 .
