### ISSUE TITLE
print() methods incl. summary() --> use .prt*() utilities from `lme4`

### ISSUE THREAD

**Issue by mmaechler** [glmmTMB/glmmTMB#105]
@bbolker and I had mentioned it Friday, that this may be a good idea.
Yesterday I have exported all these utilities (from `lme4`, the github version [https://github.com/lme4/lme4] and wrote a help page with examples for all of these: [https://raw.githubusercontent.com/lme4/lme4/master/man/utilities.Rd].
Yes, need to (re-)install lme4 from github to be able to use them.

Using them instead of re-inventing the wheel will help in consistency.

**Comment by koenvanbenthem** [comment]
Very good, I will work on it tonight!

**Comment by bbolker** [comment]
I think this is done.
