### ISSUE TITLE
Error arising when including random effects in the dispersion parameter

### ISSUE THREAD

**Issue by psmorris15** [glmmTMB/glmmTMB#1058]
I've been experimenting with including random effects in the dispersion formula. I understand this is a new feature that is still in the experimental phase. The models seem to run and converge, but I am getting this error whenever I try to print, view the summary, or call the `VarCorr` function. This has happened for both uncorrelated random effects, i.e., `(1 | group)` and correlated random effects, i.e., `ou(0 + time | group)`. 

`Error in mkVC(cor = xrep$corrdisp, sd = xrep$sddisp, cnms = cn, sc = sigma,  : 
  length(cnms) == (nc <- length(cor)) is not TRUE`

**Comment by bbolker** [comment]
I'm sure you're right that there is  a glitch. Can we have a reproducible example please?

**Comment by psmorris15** [comment]
`library(glmmTMB)
library(lme4)

data(sleepstudy)

fit <- glmmTMB(Reaction ~ Days + (Days | Subject), data = sleepstudy,
        dispformula = ~ Days + (Days | Subject))

print(fit)
summary(fit)
VarCorr(fit)`
