### ISSUE TITLE
Convergence problems related to grouping variable being a factor

### ISSUE THREAD

**Issue by 94enrico** [glmmTMB/glmmTMB#1063]
I analyse data from repeated measurements over 5 sessions. Each measurement is labelled by an identifying dichotomous variable ("A_1", "A_2" or "A_1:A_2") and perform at a specific angle "Alpha_ankle_deg_Fmax". The participants are identified by the variable "ID" and the gender by the dichotomous variable "Is_m". "Delta_F" is the response variable and is expressed in Newtons.

I noticed that the standard glmmTMB algorithm converges when ID is a string, but does not converge when ID is a factor. Actually, the model does converge when I use ID as factor as follow

`ex_df %>% mutate(ID = factor(ID)`

but not when I type

`ex_df %>% mutate(ID = factor(ID, levels = ID_lv)`. 

Probably the difference lies in the way levels are defined, but when I check the values (see the attachment), there is not rearrangement of the IDs. 

The model is rather unstable, changing the optimizer lead to non-convergence. However, I wonder if there is an explanation for this ambiguous behaviour when ID is a factor or a string.

In the zip folder [Issue_glmmTMB.zip](https://github.com/user-attachments/files/16157628/Issue_glmmTMB.zip) there's the dataset and a script to reproduce the error. Github does not support RData files, this is why the folderis loaded this way.

I haven't found any duplicates of this question online, so if there are any, I apologise in advance.

Thank you in advance for your help,
Enrico Roma

**Comment by bbolker** [comment]
When you specify a character vector (string) as a grouping variable, `glmmTMB` converts it to a factor internally anyway, so there's really no difference between your `fit_fact2` and your `fit_char`. Note that the *order of observations* does not change when you change the levels of a factor ...  

It is certainly not impossible, but is a little bit surprising to me, that changing the order of the random effects in this way would change the optimization outcome. I would have to do a lot more digging to understand exactly **why** the fitting is so unstable (in general it's not surprising that fitting a 6x6 covariance matrix = 21 RE parameters with 331 observations would be pushing it a bit ...) as far as I can see, all we're doing is permuting the columns of the $Z$ matrix, the order of the $b$ vector, and the order in which the likelihoods of the random effects for each subject are computed ...

Does that answer your question?

**Comment by 94enrico** [comment]
I knew that the number of parameters in the variance-covariance structure is quite large for 331 observations. There is a theoretical justification for the model, but given the instability of the solution, I'll probably simplify it a bit. I wanted to report the "error" exactly as it happened to me to point out a potential problem. I didn't have much time to simulate a simpler dataset to reproduce the problem, also because I didn't know where it was coming from. So thanks twice for addressing it anyway.
I wanted to see if I missed anything other than the instability of the solution, or if it could be a potential bug.

And yes, you answered the question well. Thanks very much for that!

**Comment by bbolker** [comment]
It would definitely be interesting to dig in further and find out what's going on. I experimented *briefly* and found that the value of the objective function (negative log-likelihood) and gradient at the starting values of the parameters are not quite identical for these two models, but the differences are (as expected) very small, on the order of 1e-16. Surprising that this leads to divergence in the results of optimization. Not going to dig into it further now ...
