### ISSUE TITLE
Fitting negative binomial model with dispersion parameter fixed

### ISSUE THREAD

**Issue by lingminhao** [glmmTMB/glmmTMB#1066]
Hi, thanks for the package. I would like to fit my data with a negative binomial model with dispersion fixed. I knew that I should do this by adjusting the `start` and `map` parameter. However, I do not know how to do this exactly. Could you guide me on this ?

**Comment by mebrooks** [comment]
Please see [where to ask questions](https://github.com/glmmTMB/glmmTMB?tab=readme-ov-file#where-to-ask-questions).

Here's an example of fixing the disperson parameter in `nbinom1` to 2. It's estimated on the log scale.

```

m2 <- glmmTMB(count ~ mined,
                start=list(betadisp=log(2)), map=list(betadisp=factor(NA)),				 
                family=nbinom1, data=Salamanders)

sigma(m2)
```
