### ISSUE TITLE
New/renamed covariance structures not being recognized

### ISSUE THREAD

**Issue by psmorris15** [glmmTMB/glmmTMB#1069]
I've tried adding a new covariance structure according to the guidelines in the Hacking glmmTMB vignette. After running `make enum-update` and reinstalling, the new covariance structure is not being recognized when being called in a model fit. This issue has continued even when renaming existing covariance structures.

As an example, I've renamed `homdiag` to `homdiag2` in this fork: https://github.com/psmorris15/glmmTMB_covstruct_test. Calling `homdiag` gives the error 
```
Error in vapply(obj, function(x) x[[component]], numeric(1)) : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0
```
which seems to indicate that the old name is still being recognized internally somehow? When I call `homdiag2`, the error `Error in homdiag2(Days + Subject) : could not find function "homdiag2"` is returned, despite the enum file being updated to reflect the new name. 

Is there something I am missing that is not included in the guidelines in the hacking vignette? I am not sure where to go from here. I've tried on several systems and am encountering this issue on each. 

Here is the code I am using: 
```
devtools::install_github("psmorris15/glmmTMB_covstruct_test/glmmTMB")

library(tidyverse)
library(glmmTMB)
library(lme4)


glmmTMB(
  Reaction ~ homdiag(Days | Subject),
  data = sleepstudy
)

glmmTMB(
  Reaction ~ homdiag2(Days | Subject),
  data = sleepstudy
)
```

**Comment by bbolker** [comment]
I suspect this may be related to [this issue](https://github.com/bbolker/reformulas/issues/2); since we've moved formula processing to `reformulas`, we need to do a little bit more work in `glmmTMB` to make sure that the list of "specials" is passed properly ...

**Comment by bbolker** [comment]
Adding `specials = c(names(.valid_covstruct), "s")` as an argument to `splitForm` in line 707 of `glmmTMB.R` (see diff file below) helps a little bit - now `homdiag` works, but weirdly `homdiag2` doesn't. I will dig in a bit further ...


```
diff --git a/glmmTMB/R/glmmTMB.R b/glmmTMB/R/glmmTMB.R
index 3518c2f..e14357a 100644
--- a/glmmTMB/R/glmmTMB.R
+++ b/glmmTMB/R/glmmTMB.R
@@ -707,7 +707,7 @@ getXReTrms <- function(formula, mf, fr, ranOK=TRUE, type="",
         }
 
         ## formula <- Reaction ~ s(Days) + (1|Subject)
-        ss <- splitForm(formula)
+        ss <- splitForm(formula, specials = c(names(.valid_covstruct), "s"))
 
         ## contains: c("Zt", "theta", "Lind", "Gp", "lower", "Lambdat", "flist", "cnms", "Ztlist", "nl")
         ## we only need "Zt", "flist", "Gp", "cnms", "Ztlist" (I think)
```

**Comment by bbolker** [comment]
I don't remember  how easy it is to sync your fork to a branch, but (as you can see) I've now made these changes and issued a pull request ...

**Comment by psmorris15** [comment]
It looks like this has fixed the issue. Thank you!
