### ISSUE TITLE
Error returned when including more than one s() term in a formula

### ISSUE THREAD

**Issue by psmorris15** [glmmTMB/glmmTMB#1072]
At the risk of bombarding you...

Including more than one `s()` term in a formula has started to return the error 
```
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
``` 

Here is a reproducible example:
```
library(glmmTMB)

fake_data <- data.frame(y = rnorm(n = 100),
                        x1 = rnorm(n = 100),
                        x2 = rnorm(n = 100))

glmmTMB(
  y ~ s(x1) + s(x2),
  data = fake_data
)
```

**Comment by psmorris15** [comment]
Should note that this has been occurring before and after the changes made here https://github.com/glmmTMB/glmmTMB/pull/1071

**Comment by bbolker** [comment]
Will take a look.

**Comment by bbolker** [comment]
Nice, this was a really easy one to fix: https://github.com/glmmTMB/glmmTMB/pull/1073/commits/99ad21c0ef8dc523f091f8406fbafb154961153e . Pull request [here](https://github.com/glmmTMB/glmmTMB/pull/1073)
