### ISSUE TITLE
Specify tweedie distribution power parameter

### ISSUE THREAD

**Issue by zelobup** [glmmTMB/glmmTMB#1076]
Hi, thanks for your help in advance.

I'm attempting to run a model with glmmTMB that has a tweedie distribution. The following code works:

`model <- glmmTMB(formula = formula, data = meta,
                 family = tweedie(link = "log")`

and using `family_params` returns "Tweedie power 1.710809".

However, I know my response variable's distribution is much more similar to a tweedie distribution with power parameter 1.05 - 1.1. When looking at the diagnostics using DHARMa, there were some pretty major issues with the model, and I wanted to specify a power parameter of 1.1.

Unfortunately, I've been unable to find a way to do this. The _start_ and _map_ arguments seem to be made for this purpose, as the documentation lists _psi_ as the way to supply a power parameter, but many, many attempts have all led to failure, usually through a "Link not implemented!" error, or otherwise. 

Would love to hear how glmmTMB is supposed to handle tweedie distributions with custom power parameters. Thanks so much!

**Comment by mebrooks** [comment]
It's possible that your model fit is bad and your power parameter is larger than expected due to missing covariates. 

This code works
```
glmmTMB(y ~ x, family=tweedie, data=dat, 
		start=list(psi=boot::logit(1.1 - 1)), 
		map = list(psi=factor(NA)))
```

**Comment by bbolker** [comment]
I would use `qlogis()` (if you look at `boot::logit`, it is *exactly* a synonym for `qlogis()`!) but otherwise agree. It may be worth adding a note to `?glmmTMB::tweedie` (which is the documentation page for *all* glmmTMB-specific families), because the link function (`qlogis(psi-1.0)`) is not obvious to non-developers ...

**Comment by zelobup** [comment]
I'm glad I'm not crazy and you think extra documentation for tweedie distributions is warranted. Thanks for your help and for your work on glmmTMB, it's an incredible package.

Thanks for the code @mebrooks , it works on my machine too! Could I trouble you to ask why `boot::logit()` (or `qlogis()`) take an input for _psi_ of 1.1 - 1 when specifying a power parameter of 1.1? What's the rationale behind the psi-1.0 syntax?

P.S. it may interest you to know that I'm also working on fisheries modelling! This particular model is supposed to account for patterns in abundance of larval yellowtail scad (T. novaezelandiae) down here in Australia. I'm using linear and quadratic SST, chl-a, GSLA and EKE as covariates. The idea is to incorporate copepod abundance as an extra covariate to see if it improves the model. Might be crazy. Thanks for being a part of the process. 

You are definitely correct that the fit is bad, specifying 1.1 did not improve my diagnostics! lol

**Comment by mebrooks** [comment]
I'll try to update the documentation today. 

The logic is that we're really only allowing the user to fit the compound Poisson–gamma distribution, a case of the Tweedie with the restriction that $1 < p < 2$. So in we let $p=logit^{-1}(\psi) +1$ where $\psi$ is unconstrained and  
$0 < logit^{-1}(\psi) < 1$. In terms of code, `psi` $=\psi$. 

I like to write it with `boot::logit()` to make it as transparent as possible. I know of some papers that say "logit" when they mean "inverse logit".

It sounds like a cool yellowtail study. Maybe you want to try penalized splines for the SST, but that reminds me, I should get back to my own models on that subject :)

**Comment by mebrooks** [comment]
I see @bbolker  added the info already.

**Comment by zelobup** [comment]
Thanks for the suggestion!! Best of luck with your own research.
