### ISSUE TITLE
Problems adding random effects to a betabinomial model in glmmTMB

### ISSUE THREAD

**Issue by vmsur** [glmmTMB/glmmTMB#1085]
Hello! I'm running into an issue including random effects in betabinomial models in glmmTMB. 

The data I'm working with is proportion data (proportion successes v. proportion failures in two different "groups" over multiple time points). I am trying to compare the fit of a binomial distribution to a beta-binomial distribution. I have one version of the model with the time variable as a random effect (proportion ~ group + (1|time)), and one treating it as a fixed effect that interacts with "group" (proportion ~ group*time). I can fit both versions of the model using a binomial distribution, but from the residuals it looks like there's some overdispersion and that a beta-binomial distribution might be a better fit. 

I can fit a beta-binomial model _without_ the random effect, but when I try to incorporate the random effect and family=betabinomial(link='logit'), I get the following error: Error in (function (start, objective, gradient = NULL, hessian = NULL,  : 
  NA/NaN gradient evaluation

If I switch to link='cloglog', it runs fine. There are warnings about non-integer successes and NaN function evaluation, but it does produce an output. 

Why would this be happening? Interestingly, if I turn the proportions into percentages by multiplying successes and failures by 100, the random effects version is able to run with the logit link. But if I work with the percentage-version of the data _without_ the random effect, it throws an error because values need to be [0,1].

**Comment by bbolker** [comment]
Nothing springs to mind. Could we have a reproducible example please (or at least your model call and the results of `summary()` applied to your data)?  (If you're specifying the response as a proportion in [0,1] you are including a `weights` argument to specify the number of trials for each observation, right?)

**Comment by vmsur** [comment]
Thanks for the quick response! 
That was actually a separate question I wanted to ask -- I was using weights when I originally fitted the model as a simple glm without random effects; however, when I try to use weights in the glmmTMB model call I get this error: 
Error in glmmTMB(values ~ grp * ends, data = for_glm2, wieghts = weight,  : 
  unused argument (wieghts = weight)

Maybe addressing this would solve the other error! Here is a reproducible example:

`for_glm_dummy <- data.frame(date = c('2020-03-27', '2020-04-10', '2020-04-24', '2020-05-08', '2020-05-22', 
                                     '2020-03-27', '2020-04-10', '2020-04-24', '2020-05-08', '2020-05-22'),
                  values = c(1, 0.9, 0.4, 0.3, 0.00,
                             0.8, 0.5, 0.5, 0.6, 0.7),
                  weight = c(10, 10, 10, 9, 10,
                             48, 200, 20, 150, 15),
                  grp = c('a','a','a','a','a',
                          'b','b','b','b','b'))

library(lubridate)
for_glm_dummy$date <- ymd(for_glm_dummy$date)

fit_BetaBin_dummy_a <- glmmTMB(values ~ grp*date, data=for_glm_dummy,
                   REML=T, family=betabinomial(link='logit')) # this should run
summary(fit_BetaBin_dummy_a)

fit_BetaBin_dummy_b <- glmmTMB(values ~ grp + (1|date), data=for_glm_dummy,
                   REML=T, family=betabinomial(link='logit')) # error here
summary(fit_BetaBin_dummy_b)`

I noticed that when I made mock data without any 0s in the 'values' (proportion) column, the error didn't come up!

**Comment by bbolker** [comment]
You misspelled "weights" in your example ...

**Comment by vmsur** [comment]
Ha... Sorry about that. The non-integer successes is only in my example data as I accidentally overlooked that requirement when creating it. 

And adding weights, and spelling the term correctly, resolves the error. Everything is working now :-)
