### ISSUE TITLE
Gamma GLMM with fixed parameter in betad

### ISSUE THREAD

**Issue by AlainZuur** [glmmTMB/glmmTMB#1098]
Hello,

I am trying to run a multivariate Gamma GLMM in glmmTMB. And that gives plenty of optimisation warnings (as expected). As a solution, I am trying to set the Gamma variance parameters (those under 'Dispersion model') to a fixed value.

As a simplified example, why does the following code not work?

MV2 <- glmmTMB(Y ~ 0 + MorphID + IEggM:MorphID,# + 
                                     #(1 | Clutch) + (0 + MorphID | Hatchling), 
                               #dispformula =~ 0 + MorphID,
                               family = Gamma(link = "log"),                    
                               map = list(betad = factor(NA)),
                               start = list(betad = log(summary(MV1)$sigma^2)),
                               data = PT4_long2) 

This is a simple Gamma GLM. I am trying to set the Gamma variance parameter (called dispersion estimate in the output) to a fixed value. This code works fine for a negative binomial GLMM, but not for a Gamma GLMM. The error is:

Error: unrecognized vector 'betad' in ‘start’

Any suggestions? 

Kind regards,

Alain

**Comment by bbolker** [comment]
Try `betadisp` rather than `betad` ?

**Comment by AlainZuur** [comment]
Yeap....that does the job.

Thanks,

Alain

**Comment by bbolker** [comment]
I think/hope you were using the development version (that would make everything make sense to me). This change is noted [in the NEWS file](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/inst/NEWS.Rd#L27-L34) ...
