### ISSUE TITLE
Issues with matching  phylogenetic variance-covariance matrix and data

### ISSUE THREAD

**Issue by LeaHeidrich** [glmmTMB/glmmTMB#1103]
Hello, first- time issue report here, so I hope I'm not making mistakes while reporting.

I've tried following the example of fitting a proportional random error effect structure here: https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html#proptional
 
I'v echanged the line 
```
rownames(phylo_varcov) <- colnames(rownames(phylo_varcov)) <- gsub(".", "_", rownames(phylo_varcov)) 
Error:   attempt to set 'colnames' on an object with less than two dimensions 
```

to
 
```
rownames(phylo_varcov) <- colnames(phylo_varcov) <- gsub("\\.", "_", rownames(phylo_varcov)) 
```
which worked fine. 

However, when I continue, I get the following error message:

```
> fit_phylo <- glmmTMB(log(range) ~ log(size) + propto(0 + species | dummy, phylo_varcov),  data = carnidat)  
Error: column or row names of the matrix do not match the terms.   
Expecting names:‘speciesAtelocynus_microtis’‘speciesBassariscus_alleni’‘speciesBassariscus_astutus’ [....]

```

Question:
Could this issue be related to `checkProptoNames` (commit 55d5023), or is there something I might be missing in the specification of `phylo_varcov`?

R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)
other attached packages:
caper_1.0.3    mvtnorm_1.3-1  MASS_7.3-60.2  phytools_2.3-0 maps_3.4.2     glmmTMB_1.1.10 ape_5.8        ade4_1.7-22  

Thank you for your time!

**Comment by mmcgillycuddy** [comment]
Hi, thanks for pointing this out. 

There's probably different ways you can do this, but if you order the species levels in the data to be the same order as the names of the matrix it should work. 

```
require(ade4)
require(ape)
data(carni70)
carnidat <- data.frame(species = rownames(carni70$tab), carni70$tab) 
tree <- read.tree(text=carni70$tre)
phylo_varcov <- vcv(tree)# phylogenetic variance-covariance matrix
# row/column names of phylo_varcov must match factor levels in data
rownames(phylo_varcov) <- colnames(phylo_varcov) <- gsub("\\.", "_", rownames(phylo_varcov)) 
carnidat$dummy <- factor(1) # a dummy grouping variable must be added to the dataset
carnidat$species = factor(carnidat$species, levels = rownames(phylo_varcov), ordered = T ) ### Order levels in data

fit_phylo <- glmmTMB(log(range) ~ log(size) + propto(0 + species | dummy, phylo_varcov),
                     data = carnidat)
```
Otherwise, glmmTMB will use the order from `model.matrix(~ 0 + carnidat$species) `

I will update the vignette to reflect this.

**Comment by bbolker** [comment]
Thanks @mmcgillycuddy . Seems like the vignette is the main/only place we have documentation on `propto` (except a very brief indication in `?glmmTMB` that points users to the vignette), so as long as the vignette is clear we should be all set (right?)

**Comment by mmcgillycuddy** [comment]
@bbolker yes, the vignette is currently the only place with documentation. I will update the vignette. Sorry, it was a last minute rush to get something up.

**Comment by bbolker** [comment]
Updated example:  I don't think `ordered = TRUE` is actually necessary ....??? (`ordered` doesn't do what most people think it does ...)

```
library(ape)
data(carni70, package = "ade4")
tree <- read.tree(text = carni70$tre)
phylo_varcov <- vcv(tree)# phylogenetic variance-covariance matrix
## row/column names of phylo_varcov must match factor levels in data
## (punctuation/separators in species names and ordering)
spnames <- gsub("_", ".", rownames(carni70$tab))
carnidat <- data.frame(
    species = factor(spnames, levels = rownames(phylo_varcov)),
    dummy = factor(1),
    carni70$tab)
fit_phylo <- glmmTMB(log(range) ~ log(size) +
                         propto(0 + species | dummy, phylo_varcov),
                     data = carnidat)
```

**Comment by bbolker** [comment]
@LeaHeidrich , if this now seems clear I will close the issue ...
