### ISSUE TITLE
Bug or misunderstanding? `type = "conditional"` and `type = "link"` in `predict()` for ZI models

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#1106]
A quick question, what is the relationship between `type = "conditional"` and `type = "link"` in `predict()` for ZI models? I thought the latter is the same as the first, only on the link scale? But why does back-transforming not return the same predictions?

``` r
library(glmmTMB)
data(Salamanders)
m <- glmmTMB(
  count ~ spp + mined + (1 | site),
  ziformula = ~ spp + mined,
  family = truncated_poisson,
  data = Salamanders
)

d <- expand.grid(spp = unique(Salamanders$spp), mined = "yes", site = NA)
predict(m, newdata = d, type = "conditional")
#> [1] 1.539425 1.303313 1.696995 1.433377 2.145296 2.089678 1.568268
family(m)$linkinv(predict(m, newdata = d, type = "link"))
#> [1] 0.9351738 0.5554649 1.1706423 0.7691210 1.7855018 1.7127738 0.9792208
```

<sup>Created on 2024-10-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by bbolker** [comment]
I suspect this has to do with the fact that this is a hurdle model and not (strictly speaking) a ZI model ... ??  These values do match if I use `family = poisson` instead ...  (that's an observation, not an explanation ...)

**Comment by strengejacke** [comment]
Yes, sounds good to me!
