### ISSUE TITLE
Possible error in documentation for priors

### ISSUE THREAD

**Issue by qdread** [glmmTMB/glmmTMB#1108]
In the help documentation for `priors` it says for the `class` column:

"the name of the underlying parameter vector on which to impose the prior ("fixef", "fixef_zi", "fixef_disp", "ranef", "ranef_zi", "psi")"

However I do not believe this is correct for the beta coefficients on the zero inflation parameter. I tried `"fixef_zi"` and it returns an error. Only if I specify `"betazi"` for the class, do I get the expected result. I would recommend either changing the documentation or changing the implementation of priors so it matches the documentation. 

Thanks for all your work on this excellent package!

**Comment by bbolker** [comment]
Hmm, I can't reproduce this -- everything in your example works for me.  What is `packageVersion("glmmTMB")` ? (I would ask for `sessionInfo()`, but this issue seems restricted to the `glmmTMB` package -- wouldn't be coming from a weird version of an upstream package ...

**Comment by qdread** [comment]
Apologies, I had been on v1.1.9 but all the above issues are resolved when I updated to v1.1.10. Should have tried that first. My bad!
