### ISSUE TITLE
GlmmTMB::getME with "Lambda", "Lambdat", "Lind"

### ISSUE THREAD

**Issue by dongwenluo** [glmmTMB/glmmTMB#1110]
Can we get "Lambda", "Lambdat", "Lind" for a fitted glmmTMB objects?
in earlier version of 'glmmTMB' we can get some info by:

```r
data("sleepstudy", package = "lme4")
library(glmmTMB)
 model <- glmmTMB(Reaction ~ Days + (Days | Subject), sleepstudy)
 tmb_call <- model$call
 tmb_call$doFit <- FALSE
tmbf <- try(with(model$frame, eval(tmb_call)), TRUE)
if (inherits(tmbf, "try-error")) {
    tmb_call$data <- base::merge(eval(tmb_call$data), model$frame, sort=FALSE)
    tmbf <- eval(tmb_call)
}
cond_reTrms <- tmbf$condList$reTrms
    Lambda <- t(cond_reTrms$Lambdat)    # this is NULL at glmmTMB 1.1.10
    Lambda@x <- theta[cond_reTrms$Lind] 
```

Any help will be appreciated.

Regards

Dongwen

**Comment by bbolker** [comment]
Can I ask where this code comes from?  I can see how it works (and I think I know why it doesn't work any more), but it seems as though it would be incorrect for models with a non-diagonal covariance matrix (i.e., doesn't handle covariance/correlation parameters correctly). (It could probably be extended to handle those cases ...)

**Comment by dongwenluo** [comment]
Hi Ben,

Thanks for your help, I do need to handle a non-diagonal matrix situation, just I don't know how to get it.  Any possible we can do that?

Best regards

Dongwen

**Comment by bbolker** [comment]
This seems to work:

```r
library(glmmTMB)
library(Matrix)
library(reformulas)

data("sleepstudy", package = "lme4")

model <- glmmTMB(Reaction ~ Days + (Days | Subject), sleepstudy)
model2 <- lme4::lmer(Reaction ~ Days + (Days | Subject), sleepstudy, REML=FALSE)

fr <- model.frame(model)
form <- formula(model)
rt <- mkReTrms(
                findbars(form),
    fr, reorder.terms=FALSE, calc.lambdat=TRUE)


rmattr <- function(x, a = c("correlation",  "blockCode", "stddev")) {
    for (aa in a) attr(x, aa) <- NULL
    x
}

mktheta <- function(model) {
    vc <- VarCorr(model)$cond
    get_chol <- function(v) {
        cc <- t(chol(rmattr(v)))
        cc[lower.tri(cc, diag = TRUE)]
    }
    theta <- lapply(vc, get_chol) |> unlist()
    return(theta/sigma(model))
}

rt$Lambdat@x <- unname(mktheta(model)[rt$Lind])

all.equal(rt$Lambdat, getME(model2, "Lambdat"), check.attributes = FALSE)
## [1] "Mean relative difference: 1.764745e-05"
```

**Comment by dongwenluo** [comment]
Hi Ben,

Thanks for your great help, let me follow your guid and see what will happened.

Best regards

Dongwen

**Comment by bbolker** [comment]
OK, closing for now. Re-open if necessary. (If you do need to implement the last step mentioned above, i.e. replacing specials such as `diag()` with `us()` in a formula, something with `reformulas::replaceForm` might work OK ...
