### ISSUE TITLE
Suggested way to account for repeated nodes in pairwise comparisons?

### ISSUE THREAD

**Issue by gavinmdouglas** [glmmTMB/glmmTMB#1117]
I would like to fit a model based on the pairwise comparison of every node in a network. So there are two variables I would like to fit as random effects: node1 and node2 (which are in arbitrary order).

What would be the best way to do this so that node1=nodeA, node2=nodeB would be treated the same as node1=nodeB, node2=nodeA?

I was thinking that specifying a symmetric correlation structure between these variables with dispformula could make sense, but I was not sure:
```
model <- glmmTMB(
  response ~ fixed_effects + (1|node1) + (1|node2),
  data = data,
  dispformula = ~cs(node1 + node2)
)
```

Any advice you have would be appreciated, thanks!

**Comment by bbolker** [comment]
I will think about this, but if you don't get an answer here you might try on `r-sig-mixed-models@r-project.org` or [Cross Validated](https://stats.stackexchange.com); technically, those would be better venues for this question (see ["where to ask"](https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions).

This sounds a little bit like a *multi-membership model* to me, see https://github.com/jvparidon/lmerMultiMember or https://bbolker.github.io/mixedmodels-misc/notes/multimember.html (the latter has a `glmmTMB`-based example ...

It's not immediately obvious to me how `dispformula` helps in this case ...

**Comment by gavinmdouglas** [comment]
Thanks, actually you're right that I was referring to a multi-membership model, I just did not know the terminology, and that URL will give me leads. In hindsight, I don't think `dispformula` can be used for this purpose, and that was just my misunderstanding. I will be sure to post at one of those other places in the future, sorry for missing that.

I think in my case it would be reasonable to simply duplicate my input matrix, and assign each node in a pair per observation to that observation once. Do you think this is fair? My thinking is that this that since all observations are duplicated, that this should not introduce bias in the coefficient estimates (but could for the estimates of standard error). 

So, essentially doing this:

```
test <- data.frame(x=rnorm(10),
                                y=sample(c(0, 1), 10, replace = TRUE),
                                node1 = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'),
                                node2 = c('c', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'a'))

test_dup <- data.frame(x = c(test$x, test$x),
                       y = c(test$y, test$y),
                       node = c(test$node1, test$node2))

model_out <- glmmTMB(y ~ x + (1 | node),
                     data = test_dup)
```


Thanks!

Gavin

**Comment by bbolker** [comment]
This seems not-ridiculous, but I'd rather do a proper multi-membership model:

```r
set.seed(101)
test <- data.frame(x=rnorm(10),
                   y=sample(c(0, 1), 10, replace = TRUE),
                   node1 = c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'),
                   node2 = c('c', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'a'))
library(glmmTMB)

## want to set up a model where length(b) = ncol(Z) =
##   length(unique(c(node1, node2)))
## (values will still be iid normal)
## assuming here for convenience that all nodes are represented in node1 ...

test$nodes <- test$node1
m1A <- glmmTMB(y ~ x + (1|nodes), data = test, family = binomial,
               doFit=FALSE)
m1B <- fitTMB(m1A, doOptim = FALSE)

allnodes <- sort(unique(c(test$node1, test$node2)))
W1 <- matrix(0, ncol = length(allnodes), nrow = nrow(test),
             dimnames = list(NULL, allnodes))
W1[cbind(1:nrow(test), match(test$node1, allnodes))] <- 1
W1[cbind(1:nrow(test), match(test$node2, allnodes))] <- 1

m1B$env$data$Z <- as(Matrix(W1), "TsparseMatrix")
## rebuild TMB object
m1C <- with(m1B$env,
                TMB::MakeADFun(data,
                               parameters,
                               map = map,
                               random = random,
                               silent = silent,
                               DLL = "glmmTMB"))
fit <- with(m1C, nlminb(par, objective = fn, gr = gr))
m2 <- finalizeTMB(m1A, m1C, fit)
```

**Comment by bbolker** [comment]
Unless there is further feedback/discussion needed (possibly more appropriate for `r-sig-mixed-models@r-project.org` I'm going to close this shortly ...

**Comment by gavinmdouglas** [comment]
Thanks @bbolker, I am still exploring how to best to account for multiple membership for my specific model, but I will reach out to `r-sig-mixed-models@r-project.org` with any follow-up questions.

Thanks a lot for your help!
