### ISSUE TITLE
Incorrect documentation and mysterious `theta` `rho` in `cs()`

### ISSUE THREAD

**Issue by DrJerryTAO** [glmmTMB/glmmTMB#1121]
Hi @bbolker, I tried reproducing homogeneous compound symmetry according to the suggested method at https://stat.ethz.ch/pipermail/r-sig-mixed-models/2023q4/030542.html. I noticed that although `glmmTMB()` and `gls()` give similar results, the vignette "Covariance structures with glmmTMB" incorrectly lists $\rho = \theta / \sqrt{1 + \theta^2}$ as the formula for estimand-to-parameter transformation for cs(), which applies to `ar1()` as documented though. Can you update the formula? It appears that `glmmTMB()` uses the same parameterization of compound-symmetry correlation coefficient as in `gls()` that is not scaled Cholesky factoring and includes a mysterious component in the formula that I do not understand. 

```r
data("sleepstudy", package = "lme4")
library(nlme)
library(glmmTMB)

# gls() corCompSymm
summary(Model1 <- gls(
  Reaction ~ Days, data = sleepstudy,
  correlation = corCompSymm(form = ~ 1 | Subject)))
"       AIC      BIC    logLik
  1794.465 1807.192 -893.2325
Correlation Structure: Compound symmetry
 Formula: ~1 | Subject 
 Parameter estimate(s):
      Rho 
0.5893103 
                Value Std.Error  t-value p-value
(Intercept) 251.40510  9.746736 25.79378       0
Days         10.46729  0.804221 13.01543       0
Residual standard error: 48.3595"
coef(Model1$modelStruct$corStruct, unconstrained = F)
"0.5893103 = Rho as printed correlation coefficient in summary()"
coef(Model1$modelStruct$corStruct)
"0.5338441 = raw coefficient"
nlme:::coef.corCompSymm()
"It shows that rho is calculated as
  object = Model1$modelStruct$corStruct
  val <- exp(as.vector(object))
  val <- c((val + attributes(object)$inf)/(val + 1))
  (exp(0.5338441) - 0.1111111) / (exp(0.5338441) + 1) = 0.5893103"
nlme:::coef.corAR1()
"It shows that rho is calculated as
  rho = (exp(coef) - 1)/(exp(coef) + 1)"

# glmmTMB cs + map + dispformula=~ 0
summary(Model2 <- glmmTMB(
  Reaction ~ Days + cs(0 + factor(Days) | Subject), dispformula = ~ 0, 
  map = list(theta = factor(c(rep(1, 10), 2))), 
  data = sleepstudy, REML = T))
"     AIC      BIC   logLik deviance df.resid 
  1794.5   1807.2   -893.2   1786.5      178 
 Groups  Name          Variance Std.Dev. Corr     
 Subject factor(Days)0 2343     48.4     0.59 (cs)
         factor(Days)1 2343     48.4              
         factor(Days)2 2343     48.4              
         factor(Days)3 2343     48.4              
         factor(Days)4 2343     48.4              
         factor(Days)5 2343     48.4              
         factor(Days)6 2343     48.4              
         factor(Days)7 2343     48.4              
         factor(Days)8 2343     48.4              
         factor(Days)9 2343     48.4              
Number of obs: 180, groups:  Subject, 18
Conditional model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept) 251.4051     9.7738   25.72   <2e-16 ***
Days         10.4673     0.8041   13.02   <2e-16 ***"
diagnose(Model2)
"Error in startsWith(names(nn), 'cond') : non-character object(s)"
sigma(Model2) # 0.0001220703 not exactly 0
exp(getME(Model2, name = "theta")[1])
"48.40402, close to sigma(gls(corCompSymm)) = 48.3595"
exp(getME(Model2, name = "theta")[1]) - sigma(Model1)
"higher by 0.04451696"

attributes(VarCorr(Model2)$cond$Subject)$correlation[2]
"0.5901896, very close to gls(corCompSymm) 0.5893103"
attributes(VarCorr(Model2)$cond$Subject)$correlation[2] - coef(
  Model1$modelStruct$corStruct, unconstrained = F)
"higher by 0.000879354"
getME(Model2, name = "theta")[11]
"0.5372422, somewhat different from gls(corCompSymm) raw coef 0.5338441"
getME(Model2, name = "theta")[11] - coef(Model1$modelStruct$corStruct)
"higher by 0.003398136"
get_cor(getME(Model2, name = "theta")[11])
"0.4732669, very different from the printed Corr = 0.59 in summary()"
getME(Model2, name = "theta")[11] / sqrt(
  1 + getME(Model2, name = "theta")[11]^2)
"0.4732669 identical to get_cor() but does not match Corr = 0.59 in summary(). 
Incorrect theta --> rho formula on glmmTMB covariance structure vignette"

(exp(0.5372422) - 0.1111111) / (exp(0.5372422) + 1) = 0.5901896
"Finally theta is correctly transformed to rho using the formula shown in 
  nlme:::coef.corCompSymm(), which is
  rho = (exp(theta) + ???) / (exp(theta) + 1)"
```
However, what does `attributes(gls()$modelStruct$corStruct)$inf` mean? It appears that it is calculated as `1 / (g - 1)` where `g == length(levels(factor(Days)))` is the dimension of variance-covariance component within each subject. So, 10 different days results in this "adjustment constant" to be 1/9 = 0.1111111. But I could not identify any documentation explaining such parameterization.

Also, is there a better way to extract correlation coefficient than subsetting from a possibly large correlation matrix as an attribute of `VarCorr(Model2)$cond`? The `get_cor()` correctly works with `ar1()` models but not `cs()` models.

**Comment by bbolker** [comment]
From the [source code](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L392-L393), here's the `glmmTMB` mapping from $\theta_{n+1}$ to $\rho$:

```
   Here's the  Type a = Type(1) / (Type(n) - Type(1));
    Type rho = invlogit(corr_transf) * (Type(1) + a) - a;
```

This was indeed incorrect in the covstruct vignette, I've fixed it (but it may not show up properly for a while: our pkgdown generation is broken in a hard-to-fix way (#980).

Here's some R code.

```r
n_cor <- length(unique(sleepstudy$Days))
th <- getME(Model2, "theta")
tfun <- function(theta, n) {
    a <- 1/(n-1)
    rho <- plogis(theta)*(1+a) -a
    return(rho)
}
tfun(tail(th, 1), n_cor)
cov2cor(VarCorr(Model2)$cond[[1]])[2,1]
```

As for the magic `inf` factor in `nlme`: I don't maintain that package, and the internals are definitely not well documented, but I can tell you that $\rho_{\textrm{min}} = -1/(n-1)$ is the minimum feasible value for a compound-symmetric correlation parameter; when $\rho < \rho_{\textrm{min}}$, the correlation matrix is no longer positive definite. So it makes sense to pick a transformation that maps $\{\rho_{\textrm{min}}, 1\}$ to the real line ...

(You can see that the `glmmTMB`  parameterization is also doing that &mdash; our `a` is the same as $\rho_{\textrm{min}}$ ...)
