### ISSUE TITLE
Propto bug

### ISSUE THREAD

**Issue by JasmRicard** [glmmTMB/glmmTMB#1131]
Hi,

I am trying to use `propto` in `glmmTMB` but I cannot understand its usage. I found this reference to help me use the functions https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html#proptional
But I can't even run this example:
```r
require(ade4)
require(ape)
data(carni70)
carnidat <- data.frame(species = rownames(carni70$tab), carni70$tab)
tree <- read.tree(text=carni70$tre)
phylo_varcov <- vcv(tree)# phylogenetic variance-covariance matrix
rownames(phylo_varcov) <- colnames(rownames(phylo_varcov)) <- gsub(".", "_", rownames(phylo_varcov))
carnidat$dummy <- factor(1)
fit_phylo <- glmmTMB(log(range) ~ log(size) + propto(0 + species | dummy, phylo_varcov), data = carnidat)
```

I suppose there is an error here `colnames(rownames(phylo_varcov))` that I corrected this way:
```r
rownames(phylo_varcov) <- colnames(phylo_varcov) <- gsub(".", "_", rownames(phylo_varcov), fixed = TRUE) 
```
Still, I get this error

> Erreur : column or row names of the matrix do not match the terms. Expecting names:‘speciesAtelocynus_microtis’‘speciesBassariscus_alleni’‘speciesBassariscus_astutus’‘speciesBassariscus_beddardi’‘speciesBassariscus_gabbii’‘speciesBassariscus_lasius’‘speciesBassariscus_pauli’‘speciesBassariscus_sumichrasti’‘speciesCanis_latrans’‘speciesCanis_lupus’‘speciesCerdocyon_thous’‘speciesChrysocyon_brachyurus’‘speciesConepatus_chinga’‘speciesConepatus_humboldtti’‘speciesConepatus_leuconotus’‘speciesConepatus_mesoleucus’‘speciesConepatus_semistriatus’‘speciesEira_barbara’‘speciesGalictis_cuja’‘speciesGalictis_vittata’‘speciesGulo_gulo’‘speciesHerpailurus_yaguaroundi’‘speciesLeopardus_pardalis’‘speciesLeopardus_tigrinus’‘speciesLeopardus_wiedii’‘speciesLontra_canadensis’‘speciesLontra_longicaudis’‘speciesLontra_provocax’‘speciesLyncodon_patagonicus’‘speciesLynx_canadensis’‘spec
``

 And the same thing happens when I try to use it in my own data.

Thank you for you time,

Jasmin

**Comment by bbolker** [comment]
We'll have to work on this.  For now, this looks like it works:

```
phylo_varcov <- vcv(tree)# phylogenetic variance-covariance matrix
# row/column names of phylo_varcov must match factor levels in data
rownames(phylo_varcov) <- colnames(phylo_varcov) <-
    paste0("species", gsub("\\.", "_", rownames(phylo_varcov)))
ord <- sort(rownames(phylo_varcov))
phylo_varcov <- phylo_varcov[ord, ord]
fit_phylo <- glmmTMB(log(range) ~ log(size) + propto(0 + species | dummy, phylo_varcov),
                     data = carnidat)
```

**Comment by bbolker** [comment]
Updated example:

```
library(ape)
data(carni70, package = "ade4")
tree <- read.tree(text = carni70$tre)
phylo_varcov <- vcv(tree)# phylogenetic variance-covariance matrix
## row/column names of phylo_varcov must match factor levels in data
## (punctuation/separators in species names and ordering)
spnames <- gsub("_", ".", rownames(carni70$tab))
carnidat <- data.frame(
    species = factor(spnames, levels = rownames(phylo_varcov)),
    dummy = factor(1),
    carni70$tab)
fit_phylo <- glmmTMB(log(range) ~ log(size) +
                         propto(0 + species | dummy, phylo_varcov),
                     data = carnidat)
```

Can you let us know if this resolves your problem?

**Comment by JasmRicard** [comment]
Hi,

It now works with this modification! It even works on my own data! Thank you for your time.

Jasmin
