### ISSUE TITLE
Error in `glmmTMB.Effect()`

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#1133]
Reported here: https://github.com/strengejacke/sjPlot/issues/957

``` r
library(glmmTMB)

#Data frame
set.seed(12345)
x <- round(rnorm(800, mean=20, sd=10.5),0)
x[x<6] <- 6
x[x>40] <- 40
set.seed(12345)
y <- rnbinom(800, mu=10.6, size=1.4)
set.seed(12345)
y[floor(runif(n=140, min=1, max=800))] <- 0
site <- c(rep("A",25), rep("B",50), rep("C", 75), rep("D",100), rep("E",150), rep("F",200), rep("G",200))
example <- data.frame(cbind(x,y,site))
example$x <- as.integer(example$x)
example$y <- as.integer(example$y)

mod_test <- glmmTMB(y ~ x + (1 | site), data=example, ziformula=~., family=truncated_nbinom2)
effects::Effect("x", mod_test)
#> Warning in Effect.glmmTMB("x", mod_test): overriding variance function for
#> effects/dev.resids: computed variances may be incorrect
#> Error in log(mu): non-numeric argument to mathematical function
```

<sup>Created on 2024-12-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by bbolker** [comment]
Will look into it ...

**Comment by bbolker** [comment]
I think I found the problem but don't yet know how to fix it.  [Here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/family.R#L37) we are constructing an expression to put into the `$initialize` component of a `family` object. If we don't protect the expression with `expression` or `quote`, then the expression tries to get evaluated to soon and fails. If we do protect it with `expression` or `quote`, then it is *too* protected: evaluating it just skips it.

If we look at `str(family(model)$initialize)`, the families that work (which are *not* constructed by `make_family` [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/family.R#L34-L53)) are printed as `expression({ ...`, whereas those that *are* constructed by `make_family` are printed as `language expression({ ...`.

(The code here is loosely modeled after the internal `binomInitialize` function [here](https://github.com/r-devel/r-svn/blob/main/src/library/stats/R/family.R#L299-L329))

I will have to bang on this some more. It may be as simple as `eval()`ing the expression before returning it (to convert from `language expression` to `expression`, but then we seem to run into trouble with our own `local(eval(...))` that we do elsewhere.  Do I need to `substitute` `needs_nonneg` and `needs_nonint` too ... ?

```r
library(glmmTMB)

data("sleepstudy", package = "lme4")
m2 <- glmmTMB(round(Reaction) ~ Days + (1 | Subject), sleepstudy,
              family = nbinom2)
effects::Effect("Days", m2)  ## variance warning but OK
str(family(m2)$initialize)
## expression({  if (any(y < 0))  stop("negative values not allowed for the negative binomial family")  n <- rep(1, | __truncated__


m3 <- update(m2, family = truncated_nbinom2)
try(effects::Effect("Days", m3))  ## log(mu): non-numeric argument etc.
str(family(m3)$initialize)
## language expression({     mustart <- y + 0.1 ...
```

**Comment by strengejacke** [comment]
Thanks!

**Comment by bbolker** [comment]
For the record, I would still like to understand this problem better and solve it in a more principled way (i.e., all I did to fix it was adding one more `eval()` statement, but I think I would need to consult with someone with a deep understanding of R's lazy evaluation mechanisms. I briefly worked on putting together a minimal example, but even that is a lot of work ...
