### ISSUE TITLE
document family options

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#116]
I believe that we have more distributions available than are documented for the standard glm family in family {stats}. So we may need to document them manually (e.g. beta-binomial).

**Comment by bbolker** [comment]
Are these distributions documented in the user-level docs for TMB ... ?  That might be the right place ...

**Comment by kaskr** [comment]
Yes, there will be some sort of TMB doxygen documentation for the distribution with a reference to an R package e.g. http://www.inside-r.org/packages/cran/VGAM/docs/Betabinom (and I think I prefer argument names and order closer to theirs: ```dbetabinom(x, size, shape1, shape2, give_log)```).

**Comment by bbolker** [comment]
I don't mind about the argument order.  I would suggest that the best design going forward is that in general TMB should have the basic versions/standard statistical parameterizations of the distributions, and that glmmTMB can use thin conversion layers on top to get the parameterization that is more useful for statistical modeling in general.  FWIW `library("sos"); findFn("dbetabinom")` finds `dbetabinom` functions in a handful of packages ...

**Comment by mebrooks** [comment]
Documented in `?family_glmmTMB` in #230

**Comment by mebrooks** [comment]
Add compois citation 
```
@article{Huang_2017,
    author = {Huang, A.},
    title = {{Mean-parametrized Conway–Maxwell–Poisson regression models for dispersed counts}},
    journal = {Statistical Modelling},
    volume = {17},
    number = {6},
    pages = {1-22},
    year = {2017},
    doi = {10.1177/1471082X17697749},
    URL = {http://dx.doi.org/10.1177/1471082X17697749}
}
```
