### ISSUE TITLE
ignoreZeros flag for use with truncated families?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#119]
technically speaking, if we are using truncated families then the probability of 0 is 0 (and the log-probability is `-Inf`.  However, it would be convenient for the purpose of fitting hurdle models to ignore zeros completely: that way just fitting a model with a truncated family plus zero-inflation would automatically fit a hurdle model, no need to do a separate binomial model.  Should we
- warn when there are zeros in the response if using a truncated family but then ignore them in the conditional likelihood?
- only do this if a flag is set?

We might want to consider implementing a `control()` argument for these sorts of flags, as they're going to proliferate eventually and clutter up the argument list ...

**Comment by mebrooks** [comment]
I think it might be nice to make this fix before putting it on CRAN. It seems pretty easy to add a conditional statement to  the `tmp_loglik` calculation. The part that is less obvious is, what should we do about simulating?

**Comment by mebrooks** [comment]
For simulating from a hurdle model, would it be logical to fill the whole response vector with values from the truncated distribution and then zero some of them out based on the zero-infaltion model?

**Comment by mebrooks** [comment]
I updated the [salamander example](https://github.com/glmmTMB/zipaper/blob/c8c1361d962d717cfb05d9427571c44bbfa0043e/salamanders.pdf) to reflect the changes in this commit. I wonder if we should add a more informative error message for when users try to fit a model with a truncated distribution and without zero-inflation to data containing zeros. I'm sure someone will mistakenly do it. I guess it's a tradeoff of the runtime spent checking for those 3 things co-occuring versus the time it will take the user to figure it out and possibly write to a list asking for help. @bbolker what do you think?

**Comment by kaskr** [comment]
Perhaps it suffices to just test for finiteness of logLik at the end of optimization - similar to what we do with pdHess ? Something like "this probably indicates invalid observations for the family... ".

**Comment by bbolker** [comment]
I would prefer to test upstream rather than downstream if possible ...

**Comment by kaskr** [comment]
Definitely possible - and better.
