### ISSUE TITLE
ubuntu 12.04 32-bit build issue

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#121]
I know it's a bit ridiculous to worry about it, but for future reference: I can make glmmTMB install on my archaic system by commenting out line 58 of  `include/cppad/local/pod_vector.hpp`, starred below:
```
template <> inline bool is_pod<unsigned int>(void)       { return true; }
# if CPPAD_SIZE_T_NOT_UNSIGNED_INT
template <> inline bool is_pod<size_t>(void)             { return true; }  ***
# endif
```

**Comment by kaskr** [comment]
This problem has come up many times lately, and is even more important now that we plan to put it on CRAN. I think I have the the 'right' fix implemented here:
https://github.com/kaskr/adcomp/commit/87fc5dec0829185cf92c3ab958d28fcbb2d7a540

**Comment by bbolker** [comment]
Works for me

```
library("devtools")
install_github("kaskr/adcomp",subdir="TMB",ref="fix32bit")
```
Followed by `make quick-install` from the command line.  As long as it doesn't break anything on other OS, I think it's good.

thanks!
