### ISSUE TITLE
release issues for 0.0.1

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#134]
What are critical, if-at-all-possible, and wishlist items for a preliminary release?  My list:

**critical**
- ~~print method for `summary.glmmTMB` objects~~
- ~~`summary.glmmTMB` to generate coef tables for zi, disp components if non-trivial~~
- make sure dispersion parameters are handled properly throughout for non-Gaussian models with dispersion ... (_done, not tested thoroughly_)

**if-at-all-possible**
- implement R side for AR1 models (Kasper: I'll look into this)
- tests for `cs()` variance structures
- ~~residuals method~~ (_what do we do about zero-inflated models??_)
- ~~see if we can get `TMB` submitted to/accepted on CRAN (without this we won't be releasing to CRAN anyway ...)~~

**wishlist**
- lots more examples and testing

**Comment by mebrooks** [comment]
Wow, I didn't realize the summary function was written. Thanks!
I think documenting the syntax of the family options is critical (to avoid too many questions). 
I can work on examples and testing.

**Comment by bbolker** [comment]
At least the basic version of that is written (see https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/man/glmmTMB.Rd ; the basic stuff is under the "family" argument description, while the stuff about how to specify binomial models is under Detais), but it would probably be a good idea to add some illustrative examples to that page ...

**Comment by bbolker** [comment]
I've improved handling of dispersion parameters (although I'm not sure they get printed in summaries yet ...)

Only thing left on my list is fixing all the documentation glitches -- need to dig a little deeper into roxygen rules for how to export methods *only* as methods, not as functions ...

**Comment by mmaechler** [comment]
Sorry to not being able to resist :  I *do* bet quite a bit that using roxygen has cost *much* more time than it gained .... but I know that we can't bet on this... and so this is just a  blatant claim without any data...

**Comment by bbolker** [comment]
for the record, the main issue is to *not* use Roxygen-style comments `##'` if you don't want a .Rd page to be created ...

**Comment by mebrooks** [comment]
It would be great if `family=list(family="truncated_nbinom1", link="log")` were working. Since the first paper will highlight the zero-inflation and hurdle model capabilities, I think the first thing people will do is to compare fits with nbinom1, nbinom2, and ZI and hurdle versions of those.

**Comment by bbolker** [comment]
It is working (I think): see https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/tests/testthat/test-families.R#L119

**Comment by mebrooks** [comment]
You're right. I wasn't updating the version on my computer correctly.

**Comment by mebrooks** [comment]
- edit `Examples` for `glmmTMB` function in `glmmTMB.R` to use built in data, `ziformula`, and `dispformula`

**Comment by bbolker** [comment]
I'm not sure this issue is relevant any more -- probably superseded by #214. Of course it would always be nice to have more testing and documentation ...
