### ISSUE TITLE
beta models don't seem to work

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#156]
warnings about "in fpar(...) ... value out of range in lgamma", and ridiculous results.

```
set.seed(101)
ngrp <- 20
nobs <- 400
x <- rnorm(nobs)
f <- factor(rep(1:ngrp,nobs/ngrp))
u <- rnorm(ngrp,sd=1)
eta <- 2+x+u[f]
mu <- plogis(eta)
y <- rbeta(nobs,shape1=mu/0.1,shape2=(1-mu)/0.1)
y <- pmin(0.999,pmax(0.001,y))  ## clamp
dd <- data.frame(x,y,f)

library(glmmTMB)
m1 <- glmmTMB(y~x+(1|f),family=list(family="beta",link="logit"),
        data=dd)
```

**Comment by bbolker** [comment]
Update: I don't understand the current code in `glmmTMB.cpp` handling the Beta distribution. The code below (on the `bolker_beta` branch) includes three parameterizations/translations from (mu,phi) to the shape parameters of the beta distribution: (1) what was there before (which I don't understand at all!); (2) what is currently in `dbetabinom` (which looks a little less weird, but also looks weird to me); (3) my version, which seems to work best ...

I don't want to change this without knowing what the original intention was (this stuff was first added in e062db90ea3db9dd59 by @fishfollower ...)

```
      case beta_family:
	// original:
	// stmp = (mu(i) * mu(i) - mu(i) + phi(i)) / phi(i);
	// s1 = -mu(i) * stmp;
	// s2 = (mu(i) - Type(1)) * stmp;
        // or as in dbetabinom:
	// s1 = mu(i) * mu(i) / phi(i);
	// s2 = phi(i) / mu(i);
        // as in emdbook::dbetabinom
        s1 = mu(i)/phi(i);
        s2 = (Type(1)-mu(i))/phi(i);
	tmp_loglik = weights(i) * dbeta(yobs(i), s1, s2, true);
```

In addition: we should add a check for values not strictly >0 and <1 in beta models ... this is best done via the `$initialize` component of a family (so we should write such families for beta ... we can follow `mgcv` in calling the beta family `betar` ...)

**Comment by kaskr** [comment]
The original parameterization is what you get by writing the two shape
parameters of the beta distribution in terms of mean (mu) and variance
(phi). This approach does not account for the constrained
mean-variance parameter space. E.g. it gives negative shape parameters
for mu=0.01 and phi=100.

The emdbook version seems right to me: You get the correct mean and
guarantee valid shape parameters (although the interpretation of phi
becomes less clear).

**Comment by bbolker** [comment]
fair enough about the interpretation of phi.  I think we should make phi its reciprocal, to match up with what is (I think) the standard modeling parameterization where phi is a *precision* parameter; mu=s1/(s1+s2), phi=s1+s2 or s1=mu*phi, s2 = (1-mu)*phi: e.g. http://www.jstatsoft.org/article/view/v034i02/v34i02.pdf

**Comment by bbolker** [comment]
The example above seems to work now. I'm holding off closing this because I think we could probably stand to do a bit more documentation ... there is now a `betar()` family function in `family.R` (but conflicts with `mgcv::betar`, which is itself so named to avoid conflicting with `base::beta()` (the incomplete beta function). Maybe `beta_fam()` ?  (In retrospect, the naming of the family functions in base R (`stats` package) -- `gaussian()`, `binomial()`, `Gamma()`, etc ... seems like a bad idea?)

**Comment by mebrooks** [comment]
I have a question related to the interpretation of phi, but it could be generalized to all our dispersion parameters. Suppose someone were to do a meta-analysis where the response collected from the literature is a proportion that they want to do regression on. So their data contains estimated proportions (`mu_hat`) and variances (`var_hat`). People would often use `1/var_hat` as a weight in the regression, but for glmmTMB we are suggesting to use dispersion instead of weights. In glmmTMB and betareg's formulation of beta regression, `var = mu*(1-mu)/(1+phi)`. Solving that equation for `phi` gives `phi = mu*(1-mu)/var -1`. So would it make sense to use `dispformula =~ mu_hat*(1-mu_hat)/var_hat -1` or `dispformula =~ mu_hat*(1-mu_hat)/var_hat` in a meta-analysis? 

The general idea is that if `var=f(mu, phi)` and `phi=g(mu, var)`, then does it make sense to use `dispformula=~g(mu_hat, var_hat)`?

**Comment by bbolker** [comment]
I'm confused.  In a meta-analysis one typically uses the variance *of the estimated parameter*, i.e. the variance of the sampling distribution, not the residual variance (which corresponds more closely with what phi is measuring).  The variance needed for a meta-analysis comes from `vcov()`.  (The sampling distributions of the parameters in a meta-analysis are typically assumed to be Normal; if that assumption has to be relaxed then things get kind of nasty and it would probably be necessary to have all of the original data available ...)

**Comment by mebrooks** [comment]
I was assuming that they could obtain an `var_hat` that was an uncertainty estimate, not the residual variance. I see that this doesn't match with the dispersion parameter. That's an important point to make if the dispersion formula can't fill this role of weights. I guess I'll recommend that they transform the proportions to be normal and do weighted regression with another package.

**Comment by bbolker** [comment]
This is obviously getting beyond a glmmTMB topic,  but I agree in principle that doing weighted regression on a transformed (probably logit) scale makes sense (although they'll have to do something a little bit fancy/Bayesian with any 0 or 1 values).

It also makes me realize I didn't understand your question properly. I thought you were talking about using the phi values etc. estimated from a glmmTMB run as weights in another meta-regression, not about using glmmTMB to **do** the meta-regression.  So yes, I think your idea actually *does* make sense, but I would definitely (1) work it through on paper and (2) try some simulations ...

**Comment by bbolker** [comment]
Have renamed `betar()` to `beta_family()`; closing.
