### ISSUE TITLE
use family$initialize() component for range checking etc.

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#157]
Range checking and conversion for e.g. binomial variables can be done using the `$initialize` component of the `family` object.  It would be better to do this routinely (e.g. for `beta` to check 0<y<1), and to use the code in `binomial()$initialize` rather than writing our own ... (this applies to `lme4` as well!)

Oddly, `poisson()$initialize` doesn't warn on non-integer counts the way `binomial()` does ... ? oversight or design ?

**Comment by mebrooks** [comment]
I think we can close this. We were recently using `eval(family$initialize)` to do some checks, but it also made changes to `y` and `weights` in binomial models. So as of [this commit](https://github.com/glmmTMB/glmmTMB/pull/272/files#diff-97ff024177e8f3aa12528855cf13b42cR613), we only use it to do the checks.
