### ISSUE TITLE
slow predictions?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#159]
(placeholder) -- prediction on a glmmTMB fit on a large data set (10^5 rows) with many predictors (20) is extremely slow.  I'm getting permission to share the data set/fitted models with the development team; otherwise I will try to simulate some. The dimensions of the problem are: 56479 observations, 26 fixed-effect parameters, 2816 random effects, 9 random-effects variance-covariance parameters.

When I tried to use the `predict()` method ...
```
## on my system: projects/CondomAwareness/model.R
base_model <- modList$base_model
predict(base_model,resid_type="pearson")  ## slow ...
## Error in sparseHessianFun(env, skipFixedEffects = skipFixedEffects) : 
##   Memory allocation fail in function 'MakeADHessObject2'
```

I ended up implementing a "lightweight" prediction.

```
z <- getME(base_model,"Z")
x <- getME(base_model,"X")
rr <- ranef(base_model)
rr0 <- unlist(rr$cond)
eta <- c(matrix(x %*% fixef(base_model)$cond  + z %*%  rr0))
mu <- plogis(eta)
```

I don't know if it makes sense to try to implement this kind of option, or whether it would be re-implementing the wheel. (Unfortunately there are lots of options/permutations of options for predict - which random effects are included/conditioned on/marginalized over, whether we are looking for predictions for the conditional or zero-inflation part, etc. etc.)

**Comment by kaskr** [comment]
We can easily provide fast predictions - it seems to be implemented in
the C++ template already. Looking at ```sdreport.R``` one can set
```doPredict=0``` in the ```se.fit=FALSE``` (default) case.  Then get
predictions with
```
newObj$report(oldPar)$mu
```

A recent TMB version (1.7.1) has an option to fix the memory issue
encountered when running with ```se.fit=TRUE```. But it will probably
still be slow in this case.

**Comment by psinger** [comment]
See https://github.com/glmmTMB/glmmTMB/issues/43

**Comment by psinger** [comment]
Just a further note: all functions ``fitted(m), resid(m), predict(m)`` etc. are super slow.

**Comment by bbolker** [comment]
Have you updated glmmTMB in the last few days, i.e. since the master branch pulled in @kaskr's improvements in this direction?

**Comment by psinger** [comment]
Did not see the new commit, thanks, that indeed helps a ton!
