### ISSUE TITLE
Dispersion/Residual Variance not correct for Gaussian and Gamma error models

### ISSUE THREAD

**Issue by John-R-Wallace** [glmmTMB/glmmTMB#168]
Dispersion reported is only sigma not sigma squared for the Gaussian error model.

For Gamma error models, the reciprocal of the dispersion (= shape parameter) is returned.

See below and the file "Gamma errors with random variable" here: 
            https://github.com/John-R-Wallace/GLMM-Comparison

    
    devtools::install_github("glmmTMB/glmmTMB",subdir="glmmTMB")
    
    require(glmmTMB)
    
    # ==================== Gaussian Model ==============================================================================================
    
    set.seed(123)
    N <- 10000; a <- 3; b <- 4.1; SD = 2
    
    x <- seq(1,3, len=N)
    y <- rnorm(N, a + b*x, sd = SD) 
    
    summary(glm(y ~ x))
    glmmTMB(y ~ x)
    
    data.frame(N = N, a = a, b = b, Dispersion_Variance = SD^2)
    
    
    # =========rGamma function which takes mean and var as parameters, not shape (mu) and scale (lambda) ================================================================= 
    
       rGamma <- function(n, Mean, Var, nu = NULL, Shape.Scale = FALSE, verbose = FALSE, gammaFunc = rgamma) {
    
            "  # Dispersion is 1/nu, where nu is the shape parameter.  Dispersion is equal to the CV squared for the gamma.  "
       
                if(F) {  
                "  # Example of generating data for a glm model with gamma errors.  "
                   x <- seq(1,20, len=50000)
                   y <- rGamma(50000, exp(3 + 2*x), 4*(exp(3 + 2*x))^2) # 4 is Dispersion (nu = 1/Dispersion)
                   summary(glm(y ~ x, family = Gamma(link='log'))) # Estimate of Dispersion is given in summary()
                   y <- rGamma(50000, exp(3 + 2*x),  nu = 1/4) # Now using the nu shape argument, the variance argument is not used
                   summary(glm(y ~ x, family = Gamma(link='log'))) 
               }
       
               if(is.null(nu))
                       nu <- Mean^2/Var  # Since Dispersion = CV^2 = Var/Mean^2 = 1/nu
       
               if(verbose) {
                       catf("\nAverage Shape =", mean(1/nu), "Average Scale =", mean(nu*Mean), "\n\n")
                       plot(x, nu*Mean, col='green', ylim=c(0, max(c(1/nu, nu*Mean))))
                       points(x, 1/nu)
               }
       
               if(Shape.Scale)
                 list(Shape= nu, Scale = Mean/nu)
               else
                 gammaFunc(n, nu, scale = Mean/nu)  # rgamma(n, shape, rate = 1, scale = 1/rate)
       }
       
            
    set.seed(123)
    N <- 10000; a <- 3; b <- 4.1; nu <- 1.5
    
    x <- seq(1,3, len=N)
    y <- rGamma(N, exp(a + b*x ), (1/nu)*(exp(a + b*x))^2) 
    
    summary(glm(y ~ x, family = Gamma(link='log')))
    glmmTMB(y ~ x, family = Gamma(link='log'))
    
    
    data.frame(N = N, a = a, b = b, Shape.nu = nu, Dispersion_Variance = 1/nu)

**Comment by bbolker** [comment]
I think this is resolved by https://github.com/glmmTMB/glmmTMB/pull/170 (feel free to comment/reopen if not)
