### ISSUE TITLE
Dispersion/Residual Variance for Gamma error models is incorrect

### ISSUE THREAD

**Issue by John-R-Wallace** [glmmTMB/glmmTMB#171]
See Issue #168 and #170 

The reciprocal is gone for the dispersion/resid_variance but a squaring is still needed since dispersion is a variance.  

    data.frame(N = N, a = a, b = b, Shape.nu = nu, Dispersion_Variance = 1/nu)
   N a   b Shape.nu Dispersion_Variance
1 10000 3 4.1      1.5           0.6666667 

    sigma(glmmTMB(y ~ x, family = Gamma(link='log')))
[1] 0.810617

     sigma(glmmTMB(y ~ x, family = Gamma(link='log')))^2
[1] 0.6570999

    summary(glmmTMB(y ~ x, family = Gamma(link='log')))
 Family: Gamma  ( log )
Formula: y ~ x
  ...
(Dispersion parameter for Gamma family taken to be 0.810617)
...

**Comment by bbolker** [comment]
Tried again with 9658426ce5350500672714ba7339f18b199de251 ... keep getting confused about the different scales of dispersion

**Comment by John-R-Wallace** [comment]
Looks good now. 

From the updated comparison:  

https://github.com/John-R-Wallace/GLMM-Comparison/blob/master/3.%20Gamma%20errors%20with%20random%20variable


      summary(glmmTMB.Gamma)$coefficients$cond; cat("Dispersion =", sigma(glmmTMB.Gamma)^2, "\nShape.nu =", 1/sigma(glmmTMB.Gamma)^2, "\n\n")  # Dispersion now correct as of 23 Aug 2016
    
   Estimate Std. Error    z value     Pr(>|z|)
(Intercept) 3.237148 0.48626260   6.657202 2.790903e-11
x           4.120787 0.01407119 292.852729 0.000000e+00
Dispersion = 0.6574572 
Shape.nu = 1.521012 

    summary(lme4.Gamma)$coefficients; cat("Dispersion =", sigma(lme4.Gamma)^2, "\nShape.nu =", 1/sigma(lme4.Gamma)^2, "\n\n")
            
   Estimate Std. Error    t value     Pr(>|z|)
(Intercept) 3.236981 0.49928857   6.483188 8.980471e-11
x           4.120786 0.01400445 294.248336 0.000000e+00
Dispersion = 0.654949 
Shape.nu = 1.526836 

    summary(opt.TMB.Gamma$SD, "fixed", p.value = TRUE)[1:3,]  # TMB
   Estimate Std. Error    z value   Pr(>|z^2|)
a  3.237127 0.48629455   6.656722 2.800028e-11
b  4.120786 0.01407120 292.852568 0.000000e+00
nu 1.521010 0.01960675  77.575848 0.000000e+00

     Par <- data.frame(Estimate = opt.NoTMB.Gamma$par[1:3]); rownames(Par) <- c('a', 'b', 'nu'); Par
   
   Estimate
a  2.022571
b  4.120791
nu 1.521653
