### ISSUE TITLE
extra parentheses confuse noSpecials

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#174]
This comes up when updating a complex formula.

```
noSpecials(y~a+b+(diag(c)))
```

works but 

``` 
noSpecials(y~a+b+(diag(c)))
```

gives `Error in term[[3]] : subscript out of bounds`

**Comment by kaskr** [comment]
First one should have been
```
noSpecials(y~a+b+diag(c))
```
I guess ?

**Comment by bbolker** [comment]
"should" have been, but I think `noSpecials()` should be robust to this case because (1) it's semantically sensible (extra/null parentheses shouldn't change the meaning) and (2) these parentheses somehow got introduced while using `update()` on a more complex model (I could track down how, if I needed, but I think it'd be better to fix `noSpecials()`)

**Comment by mmaechler** [comment]
I agree with you @bbolker .  It should be robust, or put differently,
`y ~ a+b+ diag(c)`   should be equivalent (almost) everywhere to
`y ~ a+b+(diag(c))`
