### ISSUE TITLE
problem with Roxygen possibly printDispersion.Rd

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#176]
When trying to run `make` on the current master branch, I get the error
```
Error : /private/var/folders/8t/zsp25_b17td7j1y5d_nmfqt00000gq/T/RtmpMWZk5F/Rbuild65f241f85f31/glmmTMB/man/printDispersion.Rd: Sections \title, and \name must exist and be unique in Rd files
```
I can't figure out the cause or solution. Googling it brought up Martin's suggestions to not use Roxygen and another solution to write the Namespace by hand. http://stackoverflow.com/questions/13137912/rd-file-name-conflict-when-extending-a-s4-method-of-some-other-package
There must be something else I can do.

I was using R 3.3.0 but updated to 3.3.1 and the problem persists.

**Comment by bbolker** [comment]
Not sure offhand/no time to troubleshoot, but `printDispersion` has `@params` specifications but no main description.  Try adding a title (prefixed by `#'` as usual).

**Comment by bbolker** [comment]
See https://github.com/glmmTMB/glmmTMB/issues/134#issuecomment-160805926  . There were roxygen comments there when there shouldn't have been (maybe my fault, haven't checked).

**Comment by bbolker** [comment]
it was my fault, I did it in 9658426ce5350 .  I usually use `R CMD build/check` manually rather than `make`, so didn't notice.

**Comment by mebrooks** [comment]
Thanks! That fixed it.
