### ISSUE TITLE
bug when missing RE

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#18]
this works 
```m2=glmmTMB(Reaction~Days + (1|Subject), sleepstudy, dispformula=~1)```

this doesn't
```m2=glmmTMB(Reaction~Days, sleepstudy, dispformula=~1)```

**Comment by mmaechler** [comment]
Hmm... you should not close an issue without comment...   
So let me:  I would actually find it  _nice_  if this (no RE) worked.  It does *not* in  `lme4`  and we had thought / convinced ourselves (?)  it was too much work to make it working there.   But given that `glmmTMB` is only just being born,  I say it would be nice..

**Comment by fishfollower** [comment]
It should work now, which is why we closed it. Should have added a comment.
