### ISSUE TITLE
devtools() install not working and only one line is needed for install.packages()

### ISSUE THREAD

**Issue by John-R-Wallace** [glmmTMB/glmmTMB#182]
I am getting:

devtools::install_github("glmmTMB/glmmTMB",subdir="glmmTMB")

Downloading GitHub repo glmmTMB/glmmTMB@master
from URL https://api.github.com/repos/glmmTMB/glmmTMB/zipball/master
Error: running command '"W:/MRO/MRO-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2

FYI:

Only  one line is needed for the install.packages() approach:

install.packages("glmmTMB", repos = "http://glmmtmb.github.io/glmmTMB/repos/")

**Comment by bbolker** [comment]
Hmmm.  Do you have development tools installed?  The reason we recommend the `install_github` approach is that it automatically gets the most recent version (whereas the binaries in the repository have to be kept up to date manually, at present, although the new R-hub facility might make that easier ...).

FWIW the `install_github()` approach is also just one line.

Googling bits of the error message turns up [this](http://stackoverflow.com/questions/40273847/build-works-in-rstudio-on-travis-but-not-through-devtoolsinstall-github) (as yet unanswered) question

**Comment by bbolker** [comment]
I've updated the `README` file to try to make this a little clearer, and to take out the comment about installing `TMB` first (it should be installed automatically either via `install_github` or `install.packages`)

**Comment by John-R-Wallace** [comment]
I have updated to the latest Rtools which didn't make any difference.

I do see that 'devtools' says it was built with R ver. 3.3.2, the 
binaries of which have not yet been released, perhaps things will work 
after R ver. 3.3.2 is installed.

BTW,  Rtools 3.4  now has mingw_32 and mingw_64 and the install helps 
you change your path to include the mingw_32.  The previous version 
(3.3) used gcc-4.6.3 .

**Comment by bbolker** [comment]
I have to admit that I'm only mildly motivated to solve this problem (i.e. if `install_github()` works do that, otherwise fall back to `install.packages()`.  Two more things to try (one based on conversation in the linked StackOverflow question):

- does `devtools::install_github` work from within RStudio (if you happen to have that installed)?
- can you try `library(ghit); install_github("glmmTMB/glmmTMB/glmmTMB",verbose=TRUE)` ?

**Comment by John-R-Wallace** [comment]
- Same error inside of RStudio.


- From a fresh install of R ver. 3.3.1 I painfully found, in opposition 
to ghit()'s description of a drop-in replacement, that all the following 
is needed and had to be found within error messages step-by-step:

update.packages()
install.packages(c('ghit', 'knitr', 'TMB', 'lme4', 'RcppEigen', 'bbmle', 
'ggplot2', 'mlmRev', 'Matrix'))   # 'Matrix' was oddly deleted after 
first glmmTMB install so added here
library(ghit)
install_github("glmmTMB/glmmTMB/glmmTMB", verbose=TRUE)
library(glmmTMB)

But it did work!

**Comment by bbolker** [comment]
Hmmm.  

- The fact of different results from 3.3.1 vs 3.3.2 suggests this is indeed some issue with out-of-sync R infrastructure (which will hopefully resolve itself soon?  3.3.2 is *very* recent (released <48 hours ago)
- I don't know why `ghit::install_github()` isn't installing dependencies properly, and don't know whether it's worth investigating whether `devtools::install_github()` has the same problem.  One potential issue is that it might be necessary to use `dependencies=c("Depends", "Imports","LinkingTo")` (this is the more typical default; I'm not sure why it's different in `ghit`).  I don't know if you have the patience to uninstall everything and try `devtools::install_github()` or `ghit::install_github()` with different arguments - I wouldn't blame you if you didn't.

**Comment by John-R-Wallace** [comment]
After deleting the packages, neither of the following work:

library(ghit)
install_github("glmmTMB/glmmTMB/glmmTMB",verbose=TRUE, 
dependencies=c("Depends", "Imports", "LinkingTo"))

install_github("glmmTMB/glmmTMB/glmmTMB",verbose=TRUE, 
dependencies=c("Depends", "Imports", "LinkingTo", "Suggests"))

Stopping at the same error as before, looking for 'knitr'.  I suppose 
'build_vignettes = F' would help for that one...

Parsing reponame for 'glmmTMB/glmmTMB/glmmTMB'...
Creating local git repository for glmmTMB...
Checking out package glmmTMB to local git repository...
[new]     41011e84fc3a484735d8 refs/remotes/github/ar1
[new]     62c8bba8c753caefbc64 refs/remotes/github/bolker_beta
[new]     9658426ce53505006727 refs/remotes/github/bolker_sigma
[new]     06b55ac8479e64462c17 refs/remotes/github/bolker_vcov
[new]     d5f2905e1020528002f8 refs/remotes/github/bolker_zifix
[new]     a48727cdfb9e79c19f42 refs/remotes/github/fix_varcorr_2nd_try
[new]     812f87c05aefe85e0df4 refs/remotes/github/genpois
[new]     cb9b48d3b33d86d95976 refs/remotes/github/gh-pages
[new]     295f7cf2deb7e819ec28 refs/remotes/github/kasper
[new]     981dc8f87c41a0d70b6e refs/remotes/github/master
[new]     498e18b2ab0dd6e64fe9 refs/remotes/github/parallel_version
Checking out package subdirectory for glmmTMB...
Adding metadata to DESCRIPTION for package glmmTMB...
Reading package metadata for 'glmmTMB/glmmTMB/glmmTMB'...
Building package glmmTMB...
* checking for file 
'C:\Users\JOHNWA~1\AppData\Local\Temp\RtmpaaQbrL\glmmTMB27903b393ce/glmmTMB/DESCRIPTION' 
... OK
* preparing 'glmmTMB':
* checking DESCRIPTION meta-information ... OK
* cleaning src
Error in loadVignetteBuilder(pkgdir, TRUE) :
   vignette builder 'knitr' not found
Execution halted
Error in build_and_insert(p$pkgname, d, vers, build_args, verbose = 
verbose) :
   Package build for glmmTMB failed!
In addition: Warning message:
running command '"W:/R/R-3.3.1/bin/x64/R" CMD build 
C:\Users\JOHNWA~1\AppData\Local\Temp\RtmpaaQbrL\glmmTMB27903b393ce/glmmTMB' 
had status 1

**Comment by bbolker** [comment]
Can you check the new version of the README and see if you think there's anything else we can do to address this issue? (I doubt it ...)

**Comment by John-R-Wallace** [comment]
Sorry, just getting back to this.

The R compiled Windows version of 3.3.2 was still not available on the 
mirror I normally use, but it was available using 
https://cloud.r-project.org/ __ <https://cloud.r-project.org/>   
(Automatic redirection to servers worldwide, currently sponsored by 
Rstudio )

Using the new install of 3.3.2  I tried:

update.packages()
install.packages('devtools')
     devtools::install_github("glmmTMB/glmmTMB/glmmTMB")

This installed lme4, RcppEigen, and TMB, but failed to install minqa and 
nloptr.

So after installing those packages , the install of glmmTMB was successful.

install.packages('minqa')
     install.packages('nloptr')
     devtools::install_github("glmmTMB/glmmTMB/glmmTMB")


FYI on the README:

- The vignette-building step applies to the ghit package; 
|devtools::install_github() doesn't have a 'build_vignettes' argument.
|

 > str(ghit::install_github)
function (repo, host = "github.com", credentials = NULL, build_args = 
NULL, build_vignettes = TRUE, uninstall = FALSE, verbose = FALSE, repos 
= NULL, type = if (.Platform[["pkgType"]] %in% "win.binary") "both" else 
"source", dependencies = c("Depends", "Imports"), ...)


 > str(devtools::install_github)
function (repo, username = NULL, ref = "master", subdir = NULL, 
auth_token = github_pat(quiet), host = "https://api.github.com", quiet = 
FALSE, ...)


- I found that using  the ghit package had more dependencies, not less.


-John
