### ISSUE TITLE
handling zero-inflation formula, offsets

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#183]
(I've already started on implementation of this, but there are some open questions, leaving this is a placeholder)

It would be convenient to be able to specify the `ziformula` argument with reference to the main `formula` argument, so that e.g.

- `~.` meant "same as the main (conditional) formula"
- `~ . - x` meant "same as the conditional formula but not including `x`"

This is all fine so far.  The only real issue is that `update.formula` (which is  what I'm using to implement the second case above) *does not drop offset terms even when explicitly asked to do so* (see [here](http://stackoverflow.com/questions/40308944/removing-offset-terms-from-a-formula)).  I'm wondering what the best way to deal with offsets would be. We could automatically drop *all* offsets with the answers from the linked SO question, but that might not be right ...

**Comment by mmaechler** [comment]
I'm too busy at the moment... but I suggest you bring this to the R-devel mailing list.
Even though there is explicit code, not dropping offset(.).... there should be an easy way to do it explicitly...
probably using Gabor's 2nd idea, but directly in R's `update.formula()` probably via a new optional argument.

**Comment by bbolker** [comment]
I don't think I have the patience to take this up at the foundational (R-core) level right now.  I have a mildly hackish solution (dropping *all* offsets from conditional formula if `.` is used in ziformula) implemented by 0aa698f
