### ISSUE TITLE
unit test best practices

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#187]
I've been testing the generalized Poisson and Conway-Maxwell Poisson distributions using data simulated from the `ZIGP` and `CMP` packages. The following code installs CMP
```
devtools::install_github( "James-Thorson/Utilities" )
devtools::install_github( "James-Thorson/Conway-Maxwell-Poisson" )
```
 `ZIGP` used to be on cran, but now only 7 year old versions are available [here](http://crantastic.org/packages/ZIGP).

I wonder, for these distributions, what would be the best way to write unit tests?  Rather than requiring the test to download these packages,  should I put 2 simulated data sets into our package?

**Comment by bbolker** [comment]
That sounds right to me.  I usually put such stuff in `inst/testdata`, whence it can be accessed by e.g. `fn <- system.file("testdata","testfile1.rda",package="glmmTMB"); load(fn)`. (One thing to watch out for when testing is that I'm not sure that `devtools::load_all()` successfully installs these files; you may need an explicit R CMD INSTALL to get them in the right place.) An alternative would be to test with minimal data sets (say, n=10) that can just be written out explicitly in the test source code.

**Comment by bbolker** [comment]
can this be closed?
