### ISSUE TITLE
don't forget about ar1 branch

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#192]

**Comment by kaskr** [comment]
Incredibly, `git rebase` didn't cause conflicts for this ~1 year old branch.

It seems the AR1 stuff is working:

```{.R}
library(glmmTMB)
example(glmmTMB)
```

There is this example:

```
fm4 <- glmmTMB(Reaction ~ ar1(DaysFac+0|Subject), sleepstudy)
```

That runs except it cannot identify the dispersion parameter:

```
Dispersion estimate for gaussian family (sigma^2): 1.16e-13 
```

Here it would be nice if the user could disable the dispersion parameter. How about allowing `dispformula = ~0` ? This should fix `betad` to something small...
