### ISSUE TITLE
robustify link/invlink functions

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#20]

**Comment by kaskr** [comment]
I have added a glmmTMB branch 'robust' that uses some new robust
parameterizations of `dnbinom` and `dbinom` on the TMB master branch. This
is, in my opinion, a better approach to robustify (mfexp and fudge
factors are completely avoided).

To try it, one currently have to re-install TMB from github.

Status:

- The @psinger examples (now in the misc folder) all run without problems.
- All automated glmmTMB tests pass.
- By reducing one of the examples to 10000 observation I could run it with glmmADMB, which failed (indicating that mfexp and fudge factors did not robustify as intended?).
- There are still a few more robustifications in glmmTMB that need to be done.

**Comment by mebrooks** [comment]
That's great! Numerical math saves the day! Before we merge it into the master branch, we should probably test it on an `nbinom` model with a linear-link. There doesn't seem to be one in the automatic tests. It's not a common thing to do, but could happen once in a while. I could write a test on Monday.

I'll keep this in mind for the generalized Poisson which might have similar issues. Unfortunately, for underdispersed distributions, we won't be able to use `log(var-mu)`.

**Comment by bbolker** [comment]
I agree this is great. Can we add a version dependency for this (i.e. `Depends: TMB (>= [current Github version])`?) We might not want to merge this branch until the next release of TMB is on CRAN ... ?

**Comment by mebrooks** [comment]
I'll follow a similar protocol for `Depends` when I merge in the `simulate` branch because it depends on the most recent TMB version. I'm curious, how often does TMB get updated on CRAN? 

As I mentioned in this thread over the weekend, I wanted to test nbinom with an identity link. It seems that glmmTMB (both older and `robust` versions) can't do that unless we were to change the way that parameters are initialized. I don't think it should be a priority, but maybe we'll get to it eventually.
```
library(glmmTMB)
library(MASS) #for glm.nb
x=1:100
m=2
b=100
y=m*x+b
dat=data.frame(obs=rnbinom(length(y), mu=y, size=5), x=x)
with(dat, plot(x, obs))
summary(glm.nb(obs~x, link="identity", dat)) #this works
summary(glmmTMB(obs~x, family=list(family="nbinom1", link="identity"), dat)) #this doesn't
```

**Comment by kaskr** [comment]
@mebrooks  version 1.7.5 has the simulation stuff so you shouldn't have to set `Depends`.

Regarding initial values I guess a very simple scheme would suffice - something like setting the intercept parameter depending on the link ?

**Comment by bbolker** [comment]
@kaskr that's right.  We already had a special case for inverse-link, adding identity to that case seems to work (we could imagine pathological/nasty situations e.g. where the scale of the response was very different from 1 -- could try to use something like mean(response) instead ... or 1/mean(response) for the inverse link ... or ??? link(mean(response)) generally ?

**Comment by kaskr** [comment]
@bbolker I agree we're probably gonna need some more advanced initialization. It's easier to make the right decision once we have a couple of those nasty examples at hand.

**Comment by bbolker** [comment]
OK to close this for now?
