### ISSUE TITLE
Convergence diagnostics

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#201]
We should somehow inform the user when a model has not converged. This raises two questions:

- How to decide if a model has converged. Simply checking whether `sdr$pdHess` is `TRUE` is usually sufficient.
- How to report it. As a warning after running  `glmmTMB` ? As part of the printed output from `print` or `summary`?

**Comment by bbolker** [comment]
`lme4`-based advice: skipping point 1 (which seems sensible, and what we've done in `lme4` has been messy and ugly and not necessarily a bad idea - ask me sometime), I think there should be *both* a warning *and* something included in the output when the model is printed or summarized.  There's a `.prt.warn` function in `lme4` that we probably don't want to copy exactly, but which could be used as an example.

**Comment by mebrooks** [comment]
In addition to a warning at the end of fitting, it would make my life easier if `AICtab` found out about convergence problems somehow and didn't include those. It's happened to me twice already that there are 1 or 2 models at the top of the AIC table that I see are problematic when I look at the `summary` and see `NA`s. Is there a good way to prevent unconverged models from ending up at the top of the AIC table? Just thinking here...if `sdr$pdHess == FALSE`, then will the `logLik` ever contain useful information, or can it return `NA`?

**Comment by mebrooks** [comment]
On the topic of warnings...would it make sense to suppress the warnings like 
```
Warning messages:
1: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
2: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
3: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
```
that usually mean the optimizer wandered into a bad region for a while, but may have gotten back out. As long as it's back in a good region by the end of optimization, then do these warnings serve a purpose?

**Comment by bbolker** [comment]
I generally err on the side of *not* sweeping warnings under the rug.  What we try to do in `lme4` is to catch the warnings and store them somewhere, then report that "warnings occurred" - it's enough to know that at least one NA/NaN evaluation occurred, one doesn't need to see 45 of them.  So, in order, my preferences are:

- try to make the fitting process more robust (e.g. via @kaskr's recent modifications) so that we can stay out of areas where the warnings occur;
- collect warnings and let the user know in a streamlined way;
- spit out all the warnings (current approach);
- convince ourselves that these warnings are definitely ALWAYS false positives and suppress them

**Comment by bbolker** [comment]
I agree that it might be a good idea to return `NA` for the likelihood when there are convergence problems (although adding warnings to the output might make it slightly less important). However, I think we'd want to allow users to override this, or tell them how they could retrieve the log-likelihoods by hand if they really want to.

**Comment by bbolker** [comment]
bump/any more thoughts on this?  @mmaechler (as someone with experience of convergence-warning debacles) ?

**Comment by mebrooks** [comment]
Just returning NA for the logLik of models with `pdHess=FALSE` won't make `AICtab`behave well. See example below. I also tried returning `Inf` and it was also bad. Do you have any other suggestions, short of rewriting `AICtab`?  
```
library(glmmTMB)
library(bbmle)
data(Salamanders)

#models to compare
nb1m2 = glmmTMB(count~spp * mined + (1|site), Salamanders, family="nbinom1")
zinb1m3 = glmmTMB(count~spp * mined + (1|site), zi=~spp * mined+ (1|site), Salamanders, family="nbinom1")

zinb1m3$sdr$pdHess
nb1m2$sdr$pdHess

logLik.glmmTMB <- function(object, ...) {
  val <- if(object$sdr$pdHess){-object$fit$objective}else{NA}
  nobs <- glmmTMB:::nobs.glmmTMB(object)
  structure(val, nobs = nobs, nall = nobs, df = length(object$fit$par),
            class = "logLik")
}

AICtab(nb1m2, zinb1m3)
```

**Comment by bbolker** [comment]
Actually, I think fixing AICtab to handle this is the right answer.  I've just pushed a fixed version to github. As soon as I check the reverse dependencies, I could push it to CRAN.  In the meanwhile you could install the patched version from Github ... 

For what it's worth, this ZI model example fails (stops on error) in my Linux VM (Ubuntu 14.04) - works (with non-PD Hessian) in MacOS ...

**Comment by mebrooks** [comment]
Thanks for changing AICtab. I installed it and it makes model selection much easier. I started a branch called `convergence_tests`. So far, the only change I made was to make `logLik.glmmTMB` return NA when `pdHess=FALSE`. Do you think `logLik.glmmTMB` should have a flag to override this, or should we just inform users that they can get the log likelihood of an unconverged model using  `-object$fit$objective`?

As for the example of the unconverged salamander model, it is a bit concerning that you get different behavior depending on the platform. What's the error you get on the Linux VM?

**Comment by bbolker** [comment]
I think clear documentation telling users how to get log-likelihood of an unconverged model is probably fine. I can imagine use cases where it would be inconvenient for the user, but maybe it's not bad that people should have to go out of their way to do silly things.

Error message:
```
Error in optimHess(par.fixed, obj$fn, obj$gr) : 
  gradient in optim evaluated to length 1 not 31
In addition: Warning messages:
1: In nlminb(start = par, objective = fn, gradient = gr) :
  NA/NaN function evaluation
...
```
Dug in a bit here, but not sure what's going on - it's inside `sdreport()` ...

**Comment by mebrooks** [comment]
Before I merge in the changes, do you have any comments on the warning message that should come at the end of `glmmTMB`? This is what I have
```
   if(!sdr$pdHess) warning(paste0("Model convergence problem. Hessian is not positive definite.", 
                             "This may indicate that a model is overparameterized."))
```

**Comment by bbolker** [comment]
Ideally, I would suggest leave the warning more vague (i.e. just tell them the Hessian is not pos def), but provide general advice on troubleshooting somewhere else (in a man page or a vignette), e.g. `warning("Model convergence problem; non-positive-definite Hessian matrix, see ?troubleshooting")`

**Comment by mebrooks** [comment]
In the `DESCRIPTION` file's `Suggests:` is it ok if I put `bbmle (>=1.0.19)` because only this version handles the NAs returned by loglik.

I'm creating a `troubleshooting` vignette.

**Comment by bbolker** [comment]
That might be a problem because bbmle 1.0.19 isn't on CRAN yet ... ?

**Comment by mebrooks** [comment]
Yeah, I thought that might be a problem, but I wasn't sure how seriously they take `Suggests`.

**Comment by bbolker** [comment]
In principle you should be able to use `R CMD check` to see if this is a problem or not ... also, I should probably try to put a new version up anyway ...

**Comment by mebrooks** [comment]
Suggesting bbmle 1.0.19 caused checking to fail, so I'll hold off on that for now.

I created a troubleshooting vignette in the mollie branch. I already added all the advice I can give from experience. If any of you feel like elaborating on troubleshooting experience, please feel free to add to the vignette. Thanks!
