### ISSUE TITLE
 Residuals and Multiple Tests

### ISSUE THREAD

**Issue by Flaiba** [glmmTMB/glmmTMB#205]
Hello, I'm new to the page, thank you very much for having a space for questions. I'm dabbling in glmm. I work with models of larval abundance in containers, which presents a negative binomial distribution with a notorious excess of zeros, with a set of fixed effects variables and two random variables nested. Because I have problems with glmmAMDB, I decided to try glmmTMB. I have been able to correctly model the abundance and presence or absence (zeros), but I have not been able to calculate the pearson residues in order to validate the model. When you try to request them as a figure in the package help
Residuals (object, type = "pearson"), I get the following error
Error in residuals.glmmTMB (M57C55, type = "pearson"):
  Variance function undefined for family 'nbinom2'; Can not compute Pearson residuals. I would like to know what other alternative I have to validate the model or how I can estimate the results of person. Finally I wanted to ask about what package I can use to make the necessary comparisons between the categories of the variables (Dunnet), since with the package multcomp I can not (library (multcomp)
> Comp_lineak <-glht (IZ1, linfct = mcp (SUPABE2 = "Dunnett"))
Error in modelparm.default (model, ...):
  Dimensions of coefficients and covariance matrix do not match).
Thank you very much!

regards
Nicolas

**Comment by bbolker** [comment]
Without looking carefully, I think the Pearson-residuals issue will be pretty easy to address.  Not sure yet what will be needed to allow multcomp-compatibility, but it's a good/important thing to implement and shouldn't (??) be too hard either.

**Comment by Flaiba** [comment]
Perfect, great news

**Comment by bbolker** [comment]
Hmm.  I can't replicate your problem with the current version of the package: according to the history, variance functions for nbinom2 were added in db4e78f1e5a (8 December 2015) ...

```
library(glmmTMB)
set.seed(101)
dd <- data.frame(y=rnbinom(1000,size=2,mu=1))
m1 <- glmmTMB(y~1,family=nbinom2,data=dd)
summary(residuals(m1))
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  -1.027  -1.027  -0.027   0.000   0.973   5.973 
summary(residuals(m1,type="pearson"))
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -0.7912 -0.7912 -0.0208  0.0000  0.7496  4.6015 
```
Can we have a reproducible example please? When/how did you install glmmTMB? (We haven't been tagging releases very well, but `packageVersion("glmmTMB")` should give you 0.0.3 -- that's pretty recent.)

**Comment by bbolker** [comment]
Here's an answer to your multiple comparisons question: the `lsmeans` can more easily be extended, and appears to do what you want.  I hacked up the necessary accessor functions:

```
recover.data.glmmTMB <- function(object, ...) {
    fcall <- getCall(object)
    recover.data(fcall,delete.response(terms(object)),
                 attr(model.frame(object),"na.action"), ...)
}
lsm.basis.glmmTMB <- function (object, trms, xlev, grid, vcov.,
                               mode = "asymptotic", component="cond", ...) {
    if (mode != "asymptotic") stop("only asymptotic mode is available")
    if (component != "cond") stop("only tested for conditional component")
    if (missing(vcov.)) 
        V <- as.matrix(vcov(object)[[component]])
    else V <- as.matrix(.my.vcov(object, vcov.))
    dfargs = misc = list()
    if (mode == "asymptotic") {
        dffun = function(k, dfargs) NA
    }
    ## use this? misc = .std.link.labels(family(object), misc)
    contrasts = attr(model.matrix(object), "contrasts")
    m = model.frame(trms, grid, na.action = na.pass, xlev = xlev)
    X = model.matrix(trms, m, contrasts.arg = contrasts)
    bhat = fixef(object)[[component]]
    if (length(bhat) < ncol(X)) {
        kept = match(names(bhat), dimnames(X)[[2]])
        bhat = NA * X[1, ]
        bhat[kept] = fixef(object)[[component]]
        modmat = model.matrix(trms, model.frame(object), contrasts.arg = contrasts)
        nbasis = estimability::nonest.basis(modmat)
    }
    else nbasis = estimability::all.estble
    list(X = X, bhat = bhat, nbasis = nbasis, V = V, dffun = dffun, 
        dfargs = dfargs, misc = misc)
}
```

Once these are defined this should work:

```
library(glmmTMB)
library(lsmeans)
set.seed(101)
dd <- data.frame(y=rnbinom(1000,size=2,mu=1),g=factor(rep(1:20,each=50)),
                 f=factor(rep(1:5,200)))
m2 <- glmmTMB(y~f,family=nbinom2,data=dd)
lsmeans(m2,pairwise ~ f) ## Tukey 
f.lsm <- lsmeans(m2, "f")
(f_contr.lsm <- contrast(f.lsm, "trt.vs.ctrl", ref = 1))  ## Dunnett
```

We should figure out how to include these with the package.

**Comment by Flaiba** [comment]
Hi Ben, thank you very much for your time before anything and I apologize for my horrible English. The last version to install glmmTMB is 0.02.
I show you what I'm doing.
To evaluate if the model is good, I evaluate the overdispersion of the residues.
For that I ask the sum of the residuals of pearson squared, divided by degrees of freedom (N-p).
This is the moment in which the error that is in the figure is produced.
My question is how do I get the pearson residuals to validate the model and know that it has a good fit to a negative binomial distribution.

![1](https://cloud.githubusercontent.com/assets/24797623/21575272/c0139798-cee5-11e6-9bb4-591eaf72e7fd.jpg)
![2](https://cloud.githubusercontent.com/assets/24797623/21575273/c0167d3c-cee5-11e6-9a1b-6327a1f2b7d8.jpg)

**Comment by bbolker** [comment]
You just need to use `family=nbinom2` instead of `family=list(family="nbinom2",link="log")` and everything should work fine.  Some of our documentation and/or examples may be out of date ...

**Comment by Flaiba** [comment]
Thank you very much for the help with the issue of residuals. It was just as you say. I work wonderfully using family = nbinom2.
TIPO and ENUSO are the categorical variables that I wish to compare in the multiple comparisons.

Ben, I do not want to bother you, but I have a problem with comparisons.

Probably a replacement error in the script. But he would not be able to make the comparisons. I ask a thousand apologies if you see that it is a nonsense, but would not be able to make the comparisons. I attach the images of the exits.


![b0](https://cloud.githubusercontent.com/assets/24797623/21575562/050680aa-ceef-11e6-9578-3e7753fc82d1.jpg)
![b1](https://cloud.githubusercontent.com/assets/24797623/21575564/050bc704-ceef-11e6-9507-9f2a37a85deb.jpg)
![b2](https://cloud.githubusercontent.com/assets/24797623/21575563/050a48a2-ceef-11e6-86ca-c2afdfcd1da0.jpg)
![b3](https://cloud.githubusercontent.com/assets/24797623/21575566/050ea8f2-ceef-11e6-9033-a093d2cda190.jpg)
![b4](https://cloud.githubusercontent.com/assets/24797623/21575565/050dbf8c-ceef-11e6-8b0c-30af660e2a1a.jpg)

You also consult, this is to make comparisons for the part that models the negative binomial (Conditional model), but to perform the comparisons of Zero-inflation model, how do I ask?


Thank you very much for your time and patience.

**Comment by bbolker** [comment]
can you send me the data or post it somewhere?

**Comment by Flaiba** [comment]
Yes, right now I'm sending it to bbolker@gmail.com

**Comment by Flaiba** [comment]
Hi Ben, I started practicing with the base of the salamanders that is exemplary. I wanted to explore modeling a truncated zeros, but I could not. Since I threw the following error


![1](https://cloud.githubusercontent.com/assets/24797623/21578564/429f000c-cf64-11e6-87bc-81b4633872e6.jpg)

Do you have any idea that it may be going wrong?
Is not recognizing the family "truncated nbinom 1.

Finally, I ask you if to perform the multiple tests in a model inflated in zeros (Dunnet or Tukey) is different in a truncated in zeros. I mean the commands in the script.

Thank you!
My best wishes
Happy New Year

And again thank you very much

**Comment by bbolker** [comment]
- The `lsmeans` comparisons are working for me (glmmTMB 0.0.3, lsmeans 2.25).
- The pairwise comparisons aren't really that interesting, I think. Some of them seem odd, it would be worth double-checking some by hand to make sure something odd hasn't happened ... checking below with a non-mixed nbinom2 model vs. MASS::glm.nb gives almost identical results, as it should ... perhaps there's something going on with zeros and the grouping variable?
- in any case it probably makes sense to try to settle on a final model before working too hard on the pairwise comparisons
- I'm not sure you have enough data/it makes sense to do pairwise comparisons on the level of zero-inflation ... it would take some more work to set this up.

Re: trucated nbinoms: I can get this to work (sort of -- there are convergence problems).  Try updating your version of `glmmTMB`?
```
m5 <- glmmTMB(Aetot ~ TIPO + ENUSO + (1|VIV),
              family=list(family="truncated_nbinom1",
                         link="log"),
              data=subset(dd,Aetot>0))
```

```
library(readxl)
dd <- read_excel("flaib_data.xlsx")

library(glmmTMB)
## try both nbinom1 and nbinom2
m2 <- glmmTMB(Aetot ~ TIPO + ENUSO + (1|VIV),
              family=nbinom1,data=dd)
m3 <- update(m2,family=nbinom2)

library(lsmeans)
source("https://raw.github.com/glmmTMB/glmmTMB/master/misc/lsmeans.R")

lsmeans(m2,pairwise ~ TIPO)
## aCOCINA-BALDE = -3.2849, se 0.562?
cc <- fixef(m2)$cond
npar <- length(cc)
contrast <- setNames(rep(0,npar),names(cc))
coef(summary(m2))
TIPO.lsm <- lsmeans(m2,"TIPO")
(TIPO_contr.lsm <- contrast(TIPO.lsm, "trt.vs.ctrl", ref = 1))

aggregate(Aetot~TIPO,data=dd,FUN=mean)
aggregate(Aetot~TIPO,data=subset(dd,Aetot>0),FUN=mean)

## ran effs look reasonable
dotchart(sort(unlist(ranef(m2)$cond$VIV)),cex=0.2)
qqnorm(sort(unlist(ranef(m2)$cond$VIV)))

lsmeans(m3,~TIPO)
## lsmeans of aCOCINA very small

m3_noran <- glmmTMB(Aetot ~ TIPO + ENUSO,
              family=nbinom2,data=dd)
m3_noran_MASS <- MASS::glm.nb(Aetot ~ TIPO + ENUSO, data=dd)
lsmeans(m3_noran, ~TIPO)
lsmeans(m3_noran_MASS, ~TIPO)

library(ggplot2)
## reorder TIPO by mean Aetot
dd <- transform(dd,TIPO=reorder(TIPO,Aetot))
ggplot(dd,aes(x=TIPO,y=1+Aetot,colour=ENUSO))+
    stat_sum(position=position_dodge(width=0.3))+scale_y_log10()+
    coord_flip()+scale_colour_brewer(palette="Set1")+
    stat_summary(fun.y=mean,geom="path",
                 aes(group=interaction(VIV,ENUSO)),alpha=0.2)+
    theme_set(theme_bw())

m4 <- glmmTMB(Aetot ~ TIPO + ENUSO + (1|VIV),
              ziform = ~TIPO,
              family=nbinom1,data=dd)
```

**Comment by FisheriesIIM** [comment]
Dear all, I am working with count data to model catch and effort data. The data ara clearly overdispersed and present a lot of zeros, so, we are dealing with zero inflated models like this:

> zinbmodel<-glmmTMB(Ntot~offset(log(pieces))+year+zone+month+depth+
                                 1|boat/trip), zi = ~depth,
                                 family=nbinom2,data=bbdd)

The model works fine; but we want to present the correspondent graphs for model validation (pearson residuals vs fitted):

> fitZINB<-fitted(zinbmodel)
> LfitZINB<-log(fitZINB)
> residZINB<-residuals(zinbmodel,type="pearson")
#but we found problems with pearson residuals
Error in residuals.glmmTMB(zinbmodel, type = "pearson") : 
  pearson residuals are not implemented for models with zero-inflation or variable dispersion

The question is that few months ago I did not find this error message and I estimated the pearson residuals for exactly the same model and using the same notation. I am not sure; but I guess I used the version 0.2.0. Is it possible to obtain pearson residuals using glmmTMB older versions? Any alternative option?

This is my session info:
 
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
#Matrix products: default
#locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252    LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    
#attached base packages:
 [1] stats4    grid      splines   stats     graphics  grDevices utils     datasets  methods   base     
#other attached packages:
 [1] dplyr_0.7.4        plyr_1.8.4         lubridate_1.7.1    bbmle_1.0.20       boot_1.3-20        ggstance_0.3      
 [7] coefplot_1.2.5     ggplot2_2.2.1      effects_4.0-0      carData_3.0-0      phia_0.2-1         car_2.1-6         
[13] gstat_1.1-5        sp_1.2-5           MASS_7.3-47        lme4_1.1-15        Matrix_1.2-12      mgcv_1.8-22       
[19] nlme_3.1-131       glmmTMB_0.2.0.9000 pscl_1.5.2        
#loaded via a namespace (and not attached):
 [1] zoo_1.8-0          TMB_1.7.12         purrr_0.2.4        reshape2_1.4.2     lattice_0.20-35    colorspace_1.3-2  
 [7] spacetime_1.2-1    survival_2.41-3    rlang_0.1.4        nloptr_1.0.4       glue_1.2.0         bindrcpp_0.2      
[13] bindr_0.1          stringr_1.2.0      MatrixModels_0.4-1 munsell_0.4.3      gtable_0.2.0       labeling_0.3      
[19] SparseM_1.77       quantreg_5.34      pbkrtest_0.4-7     parallel_3.4.3     xts_0.10-1         Rcpp_0.12.13      
[25] scales_0.5.0       useful_1.2.3       FNN_1.1            stringi_1.1.6      numDeriv_2016.8-1  survey_3.32-1     
[31] tools_3.4.3        magrittr_1.5       lazyeval_0.2.1     tibble_1.3.4       pkgconfig_2.0.1    assertthat_0.2.0  
[37] minqa_1.2.4        R6_2.2.2           intervals_0.15.1   nnet_7.3-12        compiler_3.4.3

Hopefully my query fits within this issue.
Thank you very much in advance for your time and effort. 
Best regards,
Alex Alonso

**Comment by Flaiba** [comment]
Hi Alex, I honestly do not know why it does not allow you to get pearson residuals. I currently have in the R an old version of glmmTMB (0.1.1).  This version  allows me to get pearson residuals . For now I suggest you try to download some older version that the last available. Anyway, I would wait for some member of the glmmTMB staff to give you a solution, because this is something that would affect all the users of this package.
Best regards
I'm sorry I could not help you.

Successes with the problem of residuals.

Atte: Nicolas



________________________________
De: Fisheries Ecology Group <notifications@github.com>
Enviado: jueves, 01 de febrero de 2018 08:39 a.m.
Para: glmmTMB/glmmTMB
Cc: Flaiba; Author
Asunto: Re: [glmmTMB/glmmTMB] Residuals and Multiple Tests (#205)


Dear all, I am working with count data to model catch and effort data. The data ara clearly overdispersed and present a lot of zeros, so, we are dealing with zero inflated models like this:

zinbmodel<-glmmTMB(Ntot~offset(log(pieces))+year+zone+month+depth+
1|boat/trip), zi = ~depth,
family=nbinom2,data=bbdd)

The model works fine; but we want to present the correspondent graphs for model validation (pearson residuals vs fitted):

fitZINB<-fitted(zinbmodel)
LfitZINB<-log(fitZINB)
residZINB<-residuals(zinbmodel,type="pearson")
#but we found problems with pearson residuals
Error in residuals.glmmTMB(zinbmodel, type = "pearson") :
pearson residuals are not implemented for models with zero-inflation or variable dispersion

The question is that few months ago I did not find this error message and I estimated the pearson residuals for exactly the same model and using the same notation. I am not sure; but I guess I used the version 0.2.0. Is it possible to obtain pearson residuals using glmmTMB older versions? Any alternative option?

This is my session info:

sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
#Matrix products: default
#locale:
[1] LC_COLLATE=Spanish_Spain.1252 LC_CTYPE=Spanish_Spain.1252 LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C
[5] LC_TIME=Spanish_Spain.1252
#attached base packages:
[1] stats4 grid splines stats graphics grDevices utils datasets methods base
#other attached packages:
[1] dplyr_0.7.4 plyr_1.8.4 lubridate_1.7.1 bbmle_1.0.20 boot_1.3-20 ggstance_0.3
[7] coefplot_1.2.5 ggplot2_2.2.1 effects_4.0-0 carData_3.0-0 phia_0.2-1 car_2.1-6
[13] gstat_1.1-5 sp_1.2-5 MASS_7.3-47 lme4_1.1-15 Matrix_1.2-12 mgcv_1.8-22
[19] nlme_3.1-131 glmmTMB_0.2.0.9000 pscl_1.5.2
#loaded via a namespace (and not attached):
[1] zoo_1.8-0 TMB_1.7.12 purrr_0.2.4 reshape2_1.4.2 lattice_0.20-35 colorspace_1.3-2
[7] spacetime_1.2-1 survival_2.41-3 rlang_0.1.4 nloptr_1.0.4 glue_1.2.0 bindrcpp_0.2
[13] bindr_0.1 stringr_1.2.0 MatrixModels_0.4-1 munsell_0.4.3 gtable_0.2.0 labeling_0.3
[19] SparseM_1.77 quantreg_5.34 pbkrtest_0.4-7 parallel_3.4.3 xts_0.10-1 Rcpp_0.12.13
[25] scales_0.5.0 useful_1.2.3 FNN_1.1 stringi_1.1.6 numDeriv_2016.8-1 survey_3.32-1
[31] tools_3.4.3 magrittr_1.5 lazyeval_0.2.1 tibble_1.3.4 pkgconfig_2.0.1 assertthat_0.2.0
[37] minqa_1.2.4 R6_2.2.2 intervals_0.15.1 nnet_7.3-12 compiler_3.4.3

Hopefully my query fits within this issue.
Thank you very much in advance for your time and effort.
Best regards,
Alex Alonso

**Comment by FisheriesIIM** [comment]
Thanks Nicolas for the advice,

I will try to work with an older version (I do no remember which one I 
used the first time I worked with this model); but in any case I will 
wait for the response of the glmmTMB developers.

Thanks a lot again,

Alex

**Comment by bbolker** [comment]
We disabled this capability in [this commit](https://github.com/glmmTMB/glmmTMB/commit/1101330750cb01d63be970d5921730e937dc68f5), when we realized that we were not giving the correct results for more complex models.  (So if you revert to an older version of the package, you'll just be getting *incorrect* Pearson residuals.) Computing the expected variance of a zero-inflated model (needed for Pearson residuals) is harder than for non-ZI models: see details from Zuur et al 2012 below. Here's some code that implements Pearson residuals for the ZINB2 model. To make this work more generally, we'd need to figure this out for each family and incorporate it in the code ...

```
library(readxl)
dd <- read_excel("flaib_data.xlsx")

library(glmmTMB)
## fit both nbinom1 and nbinom2
m2 <- glmmTMB(Aetot ~ TIPO + ENUSO + (1|VIV),
              family=nbinom1,data=dd)
m3 <- update(m2,family=nbinom2)
m4 <- update(m2,ziformula=~1)
m5 <- update(m3,ziformula=~1)
  
residuals(m2,type="pearson")
residuals(m3,type="pearson")
residuals(m4,type="pearson")  ## error (not available)

v <- family(m5)$variance
p <- predict(m5,zitype="zprob")  ## z-i probability
mu <- predict(m4,zitype="conditional")  ## mean of conditional distribution
pred <- predict(m4,zitype="response") ## (1-p)*mu
## sigma(.) = k = theta = overdispersion parameter ...
k <- sigma(m5)
pvar <- (1-p)*v(mu,k)+mu^2*(p^2+p)
pearson_resid <- (dd$Aetot-pred)/sqrt(pvar)
``` 

from Zuur, Alain F, Anatoly A Saveliev, and Elena N Ieno. Zero Inflated Models and Generalized Linear Mixed Models with R. Newburgh, U.K.: Highland Statistics Ltd., 2012:

![zi_pearson](https://user-images.githubusercontent.com/78918/35686317-02884a46-073a-11e8-8dcd-3546e159e7a0.png)

**Comment by Flaiba** [comment]
Hi, Ben, many thanks for informing me of this complexity. First of all thank you very much that you had the kindness to approach me a solution for my particular case, for which I contacted you more than 1 year ago, which you had in mind makes me thank you even more. I will run it with my data soon to be able to corroborate the models and check that I get the pearson residuals.

Thank you very much really.


Best regards


Nicolas



________________________________
De: Ben Bolker <notifications@github.com>
Enviado: jueves, 01 de febrero de 2018 12:32 p.m.
Para: glmmTMB/glmmTMB
Cc: Flaiba; Author
Asunto: Re: [glmmTMB/glmmTMB] Residuals and Multiple Tests (#205)


We disabled this capability in this commit<https://github.com/glmmTMB/glmmTMB/commit/1101330750cb01d63be970d5921730e937dc68f5>, when we realized that we were not giving the correct results for more complex models. (So if you revert to an older version of the package, you'll just be getting incorrect Pearson residuals.) Computing the expected variance of a zero-inflated model (needed for Pearson residuals) is harder than for non-ZI models: see details from Zuur et al 2012 below. Here's some code that implements Pearson residuals for the ZINB2 model. To make this work more generally, we'd need to figure this out for each family and incorporate it in the code ...

library(readxl)
dd <- read_excel("flaib_data.xlsx")

library(glmmTMB)
## fit both nbinom1 and nbinom2
m2 <- glmmTMB(Aetot ~ TIPO + ENUSO + (1|VIV),
              family=nbinom1,data=dd)
m3 <- update(m2,family=nbinom2)
m4 <- update(m2,ziformula=~1)
m5 <- update(m3,ziformula=~1)

residuals(m2,type="pearson")
residuals(m3,type="pearson")
residuals(m4,type="pearson")  ## error (not available)

v <- family(m5)$variance
p <- predict(m5,zitype="zprob")  ## z-i probability
mu <- predict(m4,zitype="conditional")  ## mean of conditional distribution
pred <- predict(m4,zitype="response") ## (1-p)*mu
## sigma(.) = k = theta = overdispersion parameter ...
k <- sigma(m5)
pvar <- (1-p)*v(mu,k)+mu^2*(p^2+p)
pearson_resid <- (dd$Aetot-pred)/sqrt(pvar)


from Zuur, Alain F, Anatoly A Saveliev, and Elena N Ieno. Zero Inflated Models and Generalized Linear Mixed Models with R. Newburgh, U.K.: Highland Statistics Ltd., 2012:

[zi_pearson]<https://user-images.githubusercontent.com/78918/35686317-02884a46-073a-11e8-8dcd-3546e159e7a0.png>

**Comment by stephrivest** [comment]
Hello,

I am also new to glmmTMB! It's wonderful that you have worked out calculating the Pearson residuals for nbinom2 family, but I was wondering if this has been worked out for any of the other families available in glmmTMB? Specifically, I have fitted a Poisson distributed ziglmm and am trying to assess if overdispersion is happening. How can I check for overdispersion?

Stephanie R
