### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#214]
I think we're ready to submit to CRAN. Any objections?

**Comment by mebrooks** [comment]
It passed all the checks: `R CMD check --as-cran` with current and development versions of R on my computer. Kasper also ran it on Winbuilder a week ago.

**Comment by bbolker** [comment]
Depending on how much of a hurry you're in, I'd kind of like to fix #209 first.  Can we give me a deadline of getting to it over the weekend ... ?

**Comment by mebrooks** [comment]
Sure. That's no problem.

**Comment by mebrooks** [comment]
Should I go ahead and submit today?

**Comment by mebrooks** [comment]
I submitted! I'll keep you posted if anything major comes up.

**Comment by mebrooks** [comment]
The package was accepted! That was easier than I expected, but I'm sure that's because of all your expertise that went into development with that goal in mind. Thanks you all!
