### ISSUE TITLE
Update documentation and code for "allow.new.levels" option in predict function

### ISSUE THREAD

**Issue by casperwberg** [glmmTMB/glmmTMB#222]
Unlike what it says in the documentation, predicting new levels of a random effect grouping factor works fine, for example: 

data(sleepstudy,package="lme4")
g0 <- glmmTMB(Reaction~Days+(Days|Subject),sleepstudy)
tmp <- sleepstudy[1,]
tmp$Subject="fake"
nd <- rbind(sleepstudy,tmp)
predict(g0, newdata=nd, se.fit=TRUE)

**Comment by kaskr** [comment]
It should be safe to say that `predict.glmmTMB` will work for new random effects as long as the model's parameter specification is unchanged. But who is responsible for checking this - the user or glmmTMB ?

The following example is similar to the previous. We attempt to predict a new random effect but this time not realizing that we are also expanding the model parameter vector:

```.R
sleepstudy <- transform(sleepstudy, DaysFac = factor(cut(Days,2)) )
g1 <- glmmTMB(Reaction ~ Days + (DaysFac|Subject), sleepstudy)
tmp <- sleepstudy[1,]
tmp$DaysFac <- "fake"
predict(g1, newdata=tmp) ## Nonsense output - should give error
```
