### ISSUE TITLE
No Pearson residuals for models with dispersion models or zero-inflation

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#229]
I'm working on improving `families.R` on the `families` branch. I added a check so that we don't produce Pearson residuals in models with zero-inflation. Should I also do this for models with dispersion models? Right now `residuals.glmmTMB` calls `sigma.glmmTMB`, which is only designed to work with a single value in `betad`. It should be possible to calculate Pearson residuals for non-standard models, but it will require overhauling `residuals.glmmTMB`.

**Comment by bbolker** [comment]
Yes, I think so.  In general errors are (much!) better than wrong answers, and specific/informative/upstream errors are better than letting the code fall through to a place where it causes an error as a side effect.
