### ISSUE TITLE
add tweedie?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#231]
Given that a [TMB Tweedie example](https://github.com/kaskr/adcomp/blob/master/tmb_examples/tweedie.R) already exists, it would be nice to incorporate the capability to use Tweedie responses into glmmTMB ...

**Comment by kaskr** [comment]
A free `p` parameter in `VY=a*EX^p` would not fit well into our current framework. We could of course fix it but that wouldn't be so useful. What do you think @bbolker  ?

By the way: Note that we only have the compound Poisson–gamma case (`1<p<2`) available in TMB.

**Comment by bbolker** [comment]
If I understand correctly the limitation with our current framework is that we only allow a single dispersion/shape parameter?

**Comment by kaskr** [comment]
Yes, that was my point.

We would have to expand the cpp template with extra family specific parameters, e.g.

```cpp
PARAMETER_VECTOR(thetad); // default: length zero
```

**Comment by mebrooks** [comment]
Done in pull #239
