### ISSUE TITLE
systematic segfault

### ISSUE THREAD

**Issue by meriops** [glmmTMB/glmmTMB#232]
Hi,
After having installed `glmmTMB` without any (apparent) problem, I get a segfault every time I try to run the examples from `glmmTMB()` ... not really sure what to do here... For what it's worth, it's an archlinux box with r-mkl.

**Comment by bbolker** [comment]
Well that's not good.  Hopefully the TMB experts here can suggest some diagnostic steps ...

**Comment by kaskr** [comment]
@meriops 
Try to run
```.R
library(TMB)
```
from a clean R session. Do get a warning about the Matrix package version ?
Try to run a simple example:
```R
runExample("simple")
```
Do you get a segfault here as well ? If yes, please post the output.

**Comment by meriops** [comment]
In a clean R session, 
```
library(TMB)
```
does not return any warning. 

The simple example: 
```
runExample("simple")
```
aborts and returns what seems to be an out-of-bound error (as per [section 7.2.1] in the documentation(http://kaskr.github.io/adcomp/_book/Errors.html#out-of-bounds-error)). Here are the last lines of the output: 
```
x <- as.numeric( A %*% beta + B %*% u + eps  )
  Note: method with signature ‘Matrix#numLike’ chosen for function ‘%*%’,
  target signature ‘dgTMatrix#numeric’.
  "TsparseMatrix#ANY" would also be valid
  Note: method with signature ‘sparseMatrix#matrix’ chosen for function
  ‘%*%’,
  target signature ‘dgTMatrix#matrix’.
  "TsparseMatrix#ANY" would also be valid

> ## Fit model
> obj <- MakeADFun(data=list(x=x, B=B, A=A),
  +                  parameters=list(u=u*0, beta=beta*0, logsdu=1,
    logsd0=1),
  +              .... [TRUNCATED]
  TMB has received an error from Eigen. The following condition was not
  met:
  index >= 0 && index < size()
  Please check your matrix-vector bounds etc., or run your program
  through a debugger.
  zsh: abort (core dumped)  R --no-save --quiet --no-init-file
```

**Comment by kaskr** [comment]
We need a little more:

*   ```
    packageVersion("TMB")
    packageVersion("Matrix")
    packageVersion("RcppEigen")
    sessionInfo()
    ```
* Do you get the same segfault with:
    ```
    runExample("randomregression")
    ```
* I'd also like to see the compilation output.
* If you are willing to debug a bit try this from terminal:
    ```shell
    R -d gdb
    run
    TMB:::runExample("simple", flags="-O0 -g", clean=TRUE)
    bt
    ```
    and post the backtrace. Relevant lines are probably in `#0-#5`.

**Comment by bbolker** [comment]
Is this a 32-bit system?  I'm not sure how widely this has been acknowledged, but there is a problem with Matrix 1.2-8 on 32-bit OSs: see [this StackOverflow question](http://stackoverflow.com/questions/42374635/r-lme4-error-in-usr-lib-rstudio-bin-rsession-malloc-memory-corruption/42674915#42674915). If you're on a 32-bit system, try downgrading to Matrix 1.2-7 (e.g. `devtools::install_version("Matrix","1.2-7")`) and see if that helps ...

**Comment by meriops** [comment]
@bbolker : 
This is a 64 bit system (Archlinux with kernel 4.10.6)

@kaskr: 
TMB : version 1.7.8, 
Matrix: 1.2.8
RccpEigen: 0.3.2.9.1

R is version 3.3.3 svn rev 72310 as built with MKL from [r-mkl](https://aur.archlinux.org/packages/r-mkl), although I am not entirely certain that the linking with MKL is completely right...

```r
sessionInfo()
  R version 3.3.3 (2017-03-06)
  Platform: x86_64-pc-linux-gnu (64-bit)
  Running under: Arch Linux
  locale:
  [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C
  [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8
  [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8
  [7] LC_PAPER=en_US.utf8       LC_NAME=C
  [9] LC_ADDRESS=C              LC_TELEPHONE=C
  [11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C
  attached base packages:
  [1] stats     graphics  grDevices utils     datasets  methods  base
  ther attached packages:
  [1] TMB_1.7.8
  loaded via a namespace (and not attached):
    [1] colorspace_1.3-2 Matrix_1.2-8     DBI_0.6          Rcpp_0.12.10
     [5] grid_3.3.3       lattice_0.20-35
```
Running `runExample("randomregression")` returns the same error / segfault as `runExample("simple")`.

Finally running the command through gdb gives the following output (which is quite beyond me to be honest): [link to pastebin](https://paste.scratchbook.ch/view/1a89322c)

**Comment by kaskr** [comment]
@meriops 
Interesting. The model ran without segfault using compilation flags `-O0 -g`. This could indicate some sort of over optimization in your R configuration. That's why I'd be curious to see the output from the *compilation* of e.g. `runExample("simple",clean=TRUE)`.

**Comment by meriops** [comment]
[Here](https://paste.scratchbook.ch/view/4bc7b57e) is the compilation output without specifying any flag.

**Comment by kaskr** [comment]
@meriops 
That explains it. At present TMB is not very tolerant to setting the openmp flag for non parallel implementations. It uses the `_OPENMP` preprocessor flag to signify that the template is parallelized. Non-parallel code like glmmTMB will crash.

Having `-fopenmp` as part of `R CMD config CXXFLAGS` is not standard. None of the configurations in https://cran.r-project.org/doc/manuals/r-release/R-admin.html does that. Why not use `SHLIB_OPENMP_CXXFLAGS` ?

An easy workaround is to make your own `~/.R/Makevars` with modified `CXXFLAGS`.

**Comment by meriops** [comment]
Right. It turns out `-fopenmp` was "hard set" by the AUR script building the package. Once that adjusted, both `TMB` and `glmmTMB` seem to run fine.
Thank you both @kaskr  and @bbolker for your time and dedication!
