### ISSUE TITLE
oddities with getME/environments and retrieving cached results from knitr/render

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#234]
Running the covstruct.rmd vignette, *with cached results* (haven't yet tried deleting the cache and starting again), running `getME(fit.us,"theta")` works fine (`fit.us` is a fitted model created in the course of the vignette).

However, if I start a clean R session and
- `rmarkdown::render("covstruct.rmd")`
- `print(fit.us)` ## fine
- `getME(fit.us,"theta")` ## all zero!
- `fit.us$obj$env$parList()` ## mostly uninitialized

Most of the other stuff in the environment looks uninitialized as well.

This isn't too hard to work around, but I wanted to document it.

**Comment by kaskr** [comment]
I corrected a bug in `getME` 270fb14f677413057291e6c9eb64c5a47ee816d8 - does this fix it ?

**Comment by bbolker** [comment]
fixed.  thanks!
