### ISSUE TITLE
incompatible with MuMIn::dredge

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#235]
Eventually it would be convenient if we could make `glmmTMB` compatible with `MuMIn::dredge`. This recently came up when someone wanted to dredge a simple `nbinom2` model and was tired of waiting for `lme4` to do it. I haven't looked into the machinery yet, but wanted to write it down before I forget.

**Comment by bbolker** [comment]
I think we just need to write `coeffs()`, `coefTable()`, and `getAllTerms()` methods (see `?MuMIn::coeffs`). The deeper/uglier question is whether it's possible to enable model averaging across more than just the conditional component of the model, and how we would do that ...

**Comment by mebrooks** [comment]
My opinion on model averaging is that it's ok to facilitate averaging the responses, but not the coefficients. [This article](http://rdcu.be/FsXL/) states "Sometimes the model-averaged regression coefficients for predictor variables are incorrectly used to make model-averaged predictions of the response variable when the models are not linear in the parameters." Since so many of our models are not linear in the parameters, I don't think we should waste time on averaging parameters.

**Comment by bbolker** [comment]
There's a small issue in the way that the NA-action is checked in MuMIn::.checkNaAction ...

naact is initially assigned as

    naact <- formals(eval(cl[[1L]]))$na.action

`formals(glmmTMB)$na.action`  is:

```
   $na.action
      getOption("na.action", default = na.fail)
```

Next we do this:

```
 if (!is.null(naact)) {
    naact <- as.character(naact)
    if (naact %in% naomi) 
        msg <- sprintf("%s uses the default 'na.action' = \"%s\"", 
            what, naact)
```

`naomi` is `c("na.omit","na.exclude")`

but `as.character(naact)` is weird -- it turns into

```
[1] "getOption" "na.action" "na.fail"  
```
so  `(naact %in% naomi)` is `c(FALSE,FALSE,FALSE)`

and the `if()` statement gives> the condition has length > 1 and only the first element will be used

   I can't think **imediately** of a simple way to fix this.  We could make the `na.action` argument in `glmmTMB` look more like `lm()`, which doesn't explicitly code the default behaviour in the formal arguments, but rather handles it internally ... 

From `?lm`:

> na.action: a function which indicates what should happen when the data
          contain ‘NA’s.  The default is set by the ‘na.action’ setting
          of ‘options’, and is ‘na.fail’ if that is unset.  The
          ‘factory-fresh’ default is ‘na.omit’.  Another possible value
          is ‘NULL’, no action.  Value ‘na.exclude’ can be useful.

**Comment by k-barton** [comment]
The `na.action` issue is now fixed (MuMIn version 1.40.5 on R-Forge:
```
install.packages("MuMIn", repos="http://R-Forge.R-project.org")])
```

but I agree with Ben that it would be better to have a formal argument without a default value (for consistency with the standard modelling functions).

**Comment by bbolker** [comment]
this is also resolved on the glmmTMB side by d864f53c35163d

**Comment by mebrooks** [comment]
This is really useful progress! I gave it a try and found a little bug. `dredge` is dropping RE in `ziformula`. It keeps RE in the conditional model.

```
library(glmmTMB)
library(MuMIn)
library(bbmle)
 
#models with RE in zi
m1=glmmTMB(count~mined, zi=~mined+(1|site), family="poisson", Salamanders)
m2=glmmTMB(count~mined, zi=~(1|site), family="poisson", Salamanders)
m3=glmmTMB(count~1, zi=~mined+(1|site), family="poisson", Salamanders)
m4=glmmTMB(count~1, zi=~(1|site), family="poisson", Salamanders)

#without RE
m1f=glmmTMB(count~mined, zi=~mined, family="poisson", Salamanders)
m2f=glmmTMB(count~mined, zi=~1, family="poisson", Salamanders)
m3f=glmmTMB(count~1, zi=~mined, family="poisson", Salamanders)
m4f=glmmTMB(count~1, zi=~1, family="poisson", Salamanders)

dredge(m1)
AICctab(m1f, m2f, m3f, m4f, logLik=TRUE, base=TRUE) #results match dredge
AICctab(m1, m2, m3, m4, logLik=TRUE, base=TRUE)
```

Here is an example showing it keeps the RE in the conditional model.
```
m5=glmmTMB(count~mined+(1|site), zi=~mined, family="poisson", Salamanders)
m6=glmmTMB(count~mined+(1|site), zi=~1, family="poisson", Salamanders)
m7=glmmTMB(count~(1|site), zi=~mined+1, family="poisson", Salamanders)
m8=glmmTMB(count~(1|site), zi=~1, family="poisson", Salamanders)
dredge(m5)
AICctab(m5, m6, m7, m8, logLik=TRUE, base=TRUE)
```

**Comment by mebrooks** [comment]
It's a problem with `update`, not with `dredge`.

**Comment by k-barton** [comment]
It is a problem with MuMIn's  `getAllTerms` and `makeArgs` (used by `dredge`) which handle random terms only for "cond" formula. I'm looking at it just now.

**Comment by k-barton** [comment]
It does seem to work correctly now with MuMIn 1.40.6 rev 419 (update the package from R-Forge). Note that the random effects are not manipulated by `dredge`.

**Comment by mebrooks** [comment]
Yep! I works great now. Thanks!

**Comment by julpauwels** [comment]
I tried using dredge on a glmmTMB model while specifying variables to be included in all models

```
> m = glmmTMB(activity ~ day + temperature + humidity + (1|city/point),data=data, family=nbinom2(link = "log"))
> dm = dredge(m, fixed = c("day"), trace=0)
```

 But it seems that the function doesn't understand the specification.

```
Fixed terms are "cond((Int))" and "disp((Int))"
Warning message:
In dredge(m, fixed = c("day"), trace = 0) :
  some terms in 'fixed' do not exist in 'global.model': "day"`
```

**Comment by k-barton** [comment]
The argument `fixed` expects model term names as given by `getAllTerms`. In this case this would be `"cond(day)"`.

**Comment by bbolker** [comment]
I guess we should document this in the vignette I'm working on that includes use of `MuMIn` with `glmmTMB`: https://github.com/glmmTMB/glmmTMB/blob/effects/glmmTMB/vignettes/model_evaluation.rmd

**Comment by k-barton** [comment]
I wrapped the term/coefficient names as `cond(X)` and `disp(X)` to be able to separate the two types of terms later on. But, this has a side effect that the conditional model terms do not match names from other model types, e.g. `glmer` (as in a model selection table). Now I'm thinking how to make them comparable. One idea is to use only `disp()` and leave the conditional terms as-is, but this is problematic, when e.g. user has a conditional term named `disp(x)` - it would be taken as the dispersion model coefficient. Another way would be to have an additional variable denoting the category, but that would have to be passed all the way to `dredge`/`model.sel`/`model.avg` which implies a lot of modifications in the code.
