### ISSUE TITLE
add mgcv::gam to benchmarks, discussion

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#238]
Gavin Simpson has done an example of [zero-inflated Poisson in mgcv::gam](https://gist.github.com/gavinsimpson/8a0f0e072b095295cf5f7af2762e05a7).  (Note that ZINB is *not* (apparently) available, just ZIP)

**Comment by mebrooks** [comment]
This is done in the new draft of the manuscript and https://github.com/glmmTMB/glmmTMB/blob/master/misc/timing_nbinom.pdf

It could also be added to benchmarks `vignette("glmmTMB")` which needs other updates.
