### ISSUE TITLE
improve modularity

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#246]
(slight braindump)

Over [here](https://github.com/bbolker/mixedmodels-misc/blob/master/notes/phylog.rmd) I've been putting together some code to do phylogenetic GLMMs with lme4 and glmmTMB. (It's very exciting!) The basic strategy is to (1) set up the model structures with a dummy random effect for phylogeny; (2) modify the Z matrix and related structures appropriately; (3) stick the modified structures back into the code and do the fit.

Some slight modifications to glmmTMB would make this easier. Currently, the `debug` option stops before fitting and returns the `TMBstruc`. I propose 
(1) (cosmetic) hanging the name of `debug` to `do_fit` (i.e., `do_fit=FALSE` returns information before fitting)
(2) make sure to return enough information that the returned structure is sufficient to complete the fit and make the final output object
(3) encapsulate the remaining R code (including the call to `makeADFun`) in  a single utility function

**Comment by kaskr** [comment]
I agree that 1-3 would be an improvement.
