### ISSUE TITLE
Segment fault with zero-inflated negative binomial distribution

### ISSUE THREAD

**Issue by TiphaineCMartin** [glmmTMB/glmmTMB#248]
Hi,

I try to change my model from glmmADMB to glmmTMB for zero inflated negative binomial distribution, but I have segment fault error.

Could you help me to use this new R package ?

Regards,
Tiphaine

pheno_null <- tryCatch({
glmmadmb(formula=cbind(readSuccess,readFail) ~ 1 + sex + age + (1|MZFamID),
data=dataMeth,
zeroInflation=TRUE, family="nbinom2"},
error=function(cond) {
print("glmmadmb null fail to converge. Error")
print(cond)
print("\n")
# Choose a return value in case of error
return(NULL)
},
warning=function(cond) {
print("glmmadmb null fail to converge. Warning")
print(cond)
print("\n")
# Choose a return value in case of warning
return(NULL)
},
finally={
print("glmmadmb null succeed to converge. OK")
}
)
I change to glmmTMB,
pheno_null <- tryCatch({
glmmTMB(formula=cbind(readSuccess,readFail) ~ 1 + sex + age + (1|MZFamID),
data=dataMeth,
ziformula=~1, family="nbinom2")
},
error=function(cond) {
print("glmmadmb null fail to converge. Error")
print(cond)
print("\n")
# Choose a return value in case of error
return(NULL)
},
warning=function(cond) {
print("glmmadmb null fail to converge. Warning")
print(cond)
print("\n")
# Choose a return value in case of warning
return(NULL)
},
finally={
print("glmmadmb null succeed to converge. OK")
}
)
######################
error message

 1: .Call("MakeADFunObject", data, parameters, reportenv, control = list(report = as.integer(ADreport)),     PACKAGE = DLL)
 2: retape()
 3: MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg,     profile = NULL, silent = !verbose, DLL = "glmmTMB")
 4: eval(expr, envir, enclos)
 5: eval(substitute(expr), data, enclos = parent.frame())
 6: with.default(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg,     random = randomArg, profile = NULL, silent = !verbose, DLL
 7: with(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg, [1]    random = randomArg, profile = NULL, silent = !verbose, DLL = "gl

 8: glmmTMB(formula = cbind(methCReadsGoodSamples, unmethCReadsGoodSamples) ~     1 + sex + age + (1 | MZFamID), data = dataMethylation,
 "##unmethCReadsGoodSamples 60" 9:
doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
12: doTryCatch(return(expr), name, parentenv, handler)
13: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
14: tryCatchList(expr, classes, parentenv, handlers)
15: tryCatch({    glmmTMB(formula = cbind(methCReadsGoodSamples, unmethCReadsGoodSamples) ~         1 + sex + age + (1 | MZFamID), data
16: glmmTMB.zinbmm.wald.2factor(TotalCTab[i, ], TotalTab[i, ], MethRateTab[i,     ], nameMainPhenotype, PhenotypeFile, groupSex, thresho
17: doTryCatch(return(expr), name, parentenv, handler)
18: tryCatchOne(expr, names, parentenv, handlers[[1L]])
19: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
20: doTryCatch(return(expr), name, parentenv, handler)
21: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
22: tryCatchList(expr, classes, parentenv, handlers)
23: tryCatch({    glmmTMB.zinbmm.wald.2factor(TotalCTab[i, ], TotalTab[i, ],         MethRateTab[i, ], nameMainPhenotype, PhenotypeFile,
    print("glmmTMB.zinbmm.wald.2factor. done")})
24: FUN(X[[i]], ...)
25: lapply(X = S, FUN = FUN, ...)
26: doTryCatch(return(expr), name, parentenv, handler)
27: tryCatchOne(expr, names, parentenv, handlers[[1L]])
28: tryCatchList(expr, classes, parentenv, handlers)
29: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doT
30: try(lapply(X = S, FUN = FUN, ...), silent = TRUE)
31: sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE))
32: FUN(X[[i]], ...)
33: lapply(seq_len(cores), inner.do)
34: mclapply(1:numCpGsites, mc.cores = cpucores, function(i) {    print(i)    results <- NULL    nameCpG <- rownames(TotalCTab[i, ])
An irrecoverable exception occurred. R is aborting now ...

###################
SessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux release 6.6 (Carbon)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] glmmTMB_0.1.1

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-45     Matrix_1.2-6    TMB_1.7.10
 [5] Rcpp_0.12.10    splines_3.3.0   nlme_3.1-128    grid_3.3.0
 [9] nloptr_1.0.4    lme4_1.1-12     lattice_0.20-33

**Comment by bbolker** [comment]
There are two problems here.

- a negative binomial distribution is not appropriate for modeling a proportional response in any case
- the *Details* sections of `?glmmTMB` says:

> binomial models with more than one trial (i.e., not binary/Bernoulli) must be specified in the form ‘prob ~ ..., weights = N’ rather than in the more typical two-column matrix (‘cbind(successes,failures)~...’) form.

However, your report suggests that we should put some more tests in place to (1) prevent segfaults and (2) provide an informative error message

**Comment by TiphaineCMartin** [comment]
Hi,

thanks for this quick answer.

I don't know if you are familiar with next generation sequencing data, but I have different probabilities for each sample and idem for the number of trial as they represent number of reads that map in a region and the number of reads with a specific features (methylated versus unmethylated CpG sites).
I applied this models for about 4M CpG sites the same models. 

Can I put a vector of probability and a vector of weights in this case?

My issue is that for most of CpG site, I have zero-inflated distribution. In theory, we uses beta-binomial distribution, can I define zero-inflated beta-binomial distribution with glmmTMB?

Regards,
Tiphaine

**Comment by bbolker** [comment]
zero-inflated beta-binomial is possible.
if the fraction of (e.g. methylated) reads is small, then you can use a nbinom with log(reads) as an offset.
May I suggest that follow-ups go to `r-sig-mixed-models@r-project.org`, as these are more general modeling questions?
