### ISSUE TITLE
document and improve confint

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#252]
- report (Wald) confidence intervals on dispersion parameters?
- `confint.glmmTMB` is not documented, that I can see. Also not sure that the `component` argument works as expected
- we should add some a parameter (`scale`?) to determine whether parameters/confidence intervals get returned on the link scale or the response (back-transformed) scale (it's not clear that back-transforming makes sense for models other than scalar (intercept-only) models; should at least warn in this case).

 
```
m1    <- glmmTMB(count~spp + (1|site), zi=~1, family=nbinom2, Salamanders)
confint(m1,component=c("cond","zi","disp"))
confint(m1,component=c("cond","zi","disp"))
                      2.5 %     97.5 %
cond.(Intercept) -1.2098766  0.1217612
cond.sppPR       -1.9086644 -0.7818989
cond.sppDM       -0.0871990  0.7892348
cond.sppEC-A     -1.2181834 -0.2257421
cond.sppEC-L      0.1292543  0.9925527
cond.sppDES-L     0.3495698  1.2007994
cond.sppDF       -0.1734744  0.7410111
zi.(Intercept)           NA         NA
disp.(Intercept)         NA         NA
```

**Comment by mebrooks** [comment]
#263 #266 #267
