### ISSUE TITLE
Make ranef.glmmTMB class compatible with ranef.mer class

### ISSUE THREAD

**Issue by twolodzko** [glmmTMB/glmmTMB#256]
I used glmmTMB to fit a LMM (to compare the results with lme4 as I had minor convergence issues), when I wanted to plot the random effects, I found that the function that worked for lme4

```r
dotplot(ranef(fit_lmer))
```

does not work for glmmTMB and instead I need to use

```r
dotplot(structure(ranef(fit_glmmTMB)[[1]], class = "ranef.mer"))
```

I understand that the output for GLMM's can differ as compared to LMM's, but maybe the resulting objects could be made more compatible so that such "hacks" are not needed?

**Comment by bbolker** [comment]
The main problem is that `glmmTMB` objects may have several different `ranef` structures (e.g. one for the conditional model and a different one for the zero-inflation model or dispersion model).  I would say that

```
lme4:::dotplot.ranef.mer(ranef(m1)$cond)
```

is a slightly more principled hack, but I agree it's a hack.  We could easily write our own (thin) wrapper around `dotplot.ranef.mer` (if it were exported from `lme4`) that would plot a specified component of the random effects ...

**Comment by bbolker** [comment]
FWIW `dotplot.ranef.mer` was exported in the most recent version of `lme4` (1.1-15, on CRAN now) so this could be finished ...
