### ISSUE TITLE
Parameterization of binomial model. 

### ISSUE THREAD

**Issue by fishfollower** [glmmTMB/glmmTMB#259]
Specifying binomial models with (observed count x out of N) in glmmTMB is currently done by setting the response variable to the fraction x/N and including N as a weight argument. This should be reconsidered for two reasons. 

The simulate() method returns integer counts, which seems a bit inconsistent. 

The one-obs-ahead residual calculation is difficult because the discrete support of the response variable is different for each different N.   

Should we make it such that the response is specified with a cbind(x,N-x), and update the simulate method? Most importantly the internal part should work such that the binomial density is called with x as it argument).

**Comment by mebrooks** [comment]
If I remember correctly, @bbolker and @mmaechler  had reasons for not wanting to open that can of worms. I think I would struggle a lot to rewrite the R-side of glmmTMB in this way.

**Comment by bbolker** [comment]
Brief comment.

I think I felt more strongly than @mmaechler; I think he commented recently in another (lme4?) context that the proportion/weights specification makes it harder to deal with a case of user-specified weights that have some meaning other than the number of cases.

My main complaint about the two-column response case is that it leads to lots of special-case code.

FWIW the two-column syntax does work at present, but it gives a warning saying that the other syntax is preferred. 
```
> library(glmmTMB)
> library(lme4)
> ?cbpp
> g1 <- glmmTMB(cbind(incidence, size - incidence) ~ period + (1 | herd), family=binomial, data = cbpp)
Warning message:
In glmmTMB(cbind(incidence, size - incidence) ~ period + (1 | herd),  :
  binomial models with N>1 are preferably specified as proportion~..., weights=N
```

**Comment by fishfollower** [comment]
Dear all, 

I understand the desire to avoid special-case code, but at the same time, it is convenient to be compatible with glmer/glm.  Currently, the two-column format does not work (the way I expect). Consider the example below. I would have expected those two calls to give the same result. 

Cheers, 

Anders. 

library(glmmTMB)
set.seed(123)
n<-rpois(100,12)+1
x<-rbinom(100,size=n,prob=.3)
dat<-data.frame(x=x,n=n,f=x/n)
f1<-glmmTMB(f~1, data=dat, weights=n, family=binomial)
f2<-glmmTMB(cbind(x,n-x)~1, data=dat, family=binomial)
logLik(f1)
### 'log Lik.' -189.1848 (df=1)
logLik(f2)
### 'log Lik.' -60.632 (df=1)

**Comment by kaskr** [comment]
I'll look into it now !

**Comment by bbolker** [comment]
OK, at present the two-column results are simply wrong. I haven't looked to see what's happening yet. For the  immediate future we should replace the warning with an error.

> The simulate() method returns integer counts, which seems a bit inconsistent.

It could return a proportion instead? (There are minor floating-point issues with this - `(x/N*N)` is not necessarily equal to `N` - but I don't know if that's a big deal.)

> The one-obs-ahead residual calculation is difficult because the discrete support of the response variable is different for each different N.

Not sure why this is yet (haven't looked yet)

> Should we make it such that the response is specified with a cbind(x,N-x), and update the simulate method? Most importantly the internal part should work such that the binomial density is called with x as it argument).

Don't entirely understand this (but haven't looked at the code).

**Comment by kaskr** [comment]
@bbolker 

I'll see if I can make it work with both the proportion-weights and the 2-column now.

**Comment by kaskr** [comment]
Problem with @fishfollower's example is that `weights` are set to one for `f2` fit.

**Comment by mmaechler** [comment]
Yes, @bbolker : I am rather prefering the two column form - for the reason you correctly remembered, and also it is cleaner: the 2-col form uses integer (values) and is a "crisp" binomial setup.  proportions and weights are both "real" (proportions are almost always non-integer,  weights *should* be integer if there are no other weights, but because there can be other weights "multiplied in", you cannot require integer weights.  The  (prop,  wts)  input is therefore really more messy, and hence "less crisp" than the 2-col + optional weights situp.   And you did very appropriately mention `simulate()`: There its even much more natural to get back integers and nothing else.

**Comment by mebrooks** [comment]
I have been experimenting with weights and it's going well. They do what I want for at least Poisson GLMMs and gaussian LMs. Now I need to make them do the right thing in the binomial case. We want the flexibility of having a zero-inflated binomial model; so weights need to be applicable to the zero-inflation part of the model. To enable this, I think we need to stop using weights as the number of trials. This will mean the option of specifying the response as a proportion and weights will be deprecated. Kasper and I started discussing the changes that need to be made in the code. One change is that I will remove the call to `family$initialize`; I think (other than in binomial models) this only does some checks, but doesn't actually set initial values or make any changes to objects that we use. Of course, I will make sure that this doesn't break anything besides the binomial examples with responses as proportions. I will make sure that we can still specify binary data in a single column. I just wanted to confirm before I start with the changes...are there any objections to deprecating the response being specified as a proportion to enable the other flexibility?

**Comment by kaskr** [comment]
For backwards compatibility I guess it's no problem to detect this special case and set:

```
yobs <- proportion * weights
size <- weights
weights[] <- 1
```

C++ side must me modified to include `DATA_VECTOR(size)` anyway.

**Comment by mmaechler** [comment]
I agree with the deprecation of  the "misuse" (sorry, Ben) of specifying proportions+weights for binomial,
and would consider the   cbind(k, n-k) ~ ...  to be the "default" way ... apart from the "logistic" case where allowing  y = 0 or 1   should continue to work.

I'm a bit wary about your proposal to call  `family$initialize`.  This is somehow belongs to the API of using families with glms in S and R.  Conceptually, there is an "infinite" number of possible user-specified families (family / link combinations even) and in principle the user can expect `*$initialize()` to work the same as in `glm()`.   I do think you should deprecate in a different way.

**Comment by mebrooks** [comment]
@mmaechler, I think there might be a miscommunication. I'm proposing to *not* call `family$initialize`.

**Comment by kaskr** [comment]
@mebrooks I think you missed the **stop** which was added later by @mmaechler

**Comment by kaskr** [comment]
Currently `eval(family$initialize)` is doing the following job:

* It sets initial values - that we do not use.
* It re-defines 'yobs' and 'weights' in a way we have to work around.
* It executes arbitrary code in our workspace that could in principle have side-effects.
* It throws an error if observations are outside the valid range.

Of these, only the last point seems useful. So, rather than skipping
it completely, I'd suggest changing to:

`local(eval(family$initialize))`

**Comment by mebrooks** [comment]
This sounds like a good solution to me. We can keep the checks but eliminate the unwanted/useless behavior.

**Comment by mebrooks** [comment]
As of #272, there are 4 ways to specify the binomial:

- yobs could be a factor -> treat as binary following glm
- yobs could be cbind(successes, failures)
- yobs could be binary
- (yobs, weights) could be (proportions, number of trials)
 
On the C++ side yobs must be the number of successes.
