### ISSUE TITLE
Likelihood function returns NAs

### ISSUE THREAD

**Issue by koenvanbenthem** [glmmTMB/glmmTMB#265]
Hi all,

I am running glmmTMB-0.1.3 on ubuntu 14.04 LTS. When I run the first example, I get:
>  > (m1 <- glmmTMB(count~ mined + (1|site),  zi=~mined,  family=poisson, data=Salamanders))

> Error in nlminb(start = par, objective = fn, gradient = gr, control = control$optCtrl) : 
>  gradient function must return a numeric vector of length 5
> In addition: Warning message:
> In nlminb(start = par, objective = fn, gradient = gr, control = control$optCtrl) :
>  NA/NaN function evaluation
> Timing stopped at: 0.612 0.027 0.763

diving into the function revealed that the generated likelihood function (obj) indeed returns NA at the starting values (all 0). (obj$fn(obj$par) and obj$gr(obj$par) both return NaN in the function fitTMB). When no random effect is present, the model runs fine.

I had the same problem with the Owl example. Any ideas?

**Comment by kaskr** [comment]
Sounds like what one gets when the Matrix and TMB packages are out of sync.
Do you get a warning when running
```
library(TMB)
```
in a new R session ?
