### ISSUE TITLE
NEWS file?

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#279]
I was wondering if there's a - more or less - systematic news file, which lists all the changes in the latest package version?

**Comment by mebrooks** [comment]
I haven't figured out how to do that yet, but it's a good idea. Before the next CRAN release, I'll have to look at other packages to see how it's done. I think the only changes between the last two CRAN versions were to 

- fix output of models with ar1 random effects
- add ability to do weighted regression in a way that matches the `glm` function

**Comment by strengejacke** [comment]
Thanks!
You can just add a plain text file names `NEWS` to the same directory as the `DESCRIPTION` file, or you can use a markdown file (`NEWS.md`). Both will be recognized on the CRAN page, the first option also in the package help file from within R.

**Comment by bbolker** [comment]
More formally/official, see `?news` in R: the news file should go in `inst/NEWS.Rd`, and has a very particular (and rather finicky) format: see e.g. https://github.com/lme4/lme4/blob/master/inst/NEWS.Rd

**Comment by mmaechler** [comment]
Yes, @bbolker, but I think the `inst/NEWS.Rd`  format is well worth using IMO.

**Comment by bbolker** [comment]
I agree.

**Comment by bbolker** [comment]
I added `inst/NEWS.Rd`. I didn't do any archaeology, just added the changes going forward. Leaving this open to remind people that it might still be a good idea to fill in some of the past history.

**Comment by mebrooks** [comment]
I'm getting ready to add 2 more families and was about to update `inst/NEWS.Rd`. It starts with `\section{CHANGES IN VERSION 0.2.1}` but we're on version 0.2.0.9100. Should I change the section heading?

I'm planning to increment the version number up for the new families. Does anyone have an opinion about how big of an increment some new families should be?  Should I go to 0.2.1.0 now?

**Comment by mebrooks** [comment]
Ok, I get it. The news file version number is what the next number on CRAN will be. We keep adding to that until we're ready to submit to CRAN.

**Comment by strengejacke** [comment]
Yes, I think this issue can be closed now. I'm not sure if a history back to version 0.1.x or even 0.0.x is necessray for users.
