### ISSUE TITLE
"estimate" column in confint?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#283]
this is only a question of style, but: adding an "estimate" column to the output of `confint()` seems weird to me (it's definitely not the standard output from other `confint()` methods in R).  I guess I don't mind if the default is FALSE, but at the moment it's TRUE.

Is there a strong argument for keeping the default TRUE?

**Comment by kaskr** [comment]
The estimate column is useful to match the CIs with the printed output. We figured that users will be unaware the option exits if it's not enabled by default. Being able to know what the CI actually means seems so important that it may justify a little weirdness?

Example:

```
example(glmmTMB)
confint(m2)
```

Without the estimate column it's hard to match

```
                                    2.5 %     97.5 %   Estimate
cond.Std.Dev.site.(Intercept)  0.16670592  0.8658631  0.3799270
sigma                          0.92943583  2.4585852  1.5116538
```

with the printed output

```
> print(m2)
Formula:          count ~ spp + mined + (1 | site)
Zero inflation:         ~spp + mined
Data: Salamanders
      AIC       BIC    logLik  df.resid 
1670.2990 1750.7176 -817.1495       626 
Random-effects (co)variances:

Conditional model:
 Groups Name        Std.Dev.
 site   (Intercept) 0.3799  

Number of obs: 644 / Conditional model: site, 23

Overdispersion parameter for nbinom2 family (): 1.51 

Fixed Effects:

Conditional model:
(Intercept)        sppPR        sppDM      sppEC-A      sppEC-L     sppDES-L  
    -0.6104      -0.9637       0.1707      -0.3871       0.4879       0.5895  
      sppDF      minedno  
    -0.1133       1.4294  

Zero-inflation model:
(Intercept)        sppPR        sppDM      sppEC-A      sppEC-L     sppDES-L  
     0.9100       1.1614      -0.9393       1.0424      -0.5623      -0.8930  
      sppDF      minedno  
    -2.5398      -2.5630  
```

**Comment by bbolker** [comment]
OK. I'm still not wild about it/would like to a find a better approach, but at least I understand the rationale.
