### ISSUE TITLE
Comparing regression coefficients of different models in a plot

### ISSUE THREAD

**Issue by SergioERamos** [glmmTMB/glmmTMB#302]
Dear all, 
I would be very grateful with your help with the following puzzle, as I am quite new with ZIGLMM's.
Using the Owls data and the glmmTMB package, I want to compare different zero-Inflated models that differ in the family used (ZIPOISS, ZINB1, ZINB2) and with/out the offset (logBroodSize). The first part of the code with the models follows:

`data(Owls,package="glmmTMB")`
`Owls= plyr::rename(Owls, c(SiblingNegotiation="NCalls"))
Owls= transform(Owls,
                 ArrivalTime=scale(ArrivalTime, center=TRUE, scale=FALSE),
                 `obs=factor(seq(nrow(Owls))))`

# Zero-Inflation Models

```
zipoiss<-glmmTMB(NCalls~(FoodTreatment+ArrivalTime)*SexParent+
offset(logBroodSize)+(1|Nest),
data=Owls,
ziformula = ~ 1,
family="poisson")
```

```
zinb2<- glmmTMB(NCalls~(FoodTreatment+ArrivalTime)*SexParent+
offset(logBroodSize)+(1|Nest),
data=Owls,
ziformula = ~ 1,
family="nbinom2")
```

```
zinb1 <- glmmTMB(NCalls~(FoodTreatment+ArrivalTime)*SexParent+
offset(logBroodSize)+(1|Nest),
data=Owls,
ziformula = ~ 1,
family="nbinom1")
```

```
zinb1_bs<- glmmTMB(NCalls~(FoodTreatment+ArrivalTime)*SexParent+ 
BroodSize+(1|Nest),
data=Owls,
ziformula = ~ 1,
family="nbinom1")
```

```
zinb2_bs<- glmmTMB(NCalls~(FoodTreatment+ArrivalTime)*SexParent+
BroodSize+(1|Nest),
data=Owls,
ziformula = ~ 1,family="nbinom2")
```

# Comparing the AIC of the models with package(bbmle)
`AICtab(zipoiss, zinb1, zinb2, zinb1_bs, zinb2_bs) `# it works...

# Getting the coefficients, with library(broom)

```
modList= list(zipoiss, zinb1, zinb2, zinb1_bs, zinb2_bs) # to arrange all the coefficients 

coefs= ldply(modList,tidy,effect="fixed",conf.int=TRUE,
              .id="model") %>%
    mutate(term=abbfun(term)) %>%
    select(model,term,estimate,conf.low,conf.high) %>%
    filter(!term %in% `c("Intercept","Intercept.1","NCalls","zi_NCalls"))
```

# I get an error:
_Error in as.data.frame.default(x) : 
  cannot coerce class ""glmmTMB"" to a data.frame
Also: Warning message:
In tidy.default(X[[i]], ...) :
  No method for tidying an S3 object of class glmmTMB , using as.data.frame_

I've tried different modifications of this last part of the code but cannot make it work, I'm stuck here :( , and after getting this part right, I would like to plot the coefficients to have the following kind of plot  (made with package "coefplot2" from glmmADMB models, taken from B.Bolker _et al_ http://glmmadmb.r-forge.r-project.org/glmmADMB.pdf page 7):

![image](https://user-images.githubusercontent.com/36669684/36965468-062796aa-205a-11e8-85fc-16637bc4d37c.png)

When that part of the code works, this would be the code for plotting (according to the supplementary material of https://journal.r-project.org/archive/2017/RJ-2017-066/index.html where they compare models from different R packages), of course I haven't reached that far yet:

```
gg0= ggplot(coefs, aes(color=model,shape=model,y=term, x=estimate))+
    labs(x="Regression estimate",y="")+
    geom_pointrangeh(aes(xmax=conf.high, xmin=conf.low),
                     position = position_dodgev(height = 0.6))+
     ## flip legend to match order in plot
     guides(colour = guide_legend(reverse = TRUE),
            shape =  guide_legend(reverse = TRUE))

gg1 = gg0 + scale_colour_brewer(palette="Set1")+
    scale_shape_manual(values=15:20)
print(gg1)
```

Finally, my aim is to fully understand model comparisons of glmm zero-inflated models using the owls data and then implement it with my own data, which is simpler as I have only one fixed effect and one random, and a third term which is the interaction between the fixed and the random for example:

`m1<- glmmTMB(Nseeds ~ treatment + (1|replicate) + (1|replicate:treatment), zi=~treat, family=nbinom2, data=fd)`

In my case "treatment" has 6 levels and "replicate" has 3 levels, and I have zero inflation (see the following histograms for two of my response variables, I included them to give an idea of my data). I don't have more variables as to include an offset, I just would like to get the models that best fit to my data, and I have to do many comparisons changing the order of the treatments every time to get the pairwise comparisons as a kind of _posthoc_ (is there a proper way to do this?). Apart of this, I have other counting response variables to model, that's why I think that plotting the regression coefficients would really be helpful to visually see the main differences among models regarding significant terms and other important differences. 

![image](https://user-images.githubusercontent.com/36669684/36968366-9e824e6a-2062-11e8-9e44-61189ee0cc66.png) 
![image](https://user-images.githubusercontent.com/36669684/36968447-ce6b541e-2062-11e8-8106-dd7b55b9cb56.png)

Thanks a lot in advance for your invaluable help and time with this issues. Any observations made regarding my own data would be absolutely welcome too.

**Comment by mebrooks** [comment]
Did you already try the advice I gave in a private email? 

> On page 394 of the paper (appendix), there’s a comment about how to install it
devtools::install_github("bbolker/broom")
Also, have you looked at the supplementary material here https://journal.r-project.org/archive/2017/RJ-2017-066/index.html ? That should contain all the necessary code, but let me know if it doesn’t.

**Comment by mebrooks** [comment]
This part of your error `In tidy.default(X[[i]], ...) :
No method for tidying an S3 object of class glmmTMB , using as.data.frame` makes me think you do not have the right version of broom installed.

Can you try 
`??tidy.glmmTMB`
If you have the correct version of broom installed, then there should be a topic `glmmTMB_tidiers`.

**Comment by mebrooks** [comment]
Here is a related discussion on [R-sig-mixed](https://stat.ethz.ch/pipermail/r-sig-mixed-models/2017q4/026142.html). I think that is a more appropriate place for this question.

**Comment by SergioERamos** [comment]
Well, this is the only version of "broom" that finally worked in my computer from `devtools::install_github("bbolker/broom")`
Now, `??tidy.glmmTMB` gives no results from the web, typing `tidy` gives```
 function (x, ...) 
UseMethod("tidy")
<environment: namespace:broom>
``` 
What does this mean...

**Comment by bbolker** [comment]
do please follow up on R-sig-mixed-models@r-project.org (google the info page to subscribe before posting).  You should try *either* `devtools::install_github("bbolker/broom")` (I've just updated the version number so that we should be able to tell for sure that you're using the right version) or `devtools::install_github("bbolker/broom.mixed")` (a new package I'm developing that splits the mixed-model stuff off from the `broom` package)
