### ISSUE TITLE
Not able to install glmmTMB

### ISSUE THREAD

**Issue by doctsh** [glmmTMB/glmmTMB#303]
I have tried to install the glmmTMB package on my centOS by all methods described. But everytime it fails.
The errors like: 
* installing *source* package ‘glmmTMB’ ...
** package ‘glmmTMB’ successfully unpacked and MD5 sums checked
** libs
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/home/siva/R/x86_64-redhat-linux-gnu-library/3.4/TMB/include" -I"/usr/lib64/R/library/RcppEigen/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c glmmTMB.cpp -o glmmTMB.o
{standard input}: Assembler messages:
{standard input}:253312: Error: undefined symbol `.LLSDACSE11010' in operation
g++: Internal error: Killed (program cc1plus)

make: *** [glmmTMB.o] Error 1
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/home/siva/R/x86_64-redhat-linux-gnu-library/3.4/glmmTMB’
Warning in install.packages :
  installation of package ‘glmmTMB’ had non-zero exit status
Can anyone please help me?

**Comment by kaskr** [comment]
@doctsh 
What do you get when installing other packages from source ? E.g. does `install.packages("lme4")` work ?

**Comment by doctsh** [comment]
@kaskr 
I am able to install various several packages without any issue. Even now I have installed lme4 and got this:
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (lme4)
Making 'packages.html' ... done

**Comment by kaskr** [comment]
Try searching for the message:
`g++: Internal error: Killed (program cc1plus)`
Seems to signify an out of memory error.

**Comment by doctsh** [comment]
I increased memory also enabled swap as found elsewhere but still getting same error

**Comment by bbolker** [comment]
Possible that you have an old g++ version? `g++ --version` ? What CentOS version (`rpm --query centos-release`) ?

**Comment by kaskr** [comment]
@doctsh

To investigate further whether this is a glmmTMB specific problem you may also want to try other R packages with heavy C++ template usage. What happens if you do `install.packages("rstan")` ?

A few ideas to reduce compilation memory: For `gcc` try adding `--param ggc-min-expand=10` to `CXXFLAGS` (via `~/.R/Makevars`).

Or, try the `clang` compiler by setting `CXX=clang++` (in same file).

**Comment by doctsh** [comment]
@bbolker 
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
centos-release-6-9.el6.12.3.x86_64

**Comment by doctsh** [comment]
@kaskr 
yup installing rstan gives the below error:
```
make: *** [lang__grammars__statement_grammar_inst.o] Error 1
ERROR: compilation failed for package 'rstan'
* removing '/usr/lib64/R/library/rstan'

The downloaded source packages are in
        '/tmp/RtmpwnW6NX/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("rstan") :
  installation of package 'rstan' had non-zero exit status
```

**Comment by bbolker** [comment]
Maybe not surprising that CentOS 6.9 is having trouble?  https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule says 6 is "older but still supported".  [This](https://github.com/stan-dev/rstan/issues/242) is a Stan installation issue (unresolved, unfortunately) that looks related (with CentOS 6.6, from a few years ago) ...

I don't know if it's worth heading down the [rabbit hole of installing newer GCC](https://www.vultr.com/docs/how-to-install-gcc-on-centos-6) ...

**Comment by bbolker** [comment]
any further updates on this issue?

**Comment by bbolker** [comment]
in the absence of any more detail, I'm going to close this for now; happy to re-open it if more discussion would be useful.
