### ISSUE TITLE
Bug in predict method

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#304]
Prediction with `dispformula=~0` and `family=gaussian()` doesn't work and I'm not really sure what's the right way to fix it.

```r
y <- 1:10
f <- glmmTMB(y ~ 1, disp=~0)
predict(f) ## Error
```

Problem is that `mkTMBStruc` handles this case by changing the dispformula to `~1` and setting the `map` argument.
The `predict` method should construct its `TMBStruc` using the *original* dispersion formula - not the altered version:

```r
f$modelInfo$allForm$dispformula <- ~0 ## Fix
predict(f) ## Works
```

I guess we need to decide whether `allForm` should contain *original* or *altered* formulas.

**Comment by bbolker** [comment]
... or add another stored variable/version of `allForm` that stores the original formula?

If we had a really big set of test cases I'd suggest changing it to be the way you need it to be and seeing if it breaks anything ...

**Comment by kaskr** [comment]
OK, I'll try to fix it.
