### ISSUE TITLE
glht/lsmeans-like function

### ISSUE THREAD

**Issue by rhaydock** [glmmTMB/glmmTMB#306]
I found in issue 205 someone requested the ability to perform multiple comparisons and you provided an lsmeans-like function. Whilst this still works the lsmeans package warns that it is being deprecated in favour of emmeans. Are there any plans to get glmmTMB working together with emmeans?

With regards to glht I'll preface my question by stating that I'm not sure how the output object of glmmTMB is formatted and have so far had no luck figuring it out. However is it possible to extract just the conditional model component of the fit and pass that into glht? Based on the lme4 requirement of the package I'm assuming that the conditional component is fit using something from lme4.

Thanks for all your hard work!

**Comment by bbolker** [comment]
There is a branch [here](https://github.com/glmmTMB/glmmTMB/tree/effects) where I'm trying to incorporate support for various downstream processing packages (`effects`, `emmeans`, `MuMIn`, ...). I will try to get it far enough in the near future that it can be merged into the master branch ...

**Comment by rhaydock** [comment]
That sounds brilliant. Discovery of your package has potentially completely changed how I analyse a particular type of data at work and could have single-handedly made my work easier and far more robust!
