### ISSUE TITLE
Possible problems with residuals of binomial models

### ISSUE THREAD

**Issue by aosmith16** [glmmTMB/glmmTMB#307]
The residuals from binomial models fit with **glmmTMB** aren't matching residuals from binomial models fit with **lme4**.  

I did a little digging and found three possible places that might be causing this mismatch:

1. Models fit with the response as a proportion with weights returns different fitted values.  If I do the calculations "by-hand" I get values that match the other models.

``` r
library(glmmTMB)
library(lme4)
#> Loading required package: Matrix

tmbm1 = glmmTMB(cbind(incidence, size - incidence) ~ period + (1 | herd),
                  data = cbpp, family = binomial)

tmbm2 = glmmTMB(incidence/size ~ period + (1 | herd),
                  data = cbpp, weights = size, family = binomial)

tmbm3 = glmer(incidence/size ~ period + (1 | herd),
                data = cbpp, family = binomial, weights = size)

head( fitted(tmbm1) )
#> [1] 0.30820761 0.14174829 0.12595760 0.08402875 0.15480126 0.06358019
head( fitted(tmbm2) )
#> [1] 0.22380817 0.09656894 0.08531092 0.05604497 0.19135169 0.08064738
head( fitted(tmbm3) )
#>          1          2          3          4          5          6 
#> 0.30816472 0.14177337 0.12598556 0.08405701 0.15480041 0.06360406

# Manual calculation of fitted values
head( plogis( (getME(tmbm2, "X") %*% fixef(tmbm2)$cond) + 
             rep(unlist(ranef(tmbm2)$cond),
                 times = c(4L, 3L, 4L, 4L, 4L, 4L, 4L, 1L, 4L, 4L, 4L, 4L, 4L, 4L, 4L)) ) )
#>         [,1]
#> 1 0.30820761
#> 2 0.14174829
#> 3 0.12595760
#> 4 0.08402875
#> 5 0.15480126
#> 6 0.06358019
```

2. Residuals calculated from a model fit with a matrix response uses that count matrix in the calculation of residuals.

```
# Calculate response residuals for matrix response
residuals(tmbm1)
model.response(tmbm1$frame) - fitted(tmbm1)
# Here is what these should be, which matches lme4
model.response(tmbm1$frame)[,1]/cbpp$size - fitted(tmbm1) 
getME(tmbm3, "y") - fitted(tmbm3)
```

3. Based on `family(tmbm1)$variance` being used in the function, I believe `residuals.glmmTMB` uses mu*(1-mu) as the variance used in the divisor for calculating pearson residuals.  I couldn't find the code, but based on calculations **lme4** uses the variance of a proportion in the divisor, mu*(1-mu)/m (where m is the binomial sample size of each observation).

```
residuals(tmbm3, type = "pearson")
( getME(tmbm3, "y") - fitted(tmbm3) )/sqrt( fitted(tmbm3)*(1-fitted(tmbm3))/cbpp$size )
```

**Comment by bbolker** [comment]
Thanks very much for pointing this out. Fingers crossed that some of it is already resolved in the development version ...
