### ISSUE TITLE
glmmTMB + effects package quirk: is it me, or the package?

### ISSUE THREAD

**Issue by kjklauder** [glmmTMB/glmmTMB#312]
Hi, I know that the version of glmmTMB that interfaces with the effects package is still under construction, so I completely understand if what I'm experiencing is just a bug that has yet to be resolved. But I know it's also possible that I'm just misunderstanding what's going on. When I use effects to plot results from a logistic regression in glmmTMB, the y axis goes from about -3 to 0. When I run the same model in lme4 and plot using effects, the axis goes from 0 to 1 (as would be expected for a probability result). The plots are otherwise identical. Below is the image of one covariate plotted from lme4, and the same covariate plotted from glmmTMB.
Am I just missing something? Thanks!
![image](https://user-images.githubusercontent.com/36777330/37690246-955bb134-2c5e-11e8-9f8e-609445485175.png)
![image](https://user-images.githubusercontent.com/36777330/37690273-b4b2f060-2c5e-11e8-8f96-27e43002681e.png)

**Comment by bbolker** [comment]
It looks like the effects aren't being back-transformed from the logit to the probability scale ...

**Comment by kjklauder** [comment]
Oh gosh, I thought I had checked that but I see now that I did it incorrectly! Thank you!

**Comment by bbolker** [comment]
just to clarify: does this mean it's working (as far as you know) and we can close this issue?

**Comment by kjklauder** [comment]
Yes, thank you.
