### ISSUE TITLE
glmmTMB residual checks with DHARMa 

### ISSUE THREAD

**Issue by florianhartig** [glmmTMB/glmmTMB#313]
Hi guys,

due to popular demand, I have started implementing glmmTMB support in the DHARMa package, which implements simulated quantile residuals for glmms.

The positive news is that, overall, this seems to work fine, and I wanted to encourage you to try this out and possibly give me feedback.

- Here's the issue for glmmTMB support, with instructions to install the development branch  https://github.com/florianhartig/DHARMa/issues/16
- Here's a file with examples https://github.com/florianhartig/DHARMa/blob/glmmTMB/Code/Tests/glmmTMB.Rmd
- General intro to the package in https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html

A simple example would be 

```
m <- glmmTMB(count~spp + mined + (1|site), zi=~spp + mined, family=nbinom2, Salamanders)
summary(m)

res = simulateResiduals(m)
plot(res, rank = T)
```

which results in

![image](https://user-images.githubusercontent.com/5457753/38135247-62d53396-3417-11e8-8d36-6f69955071cd.png)

Although I have to say the super nice looking residuals are probably due to the fact that this model massively overfits! Also, note the slight correlation in res ~ pred, which is due to the reform problem (see https://github.com/florianhartig/DHARMa/issues/16). 

Here a negative example with bad residual fits 

```
m <- glmmTMB(count~ mined, family=poisson, data=Salamanders)
summary(m)

res = simulateResiduals(m)
plot(res, asFactor = T)
```

![image](https://user-images.githubusercontent.com/5457753/38135367-0fab9f7e-3418-11e8-844b-2a5b6ec7c7e7.png)

OK, so in general it seems to work fine, but I also had a few problems, which are noted in https://github.com/florianhartig/DHARMa/issues/16

- glmmTMB residual function doesn't work with factor response (bug)
- glmmTMB update doesn't work with matrix response data (bug)
- pearson residuals don't work with zi terms (not implemented), which limits some of the overdispersion tests in DHARMa
- glmmTMB doesn't support the reform argument, predictions conditinal, and simulates unconditional, which creates certain problems for DHARMa, see https://github.com/florianhartig/DHARMa/issues/16

I will file extra issues for the bugs. The other two points I just wanted to mention, in case this is useful for further development. 

A final comment about the simulate function - the behavior of simulate with binomial k/n data notably breaks with the tradition from glm / glmer, which basically returned the data in the same way it was observed (glmmTMB always returns a matrix). 

This required quite a few adjustments for me. In a way, a unified sim result format, regardless of how the data was provided, makes things easier, but of course only if you expect this, and if you haven't written functions for glm, glmer ... I guess it's too late to change this, but maybe a note in the help would be useful.

**Comment by bbolker** [comment]
A few responses:

- it's great that there is popular demand for DHARMa to handle glmmTMB models
- I'm not sure that the `simulate()` behaviour is intentional (there is a long but *possibly* useful discussion of binomial formats [here](https://github.com/glmmTMB/glmmTMB/issues/259)). It may be worth posting a separate RFC (request-for-comment) issue on this subject
- The bottom of the comment thread on [this issue](https://github.com/glmmTMB/glmmTMB/issues/205) has some expressions from Zuur et al. to use in computing the Pearson residuals of a ZIP ...

**Comment by florianhartig** [comment]
Hi Ben,

- OK, the bugs are solved, 1) thanks, and 2) sorry (my bad)

- about `simulate()` - I have just read the thread, but it doesn't say much about this point. It's not really an issue though, just a slight deviation from lme4 tradition, so I think from my side, I'll just leave it there, unless you guys want to open an issue for that. 

- regarding the Pearson residuals - thinking more about this, I actually think it's better to not provide Person residuals for mixture distributions, such as zi models, as there seem few useful applications for them. I had originally wanted to use the Pearson residuals for testing overdispersion, but on reflection, I don't think the distributional assumptions will hold. I also think it makes little sense to diagnose a zi model using Pearson residuals. Directly testing / removing the mixture via simulations, as done in DHARMa, seems much more reasonable. So, I'm actually fine with that, I just have to deal with it in my code.

**Comment by bbolker** [comment]
FWIW p. 277 of Zuur et al (screenshot [here](https://github.com/glmmTMB/glmmTMB/issues/205)) suggests that they use the the variance of the ZIP/ZINB to diagnose overdispersion (not that I always take their advice without any grains of salt ...)

**Comment by florianhartig** [comment]
yes, I had seen the screenshot. Maybe the equations work, I don't know. What I meant is that I don't think there is much sense in testing for overdispersion in a neg.binom + zi, which should be able to perfectly adjust to any dispersion. Any general overdispersion problem according to this formula would likely be an artifact from some other misspecification problem. What one really wants to do in such a model is checking residual patterns for homogeneity etc., and for such a check, one will ultimately need some measure of how residuals lie on the expected (mixture) distribution, as done in DHARMa. 

In the meantime, I have played a bit more with glmmTMB, and I have to say the package really works great! I had used it before, but hadn't looked at all the options in detail. This is really a big step forward, it unifies most of what people typically want to do with a GLMM. 

If I may, I had one more question about your simulate function: are the simulations really being done including ALL fitted options of the model, in particular also

- dispformula
- struct REs?

In particular if struct REs would be re-simulated, that would be really great, because afaik, there is no such option available yet in R. 

It would of course be even better if one would be able to switch this on / off via reform in predict and simulate.

**Comment by mebrooks** [comment]
@kaskr and I talked about this at one point. Currently, the REs are resampled in simulated responses. `glmmTMB.cpp` has a bunch of lines containing `if (do_simulate)` which I believe are controlling this. So I think the cpp side of the code is fairly close to being ready for this to be optional, but I forget the details. Maybe Kasper remembers.

**Comment by bbolker** [comment]
This issue/thread has a lot of different stuff in it.  If #322 covers what's left to do on the `glmmTMB` side, can we close it?

**Comment by florianhartig** [comment]
I guess so ... I had a few more specific comments / questions, but probably I'll better open extra issues for that. Thanks a lot for the help!

**Comment by RafaelAlcala** [comment]
Hi Florianhartig

Thank you very much for you work with DHARMa and the integration with glmmTMB. I tried the link
Here's a file with examples https://github.com/florianhartig/DHARMa/blob/glmmTMB/Code/Tests/glmmTMB.Rmd, but it does not not woking

**Comment by florianhartig** [comment]
Hi Rafael,

sorry, I have moved this code to https://github.com/florianhartig/DHARMa/tree/master/Code/DHARMaPackageSupport/glmmTMB

See also https://github.com/florianhartig/DHARMa/issues/16
