### ISSUE TITLE
Model update doesn't work for n/k data

### ISSUE THREAD

**Issue by florianhartig** [glmmTMB/glmmTMB#315]
Model update doesn't work with binomial data that is provided as a matrix, e.g. 

```
library(DHARMa)
library(glmmTMB)

testData = createData(sampleSize = 200, family = binomial(), binomialTrials = 20)

fittedModel <- glmmTMB(cbind(observedResponse1,observedResponse0) ~ Environment1 + (1|group) , family = "binomial", data = testData)
temp = model.frame(fittedModel)
update(fittedModel, temp)
```

results in 

```
Error in eval(expr, envir, enclos) : 
  object 'cbind(observedResponse1, observedResponse0)' not found
```

**Comment by bbolker** [comment]
I agree that this is unfortunate, but it seems to be a general issue of the way that model frames are stored.  Here's a similar issue with `lm()`

```
set.seed(101)
dd <- data.frame(y=rnorm(20),x=rlnorm(20))
m1 <- lm(y~log(x),dd)
update(m1,model.frame(m1))
## Error in eval(predvars, data, env) : object 'log(x)' not found
```

Or for that matter

```
dd2 <- data.frame(y=rbinom(20,size=10,prob=0.5),x=1:20)
m2 <- glm(cbind(y,10-y)~x,family=binomial,data=dd2)
update(m2,model.frame(m2))
Error in eval(predvars, data, env) : object 'cbind(y, 10 - y)' not found
```

**Comment by mmaechler** [comment]
Using  an *unnamed*  to `update()`  must be a formula... and `model.frame()` really does not return a formula.  In this sense, the answer to @bbolker 's question would be:  No,  `update()` must be used differently.  There's no bug here in my view, rather what others call  "user error".

**Comment by florianhartig** [comment]
Hi guys, sorry, there were a few glitches in my example, it should be of course 

```
update(fittedModel, data = temp)
```

so this would work 

```
testData = createData(sampleSize = 200, family = binomial())
fittedModel <- glm(observedResponse ~ Environment1 , family = "binomial", data = testData)
temp = model.frame(fittedModel)
update(fittedModel, data = temp)
```

However, I just realized that glm too doesn't handle the k/n case properly, I had just forgotten what I had done about this. 

Just for the record, what I'm trying to achieve is to refit a model with new, simulated data. lme4 has a refit argument for this, but that doesn't work for other model classes. So, my current solution in DHARMa was using update with new data, with predictors extracted from the model frame. 

As @bbolker notes, this creates an issue with log(x) or something like that, but I could live with that, unless there is a better option. 

When trying this with a k/n data case, the issue is that the model frame (as the simulate function in lm / lme4) stores the response as one column in the data.frame, and apparently the model can't handle this. "Flattening" the df works, and I just checked, it also works with glmmTMB. 

```
testData = createData(sampleSize = 200, family = binomial(), binomialTrials = 20)

fittedModel <- glm(cbind(observedResponse1,observedResponse0) ~ Environment1 , family = "binomial", data = testData)

temp = model.frame(fittedModel)
temp2 = temp[[1]]
temp[[1]] = NULL
temp = cbind(temp2, temp)

update(fittedModel, data = temp)
```

OK, the bottomline is: no glmmTMB issue here, so I'll close this. 

If you have a better idea how to achieve a refit though, I'd be happy to hear about it.

**Comment by bbolker** [comment]
(1) maybe we should write a `refit` method; (2) maybe we should change `simulate()` ?

**Comment by florianhartig** [comment]
1) A refit function would be great for me, probably also for people that want to do a parametric bootstrap. In any case, I have created a hacked refit.glmmTMB in https://github.com/florianhartig/DHARMa/blob/glmmTMB/DHARMa/R/simulateResiduals.R#L256

2) I'm not sure how one would need to change simulate so that this works easier, it doesn't work with the glmmTMB version of simulate, nor with the old glm / lme4 style either. In this case, I think it's easier simply to provide refit functions for all models
