### ISSUE TITLE
glmmTMB and foreach dopar

### ISSUE THREAD

**Issue by ilyco** [glmmTMB/glmmTMB#320]
I am trying to fit a glmmTMB model inside a foreach parallelised loop and I am getting this error:

`Error in { : task 1 failed - "object 'dat' not found"`

I was wondering whether anyone else ran into this issue. Someone else reported it here: 
http://r-sig-mixed-models.r-project.narkive.com/jWp5uMns/r-sig-me-glmmtmb-and-foreach-parallel-adaptor

**Comment by koenvanbenthem** [comment]
On my machine the code from the earlier issue (that you link to) runs fine. Here, I used the currently available package version from CRAN (glmmTMB_0.2.0     doParallel_1.0.11 iterators_1.0.9   foreach_1.4.4 ).
```R
library(doParallel)
library(glmmTMB)

simSamples <- matrix(sample(0:6,300,replace=TRUE),30,10)
## Parallel version
cl <- makeCluster(3)
registerDoParallel(cl)
TMBfit <- foreach(i=1:10, .combine= cbind, .packages=c("glmmTMB")) %dopar% {
  dat <- data.frame(subject=rep(1:15,each=2),x=-14:15,m=rep(6,30),yprop=simSamples[,i]/6)
  fitLA <- glmmTMB(yprop ~ x +(1|subject),family=binomial,weights=m,data=dat)
  fitLA$fit$par
}
stopCluster(cl)
```
Maybe updating glmmTMB will resolve the issue. If not, could you maybe provide:
1. A minimal working example
2. Your sessioninfo (sessionInfo() )
this will make it easier to see what the issue might be.

**Comment by koenvanbenthem** [comment]
Due to missing response, I'm assuming that the issue has been fixed.
