### ISSUE TITLE
add info to `README` about venues

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#323]
We should clarify what venues people should go to for help (and maybe add a few words about protocol, conventions etc. (e.g. these are public forums; reproducible examples are nice; etc.)

In my opinion:

- https://github.com/glmmTMB/glmmTMB/issues for bug/infelicity/wishlist reporting
- `r-sig-mixed-models@r-project.org` for general questions about `glmmTMB` usage and mixed models
- https://groups.google.com/forum/#!forum/tmb-users for TMB-specific questions
- maintainer e-mail only for urgent/private communications

Do folks generally agree with this?

**Comment by mmaechler** [comment]
Yes,  good idea!  (if people continue to take time to *read* such instructions ...)

**Comment by bbolker** [comment]
At the very least it would be a place we could point people to/copy and paste from. (I find I have fairly definite ideas about which venues people should use for different kinds of questions, it seems only fair to communicate what they are ...)  StackOverflow / CrossValidated could perhaps be added to the list above (although that might get too broad -- at that point we could also mention r-help ...)

**Comment by mebrooks** [comment]
I'm definitely in favor of this! As maintainer, I get an email about a basic question about once per week. I answer if I can just point to another discussion in a public space (I'm so grateful that they're out there!). Otherwise, I point them to `r-sig-mixed-models@r-project.org`.

**Comment by bbolker** [comment]
Resolved in 91acb1242fa5ae7
