### ISSUE TITLE
Standard Errors in predict()

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#324]
I'm referring to the example on p.7 of this paper: https://www.biorxiv.org/content/biorxiv/suppl/2017/05/01/132753.DC1/132753-2.pdf

The confidence intervals for the predictions are fit +/- 1.98 * se.fit.

However, I had some cases where the interval exceeds the plausible range, e.g. I had a model with binary outcome: `mod <- glmmTMB(Risk ~ Landscape + veg + (1 | Site) , data=data, family=binomial)`. What `predict()` returns are the predicted probabilities. One of the CI's, however, had a value of 103%. Is this due to wrong computation of `predict()`, or due to low precision when I use `fit - stats::qnorm(.975) * se.fit`?

I'm afraid I can't provide the data for a reproducible example (this issue was reported by a user of one of my packages), but maybe I can ask. Here's a figure of the plot created with my *ggeffects* package, where you see that one CI is above 100%.

![rplots](https://user-images.githubusercontent.com/26301769/39392770-2de5d0a8-4abc-11e8-80d3-5da4b4c63baa.png)

Here's the plot from the same data, fitted with `lme4::glmer()`

![rplot](https://user-images.githubusercontent.com/26301769/39392853-d7ae1fa4-4abd-11e8-8133-11b7d16b3395.png)

The confidence intervals are smaller, because I don't take the uncertainty of random effects into account (I'm not sure how to achieve this when I use the `newdata`-argument). May this be a reason for the larger - and even out of bounds - confidence intervals in _glmmTMB_, because it "adds" the uncertainty from random effects?

**Comment by bbolker** [comment]
Could be a problem with SEs (I'll look into it), but more generally it could be that for binomial models  `p +/- 1.96*se.fit` is not guaranteed to be within [0,1] anyway; the more precise way to do the calculation is `plogis(logit.p +/- 1.96*se.fit.logit)` (i.e. compute predictions on the logit scale, find the CIs, and back-transform). (Beyond this one could think about likelihood profile confidence intervals on predictions, but people rarely bother ...)

**Comment by strengejacke** [comment]
The other example was a negative binomial model, where the CI were partly negative for the count variable.

I'm not sure, but I think that `predict()` for `glmmTMB`-models always returns the "transformed" predictions (probabilities, incidents...), not the untransformed linear scale (log-odds...)? The documentation is very sparse, as fas as I have seen, and so I relied on the code from your paper I linked to in my post above.

So, would you in general recommend to transform the predicted values back to the linear/link-scale, compute CI, and then back-transform with the link-inverse function?

My current approach is (where `fitfram` is a data frame created with `expand.grid()` to get a combination of all unique predictor values):

```r
  prdat <- stats::predict(
    model, # glmmTMB model
    newdata = fitfram,
    zitype = "response",
    type = "response",
    se.fit = se,
    ...
  )

  fitfram$predicted <- prdat$fit

  # see http://www.biorxiv.org/content/biorxiv/suppl/2017/05/01/132753.DC1/132753-2.pdf
  # page 7

  # calculate CI
  fitfram$conf.low <- prdat$fit - stats::qnorm(ci) * prdat$se.fit
  fitfram$conf.high <- prdat$fit + stats::qnorm(ci) * prdat$se.fit
```

**Comment by bbolker** [comment]
I'm just in the process of upgrading `predict()`, and switching the default predictions to the link scale  (see PR #327 ). Need to see if the other authors agree ...

**Comment by bbolker** [comment]
I think this is now in version 0.2.1 on CRAN (as of 10 May 2018).

**Comment by strengejacke** [comment]
Yes, I can confirm this.
