### ISSUE TITLE
branch "effects" install fail; throwing pragma clang diagnostic pop errors

### ISSUE THREAD

**Issue by kjklauder** [glmmTMB/glmmTMB#328]
Recently updated R to 3.4.4. (assuming it's related), and now my attempts to install the effects branch using devtools are thowing acres of "pragma clang diagnostic pop errors" similar to what was discussed [here](http://discourse.mc-stan.org/t/boost-and-rcppeigen-warnings-for-r-package-using-stan/3478), [here](http://discourse.mc-stan.org/t/r-package-using-rstantools-fails-to-install/3562), and [here](https://stackoverflow.com/questions/49525561/rcppeigen-package-pragma-clang-diagnostic-pop-warnings), and failing to install. Ultimately it reports:

Error: package or namespace load failed for 'glmmTMB' in namespaceExport(ns, exports):
 undefined exports: allEffects.glmmTMB, effect.glmmTMB
Error: loading failed

I tried fresh installs of effects, rcppeigen, and devtools, but nothing changed. I'm afraid the suggestions in the links above were rather opaque to me -- is the problem on my end?

**Comment by bbolker** [comment]
This problem has nothing to do with the "pragma clang diagnostic pop error" stuff, I think.

I think the NAMESPACE is messed up (I need to do something like import & export the `effects` and `allEffects` functions from the `effects` package);  I'm trying a quick interim fix.  Hope that works - but if it doesn't, I am planning on working on this branch in the very near future.

Let me know if the hack worked ...

**Comment by kjklauder** [comment]
Yes, was able to successfully download and install. Thank you!

**Comment by kjklauder** [comment]
Yes, was able to successfully download and install. Thank you!
