### ISSUE TITLE
Regularization

### ISSUE THREAD

**Issue by blah-crusader** [glmmTMB/glmmTMB#330]
Hi guys,

Is there a way to specify a L1 regularization using these type of models? Trying to apply a lasso technique to these types of models. 

Thanks a lot for the help!
Br,
Thibault

**Comment by bbolker** [comment]
Nothing simple springs to mind. I've thought about allowing some hooks for priors on parameters (a zero-centered Laplacian prior on parameters would [approximately?] correspond to a L1/lasso solution), but this is only a gleam in my eye at present.  It might be worth asking on the [TMB forum](https://groups.google.com/forum/#!forum/tmb-users) whether people have experience more generally with L1 regularization in TMB ... putting together a TMB model for your specific case that includes L1 might not be **too** hard (much of the complexity of the glmmTMB code base comes from attempting to provide general, robust solutions).

**Comment by bbolker** [comment]
PS: L1 regularization would be hard because it makes the likelihood surface non-differentiable at certain points. You could use the negative log-likelihood function constructed by `glmmTMB` as a component in your own proximal gradient descent (or cyclic coordinate descent) algorithm ...

**Comment by skanskan** [comment]
What other packages allows us to use regularization with random-effects models?
I only know glmnet (with different syntax) and glmmLasso (with few options).

**Comment by bbolker** [comment]
The [mixed models task view](https://cran.r-project.org/web/views/MixedModels.html)  says

> [splmm](https://cran.r-project.org/web/packages/splmm/index.html) fits LMMs for high-dimensional data by imposing penalty on both the fixed effects and random effects for variable selection. [glmmLasso](https://cran.r-project.org/web/packages/glmmLasso/index.html) fits GLMMs with L1-penalized (LASSO) fixed effects. [bamlss](https://cran.r-project.org/web/packages/bamlss/index.html) implements LASSO-like penalization for generalized additive models.

Any Bayesian mixed-model package (`brms`, `rstanarm`, `MCMCglmm`, etc.) can in some sense be used for regularization, by specifying priors. `blme` in particular still does optimization (maximum *a posteriori* estimation), rather than MCMC sampling, and allows a range of priors (it was specifically developed for regularizing random effects to push them away from boundaries corresponding to singular fits).

**Comment by bbolker** [comment]
I think I'm going to close this as out-of-scope for `glmmTMB`.  Someone ambitious could take the log-likelihoods/gradients generated by the underlying TMB object and use it to develop a quasi-Newton approach with soft thresholding (or more generally some sort of gradient descent with soft thresholding)
