### ISSUE TITLE
Variances of the random effects

### ISSUE THREAD

**Issue by 01010011-01001000** [glmmTMB/glmmTMB#343]
I'm trying to produce a caterpillar plot of my model random effects, much like this one: https://www.unc.edu/courses/2006spring/ecol/145/001/images/lectures/lecture47/fig3b.png

Whilst I can get the random effects from the model using the ranef function, I'm struggling to find the variances. In an lme4 model, I can get these using the following:

`attr(ranef(fit_2,` postVar = TRUE)[[1]], "postVar")

But this doesn't seem to work with my glmmTMB model.

**Comment by bbolker** [comment]
This is possible, we need to work on making it easy. For example:

```
data(sleepstudy,package="lme4")
library(glmmTMB)
m1 <- glmmTMB(Reaction~Days+(Days|Subject),sleepstudy)
s1 <- TMB::sdreport(m1$obj,getJointPrecision=TRUE)
sqrt(s1$diag.cov.random)  ## standard devs
```

**Comment by BITREG1** [comment]
Perfect, thank you.

**Comment by bbolker** [comment]
Better/easier access to this is available (via ranef/as.data.frame) in the development version, as of 4c7515d9e
