### ISSUE TITLE
Profile confint in NB1 & NB2 for ranef is log-transformed and fixedef is not.

### ISSUE THREAD

**Issue by chrismainey** [glmmTMB/glmmTMB#345]
I've been fitting NB1 & NB2 random intercept models in glmmTMB and also using lme4.  When using a profiled confidence interval in  lme, it returns on the same scale as the sd.  In glmmTMB, the random effect CI is log-transformed (scale of the link function?) and needs exponentiation.
The fixed effects are already exponentiated, so it could be quite confusing to users if just the random effects CI is on a different scale.

**Comment by bbolker** [comment]
Seems reasonable, but it would be helpful to have a reproducible example (even/ideally a very simple one). (Also, could you clarify slightly?  I think you're talking about random-effects variance parameters, which are presented on the standard-deviation scale in lmer?)

**Comment by chrismainey** [comment]
@bbolker , that's right.  It's the variance parameters on the standard deviation scale I'm referring to.  Is it deliberately different in glmmTMB, as I may just be misunderstanding it?

Here's an example, using the Mmmec dataset.  It's not quite the same as my own work, but I'm not able to share that data.  I was coming at it from an overdispered-Poisson model, looking at different scaling options models and the differences between them, hence using NB1 & NB2.  Here's an NB2 example that can be compared with glmer.nb.
```

lapply(c("glmmTMB", "TMB", "lme4", "mlmRev", "MASS"), require, character.only=TRUE)

data(Mmmec)


nb2_glmer<-pois_rint<-glmer.nb(deaths~ uvb+(1|region)+offset(log(expected)), data=Mmmec, )
nb2_TMB<-glmmTMB(deaths~ uvb+(1|region)+offset(log(expected)), data=Mmmec, family="nbinom2")

nb2_glmer_pr<-profile(nb2_glmer)
nb2_TMB_pr<-profile(nb2_TMB)

#Comparing the two, fixed effect is the same, as it intercept, but .sig01 and theta_1|region.1 should be the same.
confint(nb2_glmer_pr)
confint(nb2_TMB_pr)

#compare transformed raw result with exponentiated output
confint(nb2_TMB_pr)[c(4,8)]
exp(confint(nb2_TMB_pr)[c(4,8)])

#Exponetiated figures match .sig01 in glmer.nb, as I'd expect
confint(nb2_glmer_pr)[c(1,4)]

```
