### ISSUE TITLE
predict() may generate error with betabinomial models

### ISSUE THREAD

**Issue by jhmaindonald** [glmmTMB/glmmTMB#346]
In the following, `predict()` generates the error when I specify a `cloglog` link:
```
codling1988 <- subset(DAAG::codling, year==1988)
codling1988$gp <- factor(codling1988$gp)
library(glmmTMB)
Rho0.TMB <- glmmTMB(cbind(dead,tot-dead)~0+Cultivar/dose+(1|gp),
                    family=betabinomial(link='logit'),
                    data=subset(codling1988,dose>0))
Rho2.TMB <- update(Rho0.TMB, dispformula=~Cultivar+poly(dose,2),
                   formula=cbind(dead,tot-dead)~0+Cultivar/dose+(1|gp))
hatLogit <- predict(Rho2.TMB, se=TRUE)  # Fine
Rho0.TMBclog <- glmmTMB(cbind(dead,tot-dead)~0+Cultivar/dose+(1|gp),
                        family=list(family='betabinomial',link='cloglog'),
                        data=subset(codling1988,dose>0))
  ## In spite of warning messages, fit seems OK
hat0Clog <- predict(Rho0.TMBclog, se=TRUE)
  ## Error in ff$linkfun(pred) : attempt to apply non-function
Rho2s.TMBclog <- update(Rho0.TMBclog, dispformula=~Cultivar+
                            poly(dose,2),
          formula=cbind(dead,tot-dead)~0+Cultivar/poly(dose,3)+(1|gp))
  ## Fits without problem
hat2sClog <- predict(Rho2s.TMBclog, se=TRUE)
  ## Error in ff$linkfun(pred) : attempt to apply non-function
```
[sessionInfo.txt](https://github.com/glmmTMB/glmmTMB/files/2047607/sessionInfo.txt)
Using `glmmTMB_0.2.1.0`
Date/Publication: 2018-05-10 22:04:30 UTC
Built: R 3.5.0; x86_64-apple-darwin15.6.0; 2018-05-11 07:16:30

**Comment by koenvanbenthem** [comment]
I'm not certain why it doesn't work. However, I noticed that you are specifying the models differently in both cases. In the first (functional) cases, family is specified as a function and in the non-functional case as a list with two arguments. If I specify the second model in the same way as the first (i.e. giving family as a function instead of a list), I do not get the error message 'attempt to apply non-function'.
```
Rho0.TMBclog <- glmmTMB(cbind(dead,tot-dead)~0+Cultivar/dose+(1|gp),
                        family=betabinomial(link='cloglog'),
                        data=subset(codling1988,dose>0))
```
It seems that glmmTMB is not properly storing link function that are supplied in a list.

**Comment by bbolker** [comment]
I think I have a fix. We've gradually been increasing the amount of information about the link function that's used - testing hasn't kept up ...

**Comment by bbolker** [comment]
There are two useful criteria that conflict with each other:

- mimic the behaviour of base R, specifically `glm()`
     - because users coming from `glm()` might expect it
     - because base R designers knew what they were doing (arguable ...)
- provide one "right" way to do it
     - less confusing for users
     - cleaner code and tests

I would be fine with deprecating the simpler forms: tell users that we want them to pass the results of a family function (e.g. `betabinomial()`), and warn on any of the other forms (i.e. string (`"betabinomial"`), naked symbol (`betabinomial`), or list `list(family="betabinomial",link="logit")`.  (I'm not sure we ever implemented the naked-symbol option ... ??)

**Comment by jhmaindonald** [comment]
I was a bit quick in sending my message -- failed to notice that I'd copied code that used the list form of construction in
```
Rho0.TMBclog <- glmmTMB(cbind(dead,tot-dead)~0+Cultivar/dose+(1|gp),
                        family=list(family='betabinomial',link='cloglog'),
                        data=subset(codling1988,dose>0))
```
I do agree that it will be best to settle on one way to specify the family and link, and use it consistently across all families.

**Comment by bbolker** [comment]
any further thoughts ... ?

**Comment by jhmaindonald** [comment]
My preference is the family argument with family=betabinomial().

**Comment by bbolker** [comment]
I guess the question was whether we should deprecate/warn on the other possibly ways to specify the argument (list, character, symbol)

**Comment by bbolker** [comment]
I have deprecated the "naked list" argument form (only) in [this pull request](https://github.com/glmmtmb/glmmTMB/pulls); I ended up deciding that the character/function forms are not actually too hard to handle (because of what you say above -- the conversion is almost immediate).
