### ISSUE TITLE
Zero-Inflated model validation

### ISSUE THREAD

**Issue by Kreiman1** [glmmTMB/glmmTMB#348]
Hello everyone, I'm new to the site. I work with fly eggs abundance with mixed models. After some time dealing with overdispersion in glmer models, i turn to glmmTMB to try a Zero Inflated model. By comparing the Akaike, I am left with two very similar models, one with a negative binomial distribution (nbinom1) and the other with a Conway-Maxwell-Poisson (compois). My question now is **how to validate this models**. I've try the simulateResiduals function of the DHARMa package, but it won't work. I came to doubt if there can be such a thing as a Zero Inflated model with a Conway-Maxwell-Poisson distribution. If someone can shed some light over this matter it would help a lot.

Thank you all so very much for your time.

- Kreiman

**Comment by bbolker** [comment]
Can you please post this on `r-sig-mixed-models@r-project.org` (you'll need to register first, you can find the info/registration page by googling)? That venue is more appropriate for this kind of more general statistical question.
