### ISSUE TITLE
REML for the Gaussian distribution

### ISSUE THREAD

**Issue by jprice80** [glmmTMB/glmmTMB#351]
I would like to suggest the inclusion of REML estimation for the Gaussian distribution.  

Right now it looks like Maximum Likelihood Estimation is the global “go to” equation for variance/covariance optimization in glmmTMB for very understandable reasons given the number of distributions included in the package. With that said, I think that a REML option exclusively for the Gaussian distribution would be a helpful step for folks generally dealing with the normal distribution.  This link is the short description for the way that a similar commercial procedure (glimmix) handles estimation and I think it could be applicable in glmmTMB too: https://support.sas.com/documentation/cdl/en/statug/63033/HTML/default/viewer.htm#statug_glimmix_a0000001461.htm .

**Comment by kaskr** [comment]
Just to demonstrate that it might not be that difficult to get REML working with glmmTMB, see branch https://github.com/glmmTMB/glmmTMB/tree/REML.

Example:

```
library(glmmTMB)
library(lme4)
fm <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy, REML=TRUE)
fm2 <- glmmTMB(Reaction ~ Days + (Days | Subject), sleepstudy, REML=TRUE)
```

> > logLik(fm)
> 'log Lik.' -871.8141 (df=6)
> > logLik(fm2)
> 'log Lik.' -871.8141 (df=4)

**Comment by bbolker** [comment]
How much testing/thought would be required to release this? (I see that there's a potential issue with the df to consider ...)

**Comment by kaskr** [comment]
Seems to work now. Just needed to fix a few methods - see PR.

**Comment by jprice80** [comment]
Thank you so much for the help with this.  I will investigate the REML computation branch and let you know if I run across any strange results.

**Comment by mebrooks** [comment]
I went ahead and merged @kaskr's branch into the master. So you can find it there.
