### ISSUE TITLE
simulate does not seem to work with beta_family

### ISSUE THREAD

**Issue by rdiaz02** [glmmTMB/glmmTMB#357]
```
## code from https://github.com/glmmTMB/glmmTMB/issues/278
set.seed(101)
ngrp <- 100
eps <- 0.001
nobs <- 4000
ngrp <- 200
nobs <- 800
x <- rnorm(nobs)
f <- factor(rep(1:ngrp,nobs/ngrp))
u <- rnorm(ngrp,sd=1)
eta <- 2+x+u[f]
mu <- plogis(eta)
y <- rbeta(nobs,shape1=mu/0.1,shape2=(1-mu)/0.1)
y <- pmin(1-eps,pmax(eps,y))
dd <- data.frame(x,y,f)

library(glmmTMB)
m1 <- glmmTMB(y~x+(1|f),family=list(family="beta",link="logit"),
        data=dd)
m2 <- update(m1,family=beta_family())
```

```
simulate(m1)
simulate(m2)
```

give 

```
Error in simulate.glmmTMB(m1) : 
  Simulation code has not been implemented for this family
```

(I noticed this trying to use `DHARMa`: see also https://github.com/florianhartig/DHARMa/issues/16 and https://github.com/glmmTMB/glmmTMB/issues/313)

**Comment by rdiaz02** [comment]
Sure, the message is very clear, so this is not a bug per se as you indicate. It would be nice to have simulate work here, though, so that we can use, say, DHARMa for diagnostics. But obviously this falls in the "wishlist" category.

**Comment by mebrooks** [comment]
@mmaechler 's point about the `.Random.seed` is still unresolved.

**Comment by mebrooks** [comment]
I found this code in `lme4::.simulateFun`
```
    if(!is.null(seed)) set.seed(seed)
    if(!exists(".Random.seed", envir = .GlobalEnv))
        runif(1) # initialize the RNG if necessary
    RNGstate <- .Random.seed
```

In `simulate.glmmTMB`, we only have
```
    if(!is.null(seed)) set.seed(seed)
```
@mmaechler, should we add the extra 3 lines from lme4 to resolve part (1) of your comment?

For part (2) of your comment, I'm not sure how this is working in lme4. It returns a structure including `seed = RNGstate`, but according to my naive test (below), this does not give the seed that was input.
```
seed=111
if(!is.null(seed)) set.seed(seed)
if(!exists(".Random.seed", envir = .GlobalEnv))
        runif(1) # initialize the RNG if necessary
RNGstate <- .Random.seed
seed = RNGstate
seed
```

**Comment by mmaechler** [comment]
I'm 99% that we should really do what simulate.lm() and all the other methods do here.
It must keep the  `.Random.seed` anyway for those cases (default!) where `seed` was `NULL`.

So, there's
1) the argument  seed=NULL
2) the first part you mentioned above
3) the final wrapup (adding the 'seed' attribute) at the end {or via on.exit() if we'd need, I hope not}

**Comment by mebrooks** [comment]
I'm going to close this issue since simulate works with the beta distribution. If the random seed is a problem then we can open another issue.
