### ISSUE TITLE
version 0.2.2 checklist

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#363]
What issues are blocking/preferred/wishlist for sending 0.2.2 to CRAN by 2 July? (Please edit and/or discuss ... should add cross-links to existing issues too)

- **blocking**: speed up vignette build and possibly tests
- **preferred**: updated `NEWS` for all bug fixes/added features (e.g. parallel, simulate bug fixes)
- **wishlist**: resolve sigma scale and scaled vs unscaled variance issues
- **wishlist**: get `effects` branch release-ready and merge it
- **wishlist**: fix #345 (seems like it should be fairly straightforward?)

**Comment by mebrooks** [comment]
0.2.2 is on CRAN today. All together, we 

- reduced the vignette speed only through a fix to TMB
- updated the `NEWS`
- added required `plyr` suggest to get rid of a warning

We still might need to reduce speed in the next version.
