### ISSUE TITLE
How calculate R-squared for glmmTMB

### ISSUE THREAD

**Issue by Hallo951** [glmmTMB/glmmTMB#367]
Hi,

how do I calculate for normaly models and zeroinflated or hurdel models with nbinom1 or 2, binomial, gaussian and poisson distribution the rsqured? I searched the web for solutions but found none...

**Comment by mebrooks** [comment]
Repeat of #169

**Comment by Hallo951** [comment]
Thanks for the answer but I do not quite understand that yet what is the function with which I calculate the R-square and how do I call you.
