### ISSUE TITLE
Error when calling summary on zero-inflated model with different random effect structures

### ISSUE THREAD

**Issue by prockenschaub** [glmmTMB/glmmTMB#370]
I am currently trying to run a hurdle model with a truncated Poisson-lognormal structure for the count part of the model with a group-level random effect. This structure is realised via an additional observation-level random effect (OLRE), as used by Ben Bolker together with the lme4 package [here](http://glmm.wdfiles.com/local--files/examples/overdispersion.pdf). 

When fitting the binomial part of the model, I want to use the same predictors as the count model. However, I do not want to include the OLRE in this model, as logistic regression by design can't be overdispersed (and in fact, when included the variance of the OLRE is estimated very close to zero). When I omit the OLRE for the binomial model, the summary function throws the following error: `Error in reS$ziReStruc[[i]] : subscript out of bounds`.

I have chased the error down to the following line in the VarCorr.glmmTMB function:
https://github.com/glmmTMB/glmmTMB/blob/5c1ce44cec697b2c3c4a6e7f2b338c708f7d4c94/glmmTMB/R/VarCorr.R#L187

I believe that instead of `seq_along(vc.cond)`, it should say `seq_along(vc.zi)`, unless there is a strong theoretical reason why the two models should not be allowed to have different random effect structures.

Below is a reproducable example adapting code taken from [here](https://github.com/seananderson/glmm-course/blob/master/18-zero-inflation.Rmd):

```
library(tidyverse)
library(glmmTMB)

inverse_logit <- function(x) plogis(x)

# Simulate data following a hurdle model including an observation-level RE i for the count part
set.seed(99)
d <- data.frame(f = factor(rep(letters[1:10], each = 10)), 
                id = 1:400,
                x = runif(400))
u <- rnorm(10, sd = 1)
i <- rnorm(400, sd = 0.3)
d$eta0 <- with(d, u[f] + 0.1 + 0.6 * x)
d$eta <- with(d, i + u[f] + 0.1 + 4 * x)
pz <- inverse_logit(d$eta0) # probability of excess zeros
zi <- rbinom(400, size = 1, prob = pz)
rtpois <- function(N, lambda) qpois(runif(N, dpois(0, lambda), 1), lambda) # truncated poisson
d$y <- ifelse(zi==0, 0, rtpois(400, lambda = exp(d$eta)))
d$zi <- zi

hurdle_mod <- glmmTMB(y ~ x + (1 | f) + (1 | id), data = d, family = truncated_poisson(link = "log"), 
                      ziformula = ~ x + (1 | f))
summary(hurdle_mod)
```

**Comment by mebrooks** [comment]
Thanks for reporting this with the reproducible example and solution! 

I get the same behavior on my computer. I made a pull request to fix it, which should in the master branch as soon as the Travis checks pass.
