### ISSUE TITLE
Error with summary()

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#376]
I'm trying to "translate" some formulas from [this paper about FE and RE models](https://link.springer.com/article/10.1007%2Fs11135-018-0802-x) into R-syntax, using _glmmTMB_. I'm doing this with some own "real world" sample data (file "glmmtmb_data.RData" attached).

The model computes w/o warning:

```r
m <- glmmTMB(
  QoL ~ time + age + x_tv_dm + x_tv_gm + z1_ti + z2_ti + (1 + time | ID) + (1 + x_tv_dm | ID),
  data = d,
  REML = TRUE
)
```

It also prints well, but using `summary()` gives following error:

```r
summary(m)
#> Error in solve.default(as.matrix(Qm)) : 
#>   system is computationally singular: reciprocal condition number = 2.90076e-17
```

Fitting the same model with `lme4::lmer()` works fine (including `summary()`). I just wonder what does the error message exactly mean and what could be the reason behind it, especially since it works with `lme4::lmer()`.

[glmmtmb_data.zip](https://github.com/glmmTMB/glmmTMB/files/2296580/glmmtmb_data.zip)

**Comment by bbolker** [comment]
The problem happens [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/methods.R#L245), in `vcov.glmmTMB`.

Essentially, `glmmTMB` is failing to invert the *full* variance-covariance matrix (including both the fixed-effect and the random-effect parameters).  I have to admit I'm not 100% clear on how this chunk is doing what it's doing (computing the marginal of the precision matrix), nor why it's failing/what to do about it ... we could obviously wrap this step in `tryCatch()` and do something if it fails (compute marginal precision only of fixed-effect parameters?), but I don't know what the implications would be.
@kaskr ?

```
  if (REML) {
      ## NOTE: This code would also work in non-REML case provided
      ## that jointPrecision is present in the object.
      Q <- sdr$jointPrecision
      whichNotRandom <- which( ! rownames(Q) %in% c("b", "bzi") )
      Qm <- GMRFmarginal(Q, whichNotRandom)
      cov.all.parms <- solve(as.matrix(Qm))
  } else {
      cov.all.parms <- sdr$cov.fixed
  }
  keepTag <- if (full) { "."
             } else if (!trivialDisp(object)) { "beta*"
             } else "beta($|[^d])"
  to_keep <- grep(keepTag,colnames(cov.all.parms)) # only keep betas
covF <- cov.all.parms[to_keep,to_keep,drop=FALSE]
```

**Comment by bbolker** [comment]
I tried scaling the numeric inputs and got a "singular convergence" warning.  For what it's worth, `lme4` reports a singular fit (correlations of +1/-1 for the two RE terms), and we know that `glmmTMB` is not as robust at dealing with singular fits as `lme4` is - because `glmmTMB` fits RE parameters on a log-Cholesky scale, singular fits correspond to parameter estimates converging to infinite values, whereas `lme4` fits on the Cholesky scale, so these parameter estimates converge to zero.

**Comment by kaskr** [comment]
We could test on the eigen values before attempting `solve(as.matrix(Qm))`. Something like [this](https://github.com/glmmTMB/glmmTMB/blob/9cc5b7adc5420154c331051c3ffbf1e9f8098ad7/glmmTMB/R/glmmTMB.R#L890).

**Comment by bbolker** [comment]
Yes, or simply wrap the `solve(...)` in a `try(...)`.  I guess the question is what we ought to return for `vcov()` in this case.  A matrix full of `NA` values?  Would it be acceptable to fall back (with a warning) to inverting the marginalized joint precision matrix of the fixed effects alone?

**Comment by kaskr** [comment]
A matrix full of NA values sounds like the safest and easiest solution. Alternatively one could add a tiny amount to the problematic eigenvalues before inverting... Or allow tiny priors on the fixed effects in the REML case... However the last two are a bit more experimental/risky.

I don't like the idea of a generalized inverse as that would turn a zero precision into a zero variance which would be quite misleading...

**Comment by iago-pssjd** [comment]
I am having a similar issue using `family = "nbinom2"`, with the difference that when I try with `glmer.nb` instead of `glmmTMB` I get a bunch of warnings about convergence...
