### ISSUE TITLE
predict() for zero-inflated models - when is zi-part taken into account?

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#378]
This is no real issue, rather a question, but as a result you may add some information to the documentation of `predict()`.

I wonder, for zero-inflated models, if `type = "zlink"` returns the predictions for the conditional model, _taking the zero-inflation into account_? Or is it currently only possible to get the predictions for the conditional model (`type = "link"`) and zi-model (`type = "zlink"`) seperately?

**Comment by strengejacke** [comment]
I'm not sure, but I think that `type = "response"` will return the predicted values of the model _conditioned_ on the zero-inflation component - is that right?

If so, the predicted values are no longer on the link-scale, but the standard errors (if `predict(..., se.fit = TRUE)`) _are_ still on the link-scale?

**Comment by strengejacke** [comment]
(bump)

anyone there for a short comment or yes/no? :-)

**Comment by koenvanbenthem** [comment]
As far as I know, the following holds:
`type="link"`
Returns the prediction of the conditional model on the link scale, as well as their SE
`type="zlink"`
Returns prediction and errors of the zero inflated model only on the link scale. Note that these numbers correspond to the  chance of producing an additional zero. Hence, the higher the number, the higher the chance of producing an additional zero and thus the lower the expected outcome of the overall model.
`type="response"`
Returns predictions on the response scale of the overall (conditional and zero inflation) model. 

These different predictions are related. For example, for a _poisson_ model, with _log_ link function and zero-inflation the expression:
`predict(model,type="response",se.fit=FALSE)`
should give the same result as:
`exp(predict(model,type="link",se.fit=FALSE))*(1-plogis(predict(model,type="zlink",se.fit=FALSE))`

The standard errors for `type="response"` should also be on the predictor scale (not the link scale). (Although of this last statement I am slightly less certain than all others. The others I just quickly checked on some example data to be certain, but this last statement comes from my nonperfect memory )

I just looked at the documentation of the predict function (`?predict.glmmTMB') and it seems that most of this information is already in there, so I am not certain what to change. Do you have any suggestions on how we could make it clearer?

I hope this helps!

**Comment by strengejacke** [comment]
Ok, this was the reason why I thought that std. errors are on a different scale then predictions for `type = "response"`. If predictions and se are on the response scale, and you want to compute confidence intervals, then you would first need to backtransform pred and se using the link-function, then calculate CI = pred +/- 1.96 * se, and then backtransform via link-inverse the CI again.

If you do this for pred only, everything looks good, however, if you do this for se as well, you get weird CI:

``` r
library(glmmTMB)
library(dplyr)

data("Salamanders")

m <- glmmTMB(
  count ~ spp + mined + (1 | site), 
  ziformula = ~ spp + mined, 
  family = truncated_poisson, 
  data = Salamanders
)

# If both predicted values and std. errors are on the response scale
# we would need to backtransform both before calculating the CI

m %>% 
  predict(
    se.fit = T, 
    type = "response",
    newdata = data.frame(
      mined = factor(c("yes", "no")),
      spp = factor("GP"),
      site = factor("R-1")
    )
  ) %>% 
  as.data.frame() %>%
  dplyr::mutate(
    ci.low = exp(round(log(fit) - 1.96 * log(se.fit), 3)),
    ci.high = exp(round(log(fit) + 1.96 * log(se.fit), 3))
  )
#>         fit     se.fit  ci.low      ci.high
#> 1 0.1350364 0.04604922 56.3172 0.0003239245
#> 2 1.6595937 0.28961151 18.8215 0.1463140412


# Here we assume that predicted values are on response scale and need
# to be backtransformed, while std. errors are on link-scale and are
# not back transformed

m %>% 
  predict(
    se.fit = T, 
    type = "response",
    newdata = data.frame(
      mined = factor(c("yes", "no")),
      spp = factor("GP"),
      site = factor("R-1")
    )
  ) %>% 
  as.data.frame() %>%
  dplyr::mutate(
    ci.low = exp(round(log(fit) - 1.96 * se.fit, 3)),
    ci.high = exp(round(log(fit) + 1.96 * se.fit, 3))
  )
#>         fit     se.fit    ci.low   ci.high
#> 1 0.1350364 0.04604922 0.1234400 0.1477845
#> 2 1.6595937 0.28961151 0.9408232 2.9270644
```

Created on 2018-08-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mebrooks** [comment]
I think there's a mathematical problem with both of your transformations. 

Using `type = "response"` should give values that are on the scale of `Salamanders$count` so you could calculate CI with `fit - 1.96 * se.fit` except that it would ignore the constraints of the response distribution (i.e. family). 

To get CI that obey the constraints of the distribution, you probably need to combine predictions with `type="zlink"` and `type="link"`.

**Comment by mebrooks** [comment]
Something like this should work
```
log.mu=predict(m, type="link", se=TRUE)
logit.z=predict(m, type="zlink", se=TRUE)

pred=exp(log.mu$fit)*(1-boot::inv.logit(logit.z$fit))
ci.lo=exp(log.mu$fit-1.96*log.mu$se.fit)*(1-boot::inv.logit(logit.z$fit-1.96*logit.z$se.fit))
ci.hi=exp(log.mu$fit+1.96*log.mu$se.fit)*(1-boot::inv.logit(logit.z$fit+1.96*logit.z$se.fit))
```

**Comment by mebrooks** [comment]
I guess we could clear up some confusion by adding an example to the helpfile that combines predictions from `type="link"` and `type="zlink"`.

**Comment by mebrooks** [comment]
It's still possible that there's a mistake with the se calculations. I was assuming that they were coming from the C++ side, but there are some transformations going on on the R side of things that I don't quite understand. 
```
  if (type %in% c("zlink","link")) {
     ff <- object$modelInfo$family
     if (!(type=="link" && ff$link=="identity")) {
         if (type=="zlink") {
             ff <- make.link("logit")
         }
         pred <- ff$linkfun(pred)
         if (se.fit) se <- se/ff$mu.eta(pred) ## do this after transforming pred!
     } ## if not identity link  
  } ## if link or zlink
```
Maybe @bbolker can explain the logic of it?

**Comment by mebrooks** [comment]
More specifically, I can't find the definition of `mu.eta` and it isn't obvious to me how `se <- se/ff$mu.eta(pred)` can work for all non-identity links.

**Comment by bbolker** [comment]
*briefly* (I'll try to get back to this later today): from `?family`,

> mu.eta: function: derivative of the inverse-link function with
          respect to the linear predictor.  If the inverse-link
          function is mu = ginv(eta) where eta is the value of the
          linear predictor, then this function returns
          d(ginv(eta))/d(eta) = d(mu)/d(eta).

Translating standard errors to or from the link scale is done by multiplying or dividing by mu.eta. I believe that the underlying C++ code returns the standard error on the response scale, so if the link scale is requested we have to transform back ...

**Comment by mebrooks** [comment]
I just realized that my answer is probably wrong because it doesn't account for correlation in the uncertainties of mu and z.

**Comment by strengejacke** [comment]
Ok, so now I'm a bit confused. ;-)
So is there currently a correct way to calculate CI for `type = "response"`, or do you need to fix `predict.glmmTMB()` first? Just asking because an update of one of my packages relies on that function, and I could add explanations to the help-file about the state of CI.

**Comment by mebrooks** [comment]
My best answer is that there is no way to make `predict()` return the perfect CI on the response scale. We could change the package so that it returns the response on the scale of the link of the conditional model (e.g. log-scale), but this would only approximate the perfect CI that take both links into account. It might be worth experimenting with that option. Getting accurate CI on the response will involve simulation, such as parametric bootstrapping (see [appendix A, section "Alternative prediction method"](https://journal.r-project.org/archive/2017/RJ-2017-066/RJ-2017-066.pdf)) or using the `simulate()` function. It's possible that @bbolker or other people have other ideas.

**Comment by strengejacke** [comment]
I have compared the one approach, where I use `type = "response"` and backtransform pred and se, compute CI and then back-backtransform again, and the approach you suggested (https://github.com/glmmTMB/glmmTMB/issues/378#issuecomment-417329416):

``` r
library(ggeffects)
library(glmmTMB)
data("Salamanders")

m <- glmmTMB(
  count ~ spp + mined + cover + (1 | site), 
  ziformula = ~ spp + mined + cover, 
  family = truncated_poisson, 
  data = Salamanders
)

# the first approach, type = "response"
ggpredict(m, "mined", type = "fe.zi")

#> # Predicted incidents for count 
#> # x = mined 
#> 
#>  x predicted conf.low conf.high
#>  1     0.110    0.102     0.119
#>  2     1.722    0.966     3.070
#> 
#> Adjusted for:
#> *   spp = GP
#> * cover = 0.00
#> *  site = R-1

# the 2nd approach, type = "link" and "zlink"
ggpredict(m, "mined", type = "test")

#> # Predicted incidents for count 
#> # x = mined 
#> 
#>  x predicted conf.low conf.high
#>  1     0.110    0.113     0.103
#>  2     1.722    1.496     1.867
#> 
#> Adjusted for:
#> *   spp = GP
#> * cover = 0.00
#> *  site = R-1

# the first approach, type = "response"
ggpredict(m, "cover", type = "fe.zi")

#> # Predicted incidents for count 
#> # x = cover 
#> 
#>     x predicted conf.low conf.high
#>  -1.6     0.171    0.152     0.192
#>  -1.4     0.162    0.145     0.180
#>  -1.2     0.153    0.139     0.169
#>  -1.0     0.145    0.132     0.159
#>  -0.8     0.137    0.126     0.150
#>  -0.6     0.130    0.120     0.141
#>  -0.4     0.123    0.114     0.133
#>  -0.2     0.116    0.108     0.126
#>   0.0     0.110    0.102     0.119
#>   0.2     0.104    0.097     0.112
#>  ... and 8 more rows.
#> 
#> Adjusted for:
#> *   spp = GP
#> * mined = yes
#> *  site = R-1

# the 2nd approach, type = "link" and "zlink"
ggpredict(m, "cover", type = "test")

#> # Predicted incidents for count 
#> # x = cover 
#> 
#>     x predicted conf.low conf.high
#>  -1.6     0.171    0.177     0.157
#>  -1.4     0.162    0.167     0.150
#>  -1.2     0.153    0.157     0.143
#>  -1.0     0.145    0.148     0.136
#>  -0.8     0.137    0.140     0.130
#>  -0.6     0.130    0.132     0.123
#>  -0.4     0.123    0.125     0.116
#>  -0.2     0.116    0.119     0.110
#>   0.0     0.110    0.113     0.103
#>   0.2     0.104    0.108     0.097
#>  ... and 8 more rows.
#> 
#> Adjusted for:
#> *   spp = GP
#> * mined = yes
#> *  site = R-1
```

Created on 2018-08-31 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

As you can see, with your proposal the lower CI are sometime higher than the higher CI limit...

**Comment by bbolker** [comment]
I'll get back to this as soon as I can, but will be busy over the weekend/next week is the start of term ...

**Comment by koenvanbenthem** [comment]
@strengejacke https://github.com/glmmTMB/glmmTMB/issues/378#issuecomment-417744876

This may be caused by the zero inflation and the conditional model working in opposite directions. (i.e. a higher expected value for the zero inflation means a lower response, but a higher value for the conditional model means a higher response). Because of this, it seems to me that when applying a fix such as proposed in https://github.com/glmmTMB/glmmTMB/issues/378#issuecomment-417329416 , the signs should be opposed between the two parts, i.e.:
`
ci.lo=exp(log.mu$fit-1.96*log.mu$se.fit)*(1-boot::inv.logit(logit.z$fit+1.96*logit.z$se.fit))
ci.hi=exp(log.mu$fit+1.96*log.mu$se.fit)*(1-boot::inv.logit(logit.z$fit-1.96*logit.z$se.fit))
`
However, as stated before ( https://github.com/glmmTMB/glmmTMB/issues/378#issuecomment-417390681 ), these number will still be (coarse) approximations, because they do not take into account possible zero-inflation between the zero inflation and the conditional part.

**Comment by strengejacke** [comment]
@koenvanbenthem thanks! this looks better indeed...

``` r
library(ggeffects)
library(glmmTMB)
data("Salamanders")

m <- glmmTMB(
  count ~ spp + mined + cover + (1 | site), 
  ziformula = ~ spp + mined + cover, 
  family = truncated_poisson, 
  data = Salamanders
)

# the first approach, type = "response"
ggpredict(m, "mined", type = "fe.zi")
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> 
#> # Predicted incidents for count 
#> # x = mined 
#> 
#>  x predicted conf.low conf.high
#>  1     0.110    0.102     0.119
#>  2     1.722    0.966     3.070
#> 
#> Adjusted for:
#> *   spp = GP
#> * cover = 0.00
#> *  site = R-1

# the 2nd approach, type = "link" and "zlink"
ggpredict(m, "mined", type = "test")
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> 
#> # Predicted incidents for count 
#> # x = mined 
#> 
#>  x predicted conf.low conf.high
#>  1     0.110    0.042     0.276
#>  2     1.722    1.052     2.655
#> 
#> Adjusted for:
#> *   spp = GP
#> * cover = 0.00
#> *  site = R-1

# the first approach, type = "response"
ggpredict(m, "cover", type = "fe.zi")
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> 
#> # Predicted incidents for count 
#> # x = cover 
#> 
#>     x predicted conf.low conf.high
#>  -1.6     0.171    0.152     0.192
#>  -1.4     0.162    0.145     0.180
#>  -1.2     0.153    0.139     0.169
#>  -1.0     0.145    0.132     0.159
#>  -0.8     0.137    0.126     0.150
#>  -0.6     0.130    0.120     0.141
#>  -0.4     0.123    0.114     0.133
#>  -0.2     0.116    0.108     0.126
#>   0.0     0.110    0.102     0.119
#>   0.2     0.104    0.097     0.112
#>  ... and 8 more rows.
#> 
#> Adjusted for:
#> *   spp = GP
#> * mined = yes
#> *  site = R-1

# the 2nd approach, type = "link" and "zlink"
ggpredict(m, "cover", type = "test")
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> Argument `weight.by` is deprecated. Please use `weights`.
#> 
#> # Predicted incidents for count 
#> # x = cover 
#> 
#>     x predicted conf.low conf.high
#>  -1.6     0.171    0.065     0.429
#>  -1.4     0.162    0.063     0.400
#>  -1.2     0.153    0.060     0.375
#>  -1.0     0.145    0.057     0.352
#>  -0.8     0.137    0.054     0.332
#>  -0.6     0.130    0.052     0.315
#>  -0.4     0.123    0.049     0.300
#>  -0.2     0.116    0.045     0.287
#>   0.0     0.110    0.042     0.276
#>   0.2     0.104    0.039     0.266
#>  ... and 8 more rows.
#> 
#> Adjusted for:
#> *   spp = GP
#> * mined = yes
#> *  site = R-1
```

Created on 2018-09-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I think, approximated CI's are ok for my purpose.

**Comment by koenvanbenthem** [comment]
Just to clarify, when I said (coarse) approximations, what I meant is that the real confidence intervals may be completely different from those calculated with this method - depending on the specific covariance between zi and conditional parameters. Myself, I would not use these CIs and rather use bootstrapped CI's ( https://github.com/glmmTMB/glmmTMB/issues/378#issuecomment-417676794 ). 

Allow me to illustrate the problem with an example. Let's assume we have two random variables: a and b. We are interested in the confidence interval of their product: a*b and we want to calculate it from the individual confidence intervals of a and b. Both a and b are normally distributed with mean=4 and sd=1. (I chose mean=4, because it leads to nearly no numbers being negative. When numbers are also allowed to get negative, everything seems to become more complicated)

a has a 95% confidence interval of [a0,a1]
b has a 95% confidence interval of [b0,b1]

In order to calculate the CI, we'll have to make assumptions about the covariance between a and b.

**a and b are exactly correlated**
This means that whenever a is high, so is b. In this case the proposed method would work and return the appropriate 95% CI. You can verify this in R as follows:
```{R}
> # Same ordering
> a <- rnorm(1e6,4,1)
> b <- rnorm(1e6,4,1)
> a <- a[order(a)] # ordering a 
> b <- b[order(b)] # ordering b as well, thereby enforcing strong positive correlation
> quantile(a,probs=c(0.025,0.975))
    2.5%    97.5% 
2.038726 5.957635 
> quantile(b,probs=c(0.025,0.975))
    2.5%    97.5% 
2.040961 5.959855 
> quantile(a*b,probs=c(0.025,0.975))
     2.5%     97.5% 
 4.160961 35.506643 
> quantile(a,probs=c(0.025,0.975)) * quantile(b,probs=c(0.025,0.975))
     2.5%     97.5% 
 4.160961 35.506643 
```
In this case the CI of the product, can thus be calculated directly from the CI's of the individual underlying parameters.
**a and b are anti correlated**
This means that whenever a is low, b is high and the other way around.
```{R}
> a <- rnorm(1e6,4,1)
> b <- rnorm(1e6,4,1)
> a <- a[order(a)] # ordering a 
> b <- rev(b[order(b)]) # ordering b in the opposite direction, thereby enforcing strong negative correlation
> quantile(a,probs=c(0.025,0.975))
    2.5%    97.5% 
2.044690 5.961909 
> quantile(b,probs=c(0.025,0.975))
    2.5%    97.5% 
2.035372 5.963792 
> quantile(a*b,probs=c(0.025,0.975))
    2.5%    97.5% 
11.00248 16.00044 
> quantile(a,probs=c(0.025,0.975)) * quantile(b,probs=c(0.025,0.975))
     2.5%     97.5% 
 4.161705 35.555585 
```
In this case the approximation is completely wrong.
**a and b are independent random variables**
a and b are not ordered.
```{R}
> a <- rnorm(1e6,4,1)
> b <- rnorm(1e6,4,1)
> quantile(a,probs=c(0.025,0.975))
    2.5%    97.5% 
2.036479 5.957013 
> quantile(b,probs=c(0.025,0.975))
    2.5%    97.5% 
2.039933 5.958466 
> quantile(a*b,probs=c(0.025,0.975))
     2.5%     97.5% 
 6.191008 28.556624 
> quantile(a,probs=c(0.025,0.975)) * quantile(b,probs=c(0.025,0.975))
     2.5%     97.5% 
 4.154283 35.494661 
```
In this case as well, the approximation returns a wrong answer. 

**Already for these very simple cases, the 'approximation' can return very weird CI's. I would therefore not attributed much value to them. Only if the two variables are ordered in the exact same way, the approximation holds.**

**Comment by strengejacke** [comment]
Thanks, this is very helpful and very good to understand! I'll check the examples in the appendix mentioned, and see if bootstrapping performs with an acceptable speed/time.

**Comment by strengejacke** [comment]
Ok, I think my initial request is solved now, and I've implemented the approach mentioned in your paper in Appendix A. Thus, I would close this issue now...

**Comment by mebrooks** [comment]
Keep in mind that the approach in the appendix has the RE set to 0, so it's predicting the mode, not the mean. With non-indentity link functions, Jensen's inequality has an effect.

**Comment by strengejacke** [comment]
Yes, that would be another issue, how to condition on RE. As far as I know, `predict()` also does currently not support the `re.form`-argument.

**Comment by strengejacke** [comment]
Would `simulate()`, as described one paragraph later in the paper, solve this issue?
