### ISSUE TITLE
getME function conflicts with lme4

### ISSUE THREAD

**Issue by koenvanbenthem** [glmmTMB/glmmTMB#38]
could be changed by making it into getME.glmmTMB and getME.merMod. This requires adaptation of lme4. An easier solution is prefered.

**Comment by mmaechler** [comment]
in which sense does it conflict?
Surely not inside the package R code ... unless you were importing `getME()` from `lme4` which you should not even think of.
And in outside-package user code, there is no problem as that code can use  `glmmTMB::getME()` and
`lme4::getME()` ...  
My conclusion:  I do *not* see a real issue ...  (yet?)

**Comment by bbolker** [comment]
The issue (IMO) is that it would be preferable *not* to have the latest-loaded of `lme4::getME` and `glmmTMB::getME` mask each other. Maybe it will be uncommon for users to load both at once (although we will certainly do it a lot while testing), but it will happen and I expect it will lead to confusion.

**Comment by mmaechler** [comment]
As I found, there are even more stringent reasons to make `getME` an S3 generic:
We want to piggy back on `lme4`'s method : if they use `getME()` on our objects, it should use *our* `getME()` -- so we can provide the low-level interface -- and the lme4 method would do the next higher level  functionality.   This should also be a better approach for the CRAN (and github)  package (robustlmm)[https://github.com/kollerma/robustlmm]
