### ISSUE TITLE
Troubleshooting with glmmTMB

### ISSUE THREAD

**Issue by stephrivest** [glmmTMB/glmmTMB#386]
Hello,

I am unsure if this is the correct spot to ask a question, apologies if it isn't. I am currently working with a dataset for which I have fit a zero-inflated glmm using the package glmmTMB and the conditional model distribution "nbinom1".

What I am wondering, is what does it mean when you have either a very small or very large estimate for the zero-inflation intercept? In the troubleshooting vignette (https://cran.r-project.org/web/packages/glmmTMB/vignettes/troubleshooting.html), a very small value is estimated for the zero-inflation intercept. Backtransforming this value shows that "the zero-inflation probability for the baseline level is" very small, almost 0. What does this mean?

What does it mean in the opposite direction, i.e. when the zero-inflation intercept shows that the probability at the baseline level is very high, effectively 1?

What do both of these problems mean and how should one proceed when the problem is observed?

Thanks!
Stephanie R

**Comment by bbolker** [comment]
In the opposite direction, it would mean that it was estimated that you should have almost *all* structural zeros in the baseline level. These are all slightly more complicated versions of the problem of *complete separation* (e.g. see [here](https://stats.stackexchange.com/questions/132677/binomial-glmm-with-a-categorical-variable-with-full-successes)) - i.e., that based on the data there are combinations of predictor variables that will give you a certainty of failure/0 OR a certainty of a success/1. In this case the maximum likelihoods (for the log-odds of the probability) will be infinite. The  general strategies for this are (1) ignore it, if it's not messing other things up and you don't need to do inference on that part of the model; (2) use some kind of regularization or Bayesian prior to constrain the parameter estimates closer to zero.  Unfortunately the latter isn't currently available in `glmmTMB` ...

**Comment by bbolker** [comment]
PS `r-sig-mixed-models@r-project.org` might be a slightly better venue; as the [README file](https://github.com/glmmtmb/glmmTMB/) says,

- r-sig-mixed-models@r-project.org for general questions about glmmTMB usage and mixed models
- https://github.com/glmmTMB/glmmTMB/issues for bug, infelicity, and wishlist reporting
- https://groups.google.com/forum/#!forum/tmb-users for TMB-specific questions
- maintainer e-mail only for urgent/private communications
