### ISSUE TITLE
Calculating expected number of zeros in glmmTMB

### ISSUE THREAD

**Issue by stephrivest** [glmmTMB/glmmTMB#390]
Hello,

I am wondering if it is possible to calculate the expected number of zeros that a glmmTMB model predicts? I have done this before when I have implemented non-zero-inflated glmm's using the package lme4. I am wondering if the process is similar and the output can be trusted. 

For example: With a poisson distributed glmm, you can compute the overall expected number of zeros (which is conditional on the whole set of observed x's). At a given combination of the x's, you can compute (λi|xi) (where xi represents the collection of independent variables for the ith observation).

and hence P(Yi=0|xi)=e^(−λ)

In R, my code for implementing this equation looks like this:
lambda_hat <- predict(model.name, type = "response") #calculate the fitted mean for each observation of x 
expected_zeros <- sum(exp(-lambda_hat)) #exponentiate and sum
expected_zeros

My question is this: Can the same mathematics be applied to a zero-inflated glmm? Using glmmTMB to fit a zero-inflated model with mixed effects, can the same code be implemented to achieve the same response?

Any help is greatly appreciated!!

**Comment by bbolker** [comment]
The probability isn't too hard to calculate: Prob(zero) is 
```
Prob(Yi is a structural zero) + (1-Prob(Yi is  a structural zero))*exp(-lambda_hat(i))
```
You should be able to `Prob(Yi is a structural zero)` from `predict(.,type="zprob")` and lambda-hat from `type="conditional"`

These probabilities will be conditional on the random effects if you use `predict()` with specific groups specified, or population-level effects if you use `predict()` with the RE group variables set to `NA`. If you want to marginalize over random effects, that'll be trickier.

Mollie's right that simulations have an advantage in giving you the entire distribution of predicted zeros. 

Followups to `r-sig-mixed-models@r-project.org` please? (Probably more appropriate for this question -- see the [README file](https://github.com/glmmTMB/glmmTMB/blob/master/README.md) for venue suggestions ...)
