### ISSUE TITLE
ranef error with multiple random effects

### ISSUE THREAD

**Issue by fxdlmatt** [glmmTMB/glmmTMB#396]
In the [ranef.glmmTMB](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/methods.R#L170) there is an error with the list index `sd[[w]]` in L170 when multiple random effects are present.  `w` is a logical vector with length > 1 in the case of multiple random effects.  Should the logic use `sd[[which(w)]]`?

**Comment by bbolker** [comment]
nice catch.
