### ISSUE TITLE
get rid of inst/doc ?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#409]
On my system (I'm using `devtools` v 2.0.1), running `devtools::check()` produces:

> Building the package will delete...
  '/media/sf_Documents/Rpkgs/glmmTMB/glmmTMB/inst/doc'
> Are you sure?
> 1: Yes
> 2: No

I'm worried about saying "Yes" (I know I can always retrieve from the repo, but) ... should we remove this directory from the repo?  (I don't think putting it in `.Rbuildignore` will help ...)

It's never been entirely clear to me exactly when/why we should have the built versions of the vignettes in `inst/doc`; I *think* it's primarily for convenience, so that we can install directly from the source directory on disk (rather than `R CMD build` -> `R CMD INSTALL <tarball>`), or use `--no-build-vignettes`, and still have a copy of the vignettes available.  I think this is not considered best practice ... the other reason I can find (from Writing R Extensions) is that

> R CMD build will automatically create the (PDF or HTML versions of the) vignettes in inst/doc for distribution with the package sources. By including the vignette outputs in the package sources it is not necessary that these can be re-built at install time, i.e., the package author can use private R packages, screen snapshots and LaTeX extensions which are only available on his machine.

**Comment by strengejacke** [comment]
I don't know why this behaviour changed in the recent version of devtools... After using `devtools::build_vignettes()` I always move the created doc-folder from the root to the _inst_ directory.

**Comment by bbolker** [comment]
For what it's worth, `devtools::check(".",vignettes=FALSE)` works around this problem.
