### ISSUE TITLE
predict() produces warning when model does not

### ISSUE THREAD

**Issue by mdwhitby** [glmmTMB/glmmTMB#411]
The predict function produces the warning: ## Warning in f(par, order = order, ...): value out of range in 'lgamma'
The model does not produce any warnings during fitting. 

I couldn't reproduce the error with the sleepstudy data, so I uploaded my own. The warning can be reproduced with :

```

library(glmmTMB)
TrainData <- read.csv(file = "https://raw.githubusercontent.com/mdwhitby/glmmtmbIssue/master/TrainData.csv")
TestData <- read.csv(file = "https://raw.githubusercontent.com/mdwhitby/glmmtmbIssue/master/TestData.csv")

form<- as.formula(paste0("nLABO ~",
              "(1|GRID)", 
              "+poly(DoY,5)+scale(HEIGHT)+offset(night_hrs)",
              "+scale(nUwind)+scale(nVwind)",
              "+poly(nWNDsp_mean,3)",
              "+scale(nPRES)+scale(nPresChange)",
              "+scale(nRH)",
              "+scale(nCloud)",
              "+scale(nTotRain)",
              "+scale(nMoon)"))


fit <- glmmTMB(form, data=TrainData, family = nbinom1, ziformula = ~0)

p=predict(fit, newdata = TestData)
```

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] glmmTMB_0.2.2.9000   RevoUtils_11.0.1    
[3] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] minqa_1.2.4     MASS_7.3-50     compiler_3.5.1 
 [4] Matrix_1.2-14   tools_3.5.1     TMB_1.7.14     
 [7] yaml_2.2.0      Rcpp_0.12.18    splines_3.5.1  
[10] nlme_3.1-137    grid_3.5.1      nloptr_1.0.4   
[13] lme4_1.1-18-1   lattice_0.20-35

**Comment by mdwhitby** [comment]
This appears to have been fixed in the latest github commit, which also required me to update lme4 and Matrix/TMB.

**Comment by bbolker** [comment]
Huh. OK, that's nice. I guess something to do with the term-ordering bug?

**Comment by bbolker** [comment]
For what it's worth, this function is coming from deep within R: the code is [here](https://github.com/wch/r-source/blob/5a156a0865362bb8381dcd69ac335f5174a4f60c/src/nmath/lgamma.c#L74).  This comes from values of `lgamma()` that are either negative integers or (more likely) > the maximum computable x-value of 2.5327372760800758e+305 ...  I think it's very unlikely to actually be a problem, but we could (1) dig into this example and see where it's coming from, (2) add an explanation along these lines to the docs somewhere.

**Comment by mmaechler** [comment]
Thank you, Ben, for digging into the origin of the warning.  As you probably know, I've been *the* R core person caring about such numeric boundary cases in R's math library... and I argue the warning to be clearly wrong in the second case, i.e. x > 2.53...e305.     I'm pretty convinced this should be changed in R's sources.

**Comment by bbolker** [comment]
Huh. I believe you, but can you explain a bit more?  This cutoff is close to the point where the argument would overflow double precision anyway (`.Machine$double.xmax`), but it seems that the lgamma computation would overflow shortly before the argument got too big?

@mdwhitby : are you sure you want to use `offset(night_hr)` (and not `offset(log(night_hr))`) in your model??  I've recently added this paragraph to the GLMM FAQ:

> a common error is to specify an offset to a log-link model as a raw searching-effort value, i.e. offset(effort) rather than offset(log(effort)). While the intention is to fit a model where counts∝effort, specifying offset(effort) leads to a model where counts∝exp(effort) instead; exp(effort) is often a huge (and model-destabilizing) number.

Still trying to track down exactly where the warnings are triggered  ...

**Comment by mdwhitby** [comment]
Thanks for the model correction. Definitely an oversight on my part.

**Comment by mmaechler** [comment]
@bbolker : I was trying to say that  lgamma() should underflow to `0` or overflow to `Inf` "gracefully", i.e., without any warning.  Maximum Likelihood (and versions of that), i.e. optimization works "fine" in such cases, at least as long as the `optim()` method is robust. R's (and C's) arithmetic does have `Inf > 1e308` and so interval searches work fine.... and the warnings are completely misleading.

`exp(1e11)` also gives `Inf` without a warning or `exp(-1e11)` gives `0` w/o a warning and that is what should happen.

**Comment by bbolker** [comment]
Closing the loop: added a comment to the troubleshooting vignette.
