### ISSUE TITLE
glmmTMB and lsmeans

### ISSUE THREAD

**Issue by pkpddude1** [glmmTMB/glmmTMB#418]
All of a sudden i get the following error message from using lsmeans with glmmTMB.  It was working fine until a few days ago then began failing.  Some of my colleagues are not having this issue but it has appeared on my computer.  

emmeans v 1.3.0
glmmTMB v 0.2.2.0
lsmeans v 2.30-0
TMB v1.7.15

ERROR MESSAGE
lsmeans(m2, pairwise~f)  ##TUkey
Error in ref_grid(object, ...) : 
  Can't handle an object of class  “glmmTMB” 
 Use help("models", package = "emmeans") for information on supported models.

Code enclosed.

```
recover.data.glmmTMB <- function(object, ...) {
  fcall <- getCall(object)
  recover.data(fcall,delete.response(terms(object)),
               attr(model.frame(object),"na.action"), ...)
}
lsm.basis.glmmTMB <- function (object, trms, xlev, grid, vcov.,
                               mode = "asymptotic", component="cond", ...) {
  if (mode != "asymptotic") stop("only asymptotic mode is available")
  if (component != "cond") stop("only tested for conditional component")
  if (missing(vcov.)) 
    V <- as.matrix(vcov(object)[[component]])
  else V <- as.matrix(.my.vcov(object, vcov.))
  dfargs = misc = list()
  if (mode == "asymptotic") {
    dffun = function(k, dfargs) NA
  }
  ## use this? misc = .std.link.labels(family(object), misc)
  contrasts = attr(model.matrix(object), "contrasts")
  m = model.frame(trms, grid, na.action = na.pass, xlev = xlev)
  X = model.matrix(trms, m, contrasts.arg = contrasts)
  bhat = fixef(object)[[component]]
  if (length(bhat) < ncol(X)) {
    kept = match(names(bhat), dimnames(X)[[2]])
    bhat = NA * X[1, ]
    bhat[kept] = fixef(object)[[component]]
    modmat = model.matrix(trms, model.frame(object), contrasts.arg = contrasts)
    nbasis = estimability::nonest.basis(modmat)
  }
  else nbasis = estimability::all.estble
  list(X = X, bhat = bhat, nbasis = nbasis, V = V, dffun = dffun, 
       dfargs = dfargs, misc = misc)
}

library(glmmTMB)
library(lsmeans)
set.seed(101)

dd<- data.frame(y=rnbinom(1000,size=2,mu=1), g=factor(rep(1:20,each=50)), g=factor(rep(1:20,each=50)), f=factor(rep(1:5,200)))
m2 <- glmmTMB(y~f, family=nbinom2,data=dd)
summary(m2)

lsmeans(m2, pairwise~f)  ##TUkey
f.lsm <- lsmeans(m2, "f")
f_contr.lsm <- contrast(f.lsm, "trt.vs.ctrl", ref=1)
```

**Comment by bbolker** [comment]
This fails for me with the CRAN version of glmmTMB but works with the development version. Can you try this with the development version of `glmmTMB` (`devtools::install_github("glmmTMB/glmmTMB/glmmTMB")`) and see if the problem persists?  Are you able to switch to the development version (which will be coming to CRAN soon, and will have the emmeans support built in?  Are you able to switch from lsmeans (which is deprecated) to emmeans?

**Comment by pkpddude1** [comment]
Thanks for the quick reply I will try this tomorrow morning and let you know the result

**Comment by pkpddude1** [comment]
I just tried it.  I installed the development version and it works.  I can now sleep well tonight!!
