### ISSUE TITLE
add ORCIDs?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#419]
We could add ORCIDs to the DESCRIPTION file if we wanted.

**Comment by mebrooks** [comment]
I think this was done with commit 9ef08df6b7dda143eb0abe879f0888a22776ea60 but I can't build the package to check.

**Comment by bbolker** [comment]
Easily locatable ORCIDs closing until/unless other contributors ask us to add ORCIDs for them. @sadatnfs  , is your ORCID 0000-0001-5715-616X or is that someone else?
