### ISSUE TITLE
predict fails if dispformula contains data-dependent bases

### ISSUE THREAD

**Issue by jhmaindonald** [glmmTMB/glmmTMB#421]
This seems a result of changes made recently that fixed Issue #375 

```
url <- 'https://github.com/jhmaindonald/qra/blob/master/data/codling1988.rda?raw=true'
repmis::source_data(url)
HawCon <- within(HawCon, {
  trtGp <- paste0(CN,LifestageTrt)
  gp <- paste0(CN,LifestageTrt,":",RepNumber)
  scTime <- scale(TrtTime)
})
library(glmmTMB)
medFly <- droplevels(subset(HawCon,CN=='MedFly'))
medFly.TMBclog <- glmmTMB(cbind(Dead,Live)~0+trtGp/TrtTime+(TrtTime|gp),
                     dispformula=~trtGp+poly(TrtTime,2),
                     family=betabinomial(link="cloglog"), 
                     data=medFly)
nd <- within(medFly, Rep <- "new")
hatCLL <- predict(medFly.TMBclog, newdata=nd, allow.new.levels=TRUE)
## Error in model.frame.default(drop.unused.levels = TRUE, formula = ~0 +  : 
##  number of variables != number of variable names
```

Note however:

```
## The following generates warning messages, but appears to converge satisfactorily
medFly1.TMBclog <- glmmTMB(cbind(Dead,Live)~0+trtGp/TrtTime+(TrtTime|gp),
                          family=betabinomial(link="cloglog"), 
                          data=medFly)
## The following runs without problem
hatCLL1 <- predict(medFly1.TMBclog, newdata=nd, allow.new.levels=TRUE)
```

R version 3.5.1 Patched (2018-07-19 r74981)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6
. . .

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lattice_0.20-35    DHARMa_0.2.0       glmmTMB_0.2.2.9000 lme4_1.1-19.9000  
[5] Matrix_1.2-14      kableExtra_0.9.0   knitr_1.20        

loaded via a namespace (and not attached):
. . .

**Comment by bbolker** [comment]
sigh, thanks.  Will investigate/fix.

**Comment by bbolker** [comment]
What version of glmmTMB do you know this works with?  I tried it after checking out commit 2a36c780b16b74 (from Nov 29, prior to the recent flurry of commits), seems to fail with that version as well (unless I screwed something up).  Will try next with a clean CRAN install of v 0.2.2 ...

**Comment by bbolker** [comment]
Not sure it really failed with 2a36c78 . It's something to do with `predvars` handling, I think ... works (or at least doesn't throw an error!) if I change `poly(trtTime,2)` to `trtTime` in the dispersion formula ...

**Comment by bbolker** [comment]
Pretty sure it's 763bb1b ("better predvars fix" (!)) that's the problem. Works with 3eb192e (Oct 18) ; fails with e15aa72 (Oct 19, one commit *after* 763bb1b ...

**Comment by bbolker** [comment]
next comment: we don't need beta-binomial, allow.new.levels, etc.  `predict(medFly.TMBclog, newdata=medFly)` fails with the same error message ...

**Comment by bbolker** [comment]
Just to make life difficult: how would we handle a model like `formula = poly(x,2), dispformula = ~ns(x,3), ziformula = scale(x)` ... ?

**Comment by jhmaindonald** [comment]
Apologies for copying the wrong dataset name.  The code appeared to work with the last version of glmmTMB that I had tried, installed from github a few days ago.  It is then the use of the `newdata` argument that is the issue.
