### ISSUE TITLE
Bug in predict() / development version?

### ISSUE THREAD

**Issue by florianhartig** [glmmTMB/glmmTMB#423]
Hi guys, I'm testing glmmTMB for DHARMA, and I'm encountering a problem with the development version on GitHub. The following code runs with the CRAN version 

```
library(DHARMa)
library(glmmTMB)
testData = createData(sampleSize = 500, intercept = 2, fixedEffects = c(1), overdispersion = 0, family = poisson(), quadraticFixedEffects = c(-3), randomEffectVariance = 0, pZeroInflation = 0.6)
fittedModel <- glmmTMB(observedResponse ~ Environment1 + I(Environment1^2) + (1|group), ziformula = ~1 , family = "poisson", data = testData)
summary(fittedModel)
predict(fittedModel, type = "response") 
```

but not with the GitHub version
https://github.com/glmmTMB/glmmTMB/commit/b0084337f92736dfe84fd0f6386c1180a6103181
I get

```
Error in pv[[match_which(tt_vars[[i]], pv_vars) + 1]] : 
  subscript out of bounds
```

**Comment by florianhartig** [comment]
Sorry, I just saw that this may be the same issue as https://github.com/glmmTMB/glmmTMB/issues/421

**Comment by bbolker** [comment]
Can you see if it works with master branch now? (I just merged the fix.)

**Comment by florianhartig** [comment]
yes, now it works!
