### ISSUE TITLE
Prediction methods; possible to do from inside TMB?

### ISSUE THREAD

**Issue by skaug** [glmmTMB/glmmTMB#43]
The predict() methods, if written entirely in R, will constitute many
lines of code. To what extent is possible to have TMB return the predictions?

Recall that predictions are made of "new observations" after the model
has been fit. Also, it is made at an "individual level" (random effects active in TMB)
and "population level" (RE's inactive).

**Comment by psinger** [comment]
I want to pick up on this issue as I am having trouble with the predict method after fitting a model on large data:

    Error in f(x, order = 1): Memory allocation fail in function 'EvalADFunObject'

    Traceback:
    1. pred(mp2)
    2. predict(model, newdata = head(data, 100), type = "response")   # at line 3 of file <text>
    3. predict.glmmTMB(model, newdata = head(data, 100), type = "response")
    4. sdreport(newObj, oldPar, hessian.fixed = H)
    5. obj2$gr(par)
    6. f(x, order = 1)

This also happens, if I try to just pass 100 rows to the predict function. If I fit the model on a smaller sample, the predict method works fine though.

**Comment by casperwberg** [comment]
There is an option to sdreport,
      getReportCovariance=FALSE
that might help
.

2015-08-19 22:25 GMT-07:00 Hans J. Skaug <notifications@github.com>:

**Comment by bbolker** [comment]
The 2016 issue is resolved by the new "fast predict" code.
