### ISSUE TITLE
Error with   gradient function must return a numeric vector of length 5

### ISSUE THREAD

**Issue by hyunjoon12** [glmmTMB/glmmTMB#431]
Dear all,

I am trying to run a multi-level model with a predictor that is in proportions with glmmTMB (i.e, the variable ranges from 0 to 1) and I am getting an error message. 

DV: Individual reported whether they were anxious (coded as 1) or not (coded as 0) five times a day across 21 days. As I am trying to assess the trajectory of individuals' anxiety across days, I took an average of those 5-time points within a day(i.e., thus making this a proportion variable).

IV: I am trying to run a growth curve model. Thus, I have included day of the study(both linear and quadratic) as my IVs.

Noted below is the code that I ran,

anxious <- glmmTMB(imean.anxstate ~ 1 + studyday1+ studyday12 + (1|ppid), data= ema2, family=list(family="beta",link="logit"))

But for some reason, I get the error message noted below.

some components missing from �family�: downstream methods may failspecifying �family� as a plain list is deprecatedNA/NaN function evaluationError in nlminb(start = par, objective = fn, gradient = gr, control = control$optCtrl) : 
  gradient function must return a numeric vector of length 5
Timing stopped at: 0.69 0.11 0.8

I was searching around the web, but I could not find a specific reason why I am getting this error. 
Thanks in advance.

**Comment by bbolker** [comment]
The warning is supposed to be self-explanatory; you should specify the family as `family=beta_family()`.

For the error: it would be great if you could include a reproducible example. People have reported this error before, but usually with huge data sets that are awkward to reproduce ...

**Comment by hyunjoon12** [comment]
Dear Ben,

Thank you so much for your answer. I think that would solve my initial question. But, I also realized that my outcome contains the value 0.
So, I realized that I needed to run zero inflated beta model.

I was referencing this document (https://cran.r-project.org/web/packages/glmmTMB/vignettes/glmmTMB.pdf).
I was only able to find how to run a zero inflated Poisson model in this document. I was curious if there was way to specifically run zero inflated beta model in glmmTMB package?

I once again appreciate your attention to this matter.
Your help really means a lot.
Thanks in advance.

Sincerely,
Hyun Joon Park

**Comment by bbolker** [comment]
Not as a single model. Zero-inflation for a beta distribution (and more generally for continuous distributions whose range doesn't include zero) is conceptually different from zero-inflation for count data, where zeros might come from the conditional distribution (*sampling zeros*) or be *structural zeros*.  Some of your choices for proportion data with zeros:

- fit a *hurdle* model, i.e. fit a binomial model for zero/non-zero, then a beta model for the non-zero observations only (if you want you can report a log-likelihood for the full model as the sum of the log-likelihoods for these two separate models). The `brms` package has zero-inflated (and I think zero-one-inflated) beta distributions - I think (but am not sure) this is how it handles these cases.
- squeeze the zeros (and ones, if they exist) in slightly from the boundaries (see e.g. Smithson and Verkuilen's paper on beta regression)
