### ISSUE TITLE
predict() does not work with non-default contrasts

### ISSUE THREAD

**Issue by cvoeten** [glmmTMB/glmmTMB#439]
... specifically, contrasts that do not provide column names exactly equal to the levels of the factor in question.

```
> contrasts(iris$Species) <- contr.sum
> mod <- glmmTMB(Sepal.Length ~ Species,iris)
> predict(mod)
Error in checkModelMatrix(data.tmb1$X, data.tmb0$X) : 
  Prediction is not possible for unknown fixed effects: Speciesversicolor, Speciesvirginica
Probably some factor levels in 'newdata' require fitting a new model.
```

I tried digging deeper into `predict.glmmTMB` to see where exactly things went south:

- `TMBStruc$data.tmb$X` (which becomes `data.tmb1$X` in `checkModelMatrix()`) contains the factors laid out side-by-side named and treatment-coded, as you would get from `model.matrix(~Species,iris)` _without having changed the contrasts_
- `object$obj$env$data` (which is `data.tmb0$X`) contains the correctly-coded data
- so obviously, they mismatch and `checkModelMatrix()` errors out

Unfortunately, I don't understand the internals well enough to propose a fix...

**Comment by bbolker** [comment]
seems to be occurring within `checkModelMatrix` - new data frame is not inheriting contrasts from original?

**Comment by Sibbe81** [comment]
Hi all,

I have probably encountered the same problem. I am quite new to coding but I have tried different things. In my case, when I am setting non-default contrasts, custom contrasts (3 different comparisons among treatment levels) I will get similar type of error message when trying to simulate residuals and testing overdispersion and zeroinflation in the glmmTMB package + DHARMa.  I have one fixed factor (treatment with four levels), and a nested random factor (1 | Mother/rearing tube) in the model (offspring count being the dependent factor). 
I will get also "Error in checkModelMatrix(data.tmb1$X, data.tmb0$X) : Prediction is not possible for unknown fixed effects:  ..." Probably some factor levels in 'newdata' require fitting a new model."
I have tried to update the latest develop. versions of both of the packages, but it did not help.

**Comment by bbolker** [comment]
I think this is fixed now.  If you want to try it out before it gets pulled into the master development branch, try `remotes::install_github("glmmTMB/glmmTMB/glmmTMB#523")` (you'll need to have development tools such as compilers installed).  If you wait until the pull request has been honored, you can leave out the `#523` at the end to install from the master branch.

**Comment by Sibbe81** [comment]
The issue seems to be fixed now! Thank you very much!!

**Comment by cvoeten** [comment]
Confirming fixed, thanks, Ben!
