### ISSUE TITLE
Add sample weights as additional argument for glmmTMB() (Feature request)

### ISSUE THREAD

**Issue by mmeierer** [glmmTMB/glmmTMB#440]
I understand that the "weight" option in `glmmTMB()` is implemented in the same way than in `glm()`, i.e. https://stats.stackexchange.com/questions/57107/use-of-weights-in-svyglm-vs-glm. 

It would be great to have the additional argument in `glmmTMB()` to consider real sample/survey weights. Unfortunately, the option to model correlational structures and at the same time, sample weights in the setting of mixed GLMs does not yet exist elsewhere.

**Comment by mebrooks** [comment]
We need to update the weights documentation as mentioned in #285. Can you give an example of what you mean by "real sample/survey weights" and maybe we can show you how to replicate that behaviour? Or maybe it's already covered in #285

**Comment by mmeierer** [comment]
Thanks for the pointer to [# 285](https://github.com/glmmTMB/glmmTMB/issues/285). Yes, this indeed what I was referring to.
