### ISSUE TITLE
Incorrect counting of parameters in glmm.TMB object

### ISSUE THREAD

**Issue by rpmady** [glmmTMB/glmmTMB#445]
Hello,

I am trying to count the number of parameters in my model so that I can get a sense of overdispersion. And I use the code `length(fixef(zip_mod5))` but it only returns "3." I put more than that number in the model and when I do `fixef(zip_mod5)` the length looks like it should be more than 3. 
```
Conditional model:
       (Intercept)        trtmthotspot    trtmtpulsed_food  trtmtpulsed_nofood    min_aft_sunrise2            mintemp2             julian2  
        -1.9354302           3.2411138           3.6287025           2.2694383           0.0007076          -0.0007256           0.0600375  
       snow_coverY  
         0.1749731  

Zero-inflation model:
(Intercept)  
     -2.287  
```

I may be missing something here, but currently confused.

**Comment by koenvanbenthem** [comment]
This has to do with the structure of the fixef(model) object. fixef(model) returns a list with 3 entries (always), the first `cond', being the fixed effects for the conditional term, the second `zi' the fixed effects of the zero inflated model and the third `disp' the fixed effects of the dispersion model.
```
length(fixef(zip_mod5)$cond)
length(fixef(zip_mod5)$zi)
length(fixef(zip_mod5)$disp)
```
should be closer to what you are looking for.

In order to obtain all fitted parameters, I think you could also use:
zip_mod5$fit$par

at least, this function is used when calculating the total degrees of freedom:
```
df.residual.glmmTMB <- function (object, ...) 
{
    nobs(object) - length(object$fit$par)
}
```

**Comment by mebrooks** [comment]
@koenvanbenthem is right. I'll just add that there are automated ways of checking overdispersion which are built into the [DHARMa package](https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html).

**Comment by rpmady** [comment]
Thank you for the quick response! @koenvanbenthem that worked great, thanks. And @mebrooks thank you for point that out. The DHARMa package is really useful in visualizing things. Plus, the documentation is really great for something like me that struggles with the statistical side of things.

**Comment by bbolker** [comment]
Also, `glmmTMB` has a `df.residual()` method which is defined as `nobs(object) - length(object$fit$par)`.  This is how the `overdisp_fun()` from the [GLMM FAQ](http://bbolker.github.io/mixedmodels-misc/glmmFAQ.html) works:

```
overdisp_fun <- function(model) {
    rdf <- df.residual(model)
    rp <- residuals(model,type="pearson")
    Pearson.chisq <- sum(rp^2)
    prat <- Pearson.chisq/rdf
    pval <- pchisq(Pearson.chisq, df=rdf, lower.tail=FALSE)
    c(chisq=Pearson.chisq,ratio=prat,rdf=rdf,p=pval)
}
```

I'd be cautious in interpreting this overdispersion score: I'm not sure people know very much about how it actually behaves for zero-inflated models.  If you want to decide among (e.g.) ZIPoiss, ZINB1, ZINB2 models, the safest thing might be to fit them all and compare likelihoods/AIC values.

**Comment by rpmady** [comment]
Thanks @bbolker  for that! I saw that function and used it, but was on the same page as you -- wasn't sure how it works with zero-inflated models. 
I'll follow your suggestion about fitting the different models (poisson and negative binomial), thank you! Need to still figure out if I need to dredge to decide what covariates to keep in or not first.
