### ISSUE TITLE
Different ziformulas - which one should I use?

### ISSUE THREAD

**Issue by gogelmogel** [glmmTMB/glmmTMB#449]
Hi all, I am new to R and statistics in general. I am confused about the different ways of specifying the ziformula: ziformula=~0, ziformula=~1, ziformula=~., ziformula=~spp. How do they differ?

I have tried all of them in my model, and all except "~." are hardly any different.

My dataset is count data of wood inhabiting fungi, collected on pieces of deadwood within 40 forest stands that represent different management gradients. The 40 stands are divided into six clusters representing environmental variables (temperature, precipitation).

I want to investigate the impact of various environmental variables on the abundance of fungi in different forest stands and clusters. There are 2519 data points with many zeros, six predictor variables and two random effects (clusters and stands). I fitted a zero-inflated negative binomial GLMM as such:

`model1 <- glmmTMB(fungi_species ~ deadwood_volume + management_type + decay_stage + 
   deadwood_species + deadwood_position + basal_area + (1|cluster_no/stand_no), data=fungi, 
   ziformula=~1, family=nbinom2)`

If someone could comment on my code and explain the different ziformulas, it'd make me very happy.

**Comment by mebrooks** [comment]
This is not the place to [ask this type of question](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions). As it says in the paper in the R Journal, `ziformula=~spp` means that absences vary by species (spp).  As it says in the package documentation, the default `ziformula=~0` specifies no zero-inflation. Please read the documentation.

**Comment by bbolker** [comment]
specifically, try the [r-sig-mixed-models mailing list](https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models)
