### ISSUE TITLE
Error in Effect.glmmTMB

### ISSUE THREAD

**Issue by jwiethase** [glmmTMB/glmmTMB#450]
I am trying to calculate model effects using the `glmmTMB` package, but I am encountering an error: `Error: 'Effect.default' is not an exported object from 'namespace:effects'`.

I am using MAC OS High Sierra, R version 3.4.2 (2017-09-28), and glmmTMB_0.2.3.

Here is a reproducible example:

    library(glmmTMB)

    Owls <- transform(Owls,
                      Nest=reorder(Nest,NegPerChick),
                      NCalls=SiblingNegotiation,
                      FT=FoodTreatment)

    fit_zipoisson <- glmmTMB(NCalls~(FT+ArrivalTime)*SexParent+
                                   offset(log(BroodSize))+(1|Nest),
                             data=Owls,
                             ziformula=~1,
                             family=nbinom2)

    my_effect <- Effect.glmmTMB(fit_zipoisson, focal.predictors = "SexParent")
which produces

    Error: 'Effect.default' is not an exported object from 'namespace:effects'
    In addition: Warning message:
    In glmmTMB::Effect.glmmTMB(fit_zipoisson, focal.predictors = "SexParent") :
      overriding variance function for effects: computed variances may be incorrect

**Comment by bbolker** [comment]
What version of the `effects` package?  (Can you show the results of `sessionInfo()` from a clean session?

**Comment by jwiethase** [comment]
Here it is:

`> packageVersion("effects")
[1] ‘3.1.2’`

**Comment by bbolker** [comment]
The latest version of `effects` is 4.1.0.  This version depends on R >= 3.5.0.  It *may* be possible to work around/override this, but if it's at all possible for you to update your version of R and `effects` to a more recent version, that will almost certainly make it work.

**Comment by jwiethase** [comment]
Updating R to the latest version `R version 3.5.3 (2019-03-11)` resolved the error.
Many thanks!
