### ISSUE TITLE
A way to test significance of random effect?

### ISSUE THREAD

**Issue by rpmady** [glmmTMB/glmmTMB#456]
Is there a way to test whether the random effect is statistically significant (or meaningful)? I tried to use the LMERConvenienceFunctions, but the glmmTMB objects don't seem to be compatible with this function.

**Comment by bbolker** [comment]
This might be better for [r-sig-mixed-models](https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models). The [relevant section of the GLMM FAQ](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#testing-significance-of-random-effects) should cover this. Please do read that section; there are some important caveats about the limitations of likelihood ratio testing and AIC applied to variance parameters.

```
library(glmmTMB)
m3 <- glmmTMB(Reaction ~ Days+(Days|Subject), sleepstudy)
m2 <- update(m3, . ~ Days + (Days||Subject), sleepstudy)
m1 <- update(m3, . ~ Days + (1|Subject))
m0 <- update(m3, . ~ Days)
anova(m3,m2,m1,m0) ## sequential tests
```

Correlation between slope and intercept isn't statistically significant
(last test, between m2 and m3, has p=0.8), but all other terms (among-subject
intercept variation, among-subject slope variation) are.

Parametric bootstrapping should also work.

**Comment by rpmady** [comment]
Thanks for the reply @bbolker! I got in my head that I couldn't use the anova() function because, in your example, m0 isn't nested in m1--they were different structures not necessarily nested. I've still yet to do the parametric bootstrapping because I don't quite understand it in the context of the zero-inflated models I'm running. Thank you for the guidance.

**Comment by rpmady** [comment]
Also, thanks for steering me towards the r-sig-mixed-models list.

**Comment by bbolker** [comment]
FWIW these models *are* nested m0 < m1 < m2 < m3 : 

- covariance constrained to 0 (m3 -> m2)
- slope variance constrained to 0 (m2 -> m1)
- intercept variance constrained to 0 (m1 -> m0)

**Comment by rpmady** [comment]
I'm not sure what FWIW means, but yes, I see what you mean. Thanks for the clarification!

**Comment by bbolker** [comment]
"for what it's worth"
