### ISSUE TITLE
Output to latex code?

### ISSUE THREAD

**Issue by skanskan** [glmmTMB/glmmTMB#462]
Hello

How can I export the summary of my model to Latex code?
I've tried many packages buy all say "summary.glmmTMB objects not supported".

**Comment by arnima-github** [comment]
The first example in ?glmmTMB is

`m1 <- glmmTMB(count~ mined + (1|site), zi=~mined, family=poisson, data=Salamanders)`

and we can create a summary object with:

`s1 <- summary(m1)`

To export the summary tables we can use the xtable package:

```
xtable(coef(s1)$cond, digits=3)
xtable(coef(s1)$zi, digits=3)

**Comment by skanskan** [comment]
Hello and thanks for your help.

The first table is OK but what is that "zi"?

```
Error in UseMethod("xtable") : 
  no applicable method for 'xtable' applied to an object of class "NULL"
```

because my zi is 0.

```
List of 11
 $ logLik      :Class 'logLik' : -591703 (df=8)
 $ family      : chr "binomial"
 $ link        : chr "logit"
 $ ngrps       :List of 2
  ..$ cond: Named num 19
  .. ..- attr(*, "names")= chr "EAP"
  ..$ zi  : num(0) 
 $ nobs        : int 985696
```
I would like to also get as latex the beginning of the summary:

>  Family: binomial  ( logit )
> Formula:          Output ~ var1 + var2 + ... +      (1 | ID)
> Data: mydata
> 
>      AIC      BIC   logLik deviance df.resid 
>  1183432  1183536  -591803  1183405   985687 
> 
> Random effects:
> 
> Conditional model:
>  Groups Name        Variance Std.Dev.
>  ID   (Intercept) 0.3338   0.3777  
> Number of obs: 1885696, groups:  ID, 34

**Comment by arnima-github** [comment]
To include all the model information (formula, likelihood, etc.) it's best to put the entire summary output inside a verbatim block:

```
verbatim <- function(x)
{
  txt <- trimws(capture.output(x))
  txt <- c("\\begin{verbatim}", txt, "\\end{verbatim}")
  cat(txt, sep="\n")
}
```
For example,
```
m1 <- glmmTMB(count~ mined + (1|site), zi=~mined, family=poisson, data=Salamanders)
verbatim(summary(m1))
```
looks pretty good in a LaTeX document.

**Comment by bbolker** [comment]
- the reason you get an error for `zi` is precisely that you don't have a zero-inflation model.  Just skip that bit.
- Can you tell us more about what kind of output you're expecting?  e.g., what package/approach would you use to get LaTeX output for an `lm` model?

I extended @arnima-github's idea a little bit, so that the random-effects variance-covariance matrix is pretty-printed (only the top block is verbatim).

```
#' @param x an expression to evaluate
#' @param stop_ex regular expression for truncating output
#' @param stop_which which occurrence of \code{stop_ex} to find
verbatim <- function(x, stop_ex=NULL, stop_which=1) {
    txt <- trimws(capture.output(x))
    if (!is.null(stop_ex)) {
        txt <- txt[seq(grep(stop_ex,txt)[stop_which]-1)]
    }
    txt <- c("\\begin{verbatim}", txt, "\\end{verbatim}")
    cat(txt, sep="\n")
}

m1 <- glmmTMB(formula = count ~ mined + (1 | site), data = Salamanders, 
              family = poisson, ziformula = ~mined, dispformula = ~1)

verbatim(summary(m1), "Random effects:")
ss <- summary(m1)
xtable(lme4::formatVC(ss$varcor$cond))
xtable(coef(ss)$cond)
xtable(coef(ss)$zi)
```

This sets the results up as a verbatim block + three separate tables. Optimally I guess we'd want a table with sub-headings, but that seems like more work ...

In the meantime I also wrote an extension for `texreg` (but this prints only fixed-effect parameters).

```
## methods for texreg
##' @param model a glmmTMB model
##' @examples
##' m1 <- glmmTMB(formula = count ~ mined + (1 | site), data = Salamanders, 
##'    family = poisson, ziformula = ~mined, dispformula = ~1)
extract.glmmTMB <- function(model) {
    cc <- coef(summary(model))
    cc <- cc[!vapply(cc,is.null,logical(1))]
    nn <- names(cc)
    pref <- ifelse(nn=="cond","",paste0(nn,"_"))
    names <- unlist(Map(function(x,y) paste0(x,rownames(y)),
                        pref,cc))
    co <- unlist(lapply(cc,function(x) x[,"Estimate"]))
    se <- unlist(lapply(cc,function(x) x[,"Std. Error"]))
    pval <- unlist(lapply(cc,function(x) x[,"Pr(>|z|)"]))
    ## alternately could do something like
    ##  rownames(unlist(cc)) -> gsub("\\.","_",.)
    ##  -> gsub("cond_","")
    tr <- createTexreg(
        coef.names = names,
        coef = co,
        se = se,
        pvalues = pval
        ## use AIC/BIC/logLik?
        ## gof.names = gof.names,
        ## gof = gof
    )
    return(tr)
}
setMethod("extract", signature = className("glmmTMB", "glmmTMB"),
          definition = extract.glmmTMB)
```

**Comment by skanskan** [comment]
> Can you tell us more about what kind of output you're expecting? 

The same information you see at the console but preferably a little bit more beautiful, as a well formated table or two.

> e.g., what package/approach would you use to get LaTeX output for an lm model?
Any of them would be OK. Maybe xtable or stargaze.
I will copy the output to a Latex document. The table will look like Booktabs.

**Comment by bbolker** [comment]
There are a few strategies available now with add-on packages `xtable`, `texreg`, `huxtable` (listed in `vignette("model_evaluation")`, sections 3.2-3.5), closing this now.
