### ISSUE TITLE
The sign of the zi model of the hurdle() function seems to be inverted.

### ISSUE THREAD

**Issue by JOOHOJUN** [glmmTMB/glmmTMB#470]
Hi
I am using a hurdle multi-layer model with glmmTMB as a Korean student.

It may be something I do not understand, but the coefficients of zi model (logistic) in the hurdle multi-layer model seem to be reversed.

The dependent variable is Retweet Count and the independent variable is the URL and VerifiedID (VerifiedID is 1 if authenticated Twitter user, 0 otherwise.)

When using hurdle multi-layer model, the VerifiedID coefficient of the zi model was negative (-)(**result1**). Therefore, even if the analysis was performed by changing to hurdle model, the sign was the same (-)(**result2**).

I checked the data, and I can almost observe the VerifiedID only on the retweet 1 or more. There were only 3 out of 411 cases where the number of retweets was 0 and VerifiedID was 1. Therefore, the sign of verifiedID of zi model thinks (+) is normal. This is because the probability of 1 or more Retweets is greater.

I used the hurdle model of the pscl package, but the coefficients were marked with (+), unlike the above results(**result3**).

summary of zero inflation models on hurdle (mixed) model
result1 - glmmTMB(hurdle mixed model) -> VerifiedID   **-4.0355**     1.0283  -3.925 8.69e-05 ***
result2 - glmmTMB(hurdle model)            -> VerifiedID  **-3.08433**    0.58624  -5.261 1.43e-07 ***
result3 - pscl::hurdle                                  -> VerifiedID   **3.08433**    0.58624   5.261 1.43e-07  

I am sorry if I do not understand well. Nevertheless, I could not find an answer, so I asked.
Thank you.

**##### result1**---> 
Family: truncated_nbinom2  ( log )
Formula:          Retweet_Count ~ Url + VerifiedID + (1 | level2)
Zero inflation:                 ~Url + VerifiedID + (1 | level2)
Data: data
     AIC      BIC   logLik deviance df.resid 
  9970.5  10018.3  -4976.3   9952.5     1492 
Random effects:
Conditional model:
 Groups Name        Variance Std.Dev.
 level2 (Intercept) 3.443    1.856   
Number of obs: 1501, groups:  level2, 167

Zero-inflation model:
 Groups Name        Variance Std.Dev.
 level2 (Intercept) 5.156    2.271   
Number of obs: 1501, groups:  level2, 167
Overdispersion parameter for truncated_nbinom2 family (): 0.517 

Conditional model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  2.06547    0.17471  11.822   <2e-16 ***
Url         -0.03252    0.14860  -0.219   0.8268    
VerifiedID   1.32290    0.52624   2.514   0.0119 *  

Zero-inflation model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -1.5783     0.2325  -6.787 1.14e-11 ***
Url          -0.7944     0.2670  -2.975  0.00293 ** 
**VerifiedID   -4.0355**     1.0283  -3.925 8.69e-05 ***

**##### result2**>>>
 Family: truncated_nbinom2  ( log )
Formula:          Retweet_Count ~ Url + VerifiedID
Zero inflation:                 ~Url + VerifiedID
Data: data
     AIC      BIC   logLik deviance df.resid 
 11021.8  11059.0  -5503.9  11007.8     1494 
Overdispersion parameter for truncated_nbinom2 family (): 1.29e-09 

Conditional model:
             Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -14.5964  1491.6359  -0.010 0.992192    
Url           -0.7158     0.1956  -3.659 0.000254 ***
VerifiedID     1.7453     0.2546   6.854 7.16e-12 ***

Zero-inflation model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept) -0.84310    0.05999 -14.054  < 2e-16 ***
Url         -0.51391    0.13265  -3.874 0.000107 ***
**VerifiedID  -3.08433**    0.58624  -5.261 1.43e-07 ***

**##### result3**>>>pscl package::hurdle
hurdle(formula = Retweet_Count ~ Url + VerifiedID | Url + VerifiedID, data = data, 
    dist = "negbin")

Pearson residuals:
    Min      1Q  Median      3Q     Max 
-0.4345 -0.3667 -0.3282 -0.2522 99.0931 

Count model coefficients (truncated negbin with log link):
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  -4.4645     9.5701  -0.467 0.640856    
Url          -0.7162     0.1956  -3.661 0.000251 ***
VerifiedID    1.7452     0.2546   6.855 7.11e-12 ***
Log(theta)  -10.3394     9.5708  -1.080 0.280004    

Zero hurdle model coefficients (binomial with logit link):
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  0.84310    0.05999  14.054  < 2e-16 ***
Url          0.51391    0.13265   3.874 0.000107 ***
**VerifiedID   3.08433**    0.58624   5.261 1.43e-07 ***

Theta: count = 0
Number of iterations in BFGS optimization: 14 
Log-likelihood: -5504 on 7 Df

**Comment by mebrooks** [comment]
The difference is that in `glmmTMB`, `ziformula` is modelling the probability of zero, while `pscl`'s `hurdle` function, is modeling the probability of non-zero.

Here's another example
```
> library(pscl)
> library(glmmTMB)
> data("bioChemists", package = "pscl")
> glmmTMB(art ~ phd, zi=~phd, data = bioChemists, family=truncated_poisson)
Formula:          art ~ phd
Zero inflation:       ~phd
Data: bioChemists
      AIC       BIC    logLik  df.resid 
 3358.913  3378.189 -1675.457       911 

Number of obs: 915

Fixed Effects:

Conditional model:
(Intercept)          phd  
    0.61414      0.04518  

Zero-inflation model:
(Intercept)          phd  
    -0.3075      -0.1750  
> hurdle(art ~ phd, data = bioChemists)

Call:
hurdle(formula = art ~ phd, data = bioChemists)

Count model coefficients (truncated poisson with log link):
(Intercept)          phd  
    0.61415      0.04517  

Zero hurdle model coefficients (binomial with logit link):
(Intercept)          phd  
     0.3075       0.1750  
```
Here is the logistic regression that `glmmTMB` is doing internally
```
> glm((art==0) ~ phd, data = bioChemists, family="binomial")

Call:  glm(formula = (art == 0) ~ phd, family = "binomial", data = bioChemists)

Coefficients:
(Intercept)          phd  
    -0.3075      -0.1750  

Degrees of Freedom: 914 Total (i.e. Null);  913 Residual
Null Deviance:	    1119 
Residual Deviance: 1113 	AIC: 1117
```
and this is what `hurdle` is doing internally
```
> glm((art>0) ~ phd, data = bioChemists, family="binomial")

Call:  glm(formula = (art > 0) ~ phd, family = "binomial", data = bioChemists)

Coefficients:
(Intercept)          phd  
     0.3075       0.1750  

Degrees of Freedom: 914 Total (i.e. Null);  913 Residual
Null Deviance:	    1119 
Residual Deviance: 1113 	AIC: 1117
```

**Comment by JOOHOJUN** [comment]
In the paper of the hurdle model in Korea, It is usually interpreted as non-zero modeling, but for the first time I knew that glmmTMB would be modeled as Zero.

Thank you for your reply.
