### ISSUE TITLE
make car::vif() work

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#473]
haven't explored it yet, but had a report of someone who was still using `glmmADMB` because this function doesn't yet work with `glmmTMB` ...

**Comment by strengejacke** [comment]
FYI, maybe you have seen that we have started the R _easystats_-project, which aims at developing small light-weight-packages with a clear focus. Many functions of the _sjstats_-package, where I also implemented the function to compute r-squared for mixed models, are now re-implemented in a more straightforward way in different packages of the _easystats_ project.

One package is [performance](https://easystats.github.io/performance/) (which also contains the "new" `r2()`-function), which provides utilities for computing indices of model quality and goodness of fit. 

One function is `check_collinearity()`, where I implemented a multicollinearity-check for various model-types, including glmmTMB:

https://github.com/easystats/performance/blob/master/R/check_collinearity.R

While it's possible to compute the VIF for the count-/conditional model-part, `glmmTMB:::model.matrix()` does not allow to return the model matrix for the ZI-component. That's why currently it's quite difficult to calculate the VIF for the ZI-component of glmmTMB-models.

Else, car::VIF() should already work with glmmTMB, except that `vcov()` returns a list, and you need to extract the conditionl-component of that list to make car::VIF work.

**Comment by strengejacke** [comment]
A 2nd FYI: I made `check_collinearity()` work for the ZI-component of glmmTMB-models:

``` r
library(performance)
library(glmmTMB)
m <- glmmTMB(
  count ~ spp + mined + cover + DOP + sample + (1 | site),
  zi =  ~ spp + DOY + Wtemp + DOP,
  family = truncated_poisson,
  data = Salamanders
)

check_collinearity(m)
#> # Check for Multicollinearity
#> 
#> * conditional component:
#> 
#> Low Correlation
#> 
#>  Predictor  VIF Increased SE
#>        spp 1.06         1.03
#>      mined 1.18         1.09
#>      cover 1.24         1.11
#>        DOP 1.10         1.05
#>     sample 1.07         1.04
#> 
#> * zero inflated component:
#> 
#> Low Correlation
#> 
#>  Predictor  VIF Increased SE
#>        spp 1.00         1.00
#>        DOY 1.01         1.00
#>      Wtemp 1.01         1.00
#>        DOP 1.01         1.00

check_collinearity(m, "count")
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>  Predictor  VIF Increased SE
#>        spp 1.06         1.03
#>      mined 1.18         1.09
#>      cover 1.24         1.11
#>        DOP 1.10         1.05
#>     sample 1.07         1.04

check_collinearity(m, "zi")
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>  Predictor  VIF Increased SE
#>        spp 1.00         1.00
#>        DOY 1.01         1.00
#>      Wtemp 1.01         1.00
#>        DOP 1.01         1.00
```

<sup>Created on 2019-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by LincolnPetersen** [comment]
I have been searching for a way to calculate the variance inflation factor of models I am running with `glmmTMB` but cannot find a way of making `car::vif` work. This is a problem for me because I have to use the Conway-Maxwel-Poisson that is not available in other packages (and that, according to AIC, fits much better my data). I have seen that the problem arises whatever distribution I use and with or without the random intercept or the zero-inflation. I have also installed the package `performance` but the function `check_collinearity()` does not seem to be available. This is what I get:
```

> library(car)
> library(performance)
> library(glmmTMB)
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
[3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
[5] LC_TIME=Spanish_Spain.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_0.2.3     performance_0.1.0 car_3.0-2         carData_3.0-2    

loaded via a namespace (and not attached):
 [1] zip_2.0.1         Rcpp_1.0.1        nloptr_1.2.1      cellranger_1.1.0 
 [5] pillar_1.4.0      compiler_3.6.0    TMB_1.7.15        forcats_0.4.0    
 [9] tools_3.6.0       boot_1.3-22       lme4_1.1-21       tibble_2.1.1     
[13] nlme_3.1-139      lattice_0.20-38   pkgconfig_2.0.2   rlang_0.3.4      
[17] openxlsx_4.1.0    Matrix_1.2-17     curl_3.3          haven_2.1.0      
[21] rio_0.5.16        bayestestR_0.1.0  hms_0.4.2         grid_3.6.0       
[25] data.table_1.12.2 readxl_1.3.1      foreign_0.8-71    minqa_1.2.4      
[29] magrittr_1.5      splines_3.6.0     MASS_7.3-51.4     abind_1.4-5      
[33] insight_0.3.0     crayon_1.3.4     
> beta1<- 0.5
> beta2<- -2
> pred1<- runif(n=1000,0,1)
> pred2<- runif(n=1000,0,1)
> Int<- 1
> logE.y<- Int + pred1*beta1 + pred2*beta2
> E.y<- exp(logE.y)
> resp<- rpois(n=1000,lambda=E.y)
> dati<- data.frame(resp=resp,pred1=pred1,pred2=pred2)
> 
> glmCompois<- glmmTMB(resp~pred1+pred2,data=dati,compois)
> vif(glmCompois)
Error in cov2cor(v) : 'V' is not a square numeric matrix
In addition: Warning message:
In vif.default(glmCompois) : No intercept: vifs may not be sensible.
> glmPois<- glmmTMB(resp~pred1+pred2,data=dati,poisson)
> vif(glmPois)
Error in cov2cor(v) : 'V' is not a square numeric matrix
In addition: Warning message:
In vif.default(glmPois) : No intercept: vifs may not be sensible.
> glmGaus<- glmmTMB(resp~pred1+pred2,data=dati)
> vif(glmGaus)
Error in cov2cor(v) : 'V' is not a square numeric matrix
In addition: Warning message:
In vif.default(glmGaus) : No intercept: vifs may not be sensible.
```

**Comment by strengejacke** [comment]
The function is implemented in the developer version, which you can install from GitHub.

See instructions here:
https://github.com/easystats/performance/blob/master/README.md

**Comment by LincolnPetersen** [comment]
Thank you,
I have first removed (`remove.packages("performance")`), shut down R, re-initiated and then installed `performance` following the instructions to install the developer version. This is what I get:

```
> install.packages("devtools")
Installing package into ‘D:/Simone/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/devtools_2.0.2.zip'
Content type 'application/zip' length 387734 bytes (378 KB)
downloaded 378 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Simone\AppData\Local\Temp\RtmpywmRBs\downloaded_packages
> devtools::install_github("easystats/performance")
Downloading GitHub repo easystats/performance@master
√  checking for file 'C:\Users\Simone\AppData\Local\Temp\RtmpywmRBs\remotes26b45b83576a\easystats-performance-55ab743/DESCRIPTION' ... 
-  preparing 'performance':
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'performance' ...
   ** using staged installation
   ** R
   ** byte-compile and prepare package for lazy loading
   Error: object 'area_under_curve' is not exported by 'namespace:bayestestR'
   Ejecución interrumpida
   ERROR: lazy loading failed for package 'performance'
-  removing 'C:/Users/Simone/AppData/Local/Temp/Rtmp6psOyh/Rinst11042df15684/performance'
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
> library("performance")
Error in library("performance") : 
  there is no package called ‘performance’
```

**Comment by strengejacke** [comment]
Sorry, as I'm developing or contributing to these packages, I'm working with the latest GitHub versions. You also need the _bayestestR_ package from GitHub.

The packages have a dependency chain (and identical release cycle):
insight => bayestestR => performance => (other packages currently not on CRAN).

insight is very up to date on CRAN, but bayestestR is short before submission of the next version, so performance already included some functions from the _forthcoming_ bayestestR. So, install bayestestR from GitHub first, then performance, and then it _should_ work.

**Comment by LincolnPetersen** [comment]
OK, thanks, I have managed to install the last version of `performance` by first installing (via github) `bayestestR`. Now the function `check_collinearity()` is available. However, I get an error message:
```

> check_collinearity(glmCompois)
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```

**Comment by strengejacke** [comment]
I think this issue should be better discussed in the related repo (https://github.com/easystats/performance/issues/55). Do you have a reproducible example that you can post there?

**Comment by lpxcad** [comment]
Hi @strengejacke ,

Thanks for developing this package - its super useful!

I wanted to ask for you help with the following, I can use check_colinearity for glmmtmb objects but only for the count component and not the zi component 

modelZeroR <-  glmmTMB(Df$TotalASI ~  Df$currentlyusecannabis +  Df$Gender,
                    ziformula =~ Df$currentlyusecannabis +  Df$Gender,
                    data = Df) 

> check_collinearity(modelZeroR,  'count')
Low Correlation

   Parameter                       VIF     Increased SE
 Df$currentlyusecannabis 1.01         1.01
                        Df$Gender 1.01         1.01

But...
> check_collinearity(modelZeroR,  'all')
> check_collinearity(modelZeroR,  'zi')
> check_collinearity(modelZeroR,  'zero_inflated')
and leaving the default
> check_collinearity(modelZeroR)
all return
Error in `[.data.frame`(mf, , unique(c(response, fixed.component.data,  : 
  undefined columns selected

Any help you could give would be greatly appreciated!

**Comment by strengejacke** [comment]
You have provided the `data`-argument, so you don't need to use `Df$` for each predictor. This is what probably leads to the error:

``` r
library(glmmTMB)
library(performance)
data("Salamanders")
m1 <- glmmTMB(
  count ~ spp + mined + (1 | site),
  ziformula = ~ spp + mined,
  family = truncated_poisson,
  data = Salamanders
)

m2 <- glmmTMB(
  Salamanders$count ~ Salamanders$spp + Salamanders$mined + (1 | Salamanders$site),
  ziformula = ~ Salamanders$spp + Salamanders$mined,
  family = truncated_poisson,
  data = Salamanders
)

check_collinearity(m1)
#> # Check for Multicollinearity
#> 
#> * conditional component:
#> 
#> Low Correlation
#> 
#>  Parameter  VIF Increased SE
#>        spp 1.01         1.00
#>      mined 1.01         1.00
#> 
#> * zero inflated component:
#> 
#> Low Correlation
#> 
#>  Parameter  VIF Increased SE
#>        spp 1.08         1.04
#>      mined 1.08         1.04

check_collinearity(m2)
#> Error in `[.data.frame`(mf, , unique(c(response, fixed.component.data, : undefined columns selected
```

<sup>Created on 2020-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I suggest re-writing your model-formula, which should then work with `check_collinearity()`.

```
modelZeroR <- glmmTMB(
  TotalASI ~ currentlyusecannabis + Gender,
  ziformula = ~ currentlyusecannabis + Gender,
  data = Df
)
```

**Comment by lpxcad** [comment]
That did it! Thank you for taking the time to reply
