### ISSUE TITLE
fitting count distributions to non-integer data should give a warning

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#474]
In my experience these kinds of warnings catch a lot of problems, e.g. users confused about varying exposure/area per observation (i.e. don't know about offsets). I'm pretty sure that both `glm()` and `lme4::glmer()` give warnings in this situation, we can look into how/where the checks are implemented.

```
z <- rlnorm(100,1,1)
library(glmmTMB)
glmmTMB(z~1,family=poisson)
```

**Comment by mebrooks** [comment]
I agree. Someone's been emailing me lately and asking if it's ok to use `family=compois` for non-integer data. I'm trying to explain that it's best to use the raw data if possible. They pointed out something interesting, but I haven't had time to think about it carefully: in the Poisson and CMP, if you multiply the response variable by a constant (e.g. in their case to make it an integer) then the intercept absorbs the multiplication.
```
lambda=exp(1.5)
n=10000
dat=rpois(n, lambda)
dat0.1=dat*0.1  #non-integer data

fixef(glmmTMB(dat~1, family=poisson))
fixef(glmmTMB(dat0.1~1, family=poisson)) #non-integer data
log(lambda)+log(.1)
```

**Comment by mmaechler** [comment]
Of course, the *mean* multiplication factor goes into the intercept with a log() link.  
But the variance and all inference becomes completely wrong... and I agree with Ben that I'm sure many users produce nonsense analysis by using inappropriate count models for non-count but "fudged to look like count" data,  with "multiplication" being just one of several complete nonsense tricks.

I don't have too much time right now, and I'm not sure if it easy to reliably detect such user fudging.
If we give warning for non-integer, people will tell (on stackoverflow, twitter,blog, ..) how to "fix" this, e.g. by rounding their non-integers or similar nonsense.   Honestly I'm appalled how students and data analysts and probably many people who need their research papers to get published .. blog and chat and recommend tricks to each other on what to do to get rid of warnings and errors ... or use a package that does not give the warnings or errors ...  
 Even our stats master students use Google to solve their R modeling problems and cut'n'paste code found "on the internet"  and are clueless what the code does (apart from "it works afterwards")....

**Comment by mebrooks** [comment]
Yep, you're right. I hadn't noticed, but the std errors are completely different, so inference would be wrong.

**Comment by bbolker** [comment]
A little more information: 

- in base R/glm, the warning comes from calling `dpois()` with non-integer values.  [TMB's version of dpois doesn't check](https://github.com/kaskr/adcomp/blob/12b47bec0391ce48b04475c1f814856210f204a0/TMB/inst/include/lgamma.hpp#L122-L128).
- warnings for non-integer values in binomial models are flagged in `binomial()$initialize`, which seems like a more sensible/upstream place to check. `poisson()$initialize` checks for *negative* values, but not for non-integer values.  It would be nice if this were modified upstream in R, but that seems unlikely to happen, so I'd suggest that we should add a generic set of checks for count responses (any that don't already have a warning built in to their `$initialize` component) somewhere around [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L720-L728)

**Comment by bbolker** [comment]
I think the warning is a good first step.  People can always ignore it or round their data, but at least we've tried, and for a lot of well-intentioned but naive users this would be the first step of asking deeper questions about what they're trying to model.  For what it's worth, the (very simple) test case I tried for compois with non-integer responses errored out anyway ...

**Comment by bbolker** [comment]
One thought here is whether to change the tests [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L649), [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L710), and [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L737) should unified. *If* these models give plausible log-likelihoods (e.g. for integer m, the LL values for (m,m+1) are continuous between LL(m) and LL(m+1) ...) then we probably should use a consistent test with a 0.001 rounding threshold ...
