### ISSUE TITLE
fix SHLIB_OPENMP_FLAGS consistency

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#478]
` R CMD check` is now giving us a `NOTE` about compiler flags.  I think this should be pretty easily to resolve if we go and read the relevant portion of the R Extensions manual (@sadatnfs ?)

> checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... NOTE
    src/Makevars: SHLIB_OPENMP_CXXFLAGS is included in PKG_CXXFLAGS but no OPENMP macro in PKG_LIBS
    src/Makevars: it is not portable to include SHLIB_OPENMP_*' macros in PKG_CPPFLAGS
  Use of these macros is discussed in sect 1.2.1.1 of ‘Writing R
  Extensions’. The macros for different languages may differ so the
  matching macro must be used in PKG_CXXFLAGS (etc) and match that used
  in PKG_LIBS (except for Fortran: see the manual).
  PKG_CPPFLAGS is used for both C and C++ code so it is not portable to
  use it for these macros.
  Using a SHLIB_OPENMP_ macro for compilation but none in PKG_LIBS is not
  portable and may result in installation errors.

**Comment by sadatnfs** [comment]
Hmm, the 2 notes I'm seeing form the latest Travis build are not with the above trace. Do you have link to the build which showed that @bbolker?

That being said, according to this [SO](https://stackoverflow.com/questions/54056594/cran-acceptable-way-of-linking-to-openmp-some-c-code-called-from-rcpp) question, it looks like the solution is as simple as adding the `PKG_LIBS` variable in `Makevars` as such:

```
PKG_LIBS = $(SHLIB_OPENMP_CXXFLAGS) $(SHLIB_OPENMP_CFLAGS)
```

**Comment by bbolker** [comment]
it wasn't on Travis, it was on my local machine. Presumably some different checking flags set (`--as-cran`?)  Testing your solution now ...

**Comment by bbolker** [comment]
It appears that in order to pass without a `NOTE` about portability, `Makevars` must contain *only*

```
PKG_CXXFLAGS += $(SHLIB_OPENMP_CXXFLAGS)
PKG_LIBS = $(SHLIB_OPENMP_CXXFLAGS)
```

(i.e. no reference to `PKG_CPPFLAGS`).  Presumably this will work OK ... ? (I will test on Travis, but if people could also test locally that would be great ...)

**Comment by sadatnfs** [comment]
Huh. Interesting. Will test locally later on in the day, thanks!

Also, would we want to have a `+=` for the `PKG_LIBS` assignment? I don't know what its value is apriori to this assignment in the Makevars.

**Comment by barracuda156** [comment]
This will do nothing, since there is no configure to actually set OpenMP-required flags.
