### ISSUE TITLE
Converge in GLM but not in GLMMTMB

### ISSUE THREAD

**Issue by phisanti** [glmmTMB/glmmTMB#482]
I am working with a multivariate model with a Gamma distribution and I would like to make use of the lme4 syntaxis deployed in glmmTMB, however, I have noticed something strange with my model. Apparently, the model easily converges when I use `stats::glm`, but seems to give an error in the `glmmTMB `framework. Here is a reproducible example:

```
d <- data.frame(gamlss.data::plasma) # Sample dataset

m4.1 <- glm(calories ~ fat*fiber, family = Gamma(link = "log"), data = d)    # Dos parámetros con interacción
m4.2 <- glmmTMB(calories ~ fat*fiber, family = Gamma(link = "log"), data = d)    # Dos parámetros con interacción

>Warning message:
In fitTMB(TMBStruc) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
```

I guess, the solution might lie on the control parameters, but after looking on the troubleshooting vignette, I am not sure on where to start.

**Comment by bbolker** [comment]
I can confirm that the coefficients match very closely, but the variance-covariance matrix/standard errors are off:

Coefficients -- extremely close:
```
cbind(coef(m4.1),fixef(m4.2)$cond)
                     [,1]          [,2]
(Intercept)  6.1200796858  6.1200775740
fat          0.0141238094  0.0141238332
fiber        0.0510756541  0.0510758071
fat:fiber   -0.0004092008 -0.0004092024
```

Standard errors are quite different:
```
> cbind(sqrt(diag(vcov(m4.1))),
+       sqrt(diag(vcov(m4.2)$cond)))
                    [,1]         [,2]
(Intercept) 5.114823e-02 0.0224956253
fat         6.692547e-04 0.0002250972
fiber       3.704091e-03 0.0014481740
fat:fiber   4.476284e-05          NaN
Warning message:
In sqrt(diag(vcov(m4.2)$cond)) : NaNs produced
```

I'm tempted to try with a different optimizer, but if the Hessian is computed internally via TMB I'm not sure that's going to make a difference ...

**Comment by casperwberg** [comment]
The problem goes away if you standardize the explanatory variables.
The Hessian is actually positive definite, but the finite-difference method
used ( optimHess ) misses that.



Den søn. 19. maj 2019 kl. 19.43 skrev Ben Bolker <notifications@github.com>:

**Comment by bbolker** [comment]
Nice catch. More investigation of Hessian calculations:

```
tmpf <- function(h) sqrt(diag(solve(h)))[1:np]
s_vals <- cbind(glm=sqrt(diag(vcov(m4.1))),
                numDeriv=tmpf(hessian(m4.2$obj$fn,cc)),
                numJac=tmpf(jacobian(func=m4.2$obj$gr, x=cc)),
                numJac2=tmpf(jacobian(func=m4.2$obj$gr, x=cc,
                                      method="simple")),
                glmmTMB=sqrt(diag(vcov(m4.2)$cond)),
                oh1=tmpf(optimHess(cc,m4.2$obj$fn,m4.2$obj$gr)),
                oh2=tmpf(optimHess(cc,m4.2$obj$fn,m4.2$obj$gr,
                                   control=list(parscale=abs(cc))))
                )
print(s_vals,digits=3)
```

It looks like the Hessian calculations based on `numDeriv` are more accurate, even when we use "simple" finite differences of the gradients (`numJac2`) rather than Richardson extrapolation (`numJac`). We could include this in troubleshooting advice in the near future, but I wonder (@kaskr ?) if it's worth using (or allowing as an option) `numDeriv::jacobian(obj$gr)` rather than `optimHess` in `TMB::sdreport` ?


```
                 glm numDeriv   numJac  numJac2  glmmTMB      oh1      oh2
(Intercept) 5.11e-02 5.21e-02 5.21e-02 5.58e-02 0.022496 0.022507 0.022507
fat         6.69e-04 6.77e-04 6.77e-04 7.55e-04 0.000225 0.000225 0.000225
fiber       3.70e-03 3.80e-03 3.80e-03 4.24e-03 0.001448 0.001449 0.001449
fat:fiber   4.48e-05 4.54e-05 4.54e-05 5.52e-05      NaN      NaN      NaN
```

It looks like `numDeriv`

**Comment by kaskr** [comment]
@bbolker Users can already apply any Hessian method of choice through the argument `hessian.fixed` to `TMB::sdreport`. But maybe an additional option list such as
`hessianMethod = c("simple", "richardson", "exact", "optimHess")`
would be helpful. I find it interesting/unfortunate that the current default method `optimHess` is the least accurate of all methods.

**Comment by mebrooks** [comment]
Sounds promising! Should we change the default called by glmmTMB?

**Comment by kaskr** [comment]
@mebrooks I think it would make sense to use `h <- jacobian(obj$gr)` with symmetrization `h <- .5*(h+t(h))` as default. It will be ca. 4 times slower though but it's usually very accurate compared to the exact AD Hessian (which is only available without random effects and requires more memory).

**Comment by bbolker** [comment]
- One caution is that I've only showed above that `optimHess` is the least accurate for **this particular problem**.
- It would be more backward-compatible to leave `optimHess` as the default and allow alternatives
- We could also consider (as glmmADMB did) automatically standardizing and/or orthogonalizing the fixed-effect design matrix before fitting
      - this adds a layer of complexity (internal parameters have to be back-transformed)
      - especially if we orthogonalize, it adds computational complexity on the front end
      - we could offer this as an option ...

**Comment by bbolker** [comment]
@kaskr can you say a little bit more about why you expect `jacobian(obj$gr)` to be slower than `optimHess` (which is what's currently used)? AFAICT `optimHess` uses a similar approach to `jacobian(.,method="simple")` (i.e. finite differencing of the gradients)

**Comment by kaskr** [comment]
I've tracked the function/gradient evaluations of the various methods and came to the following conclusion for the n parameter case:

Method | Evals (gradient)
-|-
jacobian(gr) | 8n+1
jacobian(gr,method='simple') | n+1
optimHess(x,fn,gr) | 2n

I'm assuming optimHess uses a central difference approximation (fixed stepsize=`1e-3`) whereas the simple jacobian method uses one sided finite differences (default stepsize=`1e-4`).

**Comment by bbolker** [comment]
Interesting that in this case the one-sided finite differences appear to do better.  Maybe it's just the smaller default stepsize? (This suggests another possible knob to turn, which is attempting to guess/adjust the parscale.)  In this case there is about 1000-fold difference in the standard deviations/appropriate scales for differencing (which we only know *after* we've successfully computed the Hessian) ... in this case (as I would guess if often true), guessing that the appropriate scale is approximately proportional to the magnitude of the coefficient is probably not too bad (i.e. trying `optimHess(opt$par, fn, gr, control=list(parscale=abs(opt$par)))`) ...

**Comment by bbolker** [comment]
Bump.  Any further thoughts?

**Comment by bbolker** [comment]
I had forgotten about this, but in the meantime I think I've fixed it by trying the accurate-but-slow `jacobian(gr)` *if and only if `optimHess` gives a non-pos-def result*. Using the `better_pdcheck` branch, `glmmTMB` finds a pos-def Hessian even without scaling the inputes.
