### ISSUE TITLE
plot Effect with offset from glmmTMB formula

### ISSUE THREAD

**Issue by juliegenj** [glmmTMB/glmmTMB#489]
I have used a zero inflated NB to model animal density, so I have an offset to account for the area covered. That's how it looks:
 `glmmTMB(count ~ distance_to_pond * rainfall + distance_to_river * rainfall + (1|cell) * (1|date) + offset(log(area)), ziformula = ~1, family = nbinom2)`

I plotted my predicttors effects using the effects package but have not managed to add the offset as effects doesn't seem to handle it. So I get sthg like that, but would need the density instead. Is there a way around it or should I use another package?
Otherwise, this graph is exactly what I'm looking for.
Here is the code:
`plot(Effect(c("dwathole", "rain2"), a2x),lines = list(multiline= TRUE),confint = list(style = "auto"), main= FALSE, axes = list(grid = TRUE), xlab = "Distance to waterhole", ylab= "Number of animals")`

![image](https://user-images.githubusercontent.com/51374207/58890152-623aca00-86ea-11e9-9469-2965ac105e2b.png)

In the latter case, I'm interested in suggestions, I have tried different other ways found here, but it was a bit too hard for me to figure out how to make it work with my model and I do not have too much time left to finish my project unfortunately.

**Comment by mebrooks** [comment]
Please ask the R-sig-mixed-models list for advice. https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models
