### ISSUE TITLE
version 0.2.4 checklist

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#493]
I was thinking that it might be time to push a new version to CRAN (it's been about six months and there are some improvements); in any case, there always seems to be a lag between starting to think about a new CRAN version and actually doing it ...)  To be honest the initial motivation was because we now have a TMB/Matrix inversion (i.e., version of Matrix on CRAN is more recent than the TMB version, leading to mismatch warnings etc.), but that doesn't actually have anything to do with updating TMB ...

**Comment by bbolker** [comment]
bump. I think we should include `re.form` (#505) ...

**Comment by mebrooks** [comment]
Yep. I think this is a good idea and I'll try to start moving towards that goal, now that I finished teaching 2 days of teaching fisheries stats for the first time :) 

While checking the latest pull request, I went ahead and did a "check as cran" and found one little thing...

In `man/Owls.Rd`, this link is dead http://www.sciencedirect.com/science/article/B6W9W-4PK8B6H-8/2/e43cfbaad4dc0bb2207adfc54a460c89

Other than that it's looking good so far. I'll keep looking at the pull request.

**Comment by bbolker** [comment]
fixed Owls link: f84f3e953

@florianhartig said he would test the `re.form` stuff when he gets a chance. It'd be nice to make it more feature-ful (i.e., be able to specify population-level effects for some but not all REs) but I'd rather have a robust/well-tested release than a feature-ful one.

We still have only 11 reverse dependencies so rev-dep-checking shouldn't be too onerous.

**Comment by bbolker** [comment]
bump ... CRAN is back open now ...

**Comment by mebrooks** [comment]
I checked the `reform` branch as CRAN and it was fine. As for the reverse dependencies though, I ran `tools::check_packages_in_dir(reverse = "all", dir ="/Users/molliebrooks/Documents/glmmTMB development/glmmTMB" )` and it only checked DHARMa and sjPlot, but you say there are 11. Am I missing something?
```
> tools::package_dependencies(reverse = TRUE)$glmmTMB
[1] "DHARMa" "sjPlot"
```

I think it will be ready to submit after @florianhartig has a chance to test the `re.form`. I did a little testing of it, but did not check for exact expected numbers.

**Comment by bbolker** [comment]
I think there are only 2 strong dependencies (Depends/Imports) - the other 9 are "suggests"; I'm pretty sure they don't **need** to be checked, might be interesting to check them anyway (not sure how; I'm surprised "all" doesn't get them?).  For more heavy-duty package checking I'd suggest the `revdepcheck` package ...

I'd still like to address #481 if we can, although I guess it matters less if there are working binaries on CRAN ...

**Comment by bbolker** [comment]
bump ... ?

**Comment by bbolker** [comment]
bump ... ?

**Comment by bbolker** [comment]
bump ... ?

**Comment by florianhartig** [comment]
Hi guys, sorry for my sluggish response - I have tested the population level predictions in https://github.com/florianhartig/DHARMa/tree/2.4.2-glmmTMBfix and it works like a charm, at least as far as the integration in DHARMa and the problem I had with https://github.com/florianhartig/DHARMa/issues/16 is concerned. As soon as you push this on CRAN, I will do an update to DHARMa!

**Comment by mebrooks** [comment]
Thanks for testing it out @florianhartig ! I think we're almost ready for a CRAN submission. I'm in the process of updating my operating system (because I got side-tracked) and doing all the checks necessary for CRAN submission.

**Comment by bbolker** [comment]
Just a reminder, I would like to deal with #518 before submitting. That and #481 seem to be the major not-yet-resolved issues.

**Comment by bbolker** [comment]
... and by "deal with #518", I mean "get some feedback/input from other folks about #518".  I'm leaning toward creating a new `ziGamma` family rather than overwriting the base-R `Gamma`, to minimize masking warnings, even though the masking would be harmless.

**Comment by bbolker** [comment]
bump.  CRAN is closing for the holidays tomorrow so we won't get it in until the New Year. #481 still needs resolution (I'm willing to do the openMP/no-openMP swap, but there's a nontrivial possibility that we'll have to do a little bit of archaeology when we want to restore openMP capability at some point in the future ... We should merge the current set of pull requests, and possibly add #533 to "release-critical"

**Comment by bbolker** [comment]
bump.  CRAN is reopening tomorrow.  Thoughts?

**Comment by mebrooks** [comment]
I'm just getting over a cold. I hope to be clearheaded enough to sort this out this week. It is a high priority.

**Comment by arni-magnusson** [comment]
Hi, I'm wondering if it's time to call it version 1.0.0 soon, it being 2020 and all.
People might interpret version < 1.0 as "for testing only, not quite ready to use in actual analysis". See also https://en.wikipedia.org/wiki/Software_versioning#Version_1.0_as_a_milestone.

Version 1.0 wouldn't necessarily introduce significant changes, but be a simple statement that we consider the package ready to use for general statistical analysis.

**Comment by mebrooks** [comment]
I think that bumping up to version 1.0.0 is a good idea. 

I'll work on #533 by at least fixing `sigma` and hopefully (but not definitely) adding `predict(type="disp")`.

@bbolker if you're willing to work on the openMP issue (#481) then that would be a huge help.

**Comment by bbolker** [comment]
I will try. It would be great to get input from others (@sadatnfs???) with insight into the issues of parallelization, maybe even create a short writeup.  Worst case scenario, we can merge the `strip_openmp` branch and later do the archaeology if we want to get back to work on re-enabling parallelism in a way that won't break stuff for people trying to install from source (or provide detailed instructions on how to un-break it ...)

**Comment by sadatnfs** [comment]
Apologies; I agree with @bbolker. I haven't had any time to debug the Windows OMP issues, I think not using OMP for this submission would be my input.

**Comment by bbolker** [comment]
Current status: (1) I bumped version to 1.0.0 (maybe we should add a note to NEWS to indicate that this represents a status change, not a major/incompatible update?).  (2) Hopeful about OpenMP working (i.e. working where available, not breaking installation where unavailable) - but could probably still benefit from wider testing. (2) AFAIK everything else on the list is done, except `predict(type="disp")` (and bits and pieces like testing downstream dependencies, making sure we have up-to-date versions of vignettes, etc. etc.)

**Comment by sadatnfs** [comment]
Would it be worth putting anything on the home page about OMP installation backends for folks who'd want to use OMP but didn't configure their R with OMP when they first built it? I was basically thinking on pinging them to a section of the data.table installation vignette where they instruct on installing on Mac with an OMP compiler (https://github.com/Rdatatable/data.table/wiki/Installation).

It definitely wouldn't error out but users might think they're parallelizing when they're actually not. Thoughts?

**Comment by bbolker** [comment]
Maybe.  I was hoping that users with non-functioning OpenMP (for whatever reason) would get a warning from `TMB::openmp()` when they tried to set >1 threads.  I do get a warnings on the one system I'm using without OpenMP support, but I can't be sure it's true in general.

On the other machines I have, with the most recent commit I get 52 secs serial vs 38 secs parallel on virtual Xubuntu with nt=2, N=1e5 [which makes sense], 87 vs 45 secs on MacOS with nt=4, N=3e5 (disappointing but not ridiculous).

**Comment by bbolker** [comment]
The only thing that occurs to me now, besides merging #537 and #544, is testing (on win-builder, maybe also with [rhub](https://github.com/r-hub/rhub) , testing downstream packages, and ... maybe ?? adding some more warnings somewhere to say that the OpenMP stuff is experimental, and that users should experiment with parallelism rather than assuming it will improve performance?

**Comment by sadatnfs** [comment]
Would having warnings on library install/load make the CRAN checks sad? Or do you reckon the warning should me something more on the documentations?

**Comment by bbolker** [comment]
Messages (not warnings) would make me sad; I prefer quiet packages.  If we do add some commentary/warnings, I would think it/they should be under `?glmmTMBControl` (where the 'parallel' control argument is defined, or possibly in the parallel vignette with a pointer to it from `?glmmTMBControl`

**Comment by mebrooks** [comment]
CRAN just emailed me with a hard deadline to submit a new version that at least fixes the errors. "Please correct before 2020-02-01 to safely retain your package on CRAN."

**Comment by mebrooks** [comment]
I'm running the checks now and I'll submit to Winbuilder later today. I had a hard time debugging my new (MacOSX 10.15) configuration of `~/.R/Makevars` because the internet is spotty in my current location, but it seems ok now.

**Comment by mebrooks** [comment]
The tests were fine on the current and future versions, but 4 errors occurred on R-oldrelease. This [link](https://win-builder.r-project.org/27X64QXaTG5a) should show the log for 2 more days.
```
> if (require(car)) {
+     Anova(warp.lm,type="III")
+ }
Loading required package: car
Loading required package: carData
Error in L %*% b : requires numeric/complex matrix/vector arguments
Calls: Anova ... Anova.default -> Anova.III.default -> linearHypothesis.default
Execution halted
```

```
-- 1. Error: (unknown) (@test-downstream.R#68)  --------------------------------
  requires numeric/complex matrix/vector arguments
  Backtrace:
    1. testthat::expect_equal(f(fm2_tmb), f(fm2_lmer), tolerance = 2e-05) test-downstream.R:68:4
```

```
Quitting from lines 170-172 (model_evaluation.Rnw) 
Error: processing vignette 'model_evaluation.Rnw' failed with diagnostics:
subscript out of bounds
```

**Comment by bbolker** [comment]
It would be good to fix these if we can.

* we could probably get away with something like `if (require(car) && packageVersion("car") > SOMETHING_APPROPRIATE)` for the downstream tests (this error occurs twice, once for 32- and once for 64-bit)
* maybe similarly for the problem with the effects package in `test-downstream.R` ?
* the vignette failure is also a `car::Anova` problem.

Much as I would like to maintain back-compatibility wherever possible, I'm not sure I have the time and energy to go back and figure out how to implement all of the downstream methods so that they're compatible with old versions of `car`/`effects`/etc. ...

**Comment by mebrooks** [comment]
It looks like there's still a problem with Anova stuff in [R-oldrelease](https://win-builder.r-project.org/HKnLePKX5BKX/).  The errors are nearly identical as before, so I would worry that I didn't really run the new version, but there are small differences in the first two below.
```
> if (require(car) && packageVersion("car")>="3.0.6") {
+     Anova(warp.lm,type="III")
+ }
Loading required package: car
Loading required package: carData
Error in L %*% b : requires numeric/complex matrix/vector arguments
Calls: Anova ... Anova.default -> Anova.III.default -> linearHypothesis.default
Execution halted
```

```
== Warnings ====================================================================
  1. REML check against lmer (@test-reml.R#22) - Model failed to converge with max|grad| = 0.0135437 (tol = 0.005, component 1)
  
  == Failed ======================================================================
  -- 1. Error: (unknown) (@test-downstream.R#65)  --------------------------------
  requires numeric/complex matrix/vector arguments
  Backtrace:
    1. testthat::expect_equal(f(fm2_tmb), f(fm2_lmer), tolerance = 2e-05) test-downstream.R:65:4
    4. glmmTMB:::f(fm2_tmb)
    8. effects::allEffects.default(x)
    9. base::lapply(terms, effect, mod = mod, ...)
   11. effects::effect.default(X[[i]], ...)
   13. effects::Effect.default(predictors, mod, vcov. = vcov., ...)
   15. effects::Effect.lm(focal.predictors, mod2, ...)
```

```
Quitting from lines 170-174 (model_evaluation.Rnw) 
Error: processing vignette 'model_evaluation.Rnw' failed with diagnostics:
subscript out of bounds
```

I checked reverse dependencies once and it seemed ok except some checks stopped when I didn't have the right dependencies installed. I'll try again.

**Comment by bbolker** [comment]
Ugh.  I hate remote debugging. Contrary to my assumption, this can't be a `car` package version issue, because the problem occurs inside an if-clause that only accepts the latest version.

```
> if (require(car) && packageVersion("car")>="3.0.6") {
+     Anova(warp.lm,type="III")
+ }
Loading required package: car
Loading required package: carData
Error in L %*% b : requires numeric/complex matrix/vector arguments
Calls: Anova ... Anova.default -> Anova.III.default -> linearHypothesis.default
Execution halted
```

[This SO question](https://stackoverflow.com/questions/22906804/matrix-expression-causes-error-requires-numeric-complex-matrix-vector-arguments) looks related, but not very.

I wonder if this has to do with  `export _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=TRUE`, which came up [here](https://github.com/glmmTMB/glmmTMB/issues/382) ?

And I'm *guessing* that `coef = coef(model)` in `car:::linearHypothesis.default` is for some reason finding the wrong method ...

The easiest/brute-force thing we could do is make these particular tests dependent on the R package version, to disable them on `r-oldversion` ...

**Comment by bbolker** [comment]
OK, I have another hypothesis.  I think the problem has to do with the conditional exports [here](https://github.com/glmmTMB/glmmTMB/blob/63dc01c9c38bd95fa7a619bf1f6c97f07c2057e8/glmmTMB/NAMESPACE#L71-L80), which were added [here](https://github.com/glmmTMB/glmmTMB/commit/efe4a3752ddbbf803ad43cbb665c3b9bbdf7feee)/this [pull request](https://github.com/glmmTMB/glmmTMB/commit/8fefbcc0cf666ae91272cb7f4dcf84e932433412) (unfortunately I no longer remember exactly *why* ...)

Latest commit on `fix_old_ver` attempts to condition the tests appropriately ... @mebrooks please test on win-builder?

**Comment by mebrooks** [comment]
Ok. I sent it to win-builder one more time, just as a sanity check before I plan to email R-package-devel. 

Just to be absolutely sure I'm looking at the right branch, you mean `fix_oldver` rather than `fix_old_ver`, right?

**Comment by bbolker** [comment]
Looks like it's on CRAN now.
