### ISSUE TITLE
How can I establish the reference category in an ordered DV?

### ISSUE THREAD

**Issue by davidcanarte** [glmmTMB/glmmTMB#506]
I am using a multinomial DV measuring provision of social support. This variable was originally constructed as 0 = No support, 1 = One Support, 2 = Multiplex support. I factored "No Support", "One Support" and "Multiplex Support" before running the regressions with clmm(). However, I remember that in STATA one can establish a reference with baseoutcome(). How can I do this with the ordinal package?

**Comment by bbolker** [comment]
This isn't the right forum for this question (this issues list is specifically for the `glmmTMB` package.  I'd suggest you try `r-sig-mixed-models@r-project.org` with this question, unless the `?relevel` function solves your problem.  Good luck ...

**Comment by davidcanarte** [comment]
Sorry :( ... I got confused.
