### ISSUE TITLE
to export, or not to export, glmmTMB::Gamma?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#518]
I wrote a variation of `Gamma()` that handles zero-inflated cases (it calls `stats::Gamma()` and then modifies the `$initialize` component appropriately.  Should we:

- export it as is and mask `stats::Gamma()`?
- rename it `zGamma` (or `ziGamma`)

?  Particularly interested in @mmaechler's opinion since this is a bit of a "package etiquette" question (masking is frowned upon, although I feel like it's relatively harmless in this case - and it's not explicitly mentioned in the CRAN policies that I can see ...)

(Somewhat to my horror, tests based on the glmmTMB version of Gamma seem to have worked within the `testthat` framework, but didn't work when the package was loaded normally ...)

**Comment by bbolker** [comment]
If I don't hear otherwise I'm going to rename our version of the `Gamma()` family to `ziGamma` to avoid the masking.

**Comment by mmaechler** [comment]
Sorry to not have commented;  I agree with your proposal to rename and then export.
Confusion with the standard Gamma() family is really not worth the pain here.

**Comment by bbolker** [comment]
https://github.com/glmmTMB/glmmTMB/pull/534
