### ISSUE TITLE
Question: Is it possible to do a one-inflated poisson model with the package?

### ISSUE THREAD

**Issue by rpmady** [glmmTMB/glmmTMB#519]
I have a data set with no 0's, since it is just presence data, and an inflated amount of 1's. 
I've fit a model in glmer, but am noticing when evaluating the fit it could be better. 
So I started to investigated one-inflated and haven't found anything. 

I've used glmmTMB() for a zero-inflated poisson model and wanted to see if there is a way to do one-inflated.

**Comment by bbolker** [comment]
No, not at present, sorry.  It might be worth trying a zero-inflated NB (which would add more probability at low values (1, 2, ...) and in the tail).  It would be *possible* to code a zero-truncated, 1-inflated Poisson, but it seems like an unusual case ...

**Comment by ajkroeg** [comment]
I believe the VGAM package has a one-inflated poisson implementation you could look at. Not sure how you're expecting to model any kind of response if the response is _always_ a 1, though.

**Comment by rpmady** [comment]
Thanks for the feed-back! I've so far run a model successfully with glmmTMB with the zero-truncated poisson family and it seems to work well.
