### ISSUE TITLE
Order of confounding factors yield different p-values for main interaction

### ISSUE THREAD

**Issue by fujimurk** [glmmTMB/glmmTMB#520]
Hello,
When I ran 
```
glmmTMB(y~x + trt1 + trt2 + trt3, data=dat, family=nbinom2)
```
I would get p<0.008 for x but would get p<0.7 for x if I ran 
```
glmmTMB(y~x + trt2 + trt3 + trt1, data=dat, family=nbinom2)
```

Do you have a suggestion as to how to determine in what order the confounding factors should be? Also, I was expecting the p-value for x to be the same regardless of the order of the confounding factors; do you know why it changes?

Thanks - Kei

**Comment by bbolker** [comment]
This is surprising.  Can you show us a reproducible example?

**Comment by bbolker** [comment]
The only case I can possibly think of where order would matter would be using predictors that are nearly or completely collinear (in which case I think you would also get warning messages). Here's an example where the coefficients, p-values, etc. are independent of order. Unless you can provide a reproducible example, we probably won't be able to help you debug this ...

```
set.seed(101)
dd <- data.frame(trt1=rnorm(100),trt2=rnorm(100),trt3=rnorm(100))
dd <- within(dd, y <- rnbinom(100, mu=exp(1*trt1+0*trt2+2*trt3), size=1))
options(digits=3)
library(glmmTMB)
coef(summary(glmmTMB(y~trt1+trt2+trt3,family=nbinom2,data=dd)))$cond
##             Estimate Std. Error z value Pr(>|z|)
## (Intercept)   0.1189      0.174   0.684 4.94e-01
## trt1          1.0480      0.153   6.845 7.63e-12
## trt2         -0.0383      0.135  -0.285 7.76e-01
## trt3          2.0169      0.216   9.346 9.12e-21
coef(summary(glmmTMB(y~trt2+trt3+trt1,family=nbinom2,data=dd)))$cond
##             Estimate Std. Error z value Pr(>|z|)
## (Intercept)   0.1189      0.174   0.684 4.94e-01
## trt2         -0.0383      0.135  -0.285 7.76e-01
## trt3          2.0169      0.216   9.346 9.12e-21
## trt1          1.0480      0.153   6.845 7.63e-12
```

**Comment by fujimurk** [comment]
I’ll try to make a reproducible set but won’t be able to get to it until
maybe next week.

**Comment by bbolker** [comment]
any advance on this?

**Comment by bbolker** [comment]
closing now. Will happily re-open if there's a reproducible example.
