### ISSUE TITLE
information required regarding dispformula

### ISSUE THREAD

**Issue by efratde** [glmmTMB/glmmTMB#521]
Hello,

I've been trying to find information beyond what exists in the [package description ](https://cran.microsoft.com/web/packages/glmmTMB/glmmTMB.pdf) regarding the possibility to add a dispersion formula.
Specifically, I am interested to know 
1. How exactly adding this term changes the calculations of the model?
2. What is and is not legit to add to the dispersion formula? For example, it says in the description that only fixed affects can be used. But, do this effects have to be part of the model? And why can't I add a random effect? 
If, for example, I have a dataset that includes amounts of materials weighted per sample unit, and so variance increases as the total amount increases, but I don't use this total amount as a factor in the model, can I still add it to the dispersion formula? Can categorical variables be added?

I'll appreciate any references and advice, and if this is not the appropriate place to post such questions then I apologize and would appreciate  a link to a more appropriate place.

**Comment by mebrooks** [comment]
We would prefer to keep the GitHub issue tracker for bugs or changes to the package. This seems more like a request for advice. See [where to ask questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions).

Re 1. Equations 1, 3, and 5 of [the paper](https://journal.r-project.org/archive/2017/RJ-2017-066/RJ-2017-066.pdf) describing the package (this info is available using `citation("glmmTMB")`) give an example of how `dispformula` works for a negative binomial model.  For distributions that have a dispersion parameter (see `?sigma.glmmTMB` for dispersion parameter and variance descriptions) then there is a log-link on the dispersion parameter.

Re 2. We decided to write the code in a way that it can only take fixed effects. The fixed effects do not need to be in the other parts of the model. Fixed effects can be categorical or continuous.

In your question you mention that materials weighted differs among observations. This would commonly be used as an offset in the model, assuming that it affects the mean of the response variable also (e.g. more sample leads to higher response and higher variance). It depends on what you're measuring. The R-sig-mixed list would be a better place to ask (after reading a bit about offsets in GLMs, the paper linked above, and documentation for `sigma.glmmTMB`).

**Comment by bbolker** [comment]
A couple of notes (follow-ups to `r-sig-mixed-models@r-project.org`:

- it's not **in principle** that hard to allow for random effects in the dispersion term, but (1) implementing them for vector-valued random effects (e.g. random slopes models) could be tricky; (2) it will often take a *lot* of data to fit such a model.
- as @mebrooks says, it doesn't sound like what you want is a random effect on the dispersion. If you had `n` (number of samples) as a variable in your data set, you could use `dispformula ~ log(n)` to fit the model `log(var) ~ log(n)` or equivalently `var = a*n^b`

**Comment by mebrooks** [comment]
@bbolker's example above with `var = a*n^b` only works for the default family = gaussian, but it's more complicated for other families where the variance also depends on the mean. Those variance formulas are described in the documentation for `sigma.glmmTMB`.
