### ISSUE TITLE
bootMer does not work with binomial models

### ISSUE THREAD

**Issue by frousseu** [glmmTMB/glmmTMB#529]
Hello

The `bootMer` function does not seem to work with binomial models. For example, this produces the same value for each sample:

```r
library(glmmTMB)
library(lme4)

fun<-function(x) predict(x)[1]

Salamanders$pres<-ifelse(Salamanders$count>0,1,0)
m<-glmmTMB(pres ~ mined +(1|site), family=binomial, data=Salamanders)
b<-bootMer(m, fun, nsim=5)
b$t

##           [,1]
## [1,] -1.644759
## [2,] -1.644759
## [3,] -1.644759
## [4,] -1.644759
## [5,] -1.644759
```

Everything seems to be working fine with a Poisson model:

```r
m<-glmmTMB(count ~ mined + (1|site), family=poisson, data=Salamanders)
b<-bootMer(m, fun, nsim=5)
b$t

##            [,1]
## [1,] -2.4478737
## [2,] -2.0309344
## [3,] -1.5458759
## [4,] -1.6066516
## [5,] -0.3541022
```

This is with lme4 1.1-21 and glmmTMB 0.2.3. A similar problem is mentionned in #375. 

Thanks!

**Comment by bbolker** [comment]
Can you please check this solution by installing

```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB@bootmer_fix")
```

?

**Comment by frousseu** [comment]
It works with this branch.

Thanks!

```r
library(glmmTMB)
library(lme4)
fun<-function(x) predict(x)[1]
Salamanders$pres<-ifelse(Salamanders$count>0,1,0)
m<-glmmTMB(pres ~ mined +(1|site), family=binomial, data=Salamanders)
b<-bootMer(m, fun, nsim=5)
b$t

###          [,1]
## [1,] -2.068666
## [2,] -1.720592
## [3,] -1.500176
## [4,] -1.533502
## [5,] -2.403497
```

**Comment by bbolker** [comment]
OK, will close this when https://github.com/glmmTMB/glmmTMB/pull/532 is merged

**Comment by frousseu** [comment]
Oh, but now the Poisson case does not work anymore:

```r
m<-glmmTMB(count ~ mined + (1|site), family=poisson, data=Salamanders)
b<-bootMer(m, fun, nsim=5)
b$t

##           [,1]
## [1,] -1.422588
## [2,] -1.422588
## [3,] -1.422588
## [4,] -1.422588
## [5,] -1.422588

**Comment by bbolker** [comment]
yikes! I'll take a look

**Comment by bbolker** [comment]
should be fixed (but please continue poking at it to see and let us know if you find anything surprising!)

**Comment by frousseu** [comment]
It now works with binomial, betabinomial, poisson, nbinom1, nbinom2 and gaussian.

**Comment by bbolker** [comment]
Great (although we really need to test more rigorously than "produces non-constant results" ...)

**Comment by frousseu** [comment]
I understand from this that bootMer is still a bit experimental for glmmTMB?

**Comment by bbolker** [comment]
Let's just say that it hasn't been tested as thoroughly as I'd like.  On the other hand most of the bootMer machinery is in the lme4 package (and has been tested/widely used), it's only `refit.glmmTMB` that's really new ...
