### ISSUE TITLE
Generating predictions from the dispersion model

### ISSUE THREAD

**Issue by marek-tph** [glmmTMB/glmmTMB#533]
I have a beta regression where I model both the mean and the dispersion parameter. I would like to see what dispersion is taken for each observation. The closest I found is `sigma`, which extracts the (exponentiated) coefficients of the dispersion model. This already helps to compute dispersion by hand, but it would be neat to be able to do simply `predict(model, type="dispersion")`.

Thank you for this excellent package.

**Comment by mebrooks** [comment]
Thinking about this has gotten me confused about `sigma`. I don't think it's doing a sensible thing when there's a dispersion model. The description says it "it returns the dispersion parameter" as in a **single** parameter.  The example below (taken from the help file) shows how to get the parameters from a dispersion model 

```
## Dispersion model
sim1 <- function(nfac=40, nt=100, facsd=0.1, tsd=0.15, mu=0, residsd=1)
{
  dat <- expand.grid(fac=factor(letters[1:nfac]), t=1:nt)
  n <- nrow(dat)
  dat$REfac <- rnorm(nfac, sd=facsd)[dat$fac]
  dat$REt <- rnorm(nt, sd=tsd)[dat$t]
  dat$x <- rnorm(n, mean=mu, sd=residsd) + dat$REfac + dat$REt
  dat
}
set.seed(101)
d1 <- sim1(mu=100, residsd=10)
d2 <- sim1(mu=200, residsd=5)
d1$sd <- "ten"
d2$sd <- "five"
dat <- rbind(d1, d2)
m0 <- glmmTMB(x ~ sd + (1|t), dispformula=~sd, data=dat)
fixef(m0)$disp
c(log(5^2), log(10^2)-log(5^2)) # expected dispersion model coefficients
```

If we run `sigma(m0)`, it treats the intercept and slope of the model the same while applying the transformation for the Gaussian dispersion model `gaussian=exp(0.5*pl$betad)`, but the transformed slope and intercept are meaningless. It's the predictions from the linear model that should be transformed.  

We should probably change `sigma` to either throw an error or to do something more sensible when applied to a model with a dispersion model. Am I right, or am I confused?

**Comment by bbolker** [comment]
I think you're right.  My opinion would be that `sigma` should be `NA` when the dispersion model is non-trivial (and that we should implement `predict(type="disp")` as suggested by @marek-tph)

**Comment by mebrooks** [comment]
@marek-tph If you'd like, you could try the new predict method by installing the new branch. Feedback is very welcome.

```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB@disp_predict")
```
