### ISSUE TITLE
Can not install dev version (openMP)

### ISSUE THREAD

**Issue by idworkin** [glmmTMB/glmmTMB#542]
Likely my compiler

clang: error: unsupported option '-fopenmp'
make: *** [glmmTMB.o] Error 1
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/glmmTMB’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/glmmTMB’
Error: Failed to install 'glmmTMB' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_c/n48kt6qx6ndbrxp_g7dgmmd80000gn/T//RtmpGeVTr8/file52f2e0ddeca/glmmTMB_1.0.0.tar.gz’ had non-zero exit status

**Comment by bbolker** [comment]
Ugh.  This is the sort of the thing we were hoping wouldn't happen.  I think this is an instance of [this problem](https://github.com/kaskr/adcomp/issues/268).

Does adding the line `SHLIB_OPENMP_CFLAGS=` to  your `~/.R/Makevars` (creating the file if necessary, otherwise appending to it) fix the problem?

**Comment by bbolker** [comment]
I think [this set of instructions for setting up optional OpenMP support via autoconf](https://github.com/USCBiostats/software-dev/wiki/Setting-up-optional-OpenMP-support) might help us ... it *looks* straightforward, hopefully it Just Works.

**Comment by idworkin** [comment]
Will check now. Just finished my RoA. It makes figuring out compiling issues seem fun....

**Comment by bbolker** [comment]
I've added a `configure` file to the package which will hopefully (???) resolve this problem.  I hope you haven't updated your compiler/setup ... could you try again with the latest commit?

**Comment by bbolker** [comment]
small bump.  I think this should be OK now ...

**Comment by mebrooks** [comment]
Do I need to make sure that openMP is enabled on my computer when I build the tar ball for CRAN? It looked like openMP wasn't working for me recently even though I thought I was using clang8 from CRAN's website.

**Comment by bbolker** [comment]
You shouldn't have to.  The detection of OpenMP happens at compilation time (installation or building of the binary package), not at tarball-building time.  Interesting/annoying that OpenMP's not working for you, though ...
