### ISSUE TITLE
TMB version 1.7.16

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#543]
Just tried to submit a new TMB version (current master branch) to CRAN. Unfortunately glmmTMB is blocking my submission due to a failed test:

```
 â•â• Warnings â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    1. (unknown) (@test-disp.R#39) - Model convergence problem; false convergence (8). See vignette('troubleshooting')
    
    2. (unknown) - Model convergence problem; false convergence (8). See vignette('troubleshooting')
    
    3. (unknown) (@test-downstream.R#49) - overriding variance function for effects: computed variances may be incorrect
    
    4. terms (@test-methods.R#137) - Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
    
    5. terms (@test-methods.R#137) - Model convergence problem; function evaluation limit reached without convergence (9). See vignette('troubleshooting')
    
    6. (unknown) (@test-predict.R#75) - `failure_message` is missing, with no default.
    
    7. (unknown) (@test-predict.R#77) - `failure_message` is missing, with no default.
    
    â•â• Failed â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    â”€â”€ 1. Failure: (unknown) (@test-VarCorr.R#167)  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    `c3` not equal to structure(...).
    Component "V3": Mean relative difference: 1.444528e-05
    
    â•â• DONE â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    Error: Test failures
    Execution halted
```

The failure is machine specific (i.e. I don't get it on mine). I think we should change the tolerance from `1e-5` to `1e-4` in `test-VarCorr` [here](https://github.com/glmmTMB/glmmTMB/blob/4772fc7250f501aacc809c5a9282f15e2179ab7b/glmmTMB/tests/testthat/test-VarCorr.R#L170) before next CRAN submission of glmmTMB.

**Comment by mebrooks** [comment]
Sounds like a good solution. I'm looking into this now.

**Comment by kaskr** [comment]
The CRAN maintainers let the new TMB through despite the failed test, but I got this in return - i.e. we should submit glmmTMB to CRAN very soon:

```
Thanks, on its way to CRAN.

But we need the new glmmTMB NOW as this fails with an ERROR on CRAN now.

Best,
Uwe Ligges
```

**Comment by mebrooks** [comment]
I can't replicate the error on my Mac and I can't figure out how to install the development version of TMB on my Windows computer. I guess we can start by assuming that increasing the tolerance will fix the problem and see what happens next. I'm hoping winbuilder would catch errors like this that don't show up on Mac and Linux.

**Comment by bbolker** [comment]
We can get a little more detail on the problems by looking at the CRAN tests [here](https://cran.r-project.org/web/checks/check_results_glmmTMB.html) (looks like the problems are on Fedora with both gcc and clang.  More problems may pop up -- not sure all tests have been run with the new version of TMB yet ...)

**Comment by bbolker** [comment]
Out of curiosity, @kaskr, would you have any guesses about what changed that would propagate to `glmmTMB`? The only thing I see in the NEWS that looks as though it would affect results is (possibly) `logspace_add: Added some edge case reductions` ...  (I can also imagine that there is some change to CRAN's environment (e.g. compiler or compiler flags) that propagates through - I don't know if the version of TMB used when testing glmmTMB would be re-built every time ...)

**Comment by kaskr** [comment]
Given that the failing test is Gaussian, part of the reason could be that TMB's dnorm was changed from using `pow(x,2)` to `x*x`.
But there must also be some compiler/OS randomness involved - recall that neither Mollie or I could reproduce the error.

**Comment by mmaechler** [comment]
yes, the only failure is this (the others are warnings) :+1: 
  
     ── 1. Failure: (unknown) (@test-VarCorr.R#167) ────────────────────────────────
     `c3` not equal to structure(...).
     Component "V3": Mean relative difference: 1.444528e-05

--------------
which is https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/tests/testthat/test-VarCorr.R#L167  with R  code  (manually formatted by me)

```r
expect_equal(c3, structure(list(V3 = c(4.814071, 0.046192, 1.716208), 
                              V4 = c(NA, -0.581, NA)), .Names = c("V3", "V4"), 
                              class = "data.frame", row.names = c(NA, -3L)),
                      tolerance=1e-5)
```    
so now you get 1.44e-5 which is larger than 1e-5 ... so do increase that to say `5e-5` -- not really a big deal, no?
