### ISSUE TITLE
prepping for R 4.0.0

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#556]
I recently got an email from CRAN saying that we need to prepare for the new R. Whenever we use `data.frame` or `read.*` to create a data frame containing a factor, it's a good idea to explicitly define the levels of the factor, or at least that's what I take away from reading [this blogpost](https://developer.r-project.org/Blog/public/2020/02/16/stringsasfactors/index.html). 

We currently have two [errors on R-devel ](https://cran.r-project.org/web/checks/check_results_glmmTMB.html).

I already wrote code to fix the error in `test-disp.R` (see branch stringsAsFactors) and the error in `test-predict.R` should also be easy to fix. However, I can't install our package in R-devel on my computer. So far, the hurdle I found is that I can't install `lme4` because I can't install its dependency `nloptr`.

Based on the issue [here](https://github.com/jyypma/nloptr/issues/50), I tried `brew reinstall nlopt` in the command line and it appeared to work, but I still can't install `nloptr`.

```
make[3]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/private/var/folders/8t/zsp25_b17td7j1y5d_nmfqt00000gq/T/RtmpP1PDfx/R.INSTALL1428a5b7c24ed/nloptr/src/nlopt_src/include'
/bin/sh: .././install-sh: Permission denied
make[3]: *** [install-includeHEADERS] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
ERROR: configuration failed for package ‘nloptr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/nloptr’
```

Can any of the other developers install R-devel and our package so that you could test some code when I (or we) try to fix the errors?

**Comment by mebrooks** [comment]
The deadline to fix this and stay on CRAN is 20 March.

**Comment by mmaechler** [comment]
I've always managed to install `lme4`  with R-devel ... so, I'll try and tell you soonish.

**Comment by mmaechler** [comment]
Installation was no problem, however `R-devel CMD check lme4`  also gives an ERROR (probably for the exact same reason as with glmmTMB:  Having character vectors instead of factors in some cases, because  `stringsAsFactors=FALSE` now being default.

**Comment by bbolker** [comment]
@mebrooks : I can see that the binaries for nloptr are behind on CRAN, but can you get away with installing the binary of the older version (1.2.1) by answering "no" to the "install from source?" question? (I very much doubt the nloptr version matters to us)

**Comment by bbolker** [comment]
For convenience, here are the test failures (copied from the CRAN check page):

```
  -- 1. Failure: disp calc (@test-disp.R#35) ------------------------------------
  unname(fixef(m0)$disp) not equal to c(log(10^2), log(5^2) - log(10^2)).
  2/2 mismatches (average diff: 2.09)
  [1] 3.21 - 4.61 == -1.39
  [2] 1.39 - -1.39 == 2.78
  
  -- 2. Error: contrasts carried over (@test-predict.R#240) ---------------------
  contrasts apply only to factors
  Backtrace:
   1. stats::`contrasts<-`(...) test-predict.R:240:4
```

**Comment by mebrooks** [comment]
Do you think we're ready to test the [new branch](https://github.com/glmmTMB/glmmTMB/tree/stringsAsFactors) on R-devel? Or are there more things to fix?

**Comment by mebrooks** [comment]
I still haven't managed to install `nloptr`. The latest try resulted in no feedback in the end. 
```
> install.packages("nloptr")
Warning: unable to access index for repository http://stat.ethz.ch/CRAN/bin/macosx/el-capitan/contrib/4.0:
  cannot open URL 'http://stat.ethz.ch/CRAN/bin/macosx/el-capitan/contrib/4.0/PACKAGES'
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘nloptr’
Do you want to attempt to install these from sources? (Yes/no/cancel) no
> 
```
I'll try again tomorrow, possibly with fresh ideas.

**Comment by bbolker** [comment]
The "unable to access index" error sounds like a network problem?

I believe all the `stringsAsFactors` issues are resolved with 9e249494c08 ; I've started the PR for that branch.

What other issues do we want to identify as top priority/release-critical (balancing "it's good to get improvements into this release because we might not release again for a while" vs. "it's good not to rush changes into a release in case of goofs/surprises")?

**Comment by mebrooks** [comment]
I'm checking if the new version might be nearly ready for CRAN. When I build  and check as CRAN (on current not devel R) I'm getting warnings from config.log. I don't know what this is, but I'll keep trying to look into it.

```
configure:2023: clang++ -std=gnu++11 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Wno-aggressive-loop-optimizations -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-enum-compare -Wno-int-in-bool-context   conftest.cpp  >&5
warning: unknown warning option '-Wno-aggressive-loop-optimizations' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-int-in-bool-context'; did you mean '-Wno-gnu-include-next'? [-Wunknown-warning-option]
2 warnings generated.
```

**Comment by kaskr** [comment]
@mebrooks 
Just guessing: I suspect you have an old gcc-specific `~/.R/Makevars` with `-Wno-aggressive-loop-optimizations -Wno-deprecated-declarations -Wno-ignored-attributes` ? At some point you switched to clang and now get the warnings...

**Comment by mebrooks** [comment]
Yep. The warnings disappeared when I removed that line from `~/.R/Makevars`. I must have added it when I was struggling with a recent update to my OS.

So I'll check the new version on winbuilder now.

**Comment by mebrooks** [comment]
I'm testing the News branch on winbuilder now. If it passes, is there anything else I should wait for before submitting to CRAN? I'm thinking that the deadline is in a week, but most EU public employees have switched to working from home, so I don't want to risk getting too close to the deadline in case work slows down or stops.

**Comment by bbolker** [comment]
Go for it.

**Comment by mebrooks** [comment]
R-devel on winbuilder gave one error (others were fine).
```
== Failed ======================================================================
  -- 1. Failure: REML check against lmer (@test-reml.R#30)  ----------------------
  vcov(fm2.glmmTMB)$cond not equal to as.matrix(vcov(fm2.lmer)).
  1/4 mismatches
  [1] 0.601 - 0.6 == 0.00139
```
@kaskr do you think this is a case when it's ok to increase the tolerance of the test?

**Comment by mebrooks** [comment]
Good news! The package was fine on [R-devel](https://win-builder.r-project.org/6qRK546WLlx9/00check.log).  Oddly it took more than 24 hours for winbuilder to get around to processing that job.  The error happened on the [experimental R-devel](https://win-builder.r-project.org/snf0or6giQfW/00check.log) "R-devel_gcc8".

**Comment by bbolker** [comment]
- I think winbuilder is swamped right now. 
- I think it's fine to increase the tolerance a little bit for that test. It doesn't surprise me that it's a little sensitive; it's a singular fit (not sure why we chose this example ... ?)

**Comment by mebrooks** [comment]
I uploaded the version from the `News1.0.1` branch to CRAN just now after checking it again on winbuilder. I'll go ahead and merge the branch to master, even though it's mine. The changes are so minor.
