### ISSUE TITLE
Residual diagnostics with unstructured covariance

### ISSUE THREAD

**Issue by andrjohns** [glmmTMB/glmmTMB#561]
I'm estimating a model that uses an unstructured matrix for the residuals, and I want to clarify whether the normal approaches to residual diagnostics are appropriate. Because using the ```us``` structure requires fixing the residual variance to (near-)zero to avoid over-parameterisation, any extracted residuals are very small:
```
data("sleepstudy",package="lme4")
sleepstudy = sleepstudy[sleepstudy$Days < 4,]

fm4 <- glmmTMB(Reaction ~ factor(Days) + us(0+factor(Days)|Subject), 
               sleepstudy,dispformula = ~0)
head(resid(fm4))
            1             2             3             4            11            12 
-1.370495e-10 -1.226681e-10 -2.994653e-09  2.520153e-09  7.131007e-11 -1.787441e-10 
```

This makes me think that I shouldn't use these residuals for any model diagnostics. Is that right? Is there a more appropriate method of extracting the residuals in this case?

Thanks!

**Comment by bbolker** [comment]
The "residuals" in this case will be the random effects: `ranef(fm4)$cond$Subject` gives you a data frame with one row per subject and 4 columns (one for each day).

In future (or for follow-up questions), I think this kind of question is better suited to `r-sig-mixed-models@r-project.org` (see https://github.com/glmmTMB/glmmTMB#where-to-ask-questions )

**Comment by andrjohns** [comment]
Thanks for clarifying and apologies for clogging up your issue feed!
