### ISSUE TITLE
Rolf Turner cloglog example

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#564]
Two examples here, one that seems as though it will require clamping the inverse link function? The `predict()` example is OK in master/1.0.1, should double-check to make sure we haven't broken it in making changes to the cloglog machinery.

```

library(glmmTMB)
fmla <- cbind(Dead, Alive) ~ (Trt + 0)/Dose + (Dose | Rep)
X    <- dget("X.txt")
fit0  <- glmmTMB(fmla, data = X, family = binomial(link = "cloglog"),
                 dispformula = ~1)

fit1  <- glmmTMB(fmla, data = X, family = betabinomial(link = "logit"),
                 dispformula = ~1)

fit2  <- glmmTMB(fmla, data = X, family = betabinomial(link = "cloglog"),
                dispformula = ~1,
                start=list(beta=fixef(fit0)$cond),
                control=glmmTMBControl(optArgs=list(trace=1)))

fit3  <- glmmTMB(fmla, data = X, family = betabinomial(link = "cloglog"),
                dispformula = ~1,
                control=glmmTMBControl(optArgs=list(trace=1)))

if (FALSE) {
    ## within glmmTMB:::fitTMB
    obj$fn(TMBStruc$parameters) ## NaN
    obj$gr(TMBStruc$parameters) ## all NaN
}
fit$parameters
debug(glmmTMB:::fitTMB)
## Error in (function (start, objective, gradient = NULL, hessian = NULL,  : 
##   gradient function must return a numeric vector of length 16
## In addition: Warning message:
## In (function (start, objective, gradient = NULL, hessian = NULL,  :
##               NA/NaN function evaluation
              
Timing stopped at: 0.068 0.004 0.12
-2*logLik(fit0)/df.residual(fit0)
library(ggplot2); theme_set(theme_bw())
ggplot(X,aes(Dose,Dead/(Alive+Dead),colour=Trt)) + geom_point(aes(size=Dead+Alive)) +
    geom_line(aes(group=interaction(Rep,Trt)))
with(X,table(Rep,Dose,Trt))


library(glmmTMB)
X <- dget("demoDat.txt")
fit1 <- glmmTMB(cbind(Dead,Alive) ~ (0+Trt)/Dose +
                 (Dose|Rep),family=binomial(link="logit"),data=X)
fit2 <- glmmTMB(cbind(Dead,Alive) ~ (0+Trt)/Dose +
                 (Dose|Rep),family=binomial(link="cloglog"),data=X)
p1 <- predict(fit1,type="response")
p2 <- predict(fit2,type="response")
plot(p1,p2)
abline(a=0,b=1)
```

[demoDat.txt](https://github.com/glmmTMB/glmmTMB/files/4371988/demoDat.txt)
[X.txt](https://github.com/glmmTMB/glmmTMB/files/4371989/X.txt)

**Comment by bbolker** [comment]
@kaskr, are you willing to look at the changes I've made to the [cloglog_fix branch](https://github.com/glmmTMB/glmmTMB/tree/cloglog_fix)  and see if I'm missing something obvious? I'm trying to get to the point where I can diagnose exactly where the `NaN` values are first appearing ...

**Comment by kaskr** [comment]
@bbolker I'll take a look at it soon.

**Comment by kaskr** [comment]
I think we should skip the cloglog_fix branch and start from scratch (avoid clamping as that will just lead to more trouble).
We have two problems.

### Problem 1:

betabinomial family has

```
s2 = (Type(1)-mu(i))*phi(i);
```

When `mu(i)` is really close to one, e.g. `1 - 1e-100` (which cannot be represented accurately on natural scale), we get `1-mu(i)` evaluates to zero rather than `1 - (1 - 1e-100) = 1e-100`. The binomial family shows how to represent p and 1-p accurately at the same time by transforming to logit scale. I suggest doing the same - [fixed here](https://github.com/glmmTMB/glmmTMB/tree/cloglog_fix2).

### Problem 2:

Even if we can accurately evaluate `s2`, on the entire double precision floating point range, we are limited by the precision of `lgamma(s2)` used in `dbetabinomial`.
To solve this we would need a transformed version `lgamma_exp(x):=lgamma(exp(x))`. Could be done using the approximation `lgamma(exp(x)) ~ -x` for left tail. But, I don't think it's worth it given that this problem only occurs in a case where we start from extreme inital values (fit2). Solution: use the defaults.

**Comment by bbolker** [comment]
Thanks for working on this! I haven't had a chance to check the new branch yet (despite not having kids or online teaching to do, I still seem to be super-busy ...)

* do you know yet if your modification works on Rolf's problem? (It sounds like it does.) Are there tests yet?
* I like the idea of solving Problem 2 at the same time, if it's not too hard. We know that no matter what problem we find, someone will hit it eventually ...
* I agree about getting rid of clamping. Is it worth saving the TMB function without the clamp? Or if not, saving the thing I did earlier (using a logspace_sub in the cloglog inverse link function)?

**Comment by kaskr** [comment]
I added a solution to problem 2 and now all the examples 'work' (converge but some fits are singular). I'll make a PR. It may be worth keeping 'cloglog_fix' branch in case we have to return to this issue.

**Comment by bbolker** [comment]
Hmm. I added tests and `fit2` doesn't work for me (on Ubuntu 16.04/r-devel) ... can you look and see if I missed something/if it works for you? (If need be we can comment out that test and move on, but it'd be nice to see)

**Comment by bbolker** [comment]
this is looking better - fits don't actually give errors.  I don't know if we're getting the right answers though: See [here](https://github.com/glmmTMB/glmmTMB/blob/cloglog_fix2/glmmTMB/inst/test_data/turner_glmmadapt.R) and [here](https://github.com/glmmTMB/glmmTMB/blob/cloglog_fix2/glmmTMB/tests/testthat/test-families.R#L184-L201) (it also seems that the Laplace approximation may not be great here ...)

**Comment by bbolker** [comment]
I think this is the best we'll do for now. No errors. First attempt (from default starting values) complains (non-pos-def Hessian etc.). Second attempt (from values found on first run) converges to a singular fit. Comparing to `GLMMadaptive` fits, the fit is pretty close to those with >= 2 quadrature points (for some reason `GLMMadaptive` gets a different (worse?) fit with 1 quad point = Laplace approximation ...
