### ISSUE TITLE
setting "na.exclude" produces strange off-by-one-like behavior (but not really that) from predict() and residuals()

### ISSUE THREAD

**Issue by jmobrien** [glmmTMB/glmmTMB#568]
Hi, ran into a problem with the `predict.glmmTMB` and `residuals.glmmTMB` functions, both, when models were fitted from the main function with `na.action = "na.exclude"`.  They both seem to drop a value following an NA, then they add a seemingly valid value in at the end, whose origin is obscure to me.  Kind of like an off-by-one error, but with the odd value at the end there's evidently more going on.  

This seems like a pretty substantive problem, especially as it could be easy to miss in many use cases.

Reproducible example below, tested on 1.0.1

(Also, possibly related somehow to #545 ?  Not sure.)

```r
require(glmmTMB)

# Generate some data from a Poisson process 
# (reproducible using other families, though)
b <- rnorm(332)
mu <- exp(1.5 + .26*b)
y <- sapply(mu, function(mu){rpois(1, lambda = mu)})

# add a missing value to b:
b[51] <- NA 

# and version of y with missing:
y.na <- y
y.na[51] <- NA 


# DEFAULT MODEL

# Estimate a simple model:
mod <- glmmTMB(y ~ b, family = "poisson")
summary(mod)
# Get predicted responses & residuals
pr <-predict(mod, type = "response")
rs <- residuals(mod) # "response" implied

# Looks okay: integer counts
(pr.rs <- pr + rs)
names(pr.rs) <- NULL #so all.equal() works

# Matches up perfectly w/ true outcome 
# (if we drop the missing value from y):
all.equal(pr.rs, y[-51])

# PREDICTION ISSUES  WHEN USING NA.EXCLUDE:

# same mode, just w/na.exclude
(mod.ex <- glmmTMB(y ~ b, family = "poisson", na.action = "na.exclude"))
summary(mod.ex) # looks okay

# Get predictions/resids
pr.ex <- predict(mod.ex, type = "response") # SEEMS to work fine
rs.ex <- residuals(mod.ex, type = "response") # Warns of length mismatch

# also SEEMS to produce legitimate integer counts
# (implying that predictions and residuals match up):
(pr.rs.ex <- pr.ex + rs.ex) # NOTE: names attr. gone too (not sure if relevant)?

# Has a missing value in position 51
pr.rs.ex[51]

# Length checks out:
length(pr.rs.ex) == length(y)

# But does NOT match up with outcome:
all.equal(pr.rs.ex, y.na)

#But, what's going on?

# Fine until the first NA:
all.equal(pr.rs.ex[1:51],
          y.na[1:51])

# Ater the first NA
# There's something that looks like an off-by-one error:
all.equal(
  # In pred + resid, remove up to the first missing, 
  # AND the last pred value:
  pr.rs.ex[c(-(1:51), -length(pr.rs.ex))],
  # In the original data, remove up to the first missing,
  # PLUS one additional value following that:
  y.na[-(1:52)] 
) # Then they match up

# But it's not cleanly an off-by-one error:
# The dropped value in y (position 52) was not moved to the end
# (run this again if they match by chance)
y.na[52]
pr.rs.ex[length(pr.rs.ex)]
```

**Comment by bbolker** [comment]
Looks fairly straightforward: fitted values were getting NAs filled in via `napredict()`, but responses were being extracted from model frame and *not* having NAs restored. See https://github.com/glmmTMB/glmmTMB/pull/569

**Comment by jmobrien** [comment]
Great, appreciate the quick response!  Glad it was an easy fix.  

Just curious--where was that extra element on the end in both functions coming from?  It was apparently being "recycled" in from somewhere, but it wasn't obvious from where.  (But I might be just missing a lot here as I'm still not seeing the link that explains why fixing `resid` fixes `predict` also.  Regardless, I updated from the new branch and it works, so thanks!)

**Comment by bbolker** [comment]
The short answer is that I think `predict()` was OK all along; I fixed `resid` so that it didn't internally try to insert extra `NA` values *twice*. I'm super-busy right now so I'm going to go ahead and mark this closed/submit a PR for the fix.  If you find something else wrong, feel free to re-open or open a new issue.
