### ISSUE TITLE
Function Anova.glmmTMB not working

### ISSUE THREAD

**Issue by MG-85** [glmmTMB/glmmTMB#570]
I have installed package **glmmTMB v1.0.1**  in **R 3.6.3 (64-bit)**. When trying to use the function _Anova.glmmTMB_ on a model I get the error message:

Error in Anova.glmmTMB(M0): 
  could not find function "Anova.glmmTMB".

I have also tried with some older packages and got same results. 

Any advice?
Thanks

**Comment by mebrooks** [comment]
Have you tried just `Anova`? 

There is some documentation of `car::Anova` in `vignette("model_evaluation")`

**Comment by MG-85** [comment]
It worked with just `Anova`
Thanks for your help

-
