### ISSUE TITLE
confint

### ISSUE THREAD

**Issue by monicachaudhari** [glmmTMB/glmmTMB#571]
Issue: confint() does not return CIs when  dispformula is included in the model and throws an error shown below:

```
glmmformula <- formula(Y ~  sex + agestd + ethnicity + batch + disease*time + (1|donor)) 
 modl <- glmmTMB::glmmTMB(glmmformula
                              , dispformula=~ sex + agestd +  batch + disease 
                              , family=glmmTMB::beta_family(link = "logit")
                              , data = tmpdat)
confint(modl,full=TRUE )
```

> Error in dimnames(x) <- dn : 
>  length of 'dimnames' [2] not equal to array extent

**Comment by mebrooks** [comment]
I can't work on this at this moment, but I agree and here is a repeatable example
```
## Dispersion model
sim1 <- function(nfac=40, nt=100, facsd=0.1, tsd=0.15, mu=0, residsd=1)
{
  dat <- expand.grid(fac=factor(letters[1:nfac]), t=1:nt)
  n <- nrow(dat)
  dat$REfac <- rnorm(nfac, sd=facsd)[dat$fac]
  dat$REt <- rnorm(nt, sd=tsd)[dat$t]
  dat$x <- rnorm(n, mean=mu, sd=residsd) + dat$REfac + dat$REt
  dat
}
set.seed(101)
d1 <- sim1(mu=100, residsd=10)
d2 <- sim1(mu=200, residsd=5)
d1$sd <- "ten"
d2$sd <- "five"
dat <- rbind(d1, d2)
m0 <- glmmTMB(x ~ sd + (1|t), dispformula=~sd, data=dat)
confint(m0)
```

**Comment by monicachaudhari** [comment]
Surprisingly, it does not recognize the function when called by  glmmTMB::confint(). I suspect, it is calling stats::confint() and hence the error.

**Comment by bbolker** [comment]
No, it's really our problem. `glmmTMB:::confint.glmmTMB(m0)` replicates what's actually happening (S3 methods like `confint.glmmTMB` don't have to be exported in order to be found by R's method dispatch machinery.

**Comment by ash-pathak** [comment]
Hello folks. Any updates on this issue? Thanks.

**Comment by bbolker** [comment]
not yet.  Spent some time poking around today.  May have localized it to the behaviour of the internal `.CI_univariate_monotone` function, but still trying to figure out what's going on.

**Comment by bbolker** [comment]
this should be fixed: `remotes::install_github("glmmTMB/glmmTMB/glmmTMB@confint_fix")` should give you the fixed version (will wait for comments before closing.

**Comment by mebrooks** [comment]
That branch was merged last night. Try installing the master branch. 
`remotes::install_github("glmmTMB/glmmTMB/glmmTMB")`

**Comment by alex-pk-sir** [comment]
Wow... good timing on my part. Thank you @mebrooks!

**Comment by alex-pk-sir** [comment]
This is works now but not for models that incorporate an autocorrelation term. For example, I can fit a negative binomial model without an exponential autocorrelation matrix but when I include it and try to get the confidence intervals on theta, I get the following error: 

Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

**Comment by bbolker** [comment]
Can you please open a new issue, with a reproducible example?  Thanks ...
