### ISSUE TITLE
Specify special cases of distribution families

### ISSUE THREAD

**Issue by yulanvanoppen** [glmmTMB/glmmTMB#577]
This might be very simple question, but I am having trouble finding how to fixing parameters in certain distribution families. I would like to run a geometric regression, and since the respective response distribution is a special case of the Conway-Maxwell-Poisson distribution, I suppose this is possible. However, in cannot find the part of the documentation that describes how to set the parameters accordingly (something like `nbinom2(phi = 1)` results in an unused argument error). I have also tried to find the answer in `?family_gglmmTMB` and `?sigma.glmmTMB` without succes. Is this actually possible, and if so, how? Thanks in advance!

**Comment by mebrooks** [comment]
In theory this might be possible, but I couldn't get it to work for the geometric distribution. Although it's a special case of the CMP, it's on the boundary (nu=0 and phi=1/nu=infinity). I could have tried more, but this distribution is so slow and I have a lot of other obligations right now. Although it might get faster when @kaskr unveils a new TMB. For now, hopefully this will get you headed on the right track. 

In this example `pmod_sub` has nu fixed at 1. Note that there's a log link on the dispersion model. 

```
library(glmmTMB)
dat=expand.grid(x=1:20, rep=1:5)
dat$y=rpois(nrow(dat), exp(.1+.2*dat$x))
pmod1=glmmTMB(y~x, family=compois, dat)
summary(pmod1)
pmod_sub=glmmTMB(y~x, family=compois, dat, map=list(betad=factor(NA)), start=list(betad=0))
summary(pmod_sub) #has overdispersion parameter fixed at = 1 = exp(0)
```

In this example (continuing with data from above), I tried to simulate and fit geometric data, but it's slow and doesn't converge.
```
dat$g=rgeom(nrow(dat), boot::inv.logit(-1+.2*dat$x))
gmod_sub1=glmmTMB(g~x, family=compois(link="logit"), dat, map=list(betad=factor(NA)), start=list(betad=20, beta = c(-1, .2)))
summary(gmod_sub)
```

An alternative route might be to add a new family.

**Comment by bbolker** [comment]
I was going to try something like this, but it would be much easier with a nbinom2 (which is (a) a simpler, faster, more robust distribution) and (b) the special case for the geometric distribution (shape=1) is not on the boundary ...

**Comment by mebrooks** [comment]
Oh yeah, excellent idea! I had forgotten that it was a special case of nbinom2, but was just reading that on wikipedia. Theres seems to still be something wrong with my example below because the beta parameter estimates are way off.
```
library(glmmTMB)
dat=expand.grid(x=1:20, rep=1:50)
dat$g=rgeom(nrow(dat), boot::inv.logit(-1+.2*dat$x))
gmod_sub_nb=glmmTMB(g~x, family=nbinom2(link="logit"), dat, map=list(betad=factor(NA)), start=list(betad=log(1)))
summary(gmod_sub_nb)
```

**Comment by bbolker** [comment]
You need to be careful with parameterizations. `rgeom()` is not the same parameterization as `rnbinom(..., size=1)`.

I don't know if this does what the OP wants, but it's at least internally consistent. (Thanks for the example!)

```
library(glmmTMB)
dat=expand.grid(x=1:20, rep=1:50)
## dat$g=rgeom(nrow(dat), plogis(-1+.2*dat$x))
dat$g=rnbinom(nrow(dat), mu=exp(-1+.2*dat$x), size=1)
gmod_sub_nb=glmmTMB(g~x, family=nbinom2(link="logit"), dat,
                    map=list(betad=factor(NA)), start=list(betad=log(1)))
summary(gmod_sub_nb)
```

**Comment by yulanvanoppen** [comment]
That indeed does the trick, thanks a lot! I was trying all sorts of options, like `phi = 1` or `theta = 1`, but I couldn't find that its called `shape` (I guess this is a very standard argument name).

**Comment by bbolker** [comment]
It's actually called `size`, which is weird until you remember that in the classic coin-flip/discrete survival analysis parameterization of the NB, the dispersion/shape parameter is also the number N of failures you're waiting to experience (so N=1 -> geometric)
