### ISSUE TITLE
Fitting glmmTMB advice

### ISSUE THREAD

**Issue by Anfileida2019** [glmmTMB/glmmTMB#585]
Hello there, I was wondering if you help. I am still learning how to work with GlmmTMB and  I have fitted GlmmTMB before but for categorical data . I currently am working on a paper and have a data set where I am trying to fit a GlmmTMB. I want to show the effect climate data on species richness and abundance . I have fitted the predictor response with species  "Richness Index" and another with "abundance ", and predictor variables "climate data" such as tmax, tmin, precipitation (Richness index I calculated using vegan package). I have fitted (site and Month) as random intercept, because the data was collected with no consistency but random days and month, and years (2010-2019). There are 19 different specimens, and n= 467. All variables are numerical. #Global Model example: Abun_2<- glmmTMB(Richness ~ (tmin +ppt1 + tmax1 + tmax2 +tmin2+ ppt2 + Year)^2+ (1|Site/Month), data=Main_data, family="nbinom2"). However when I run this  model, I come across some warning messages:

 "Found more than one class "Matrix" in cache; using the first, from namespace 'Matrix'
Also defined by ‘arkhe’
Warning messages:
_1: In glmmTMB(Abundance ~ (tmin + ppt + tmax2 + tmax + tmin2 + ppt2 +  :
  non-integer counts in a nbinom2 model
2: In fitTMB(TMBStruc) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
3: In fitTMB(TMBStruc) :
  Model convergence problem; function evaluation limit reached without convergence (9). See vignette('troubleshooting')".

I checked vignette, but the truth is, this is too advanced for and I do not understand what it is saying:) I would love to have some feedback with regards to the model. Additionally, should I use just count for Richness instead the Menhinick index for richness ? Or should I use a completely different model? I would be very grateful for any feedback please:):) Thank you in advance. :x

**Comment by mebrooks** [comment]
Please see info on [where to ask questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions). This is more appropriate for R-sig-mixed list.

There may be something wrong with `(tmin +ppt1 + tmax1 + tmax2 +tmin2+ ppt2 + Year)^2`. Try formulating it more carefully and see info on [model specification](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#model-specification).

**Comment by Anfileida2019** [comment]
Apologies for getting the incorrect forum:( I don't use it very often:( I will follow your instructions;) Thank you so much for your time!
