### ISSUE TITLE
GlmmTMB error messages

### ISSUE THREAD

**Issue by Anfileida2019** [glmmTMB/glmmTMB#586]
Dear all, I posted this elsewhere, but not getting any reply. I was wondering if you  can help. I am still learning how to work with GlmmTMB and I have fitted GlmmTMB before but for categorical data . I am currently working on a paper and have a data set where I am trying to fit a GlmmTMB. I want to show the effect climate data on species richness and abundance . I have fitted the predictor response with species "Richness Index" and another with "abundance ", and predictor variables "climate data" such as tmax, tmin, precipitation (Richness index I calculated using vegan package) . I have fitted (Date) as random intercept, because the data was collected with no consistency but random days and month, and years (2010-2019). There are 19 different specimens, and 467  spp. 
data.frame':	42 obs. of  67 variables: data structure

 $ Year                      : Factor w/ 10 levels "2010","2011",..: 1 1 1 1 1 1 2 2 2 2 ...
 $ Month_year                : Factor w/ 42 levels "1.11","1.12",..: 22 24 28 32 35 41 1 7 12 15 ...
 $ Date                      : Factor w/ 41 levels "03/05/2016","05/11/2019",..: 12 6 18 19 26 20 7 30 24 10 ...
 $ Month                     : Factor w/ 12 levels "1","2","3","4",..: 7 8 9 10 11 12 1 2 3 4 ...
 $ Richness                  : num  7 4 9 8 7 11 4 4 2 1 ...
 $ Abundancy                 : num  16 6 40 28 18 45 14 9 5 2 ...
 $ Adenomera.marmorata       : int  1 0 2 1 0 2 0 0 0 0 ...
 $ Chiasmocleis.leucosticta  : int  0 1 0 2 0 2 0 0 0 0 ...
 $ Crossodactylus.caramaschii: int  0 0 0 0 0 0 0 0 0 0 ...
 $ Haddadus.binotatus        : int  0 0 1 0 0 0 0 0 0 0 ...
 $ Leptodactylus.flavopictus : int  0 0 0 0 0 1 0 0 0 0 ...
 $ Leptodactylus.fuscus      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Leptodactylus.latrans     : int  1 0 3 1 0 4 1 0 0 0 ...
 $ Leptodactylus.notoaktites : int  3 2 1 14 6 18 5 3 1 0 ...
 $ Leptodactylus.sp.         : int  3 1 0 0 1 1 0 0 0 0 ...
 $ Ololygon.rizibilis        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Physalaemus.cuvieri       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Physalaemus.lateristriga  : int  0 0 2 0 2 4 5 1 0 0 ...
 $ Physalaemus.spiniger      : int  0 0 5 3 1 1 0 0 0 0 ...
 $ Proceratophrys.boiei      : int  0 0 2 1 1 3 0 0 0 0 ...
 $ Proceratophrys.sp.        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Rhinella.icterica         : int  2 0 4 1 1 2 0 1 0 0 ...
 $ Rhinella.ornata           : int  6 2 11 5 6 6 3 4 4 2 ...
 $ Trachycephalus.mesophaeus : int  0 0 0 0 0 0 0 0 0 0 ...
 $ tmax                      : num  23.7 23.3 26 25.6 31.1 29.4 31.1 30.6 28.1 27.1 ...
 $ tmin                      : num  12.5 12.4 16 16.1 21.2 19.6 21.2 20.7 18.4 17.1 ...
 $ ppt                       : num  109 27 69 141 343 184 343 318 106 129 ...
 $ vap                       : num  1.64 1.57 1.88 1.84 2.53 2.29 2.53 2.52 2.19 2.09 ...
 $ pdsi                      : num  5.8 4.8 4 3.3 5.7 2.2 5.7 6.7 5.8 5.6 ...
 $ tmax2                     : num  23.3 23.5 24.6 25.8 30.3 ...
 $ tmin2                     : num  12.3 12.4 14.2 16.1 20.2 ...
 $ ppt2                      : num  83.5 68 48 105 316 ...
 $ vap2                      : num  1.7 1.6 1.73 1.86 2.37 ...
 $ pdsi2                     : num  5.8 5.3 4.4 3.65 5.05 2.35 5.05 6.2 6.25 5.7 ...
 $ tmax3                     : num  23.3 23.3 24.3 25 29.6 ...
 $ tmin3                     : num  12.5 12.3 13.6 14.8 19.6 ...
 $ ppt3                      : num  78.3 64.7 68.3 79 242.3 ...
 $ vap3                      : num  1.69 1.65 1.7 1.76 2.27 ...
 $ pdsi3                     : num  6.2 5.47 4.87 4.03 4.27 ...
 $ tmax4                     : num  24.1 23.3 24 24.6 28.6 ...
 $ tmin4                     : num  13.4 12.4 13.2 14.2 18.7 ...
 $ ppt4                      : num  108.5 65.5 65.8 86.5 217 ...
 $ vap4                      : num  1.77 1.66 1.71 1.73 2.16 ...
 $ pdsi4                     : num  6.62 5.85 5.1 4.47 4.03 ...
 $ tmax5                     : num  25.1 23.9 23.8 24.3 28.1 ...
 $ tmin5                     : num  14.7 13.2 13.2 13.8 18.2 ...
 $ ppt5                      : num  128.4 92.2 66.2 80.8 187.4 ...
 $ vap5                      : num  1.89 1.73 1.71 1.74 2.1 ...
 $ pdsi5                     : num  6.72 6.26 5.48 4.74 4.02 3.26 4.02 4.56 5.06 5.64 ...
 $ tmax6                     : num  26.2 24.8 24.3 24.1 27.3 ...
 $ tmin6                     : num  15.9 14.3 13.7 13.7 17.2 ...
 $ ppt6                      : num  143.5 111.5 88.3 78.7 160.7 ...
 $ vap6                      : num  2.02 1.84 1.75 1.73 2.02 ...
 $ pdsi6                     : num  6.73 6.4 5.88 5.12 4.15 ...
 $ tmax12                    : num  27.1 27.1 27.1 27 26.8 ...
 $ tmin12                    : num  16.9 16.9 16.9 16.8 16.6 ...
 $ ppt12                     : num  176 171 160 157 152 ...
 $ vap12                     : num  2.07 2.06 2.06 2.05 2.02 ...
 $ pdsi12                    : num  5.82 5.99 5.97 5.84 5.44 ...
 $ tmax.anomaly              : num  -2.2975 -2.6975 0.0025 -0.3975 5.1025 ...
 $ tmin.anomaly              : num  -3.27 -3.37 0.23 0.33 5.43 ...
 $ temp.amplitude            : num  11.2 10.9 10 9.5 9.9 9.8 9.9 9.9 9.7 10 ...
 $ Richness_menhinick        : num  1.495 1.743 1.256 0.882 1.593 ...
 $ Rarefy                    : num  6 7 4 5 6 5 6 7 5 4 ...
 $ Simpson_Index             : num  0.827 0.715 0.858 0.81 0.799 ...
 $ Abundance                 : num  16.1 16.1 10.1 32.2 14.2 ...
 $ Pielou_evenes             : num  0.376 0.399 0.345 0.352 0.363 ..

#Global Model example: Rich_Global<- glmmTMB(Richness ~ (tmin +ppt1 + tmax1 + tmax2 +tmin2+ ppt2 + Year)^2+ (1|Date), data=Main_data, family="nbinom2"). 

However when I run this model, I come across some warning messages:
"
Warning messages:
1: In fitTMB(TMBStruc) :
  Model convergence problem; extreme or very small eigen values detected. See vignette('troubleshooting')
2: In fitTMB(TMBStruc) :
  Model convergence problem; false convergence (8). See vignette('troubleshooting')".

I checked vignette, but the truth is, this is too advanced for me and I do not understand it.  I would really appreciate some feedback with regards to the model. Additionally, should I use just count for Richness instead the Menhinick index for richness ? Or should I use a completely different model? I would be very grateful for any feedback please:):) Thank you in advance. :x

**Comment by mebrooks** [comment]
Repeat of #585
