### ISSUE TITLE
An advice on GlmmTMB models

### ISSUE THREAD

**Issue by Anfileida2019** [glmmTMB/glmmTMB#587]
Dear all, I posted this elsewhere, but not getting any reply. I was wondering if you can help. I am still learning how to work with GlmmTMB and I have fitted GlmmTMB before but for categorical data. I am currently working on a paper and have a data set where I am trying to fit a GlmmTMB. I want to show the effect of climate data on species richness (n= 16) and abundance (n= 486). I have fitted the predictor response with species "Sahnnon_Index", and predictor variables "climate data" such as tmax, tmin, precipitation (Shannon Index was calculated using vegan package). I have fitted (Date) as random intercept because the data was not consistently collected but random days and months, and years (2010-2019). However, I am getting a consistent error "

Abun_1<- glmmTMB(Shannon_Index ~ tmin + tmax + ppt + vap + year+Habit+Habitat+Development+Size_category+ (1|Date),zi= ~ tmin + tmax + ppt + vap + year+Habit+Habitat+Development+Size_category,data=Abun_SAD, family=nbinom2())

"Warning messages:
1: In glmmTMB(Shannon_Index ~ tmin + tmax + ppt + vap + year + Habit +  :
  non-integer counts in a nbinom2 model
2: In fitTMB(TMBStruc) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
3: In fitTMB(TMBStruc) :
  Model convergence problem; false convergence (8). See vignette('troubleshooting')"

vignette('troubleshooting')
fixef(Abun_1)

Cfixef(Abun_1)

Conditional model:
         (Intercept)                  tmin                  tmax                   ppt  
          -1.556e+01            -3.141e-02            -1.095e-02             3.798e-05  
                 vap                  year       HabitRheophilic      HabitTerrestrial  
           3.750e-01            -4.824e-04             1.559e+01             1.602e+01  
HabitatForested_Open           HabitatOpen   DevelopmentIndirect   Size_categoryMedium  
           2.680e-01            -9.517e-01             1.304e+00             2.308e-01  
 Size_categorySmall   
           1.497e-02  

Zero-inflation model:
         (Intercept)                  tmin                  tmax                   ppt  
           -0.001423              1.032264              0.741674             -0.263141  
                 vap                  year       HabitRheophilic      HabitTerrestrial  
            0.078434             -0.033380             -0.027334             -0.062907  
HabitatForested_Open           HabitatOpen   DevelopmentIndirect   Size_categoryMedium  
            0.040984              0.063090             -0.001231             -0.174544  
 Size_categorySmall   
            0.081475  

-> After looking at my data I saw intercept (-1.56), I have realized that 13 out of the 16 species are <10 per year. Does it mean my sample is too small to run a GLMM and I should look at other ways of analyzing the data? if so is there any other suggestion? would a Least Square Regression be suitable? 

#=====================================================

**data structure**
str(Abun_SAD)
'data.frame':	152 obs. of  53 variables:
 $ ID               : int  1 2 4 5 224 278 384 444 446 448 ...
 $ Date             : Factor w/ 102 levels "01/09/2010","01/10/2010",..: 98 24 97 3 28 82 79 75 60 20 ...
 $ month            : int  7 9 10 12 3 9 11 1 2 11 ...
 $ year             : int  2010 2010 2010 2010 2012 2013 2017 2018 2018 2018 ...
 $ Species          : int  1 1 1 1 1 1 1 1 1 1 ...
 $ species          : Factor w/ 16 levels "Adenomera marmorata",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Shannon_Index    : num  2.43 2.43 2.43 2.43 2.43 ...
 $ Pielou_evenness  : Factor w/ 38 levels "0.04453093","0.04653607",..: 38 23 38 23 38 38 38 22 22 37 ...
 $ Abundance        : int  1 2 1 2 1 1 1 2 2 1 ...
 $ Habit            : Factor w/ 3 levels "Arboreal","Rheophilic",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ Habitat          : Factor w/ 3 levels "Forested","Forested_Open",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ Main_calling_site: Factor w/ 3 levels "Forest floor",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Development      : Factor w/ 2 levels "Direct","Indirect": 2 2 2 2 2 2 2 2 2 2 ...
 $ Adult_size_cm    : Factor w/ 11 levels "01-Mar","02-Apr",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Size_category    : Factor w/ 3 levels "Large","Medium",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ tmax             : num  23.7 26 25.6 29.5 29 25.6 28.2 29.5 28.9 28.3 ...
 $ tmin             : num  12.5 16 16.1 19.2 19.3 15.6 18.1 19.6 19.2 18.6 ...
 $ ppt              : int  109 69 141 289 85 122 133 305 107 65 ...
 $ vap              : num  1.64 1.88 1.84 2.2 2.32 1.84 2.04 2.31 2.27 2.05 ...
 $ pdsi             : num  5.8 4 3.3 4.4 1.1 1.8 1.9 2.9 1.9 0.4 ...
 $ tmax2            : num  23.3 24.6 25.8 28.9 30.1 ...
 $ tmin2            : num  12.3 14.2 16.1 18.8 20.4 ...
 $ ppt2             : num  83.5 48 105 192 142.5 ...
 $ vap2             : num  1.7 1.73 1.86 2.13 2.46 ...
 $ pdsi2            : num  5.8 4.4 3.65 3.55 1.6 1.6 2.05 2.8 2.4 -0.25 ...
 $ tmax3            : num  23.3 24.3 25 27.8 29.9 ...
 $ tmin3            : num  12.5 13.6 14.8 17.9 20.1 ...
 $ ppt3             : num  78.3 68.3 79 175 156.3 ...
 $ vap3             : num  1.69 1.7 1.76 2.04 2.4 ...
 $ pdsi3            : num  6.2 4.87 4.03 3.47 1.8 ...
 $ tmax4            : num  24.1 24 24.6 27.4 29.8 ...
 $ tmin4            : num  13.4 13.2 14.2 17.4 19.9 ...
 $ ppt4             : num  108.5 65.8 86.5 148.5 148 ...
 $ vap4             : num  1.77 1.71 1.73 2 2.35 ...
 $ pdsi4            : num  6.62 5.1 4.47 3.6 1.98 ...
 $ tmax5            : num  25.1 23.8 24.3 26.5 29.3 ...
 $ tmin5            : num  14.7 13.2 13.8 16.4 19.4 ...
 $ ppt5             : num  128.4 66.2 80.8 124.2 135 ...
 $ vap5             : num  1.89 1.71 1.74 1.91 2.28 ...
 $ pdsi5            : num  6.72 5.48 4.74 3.84 2.26 0.48 2.38 2.28 2.32 -0.48 ...
 $ tmax6            : num  26.2 24.3 24.1 26.1 28.9 ...
 $ tmin6            : num  15.9 13.7 13.7 15.8 19.1 ...
 $ ppt6             : num  143.5 88.3 78.7 121.7 146.5 ...
 $ vap6             : num  2.02 1.75 1.73 1.87 2.23 ...
 $ pdsi6            : num  6.73 5.88 5.12 4.17 2.58 ...
 $ tmax12           : num  27.1 27.1 27 26.7 26.4 ...
 $ tmin12           : num  16.9 16.9 16.8 16.5 16.2 ...
 $ ppt12            : num  176 160 157 157 118 ...
 $ vap12            : num  2.07 2.06 2.05 2.01 1.97 ...
 $ pdsi12           : num  5.82 5.97 5.84 5.57 3.54 ...
 $ tmax_anomaly     : num  -2.298 0.003 -0.398 3.503 3.003 ...
 $ tmin_anomaly     : num  -3.27 0.23 0.33 3.43 3.53 -0.17 2.33 3.83 3.43 2.83 ...
 $ temp_amplitude   : num  11.2 10 9.5 10.3 9.7 10 10.1 9.9 9.7 9.7 ...

Thank you so much for your help:) I am sure you have worked out, I am not a statistician:(

**Comment by mebrooks** [comment]
This is basically a repeat of #585, but with a slightly improved model formula. I will try to give some advice on the R-sig-mixed list because that is the appropriate place (as I said in #585).
