### ISSUE TITLE
Problems fitting a GLMM with betabinomial distribution

### ISSUE THREAD

**Issue by nico-mbio** [glmmTMB/glmmTMB#590]
At first I tried to adjust to a Binomial distribution, I was even able to fit a random-effect. When I proceeded to validate the model, it came clear that it didn't fit the assumptions.
Then I attempted to use a Beta Binomial distribution (since it was the only alternative I knew for a binomial distribution - I didn't even consider a quasibinomial, it's no help).
When I compared the raw model using a binomial vs the betabinomial, it showed a more than significant improvement. But when I tried to fit the random-effect, I got this warning

"Warning message:
In (function (start, objective, gradient = NULL, hessian = NULL,  :
  NA/NaN function evaluation"

Nonetheless, the model converged (the summary showed no issues). The model was the following:

mod1 <- glmmTMB(cbind(viables,inviables)~transecta+lote*diametro + (1|estacion),family=betabinomial,data=datos)

I could not find what the warning meant, so I don't know if I can disregard the warning and carry on or maybe it means that the model is invalid.

**Comment by bbolker** [comment]
The warning means that at some point in the fitting process, an 'illegal' set of parameter values was tried; this is mildly surprising and would be worth chasing down at some point. For example, it's possible that some computation under/overflowed.  But, provided that everything looks sensible (graphical diagnostics, parameter values, etc.), it's probably not something to worry about much.
