### ISSUE TITLE
Error in MakeADFun link not implemented

### ISSUE THREAD

**Issue by thornton-alex** [glmmTMB/glmmTMB#599]
To familiarise myself with glmmTMB and bootstrapping methods in glmmboot, I am trying to run the "Standard Example" given here: https://cran.r-project.org/web/packages/glmmboot/vignettes/quick_use.html.

This gives me an error message as shown below

```
library(glmmboot)
data(test_data)
library(glmmTMB)
model_formula <- as.formula(y ~ x_var1 + x_var2 + x_var2 + (1 | subj))

base_run <- glmmTMB(formula = model_formula,
                    data = test_data,
                    family = binomial)
```
> Error in MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg,  : 
  Link not implemented!
> In addition: Warning message:
In eval(family$initialize) : non-integer #successes in a binomial glm

: I understand from the guide on CRAN that the non-integer message is not an issue, but have not been able to get to the bottom of  the "Error in MakeAdFun" message. Presumably as a consequence of this, when I try to run the bootstrapping procedure, I get this:

```
base_run <- glmmTMB(formula = model_formula,
                    data = test_data,
                    family = binomial)
```

> Error in model.frame.default(formula = y ~ x1 + x2, data = sample_data,  : 
  variable lengths differ (found for 'x1')**

```
print(bootstrap_over_subj)
```

> Error in print(bootstrap_over_subj) : 
  object 'bootstrap_over_subj' not found**

I'd be very grateful for any advice on this!

Many thanks.

**Comment by bbolker** [comment]
This is a very peculiar (and non-reproducible for me) example.  My best guess is that you have a function called `binomial()` that's masking the base-R version of binomial. You could:

- try `find("binomial")` (should be `package:stats`)
- try starting from a clean R session (nothing else in your environment, no other packages loaded)
- try use `stats::binomial` as your `family=` argument.

**Comment by thornton-alex** [comment]
specifying stats::binomial seems to have done the trick. Thanks!

**Comment by bbolker** [comment]
It would be a good idea to `find("binomial")` as well to find out where the rogue copy of `binomial` is coming from: it could potentially mess up other things in your workflow (if it's done by an add-on package, I would say that it's displaying somewhat antisocial behaviour [i.e., masking a widely used function from base R]).
