### ISSUE TITLE
version 1.0.2 release checklist

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#601]
We need to submit a new version (presumably 1.0.2) by 29 June 2020, due to breakage by a suggested package (`huxtable`). [This pull request](https://github.com/glmmTMB/glmmTMB/pull/600) should fix the critical issues, but I wonder if there is anything else we want to squeeze in for this release.

* bump version number
* reverse dependency checks 
* platform checks (win-builder, r-hub, etc.)
* make sure [NEWS file](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/inst/NEWS.Rd) is up to date
* low-hanging fruit (e.g. #595 ?)

**Comment by mebrooks** [comment]
I ran the usual checks. The only problem were these slight differences on the old release of R (release and devel were fine).
```
== Failed ======================================================================
  -- 1. Failure: basic fits (@test-sparseX.R#11)  --------------------------------
  fixef(fm2) not equal to fixef(fm2S).
  Component "cond": Mean relative difference: 7.585546e-07
  Component "disp": Mean relative difference: 9.9755e-07
  
  -- 2. Failure: basic fits (@test-sparseX.R#12)  --------------------------------
  VarCorr(fm2) not equal to VarCorr(fm2S).
  Component "cond": Component "Subject": Attributes: < Component "correlation": Mean relative difference: 0.0003392944 >
  Component "cond": Component "Subject": Attributes: < Component "stddev": Mean relative difference: 1.304289e-05 >
  Component "cond": Component "Subject": Mean relative difference: 3.766924e-05
  
  -- 3. Failure: basic fits (@test-sparseX.R#14)  --------------------------------
  predict(fm2) not equal to predict(fm2S).
  180/180 mismatches (average diff: 0.000134)
  [1] 254 - 254 ==  5.19e-04
  [2] 274 - 274 ==  4.19e-04
  [3] 293 - 293 ==  3.20e-04
  [4] 313 - 313 ==  2.21e-04
  [5] 332 - 332 ==  1.21e-04
  [6] 352 - 352 ==  2.17e-05
  [7] 371 - 371 == -7.78e-05
  [8] 391 - 391 == -1.77e-04
  [9] 411 - 411 == -2.77e-04
  ...
  
  -- 4. Failure: basic fits (@test-sparseX.R#16)  --------------------------------
  predict(fm2, newdata = nd) not equal to predict(fm2S, newdata = nd).
  1/1 mismatches
  [1] 254 - 254 == 0.000519

```
Since they're all just small differences in test tolerance on the old version, I'm inclined to ignore them. I don't see anything in the CRAN policies requiring that it passes all tests with oldrelease. Is that ok, or do we need to adjust the tolerances?

**Comment by bbolker** [comment]
CRAN is often crankier than is explicitly stated in the policies.  It would be safer to adjust the tolerances (this also protects against, say, the errors being larger on a platform we don't have access to, such as Solaris ...)

**Comment by mmaechler** [comment]
not to forget the upcoming non-intel Macs with "A processors" (based on ARM).

**Comment by mebrooks** [comment]
Ok. I submitted to CRAN after it passed all tests with relaxed tolerances. It was accepted. 

I probably could have come up with more News items to add; I only added the bug fix for the beta family documentation. I'm hoping anything important was already there.

**Comment by bbolker** [comment]
Thanks!  We can always fix the NEWS after the fact, although we're more likely to forget the longer we wait ...  the one thing I'd like to add (retrospectively) are release dates for previous versions: we can probably  get these from the [archive](https://cran.r-project.org/src/contrib/Archive/glmmTMB/) (we can cross-check with the repo, but I think the archives are added when the next version goes up)

**Comment by mebrooks** [comment]
There was a problem with the vignette building on Debian. It appears to possibly involve `centerbox`
`  ! LaTeX Error: Environment centerbox undefined.`

https://win-builder.r-project.org/incoming_pretest/glmmTMB_1.0.2_20200629_173731/Debian/00check.log

**Comment by bbolker** [comment]
Huh.  This feels like it's still huxtable-related, but I thought I got rid of all of those references ... I'll take a look

**Comment by mebrooks** [comment]
The output is confusing because near the top it says
```
* this is package ‘glmmTMB’ version ‘1.0.2’
```
but lower down, there are several places where it says 
```
Version: 1.0.1
```
without enough context to be sure that it's referring to `glmmTMB`.

**Comment by mebrooks** [comment]
Maybe this info from the email is more useful than the link to the check.
```
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
 Maintainer: 'Mollie Brooks <mollieebrooks@gmail.com>'

Flavor: r-devel-windows-ix86+x86_64
Check: Overall checktime, Result: NOTE
 Overall checktime 12 min > 10 min

Flavor: r-devel-linux-x86_64-debian-gcc
Check: Rd cross-references, Result: WARNING
 Non-file package-anchored link(s) in documentation object 'bootmer_methods.Rd':
   '[lme4]{isLMM}'

 Non-file package-anchored link(s) in documentation object 'weights.glmmTMB.Rd':
   '[stats]{weights.glm}'

 See section 'Cross-references' in the 'Writing R Extensions' manual.
```

**Comment by bbolker** [comment]
* The link warnings appear to be a recent addition, see [here](https://github.com/wch/r-source/commit/f27cbf1a52a31cd9b9676340394946a22041a4ae).  Since AFAICT they only occur with 
     * r-devel more recent than June 10
     * on Debian (?? don't know why: maybe `_R_CHECK_XREFS_MIND_SUSPECT_ANCHORS_` is only set there?
     * with `--as-cran`

I can now see I could have missed them (hadn't updated my r-devel for slightly too long ...)

* I think the other warnings are leftover from the current version, i.e. irrelevant: they're in a section headed

> Current CRAN status: WARN: 7, NOTE: 5
> See: <https://CRAN.R-project.org/web/checks/check_results_glmmTMB.html>

Do we know if the submission was *actually* accepted? `foghorn::cran_incoming("glmmTMB")` lists "archive" as the current location, and `?foghorn::cran_incoming` says

> archive: package rejected: it does not pass the checks cleanly and  the problems are unlikely to be false positives

I'm guessing we're going to have to bump the version number (ugh) and try again with the link fixes. (Don't forget to add a filler NEWS entry ...)

**Comment by mebrooks** [comment]
It was rejected, so I'm in the process of preparing to resubmit. I bumped the version number to 1.0.2.1. What sort of NEWS entry do you think is needed? Right now the latest news is for 1.0.2, so I was hoping that would be enough. Or should we go to 1.0.3?

**Comment by bbolker** [comment]
1.0.2.1 sounds good to me.  For NEWS I would suggest something like

```
\section{CHANGES IN VERSION 1.0.2.1}{
	\itemize{
      \item fix documentation links for CRAN checks
	}
}
```

and add `(unrelease)` to the version 1.0.2 description ...

**Comment by mmaechler** [comment]
Version number and both NEWS entries are good ideas; I'd keep in mind for my own pkgs in a similar situation.

**Comment by bbolker** [comment]
I see (or rather `foghorn::cran_incoming("glmmTMB")` sees) that the new version is submitted. Thanks, fingers crossed!

**Comment by mebrooks** [comment]
Yay! It's accepted! I'm happy that we were able to grab a few low hanging fruits, too.
