### ISSUE TITLE
error with new version of TMB?

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#615]
I can't replicate this after re-installing glmmTMB, but I suspect that updating TMB to the newest version (1.7.18) without reinstalling glmmTMB may lead to this error:

> Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) :   "FreeADFunObject" not available for .Call() for package "glmmTMB"

**Comment by kaskr** [comment]
I can confirm that reinstallation of glmmTMB is necessary after upgrading to TMB 1.7.18.

**Comment by bbolker** [comment]
Hopefully people encountering this error message will do a web search and find this page ...

**Comment by jennifertennessen** [comment]
I have encountered this same problem where a call to glmmTMB() yields the following error message:
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : "FreeADFunObject" not available for .Call() for package "glmmTMB"

I tried the suggestion here to upgrade to TMB 1.7.18 and then reinstall glmmTMB, but I am still receiving this error message. I am using R v 3.6.3 Patched, and RStudio v 1.3.1056 on a MacOS 10.13.6. I have also tried this using R v 4.0.2, and received the same error message as above.

Can you suggest anything else I might be missing? Thank you in advance for your help!

**Comment by mebrooks** [comment]
I was able to replicate the error you saw, but the model successfully ran anyway. To make the error stop occurring, I ran 
```
install.packages("glmmTMB", type="source")
```
and then restarted R.

**Comment by bbolker** [comment]
Nice catch @mebrooks  (I never remember this because I'm on Linux → always installing from source anyway ...)

This may mean we should try to push a new version to CRAN sooner rather than later (to avoid problems with people who don't have compilers or have configuration problems with their compilers ...)

**Comment by jennifertennessen** [comment]
Thank you @mebrooks! This resolved it.

**Comment by strengejacke** [comment]
I just re-installed glmmTMB (not from source, just running `install.packages("glmmTMB", dependencies = TRUE)`) and the error no longer seems to appear. I'm working with R4.0.2 on Windows 10. I did recognize that running models doesn't seem to be affected, however, this error message of course leaves a little feeling of uncertainty.

**Comment by dswingley** [comment]
Struggling with this too, under macOS Catalina 10.15.6. I attempted to remove my entire R install, and reinstalled R 4.0.2 from cran. Package versions are 1.0.2.1 for glmmTMB and 1.7.18 for TMB; front end RStudio 1.3.1093.  Reinstallation of glmmTMB using ` install.packages("glmmTMB", type="source")`. 
> Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
I have also tried the "dependencies = TRUE" version of the install.
The model does appear to run, despite the error messages.

**Comment by bbolker** [comment]
Huh.  Installing glmmTMB *from source* after installing TMB 1.7.18 should work without errors ... ???

**Comment by dswingley** [comment]
It's possible I did this in a flailing, out of order kind of way.  I'll do it more systematically later today and report back. (in particular, I might have installed glmmTMB and then TMB)

**Comment by samhforbes** [comment]
I was having this issue as well, can confirm that install_github cleared it up for me.

**Comment by dswingley** [comment]
aha: in my experience, installing TMB first, and then installing glmmTMB from source, led to glmmTMB running normally without unusual warnings at runtime.  The install produced some unfamiliar warnings. I reproduce most of the process below, for reference.

> install.packages("TMB")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/TMB_1.7.18.tgz'
Content type 'application/x-gzip' length 1206055 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

The downloaded binary packages are in
	/var/folders/1h/2bnz7qfj639_rmkq87xs9k3h0000gp/T//Rtmpm01DFB/downloaded_packages
> install.packages("glmmTMB", type="source")
trying URL 'https://cran.rstudio.com/src/contrib/glmmTMB_1.0.2.1.tar.gz'
Content type 'application/x-gzip' length 2964506 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

>* installing *source* package ‘glmmTMB’ ...
** package ‘glmmTMB’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TMB/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c glmmTMB.cpp -o glmmTMB.o
In file included from glmmTMB.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/TMB/include/TMB.hpp:53:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/Dense:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/Core:535:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop
                             ^
In file included from glmmTMB.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/TMB/include/TMB.hpp:53:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/Dense:2:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/LU:47:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include/Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop

[ .. a dozen or so messages like the above ]

**Comment by rnelson26** [comment]
I'm having a similar issue to dswingley on Mac Catalina. I installed TMB first then tried:

install.packages("glmmTMB", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/glmmTMB_1.0.2.1.tar.gz'
Content type 'application/x-gzip' length 2964506 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

* installing *source* package ‘glmmTMB’ ...
** package ‘glmmTMB’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/glmmTMB’
Warning in install.packages :
  installation of package ‘glmmTMB’ had non-zero exit status

**Comment by bbolker** [comment]
(To @rnelson26) Hmmm.  You definitely installed TMB, *then* installed glmmTMB from source, then re-started R and re-ran your models,  following [@dswingley's example](https://github.com/glmmTMB/glmmTMB/issues/615#issuecomment-698086574) precisely ... ?

**Comment by rnelson26** [comment]
@bbolker Thank you this is really helpful. I re-followed @dswingley example and it worked. The reason it didn't work for me the first time is because I did not have the command line tools downloaded on my mac. After I downloaded the command line tools from Apple Developer, I had to start over from the beginning of the example and then it worked out.

**Comment by bbolker** [comment]
yay!

**Comment by dswingley** [comment]
Three cheers for this brave new world!

**Comment by GabriellaS-K** [comment]
Hi! I have encountered the same issue. Have read through all of these, uninstalled the packages, then reinstalled TMB, then glmmTMB from source. Still no luck. Then spent the afternoon clearing space on my Mac to install Xcode for Mac, and now I'm not sure what to do with it! @rnelson26 what did you do with the Xcode tools on your Mac? Thanks!

**Comment by bbolker** [comment]
Should we consider building a MacOS binary (with up-to-date TMB) and posting it on a repo somewhere?

**Comment by GabriellaS-K** [comment]
> Hi! I have encountered the same issue. Have read through all of these, uninstalled the packages, then reinstalled TMB, then glmmTMB from source. Still no luck. Then spent the afternoon clearing space on my Mac to install Xcode for Mac, and now I'm not sure what to do with it! @rnelson26 what did you do with the Xcode tools on your Mac? Thanks!

PS. If anyone is silly, like me, and is trying to create space to download Xcode on Mac, so you can get the command line tools, STOP! You don't need it, you can get the command line tools without Xcode. check: https://www.embarcadero.com/starthere/xe5/mobdevsetup/ios/en/installing_the_commandline_tools.html

**Comment by GabriellaS-K** [comment]
my glmmTMB version is: 1.0.2.1’ 
I'll paste my error message below: 

```
> install.packages("glmmTMB", type = "source")
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/glmmTMB_1.0.2.1.tar.gz'
Content type 'application/x-gzip' length 2964506 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

* installing *source* package ‘glmmTMB’ ...
** package ‘glmmTMB’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
/usr/local/Cellar/gcc/10.1.0/bin/g++-7 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/TMB/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppEigen/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c glmmTMB.cpp -o glmmTMB.o
/bin/sh: /usr/local/Cellar/gcc/10.1.0/bin/g++-7: No such file or directory
make: *** [glmmTMB.o] Error 127
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/glmmTMB’
Warning in install.packages :
  installation of package ‘glmmTMB’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/bf/s948qjx51kb_vxsf6f4kjc7r0000gn/T/Rtmp2mvzBY/downloaded_packages’
```

If I run a glmmTMB function, I get: 

```
Error in .Call("FreeADFunObject", ptr, PACKAGE = DLL) : 
  "FreeADFunObject" not available for .Call() for package "glmmTMB"
```
but the model still runs...is this a usable model?

**Comment by rnelson26** [comment]
@GabriellaS-K I'm sorry you're also having an issue with this! I did not use xcode but installed the command line tools similar to the method you mentioned in your comment. After I installed the command line tools, I then uninstalled the TMB/glmmTMB packages and started a new r session. I then repeated all of the steps that @dswingley did and it worked. I think earlier in this thread @bbolker mentions that the error you are getting is likely from updating TMB to the newest version (1.7.18) without successfully reinstalling glmmTMB. Hope this is helpful!

**Comment by bbolker** [comment]
Can you try

```r
install.packages("glmmTMB", repos="https://glmmTMB.github.io/glmmTMB/repos", type="binary")
```
and let us know if it works (and how it fails, if it doesn't work) ?  (This is assuming you are using R >= 4.0.0)

**Comment by GabriellaS-K** [comment]
Hi! Trying this now, sorry haven't been online in a few days!

**Comment by GabriellaS-K** [comment]
SUCCESS! It worked perfectly! Thank you so much. What is it that was the problem? Mac couldn't download it properly? 

Thanks

**Comment by bbolker** [comment]
You apparently didn't have all of the developer tools installed properly (R was complaining that it couldn't find `g++`, the C++ compiler, in the place where it was looking for it); given enough time and energy that could probably be debugged but ...  

I was surprised that your model "still ran" after the error you listed above ... perhaps you were picking up an old/previously fitted model object?

In any case, all's well that ends well.

**Comment by GabriellaS-K** [comment]
thank you so much, for all the help and explanation!

**Comment by bbolker** [comment]
To-do for developers (me or @mebrooks or ... ?); [misc/mkrepos.R](https://github.com/glmmTMB/glmmTMB/blob/master/misc/mkrepos.R) gives machinery for building Windows/MacOS binaries using `rhub`, downloading them, and copying them to the right places in the `repos/` directory on the `gh-pages` branch. We should (1) document the process better (maybe add it to the Makefile?) so we can more easily do it again when needed; (2) add user-level documentation for installing binaries from the repository (i.e. [these instructions](https://github.com/glmmTMB/glmmTMB/issues/615#issuecomment-738854298)) to the README file ...

**Comment by sebastianodebona** [comment]
I am encountering the same error message (and as for @GabriellaS-K, glmmTMB() returns a model despite the error), but I am unable to update to R 4.0.0 (stuck with R 3.6.3 on MacOS 10.11.16 El Capitan). I tried all other suggested solutions with no luck.
Is there any workaround for R 3.6.3? Or can I trust the model output despite the error? Thanks!

**Comment by webbshasta** [comment]
I ran into the same issues as above, but I *think* I fixed it with Xcode and the uninstalling and reinstalling of TMB and glmmTMB. When I run my model, I receive these warnings:

`Warning messages:
1: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
2: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
3: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you`

I am able to get a summary of my model and do downstream plotting etc, but I am wondering if these warnings are something I need to be concerned about? If I understand the warning, it's simply stating that giveCsparse is no longer used. Is it safe to ignore these warnings and move on? Thanks for any input!

**Comment by bbolker** [comment]
Yes, it's safe. This has been fixed in the development version ...

**Comment by bbolker** [comment]
@sebastianodebona You could *try* downloading https://github.com/glmmTMB/glmmTMB/blob/gh-pages/repos/bin/macosx/contrib/4.0/glmmTMB_1.0.2.9000.tgz and installing the package locally. It's built for R 4.0.0 on MacOS 10.13.6, but it might work ... (the machinery we have for compiling on MacOS doesn't include an "old-release" platform that would let us build a binary file for 3.6.x ...)

**Comment by ginggs** [comment]
This went undetected in Debian testing for 5 months. :(  Luckily, once I found the error, I easily found this page.

Is there any way that glmmTMB can detect when it needs to be re-installed and warn the user?

Something like:
https://github.com/kaskr/adcomp/commit/d076d456c1c72ed800ed3fa474623b679764d06a

**Comment by aklogan** [comment]
Hi 
I am having trouble with this despite everything.

The model I wanted to run is: NBmod<-glmmTMB(Roots ~ Technique+Timing+BirthSession + (1|halfrow:Replicate), family=nbinom2, data=FineRoots_observation)

I got this error message: 

Warning messages:
1: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
2: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
3: In Matrix::sparseMatrix(dims = c(0, 0), i = integer(0), j = integer(0),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
> 
Hence why I am here. I tried installing TMB, then glmTMB without any luck. Then I tried remotes::install_github("glmmTMB/glmmTMB/glmmTMB") without any luck. 

What other approaches have you tried to troubleshoot and successfully run your negative binomial model?

Below are the versions of R, macOS, etc I am working with.


R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] TMB_1.7.20        dplyr_1.0.6       data.table_1.14.0 ggplot2_3.3.3     emmeans_1.6.1    
[6] car_3.0-10        carData_3.0-4     remotes_2.4.0     glmmTMB_1.0.2.1  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       mvtnorm_1.1-2    lattice_0.20-44  zoo_1.8-9        assertthat_0.2.1
 [6] utf8_1.2.1       R6_2.5.0         cellranger_1.1.0 pillar_1.6.1     rlang_0.4.11    
[11] curl_4.3.1       multcomp_1.4-17  readxl_1.3.1     rstudioapi_0.13  minqa_1.2.4     
[16] nloptr_1.2.2.2   Matrix_1.3-3     splines_4.1.0    lme4_1.1-27      foreign_0.8-81  
[21] munsell_0.5.0    compiler_4.1.0   pkgconfig_2.0.3  tidyselect_1.1.1 tibble_3.1.2    
[26] rio_0.5.26       codetools_0.2-18 fansi_0.5.0      withr_2.4.2      crayon_1.4.1    
[31] MASS_7.3-54      grid_4.1.0       nlme_3.1-152     xtable_1.8-4     gtable_0.3.0    
[36] lifecycle_1.0.0  DBI_1.1.1        magrittr_2.0.1   scales_1.1.1     zip_2.2.0       
[41] estimability_1.3 stringi_1.6.2    ellipsis_0.3.2   vctrs_0.3.8      generics_0.1.0  
[46] boot_1.3-28      sandwich_3.0-1   openxlsx_4.2.3   TH.data_1.0-10   tools_4.1.0     
[51] forcats_0.5.1    glue_1.4.2       purrr_0.3.4      hms_1.1.0        abind_1.4-5     
[56] survival_3.2-11  yaml_2.2.1       colorspace_2.0-1 haven_2.4.1  

Thanks for your help!
Anne

**Comment by bbolker** [comment]
A few comments and questions:

- the proximal problem is that your version of `Matrix` (1.3-3) is ahead of your version of `glmmTMB` (1.0.2.1)
- **this is not an error**: as stated in the [thread above](https://github.com/glmmTMB/glmmTMB/issues/615#issuecomment-763183844) and [on StackOverflow](https://stackoverflow.com/questions/67040472/warning-in-every-model-of-glmmtmb-givecsparse), it's harmless (if annoying)
- when you say you tried `remotes::install_github(...)` "without any luck", do you mean that it failed to install? (I assume so, since your info above states `glmmTMB` package version 1.0.2.1, which is the CRAN version and not the development version.  Another possibility is that you successfully installed the development version but didn't restart R/successfully reload the package in your current session.)
- I would say you could try installing a pre-built binary from our repository, but we haven't built one for R 4.1.0 yet ...

Since we are working on submitting a new version to CRAN in the near future, I would recommend just ignoring the warning ...

**Comment by aklogan** [comment]
Thank you for your quick response! Yes, the remotes::install_github(...) command failed to install the 'glmmTMB' from GitHub. 

 It seems I was able to install the glmmTMB package as I got the message "Package glmmTMB has compiled code", but R recommended that I installed X code: "no suitable compiler(s) were found. Installation will likely fail. Install XCode and make sure it works." 

> install.packages("Xcode") but there is no available Xcode package for this version of R. 

So I will google where to find said package - do you have advice of where I could find it?

Thanks so much!

**Comment by bbolker** [comment]
Xcode is not an R package, but a system package of development tools for MacOS, documented [farther up in this thread](https://github.com/glmmTMB/glmmTMB/issues/615#issuecomment-736888379): start [here](https://www.embarcadero.com/starthere/xe5/mobdevsetup/ios/en/installing_the_commandline_tools.html).

**Comment by aklogan** [comment]
> Xcode is not an R package, but a system package of development tools for MacOS, documented [farther up in this thread](https://github.com/glmmTMB/glmmTMB/issues/615#issuecomment-736888379): start [here](https://www.embarcadero.com/starthere/xe5/mobdevsetup/ios/en/installing_the_commandline_tools.html).

It's working now! I did the update and installed the Xcode command. So the said glmmTMB packages are finally running. Thank you for your help!

**Comment by despo5555** [comment]
hello! I am also having this issue. But, I am a bit confused about how to use the Xcode command-line tools. I downloaded it but what do you do next.  Sorry i am new to this stuff.

**Comment by bbolker** [comment]
@despo5555 , if you successfully downloaded and installed Xcode following [these instructions](https://www.embarcadero.com/starthere/xe5/mobdevsetup/ios/en/installing_the_commandline_tools.html), then you should be able to re-install TMB from source.

**Comment by bbolker** [comment]
I'm going to close this.  I hope it remains searchable ...

**Comment by ColmanHumphrey** [comment]
Bit late to the party: I was having some issues on the M1 Mac / Arm, with Big Sur. I tried most of the above, but still got odd errors. Then I realised I was a bit behind on R versions: I was on 4.0.3 built for Mac Arm. Updating to 4.1.0 made the example  from @dswingley work! Happy days.
