### ISSUE TITLE
Unable to install glmmTMB

### ISSUE THREAD

**Issue by iago-pssjd** [glmmTMB/glmmTMB#617]
Hi!,

I am trying to install `glmmTMB` on a 32-bit laptop but when compilation starts it hangs at first instruction. Is 32-bits and obstruction to the package installation? Maybe my `gnu` version? Otherwise, which could be the reason?

I have installed `TMB 1.7.18` and `R 4.0.2` on platform `i686-pc-linux-gnu (32-bit)`.

I have tried with CRAN and github versions with the same result. Next code appears in screen and does anything more:
...
```r
* installing *source* package 'glmmTMB' ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I'/home/minho/R/i686-pc-linux-gnu-library/4.0/TMB/include' -I'/home/minho/R/i686-pc-linux-gnu-library/4.0/RcppEigen/include'    -fpic -g -02 -fdebug-prefix-map=build/r-base-omhSG9/r-base-4.0.2=.  -fstack-protector-strong -Wformat  -Werror=format-security  -Wdate-time  -D_FORTIFY_SOURCE=2  -g   -c glmmTMB.cpp -o glmmTMB.o
```

Thank you!

**Comment by bbolker** [comment]
How long does it hang for? (5 mins? 10 mins? 30 mins?)

Results of `g++ --version` ?

Does `TMB::runExample("randomregression")` work?

**Comment by iago-pssjd** [comment]
It is fully hanged (more than 30 mins). I only can `kill` the R/RStudio process to continue.
```
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
The `TMB::runExample("randomregression")` seems to work.

Thank you!

**Comment by bbolker** [comment]
I'm not sure how much more I'm going to be able to do, unfortunately.  The only ideas  I have are:

* see whether binaries can be built on/retrieved from r-hub?  It doesn't look like they have 32-bit Linux platforms though: https://r-hub.github.io/rhub/articles/rhub.html
* how old is this laptop? Which distribution? https://hackaday.com/2019/07/09/the-saga-of-32-bit-linux-why-going-64-bit-raises-concerns-over-multilib/ ; https://itsfoss.com/32-bit-os-list/ ...

**Comment by iago-pssjd** [comment]
Laptop is around 13 years old. I have recently installed newest Ubuntu distribution supporting 32-bit, so 18.04.

It is not an issue of big importance for me since that computer is not my main tool for work, but I commented it because I believe it would be interesting to know if this is a general problem and in that case which would be the reason (lack of system prerequisite) of it.

Thank you again for the help!

**Comment by bbolker** [comment]
I wonder if we should close this ... I can't think of any way to do further troubleshooting, other than running the offending compilation step  in a terminal and seeing if there is any useful/informative output that's getting swallowed by the R package-building environment ... I guess you could try compiling it at a lower optimization level, e.g. substitute `-O0` for `-O2` and see if that makes a difference?? (Grasping at straws here ...)

```
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I'/home/minho/R/i686-pc-linux-gnu-library/4.0/TMB/include' -I'/home/minho/R/i686-pc-linux-gnu-library/4.0/RcppEigen/include'    -fpic -g -02 -fdebug-prefix-map=build/r-base-omhSG9/r-base-4.0.2=.  -fstack-protector-strong -Wformat  -Werror=format-security  -Wdate-time  -D_FORTIFY_SOURCE=2  -g   -c glmmTMB.cpp -o glmmTMB.o
```

**Comment by iago-pssjd** [comment]
I do not know how should I do to compile the package manually. Download I the source to the libraries location and just compile it with `-00` instead of `-02`? Or should I do something more/different previously? (Is there any guide?)

Thank you!

**Comment by bbolker** [comment]
Yes; start by downloading and unpacking (`tar zxvf ...`) https://cran.r-project.org/src/contrib/glmmTMB_1.0.2.1.tar.gz , then try `R CMD INSTALL glmmTMB` from the parent directory. If this fails in the same way as `install.packages()`, `cd glmmTMB/src` and run the `g++` command there.  Then try substituting `-O0` ...

As far as compilation guides go, try https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Customizing-package-compilation

**Comment by iago-pssjd** [comment]
Thank you!

I will try as soon as possible and let you know.

**Comment by iago-pssjd** [comment]
Finally, I tried using `R CMD INSTALL glmTMB` and also using compilation substituting `-O0` for `-O2` in both cases without success.

Please, feel free to close the issue if nothing more can be done.

Thank you again!

**Comment by bbolker** [comment]
Well, it's not solved, so I don't mind leaving it open in case someone comes along with better ideas ...

**Comment by bbolker** [comment]
Closing.
