### ISSUE TITLE
AR1 models fail to converge

### ISSUE THREAD

**Issue by maxcastorani** [glmmTMB/glmmTMB#623]
I am trying to utilize the first-order autocorrelation [AR(1)] covariance structure abilities of the glmmTMB package to model experimental time series data collected from multiple locations. However, the models consistently fail to converge, with the warning message: In fitTMB(TMBStruc) :  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting').

To diagnose the problem, I created some simulated AR1 data (see code below). However, the failure-to-converge problem persists even when varying the time series length, data distribution and link function, dispersion, zero inflation, and model random effects structure.

Is this a problem with my syntax, a data issue, or a glmmTMB bug? Many thanks for the assistance.

```
# Simulation test of AR(1) time series using glmmTMB

# Install or load packages

#install.packages('bbmle')
#install.packages('dplyr')
#install.packages('ggplot2')
#install.packages('patchwork')
#install.packages('Matrix')
#install.packages('devtools')
#library('devtools')
#devtools::install_github("glmmTMB/glmmTMB/glmmTMB")

library(bbmle)
library(dplyr)
library(ggplot2)
library(glmmTMB)
library(patchwork)

# Set parameters
t = 40       # Length of time series
phi = 0.8    # Amount of autocorrelation
stdev = 0.1  # Standard deviation
eff <- 3    # Effect of a treatment relative to a control

# Simulate data
sim.dat <- expand.grid(time = 1:t,
                      treatment = c("control", "manipulate"),
                      location = c("site1", "site2", "site3", "site4", "site5"))
sim.dat$plot <- paste(sim.dat$location, sim.dat$treatment, sep = "_")

# List description for AR(1) model
ar.sim <- list(order = c(1, 0, 0), ar = phi, sd = stdev)

# Simulate AR(1) data for each plot (= unique combination of location and treatment)
set.seed(1);  ar1.sim_site1.control      <- arima.sim(n = t, model = ar.sim)
set.seed(2);  ar1.sim_site2.control      <- arima.sim(n = t, model = ar.sim)
set.seed(3);  ar1.sim_site3.control      <- arima.sim(n = t, model = ar.sim)
set.seed(4);  ar1.sim_site4.control      <- arima.sim(n = t, model = ar.sim)
set.seed(5);  ar1.sim_site5.control      <- arima.sim(n = t, model = ar.sim)
set.seed(6);  ar1.sim_site1.manipulate   <- arima.sim(n = t, model = ar.sim) + eff
set.seed(7);  ar1.sim_site2.manipulate   <- arima.sim(n = t, model = ar.sim) + eff
set.seed(8);  ar1.sim_site3.manipulate   <- arima.sim(n = t, model = ar.sim) + eff
set.seed(9);  ar1.sim_site4.manipulate   <- arima.sim(n = t, model = ar.sim) + eff
set.seed(10); ar1.sim_site5.manipulate   <- arima.sim(n = t, model = ar.sim) + eff

sim.dat$response <- c(as.vector(ar1.sim_site1.control),
                      as.vector(ar1.sim_site1.manipulate),
                      as.vector(ar1.sim_site2.control),
                      as.vector(ar1.sim_site2.manipulate),
                      as.vector(ar1.sim_site3.control),
                      as.vector(ar1.sim_site3.manipulate),
                      as.vector(ar1.sim_site4.control),
                      as.vector(ar1.sim_site4.manipulate),
                      as.vector(ar1.sim_site5.control),
                      as.vector(ar1.sim_site5.manipulate)
                      )

# Add random noise
set.seed(100)
sim.dat$response <- sim.dat$response + runif(nrow(sim.dat), min = -0.5, max = 0.5)

# Convert simulated data to positive integers for poisson model
sim.dat$response <- round(sim.dat$response * 100) 
sim.dat$response <- sim.dat$response - min(sim.dat$response)
hist(sim.dat$response)

# Plot simulated data
ggplot(data = sim.dat, aes(x = time, y = response, color = treatment)) +
  geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  geom_line() +
  facet_wrap(~ location, ncol = 1, scales = 'fixed')

# Fit models using glmmTMB

# Fixed-effects model, no correlation structure
sim.mod1 <- glmmTMB(response ~ treatment, family = poisson, data = sim.dat)

# Mixed-effect model (random intercept), no correlation structure
sim.mod2 <- glmmTMB(response ~ treatment + (1 | location), family = poisson, data = sim.dat)

# Fixed-effects model, AR(1) correlation structure
sim.mod3 <- glmmTMB(response ~ treatment + ar1(time + 0 | location), family = poisson, data = sim.dat)
# WARNING: Model convergence problem; non-positive-definite Hessian matrix.

# Mixed-effect model (random intercept), AR(1) correlation structure
sim.mod4 <- glmmTMB(response ~ treatment + (1 | location) + ar1(time + 0 | location), family = poisson, data = sim.dat)
# WARNING: Model convergence problem; non-positive-definite Hessian matrix.

AICtab(sim.mod1, sim.mod2, sim.mod3, sim.mod4)

# Calculate and visualize ACF

# Define function
plot.acf.fun <- function(sim.mod){
  sim.dat$resid <- resid(sim.mod, type = "pearson")

  acf.dat <- sapply(unique(sim.dat$location), function(x){
acf(sim.dat$resid[sim.dat$location == x], lag.max = length(unique(sim.dat$time)) / 3, plot = FALSE)$acf
  })

  pacf.dat <- sapply(unique(sim.dat$location), function(x){
pacf(sim.dat$resid[sim.dat$location == x], lag.max = length(unique(sim.dat$time)) / 3, plot = FALSE)$acf
  }
  )

  acf.dat <- data.frame(acf.dat)
  pacf.dat <- data.frame(pacf.dat)

  colnames(acf.dat) <- (unique(sim.dat$location))
  colnames(pacf.dat) <- (unique(sim.dat$location))

  acf.dat <- acf.dat %>%
    dplyr::mutate(lag = 1:nrow(acf.dat) - 1) %>%
    tidyr::gather(key = "location", value = "acf", -lag)

  pacf.dat <- pacf.dat %>%
    dplyr::mutate(lag = 1:nrow(pacf.dat)) %>%
    tidyr::gather(key = "location", value = "pacf", -lag)

  acf.dat <- dplyr::left_join(acf.dat, pacf.dat, by = c("lag", "location"))

  # Calculate critical value (based on the lowest length of time series available)
  acf.dat$crit <- qnorm((1 + 0.95)/2) / sqrt(length(unique(sim.dat[sim.dat$location == "a1", ]$time)))

  # Plot ACF by location
  p1 <- ggplot(data = acf.dat, aes(x = lag, y = acf)) +
    ggtitle("Autocorrelation by location") +
    facet_wrap(~ location) +
    geom_bar(stat = "identity", width = 0.1, color = "black", fill = "black") +
    geom_hline(yintercept = 0) +
    geom_line(aes(y = crit), linetype = "dashed") +
    geom_line(aes(y = -crit), linetype = "dashed") +
    scale_y_continuous(breaks = seq(-10, 10, by = 2)/10, name = "ACF") +
    scale_x_continuous(breaks = 0:max(acf.dat$lag), name = "Lag") +
    theme_classic() +
    theme(aspect.ratio = 1)

  # Plot average PACF
  p2 <- ggplot(data = acf.dat[!is.na(acf.dat$pacf), ], aes(x = lag, y = pacf)) +
ggtitle("Average partial autocorrelation across locations") +
stat_summary(fun.data = mean_cl_boot) +
geom_hline(yintercept = 0) +
geom_line(aes(y = crit), linetype = "dashed") +
geom_line(aes(y = -crit), linetype = "dashed") +
coord_cartesian(ylim = c(-0.4, 1.0)) +
scale_y_continuous(breaks = seq(-1, 1, by = 0.2), name = "PACF") +
scale_x_continuous(limits = c(0.95, max(acf.dat$lag)), breaks = 1:max(acf.dat$lag), name = "Lag") +
    theme_classic() +
    theme(aspect.ratio = 1)

  p1 + p2
}

plot.acf.fun(sim.mod1) # Fixed-effects model, no correlation structure
plot.acf.fun(sim.mod2) # Mixed-effect model (random intercept), no correlation structure
plot.acf.fun(sim.mod3) # Fixed-effects model, AR(1) correlation structure
plot.acf.fun(sim.mod4) # Mixed-effect model (random intercept), AR(1) correlation structure
```

**Comment by bbolker** [comment]
Taking a look ...

**Comment by bbolker** [comment]
Everything seems to work fine if `time` is a factor instead of numeric.  This is stated in the [covstruct vignette](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/vignettes/covstruct.rmd#L110-L112), but it should definitely be documented somewhere easier to find, and tested for!

**Comment by maxcastorani** [comment]
Thank you very much for the rapid reply. 

I assume that in order to capture the AR1 process, you must specify the levels of the time factor in sequential order (e.g., 1, 2, 3, ...) since it would no longer exist as a numeric or integer?

**Comment by bbolker** [comment]
Yes.  If you have a time vector (assumed to be evenly spaced) then just specifying as `factor(time)` should work.  This pull request: https://github.com/glmmTMB/glmmTMB/pull/624 should implement a check that throws an error if a non-factor variable is specified as the time variable in an `ar1()` term

**Comment by rainforest-stat** [comment]
I have the same error in ar1. In my case random factor is 5 locations and the the fixed effect is 'years' which is numeric. how can I run AR1 any suggestion please.

**Comment by mebrooks** [comment]
@rainforest-stat `years` as numeric won't work because it needs to be a factor as bbolker said above.

**Comment by rainforest-stat** [comment]
> @rainforest-stat `years` as numeric won't work because it needs to be a factor as bbolker said above.

Thanks@mebrooks for making it specific, I see the AIC,BIC, but there is still warning 
In FUN(X[[i]], ...) : AR1 not meaningful with intercept.

**Comment by mebrooks** [comment]
@rainforest-stat did you see the example in [the vignette](https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html)? It includes `ar1(times + 0 | group)` so I'm guessing you don't have `+0` in your model. Maybe try `ar1(factor(years) + 0 | location)`

**Comment by rainforest-stat** [comment]
> @rainforest-stat did you see the example in [the vignette](https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html)? It includes `ar1(times + 0 | group)` so I'm guessing you don't have `+0` in your model. Maybe try `ar1(factor(years) + 0 | location)`

@mebrooks, thank you so much. But I would like to see the "location" as random variable and its effects on "years" which is fixed variable. then should it be like: 'ar1(Location| Year)

**Comment by mebrooks** [comment]
@rainforest-stat this is the wrong place to ask. Please see [where to ask questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions)

Regardless, the error message is telling you to add `+0` as in the example.

**Comment by rainforest-stat** [comment]
@mebrooks, thank you it makes sense, sorry for repetitive questions

**Comment by bbolker** [comment]
FWIW as far as I can see `ar1(0 + factor(Year)|Location)` is indeed what you want: this allows the response to vary by year in a way that is AR1-correlated within locations, and independent across locations. In many cases you would also want to include a *separate* `(1|Location)` random effect (time-independent/"nugget" variation across locations)

**Comment by rainforest-stat** [comment]
@bbolker , thank you, my models is: 
glmmTMB(log(Y) ~ Year  + (1|locations) + ar1(locations|Year), data = DF), I wanted to see the "year" as fixed effects. but when I run the model, the performance of the model doesn't show conditional r square.
And again if my convert "year"it to factor, does it have any changes on the model estimates.

**Comment by bbolker** [comment]
I shouldn't have responded here; please see the note by @mebrooks above; you should probably ask this question on `r-sig-mixed-models@r-project.org`

**Comment by rainforest-stat** [comment]
> I shouldn't have responded here; please see the note by @mebrooks above; you should probably ask this question on `r-sig-mixed-models@r-project.org`

Hi Ben, this is wrong place to ask, but I have always error with "Warning message:
In FUN(X[[i]], ...) : AR1 not meaningful with intercept". thank you again for your response

**Comment by bbolker** [comment]
So don't ask here! :-) Feel free to ask on `r-sig-mixed-models@r-project.org`.

**Comment by bbolker** [comment]
an appropriate warning about non-factor-valued time variables was added in 6cb3b53babe7
