### ISSUE TITLE
Error when predicting with an offset term and no fixed effects specified

### ISSUE THREAD

**Issue by fxdlmatt** [glmmTMB/glmmTMB#625]
When calling `predict` on a fit with an `offset` and no specified fixed effects, I'm getting an error.  If I add a fixed effect or even explicitly add the intercept to the formula, everything seems fine.

```
owls_nb1 <- glmmTMB(SiblingNegotiation ~ offset(log(BroodSize)),
              family = nbinom2(),
              data=Owls)

owls_nb2 <- glmmTMB(SiblingNegotiation ~ 1 + offset(log(BroodSize)),
              family = nbinom2(),
              data=Owls)

predict(owls_nb1)
predict(owls_nb2)
````

```
> predict(owls_nb1)
Error in for (o in extractForm(fixedform, quote(offset))) { : 
  invalid for() loop sequence
```

I'll try to look into it in more detail over the weekend.

Thanks,

--Matt

**Comment by bbolker** [comment]
Thanks, will take a look. (This kind of edge case doesn't really surprise me ...)
