### ISSUE TITLE
Pairwise comparisons with emmeans of a negative binomial

### ISSUE THREAD

**Issue by TristanDJGraham** [glmmTMB/glmmTMB#628]
Hi,

Question 1) Am I appropriately doing the pairwise comparisons?
Question 2) Why is the Sidak method used for the emmeans? Should I instead use adjust = "none" for these?

Context:
I have a negative binomial looking at the effect of three treatments on count data:
`M1a <- glmmTMB(data = A, n ~ Treatment, family = nbinom2, ziformula = ~0)`

I'd like to compare the means of each treatment with one another:
`emmeans(M1a, pairwise ~ Treatment, adjust = "tukey", type = "response")`

This produces the following output:

```
$emmeans
 Treatment response   SE df lower.CL upper.CL
 C             9.96 1.56 14     6.51     15.2
 E             9.31 1.46 14     6.08     14.2
 A             6.78 1.08 14     4.41     10.4

Confidence level used: 0.95 
Conf-level adjustment: sidak method for 3 estimates 
Intervals are back-transformed from the log scale 

$contrasts
 contrast ratio    SE df t.ratio p.value
 C / E     1.07 0.237 14 0.304   0.9505 
 C / A     1.47 0.328 14 1.726   0.2305 
 E / A     1.37 0.307 14 1.422   0.3568 

P value adjustment: tukey method for comparing a family of 3 estimates 
Tests are performed on the log scale 
```

I was using the Tukey adjustment as that's what I understood the emmeans vignette on "confidence-intervals" to be recommending. I assume this is correcting for two probability distributions (eg. treatment "C" and treatment "E").
I notice though that after the means estimation table it says the Sidak method was used for CI adjustment.

**Comment by bbolker** [comment]
Hi Tristan,  this is not the right venue for this question - please see https://github.com/glmmTMB/glmmTMB#where-to-ask-questions .  It's not specifically a glmmTMB question *or* a mixed-model question; [CrossValidated](https://stats.stackexchange.com) might be a good choice.
