### ISSUE TITLE
Error when attempting to run command bootMer in a glmmTMB model at a computer cluster

### ISSUE THREAD

**Issue by juan-duenas** [glmmTMB/glmmTMB#629]
Good Morning,

This is probably a silly issue, so my apologies if this is not the rigth forum for it. I get an error mesage when I attempt to run command lme4::bootMer in an R session within a high performace computer cluster. The error reads:

> Error in registerFinalizer(Fun, DLL) :   could not find function "registerFinalizer" 

This command works fine in my home computer, but I need to run it in a HCP because I want to do 10K bootstraps to obtain C.I.s of my model predictions. I suspect the error apears because there is maybe a conflict between the package versions I have in my computer versus those available at the cluster. Below is my own session info:

>  R version 3.6.3 (2020-02-29)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.7 LTS
> 
> Matrix products: default
> 
> BLAS:   /usr/lib/libblas/libblas.so.3.6.0
> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
>  [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
> [10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] glmmTMB_1.0.2.1 lme4_1.1-23     Matrix_1.2-18  
> 
> loaded via a namespace (and not attached):
>  [1] minqa_1.2.4     MASS_7.3-53     compiler_3.6.3  tools_3.6.3     TMB_1.7.18      Rcpp_1.0.5     
>  [7] splines_3.6.3   nlme_3.1-149    grid_3.6.3      nloptr_1.2.2.2  boot_1.3-25     statmod_1.4.34 
> [13] lattice_0.20-41

And the following is the session info of the R version available at the cluster:

> R version 4.0.0 (2020-04-24)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS/LAPACK: /trinity/shared/easybuild/software/OpenBLAS/0.3.9-GCC-9.3.0/lib/libopenblas_skylakexp-r0.3.9.so
> 
> Random number generation:
>  RNG:     Mersenne-Twister 
>  Normal:  Inversion 
>  Sample:  Rounding 
>  
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] glmmTMB_1.0.1 lme4_1.1-23   Matrix_1.2-18 dplyr_0.8.5  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.4.6     TMB_1.7.16       magrittr_1.5     splines_4.0.0   
>  [5] MASS_7.3-51.6    tidyselect_1.0.0 statmod_1.4.34   lattice_0.20-41 
>  [9] R6_2.4.1         rlang_0.4.5      minqa_1.2.4      grid_4.0.0      
> [13] nlme_3.1-147     ellipsis_0.3.0   assertthat_0.2.1 tibble_3.0.1    
> [17] lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4      nloptr_1.2.2.1  
> [21] vctrs_0.2.4      glue_1.4.0       compiler_4.0.0   pillar_1.4.3    
> [25] boot_1.3-25      pkgconfig_2.0.3 

Any help on regards of this issue is appreciated. 

Best Regards,

Juan

**Comment by juan-duenas** [comment]
Solved. It was a conflict between the packages. I installed the latest versions of glmmTMB, TMB, lme4, and Matrix on my local package library and now it runs.

**Comment by bbolker** [comment]
Thanks for sorting that out so we didn't have to!
