### ISSUE TITLE
Convergence in glmmTMB but not glmer

### ISSUE THREAD

**Issue by dwright441** [glmmTMB/glmmTMB#633]
Hello, 
I'm having convergence issues when using glmer in lme4, but not glmmTMB. I'm running a series of generalized linear mixed effect models with poisson distribution for ecological count data. I've included a random effect of site (n = 26) in each model.

The coefficient estimates of models run in glmer and glmmTMB are very similar, but models run in glmer are having convergence issues. Any advice would be appreciated, as I'm not sure if I can rely on my results from glmmTMB.

Here's an example of outputs from glmmTMB vs glmer:

-----glmmTMB------
[glmmTMBSummary.txt](https://github.com/glmmTMB/glmmTMB/files/5410135/glmmTMBSummary.txt)

----------------------

-----glmer------
[glmerSummary.txt](https://github.com/glmmTMB/glmmTMB/files/5410140/glmerSummary.txt)

**Comment by bbolker** [comment]
This would be a great question for `r-sig-mixed-models@r-project.org` (don't forget to subscribe to the mailing list first) ...  https://github.com/glmmTMB/glmmTMB#where-to-ask-questions
