### ISSUE TITLE
[Question] Is it possible to extract the printed correlations from VarCorr()["cond"]

### ISSUE THREAD

**Issue by Dekermanjian** [glmmTMB/glmmTMB#636]
I have been searching for a way to extract only the correlation matrix from the VarCorr()["cond"] print output. I have tried `print(VarCor()["cond"], comp = "correlation")`, but that does not work. Is there any way to extract these correlations?
Any help is appreciated, thank you.

**Comment by bbolker** [comment]
This is probably better for `r-sig-mixed-models@r-project.org` (see https://github.com/glmmTMB/glmmTMB#where-to-ask-questions ), but: running `str(VarCorr(.))` shows you what the components of the underlying object are: 

```
data("sleepstudy",package="lme4")
m4 <- glmmTMB(Reaction~Days+ (Days|Subject), sleepstudy)
attr(VarCorr(m4)$cond$Subject,"correlation")
```

ideally there would be an option to the print method, but in the meantime ...
