### ISSUE TITLE
Analogue to glm.nb()/glmer.nb()

### ISSUE THREAD

**Issue by bwiernik** [glmmTMB/glmmTMB#641]
Would it be possible to add a function analogous to glm.nb() or glmer.nb() to estimate the theta parameter within a glmmTMB() model, rather than requiring it to be specified as a fixed parameter?

**Comment by bbolker** [comment]
I'm confused.  I think it is estimated?

```r
library(MASS)
library(glmmTMB)
m1 <- glm.nb(Days ~ Sex/(Age + Eth*Lrn), data = quine)
m2 <- glmmTMB(Days ~ Sex/(Age + Eth*Lrn), data = quine, family=nbinom2)
m1$theta
## [1] 1.597991
sigma(m2)
## [1] 1.597986
```
Not identical, but obviously estimating the same thing ...

**Comment by bwiernik** [comment]
Oh, sorry, I was misreading the source of nbinom2; was thinking that it just used a value of "one" always if missing. And think I crossed my results from nbinom1/nbinom2. Sorry.
