### ISSUE TITLE
Anova(model, type = "III", component = "zi") problem

### ISSUE THREAD

**Issue by ldharder** [glmmTMB/glmmTMB#642]
Hi,

I've encountered a problem (and inconsistency) with Anova testing of fixed effects for the zero-inflated component of a fitted model (Tweedie distribution).  Fixed effects in the analysis in question involve two categorical factors, trt (3 levels) and colour (2 levels).  The summary() of the fixed effects is 

> Conditional model:
>              Estimate Std. Error z value Pr(>|z|)    
> (Intercept)   4.26604    0.04988   85.53  < 2e-16 ***
> trt1         -0.21970    0.03073   -7.15 8.75e-13 ***
> trt2          0.02255    0.02964    0.76   0.4468    
> colour1      -0.10311    0.04973   -2.07   0.0381 *  
> trt1:colour1 -0.02086    0.03061   -0.68   0.4956    
> trt2:colour1 -0.03986    0.02968   -1.34   0.1792    
> 
> Zero-inflation model:
>              Estimate Std. Error z value Pr(>|z|)    
> (Intercept)  -10.7097     1.3556  -7.900 2.78e-15 ***
> trt1           2.8360     0.7114   3.986 6.71e-05 ***
> trt2          -1.5226     0.8090  -1.882   0.0598 .  
> colour1        1.0833     0.7434   1.457   0.1450    
> trt1:colour1  -1.1803     0.6115  -1.930   0.0536 .  
> trt2:colour1   1.6519     0.8012   2.062   0.0392 * 

Note that the test probabilities for colour are 0.0381 and 0.145 for the conditional and zero-inflation components, respectively.

The problem is that Anova calls for each component produce identical results:

> > Anova(PR_full_zi1, type = "III", component = "cond")
> Analysis of Deviance Table (Type III Wald chisquare tests)
> Response: sds
>                 Chisq Df Pr(>Chisq)    
> (Intercept) 7315.6516  1    < 2e-16 ***
> trt           63.9480  2    1.3e-14 ***
> colour         4.2993  1    0.03813 *  
> trt:colour     4.5322  2    0.10371    
> 
> > Anova(PR_full_zi1, type = "III", component = "zi")
> Analysis of Deviance Table (Type III Wald chisquare tests)
> Response: sds
>                 Chisq Df Pr(>Chisq)    
> (Intercept) 7315.6516  1    < 2e-16 ***
> trt           63.9480  2    1.3e-14 ***
> colour         4.2993  1    0.03813 *  
> trt:colour     4.5322  2    0.10371

Note that test probabilities for colour in both cases are 0.0381, which is identical to the summary() result for the conditional model.  Thus, the Anova call for component = "zi" produces results for the conditional model, rather than for the zero-inflated model.

This problem does not occur for type="II" tests:

> > Anova(PR_full_zi1, type = "II", component = "cond")
> Analysis of Deviance Table (Type II Wald chisquare tests)
> Response: sds
>              Chisq Df Pr(>Chisq)    
> trt        64.5327  2  9.703e-15 ***
> colour      4.1015  1    0.04285 *  
> trt:colour  4.5322  2    0.10371    
> 
> > Anova(PR_full_zi1, type = "II", component = "zi")
> Analysis of Deviance Table (Type II Wald chisquare tests)
> Response: sds
>              Chisq Df Pr(>Chisq)   
> trt        12.4646  2   0.001965 **
> colour      0.0154  1   0.901379   
> trt:colour  4.7478  2   0.093119 . 

Nor does it occur for emmeans comparisons for colour:

> > emmeans(PR_full_zi1, ~colour, component = "cond")
>  colour   emmean         SE  df lower.CL upper.CL
>  pink   4.162933 0.06822901 748 4.028990 4.296877
>  red    4.369157 0.07256781 748 4.226696 4.511617
> 
> > emmeans(PR_full_zi1, ~colour, component = "zi")
>  colour    emmean       SE  df  lower.CL  upper.CL
>  pink    -9.62641 1.268765 748 -12.11717 -7.135647
>  red    -11.79309 1.780715 748 -15.28888 -8.297295

Suggestions for a solution would be greatly appreciated.

**Comment by bbolker** [comment]
I think this should be fixed in af2749e15b81f .  If you have the capability (development tools/compilers/etc. installed), can you try `remotes::install_github("glmmTMB/glmmTMB/glmmTMB@fix_Anova_comp")` and see if your problem is resolved?

**Comment by ldharder** [comment]
glmmTMB@fix_Anova_comp does provide different results for component = "cond" and component = "zi", as advertised.  When do you foresee this becoming the public version?  

Thanks for the fix.

**Comment by bbolker** [comment]
Do you mean merged into the master branch, or on CRAN? We haven't had a release for a while yet, so we should do it fairly soon, but I wouldn't expect a new version on CRAN sooner than a few weeks from now at the earliest ...
