### ISSUE TITLE
Permission to use code in another program

### ISSUE THREAD

**Issue by marksorel8** [glmmTMB/glmmTMB#645]
Hello @mebrooks, @bbolker, @arni-magnusson, @skaug, @fishfollower, @casperwberg, @kaskr, @mmaechler, and @koenvanbenthem,

My name is Mark Sorel and I'm a Ph.D. student at the University of Washington School of Aquatic and Fishery Sciences. I am writing to ask for your permission to (attempt to) use portions of the `glmmTMB` source code to implement glmm's for parameters in a multistate Cormack-Jolly-Seber model of survival and maturation age of an endangered Chinook salmon population in the Wenatchee River. I do plan to attempt to publish my results in a peer-reviewed journal and make the code used for the analysis publicly available. I would apply the GNU Affero General Public License to my code to be compliant with the License for glmmTMB, and I would provide attribution both in the paper and within the code.

If I were to be successful and there was interest, I would be happy to contribute some sort of "hidden Markov model distribution" for analyzing mark-release-recapture data with glmmTMB, or perhaps this would be better suited for contribution to a different package such as [marked](https://cran.r-project.org/web/packages/marked/index.html) at some point. 

Thank you very much for considering my request, as well as for this very useful package and it's documentation. 

Sincerely,
Mark

**Comment by bbolker** [comment]
FWIW this question is only really relevant to people marked as "aut" (authors) rather than "ctb" (contributors) in the DESCRIPTION file (i.e. "only" the first 9 in your list).

Fine with me. (As I pointed out to @marksorel8 in e-mail, it's not actually *necessary* to ask for permission to re-use - the current license allows this automatically provided the copied/modified code is distributed in a way compliant with the license.)

**Comment by marksorel8** [comment]
Ahhhh, I have actually been wondering what those [aut] and [ctb] etc. tags were after folks' names. Thanks @bbolker for clearing that up for me :) I've taken the others off.

**Comment by koenvanbenthem** [comment]
Also fine with me. I assume (with 95% certainty) that you are aware that Jeff Laake has also included the option of using TMB and some optimize to fit certain capture mark recapture models in the marked package - but wanted to mention this just in case you didn't know.

**Comment by marksorel8** [comment]
Totally @koenvanbenthem! I might be able to do everything that I want with 'marked' and might go down that road, but I also might work on something that is very specific to my needs but might be a little faster. I'm not sure yet. I'm definitely drawing lots of inspiration (and data-processing functions) from `marked` / `rmark` though, so I plan to chat with Jeff Laake and Devin Johnson, and cite them as well. Thanks!

**Comment by bbolker** [comment]
I'm going to say you should just go ahead, and I will close this issue. If others feel it's worth re-opening the issue, go ahead ...
