### ISSUE TITLE
Can glmmTMB handle exact 1 values for beta analysis?

### ISSUE THREAD

**Issue by mariam637** [glmmTMB/glmmTMB#660]
Hello, 

I tried running a glmmTMB model on my data set and got the following error message:

Error in eval(family$initialize) : y values must be 0 <= y < 1

I was able to specify zero-inflation but not one inflation I and just wanted to confirm there is no way that glmmTMB can analyse data sets containing 1s? I have  managed to run models when I have changed the values of 1 to the max non-one value and arbitrarily 0.995 but these methods seem hackish and yield different patterns in the data.

Any help will be greatly appreciated.

Thank you.

**Comment by bbolker** [comment]
Yes, we haven't implemented "zero-one inflation" (it would be possible to implement, but would require more special machinery; zero-inflation is more generally useful since it applies to count distributions such as Poisson and NB as well). The `brms` package handles zero-one-inflated Beta responses (but will expose you the ~horrors~ joys of Bayesian data analysis via MCMC ...)

**Comment by mariam637** [comment]
Thank you very much for your response. I will have a look into other options

**Comment by mariam637** [comment]
Thank you very much for your additional advice. I think I will definitely give it a go on my data. If it's not too much trouble I would very much appreciate an example

**Comment by bbolker** [comment]
This is very quick, may have mistakes, but should give the general idea:

```r
library(glmmTMB)
set.seed(101)

## Start by showing that zero-inflated beta is equivalent to binomial + beta ...
n <- 100
dd1 <- data.frame(x=runif(n))

## Beta distrib parameterized by mean and dispersion
## copied from emdbook:::rbetabinom
rbeta_mean <- function(n,prob, theta) {
    shape1 <- theta * prob
    shape2 <- theta * (1 - prob)
    return(rbeta(n, shape1, shape2))
}

dd1$y <- ifelse(runif(n)<0.2,0,rbeta_mean(n,plogis(-1+2*dd1$x),theta=10))
plot(dd1$x,dd1$y)


mod1 <- glmmTMB(y~x, ziformula=~1, data=dd1, family=beta_family())
(ff1 <- fixef(mod1))
plogis(ff1$zi)

## zero-infl beta as hurdle model
mod2A <- glmmTMB((y==0) ~ 1, data=dd1, family=binomial)
mod2B <- glmmTMB(y ~ x, data=subset(dd1, y>0), family=beta_family)
fixef(mod2A)
fixef(mod2B)

## zero-one inflated data
r <- runif(n)
dd2 <- dd1
dd2$y <- ifelse(r<0.2,0,
                ifelse(r>0.8,1,
                       rbeta_mean(n,plogis(-1+2*dd1$x),theta=10)))
mod3A <- glmmTMB((y==0) ~ 1, data=dd2, family=binomial)
mod3B <- glmmTMB(y ~ x, data=subset(dd1, 0<y & y<1), family=beta_family)
mod3C <- glmmTMB((y==1) ~ 1, data=dd2, family=binomial)
```

**Comment by mariam637** [comment]
Thank you very, very much for your example and all your help
