### ISSUE TITLE
confint.glmmTMB does not work for models which have a dispersion formula defined.

### ISSUE THREAD

**Issue by AndreMBellve** [glmmTMB/glmmTMB#661]
I keep hitting an error when I try to use `confint` on a `glmmTMB` model which includes a dispersion parameter. I have seen on CRAN documentation for a `confint.glmmTMB` but I was wondering if it has been extended to include models with a dispersion formula .Below is a toy example but the same thing happens when I try to calculate confidence intervals with models based on other data.
```
data(cbpp, package = "lme4")

 bovine <- glmmTMB(cbind(incidence, size-incidence) ~ (1|herd),
                   family=betabinomial, dispformula = ~period, data=cbpp)

confint(bovine)
## Error in dimnames(x) <- dn : 
##   length of 'dimnames' [2] not equal to array extent


m2 <- glmmTMB(count ~ spp + mined + (1|site),
              zi=~spp, dispformula = ~mined,
               family=nbinom2, data=Salamanders)
confint(m2)
## Error in dimnames(x) <- dn : 
##  length of 'dimnames' [2] not equal to array extent
```
Am I doing something wrong? Or is it not possible to calculate intervals when you have dispersion parameters?
Any insights into the matter are greatly appreciated!

Cheers,
André

**Comment by bbolker** [comment]
This is the same as #571 , which is fixed in the development version (fixed as of Aug 2020).

If you have development tools (compilers etc.) installed you can `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")`. Otherwise, can you try `install.packages("glmmTMB", repos="https://glmmTMB.github.io/repos")` and see how it goes ... ?

**Comment by AndreMBellve** [comment]
Thank you for the prompt response and sorry for not more carefully searching known issues. That resolved the issue!
