### ISSUE TITLE
Analysis of explanatory variables at two levels

### ISSUE THREAD

**Issue by HParkUBC** [glmmTMB/glmmTMB#663]
I have drivers (or explanatory variables) at two different levels (e.g., level 1: survey participants, level2: organizations of survey participants) and wonder if and how GLMMtmb analyses the relationships between explanatory variables at two different levels and outcome variables. I have been reading documents on GLMMtmb but I have not found good descriptions yet. 

Thank you for your help!

**Comment by bbolker** [comment]
This would be a good question for the `r-sig-mixed-models@r-project.org` mailing list (when in doubt see ["Where to ask"](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions)); you should probably subscribe to the list first [here](https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models).
