### ISSUE TITLE
Question about QAIC of glmmtmb

### ISSUE THREAD

**Issue by hobbitish1028** [glmmTMB/glmmTMB#675]
I want to calculate the QAIC of glmmtmb with quasi poisson family. For glmmtmb, there are two models (quasi Poisson model and zero logistic model), when calculating the QACI, we should divide the likelihood of quasi Poisson model by over-dispersion parameter phi only and keep the likelihood of logistic model unchanged. Is it correct? I noticed that you just divided the whole likelihood by phi.

**Comment by bbolker** [comment]
We need a little more context please.  Are you referring to an example in a vignette or ?? Some confusions/comments on my part:

- base glmmTMB doesn't offer quasi-likelihood families
- what is a "zero logistic model" ?  Are you talking about a zero-inflated logistic regression (binomial family) or ... ?

For what it's worth, glmmTMB offers overdispersed alternatives for most of the distributions you would want (Poisson → nbinom1, nbinom2; binomial → beta-binomial) so I can't really see why you'd need quasi-likelihood approaches anyway ... ?

**Comment by hobbitish1028** [comment]
Thanks for your response!
The "quasi poisson" I meant is "nbinom1" in glmmTMB, which is a quasi Poisson model with assumption "v = lambda * phi"; the "zero logistic model" is "zero inflated logistic regression of binomial family". Sorry for the confusion.

I want to generate the QAIC, but in your QAIC function "AICc" code, I found you just divide the whole likelihood by over dispersion parameter phi. I think it should be 

QAIC =- 2 * log likelihood of zero inflates logistic regression  - 2 *  (log likelihood of quasi poisson model / phi) + 2*p  
rather than 
QAIC =( - 2 * log likelihood of zero inflates logistic regression  - 2 *  log likelihood of quasi poisson model / phi) + 2*p  

Is that right? Thanks for your reading!

**Comment by bbolker** [comment]
It's confusing, but `nbinom1` is **not** a quasi-likelihood model; it happens to happen to have the same mean and variance as the quasi-Poisson model, but it is not quasi-, and you shouldn't try to compute QAIC for it (that would be double-counting the effect of the dispersion parameter). Just use the log-likelihood/AIC (or whatever) that the built-in methods give you.
