### ISSUE TITLE
summary() may not work if parameters are fixed via map

### ISSUE THREAD

**Issue by florianhartig** [glmmTMB/glmmTMB#678]
This emerged here https://github.com/florianhartig/DHARMa/issues/265, reproducible example:

```
df1 <- data.frame(production=c(15,12,10,9,6,8,9,5,3,3,2,1,0,0,0,0), 
                  Treatment_Num=c(1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4), 
                  Genotype=c(1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2))

tpow_link <- function(x) { qlogis(x-1) }
df1_tweedie <- glmmTMB(production ~ Treatment_Num +(1|Genotype),
                       data = df1,
                       family=glmmTMB::tweedie(link="log"),
                       map=list(thetaf=factor(NA)),
                       start = list(thetaf=tpow_link(1.9)))

summary(df1_tweedie)

#Error in if (length(nameList) >= w) { : 
#  missing value where TRUE/FALSE needed
```

**Comment by bbolker** [comment]
TMB folks (@kaskr, @fishfollower , @arni-magnusson , @mebrooks ): is there an obvious idiom for reconstructing the full parameter vector including parameters that were "mapped" (held fixed during optimization)? (I poked around a little bit but didn't find an obvious answer so far ...)

**Comment by bbolker** [comment]
Does this look a reasonable approach?

```
allpars <- function(x) {
    uu <-unlist(x$obj$env$parList())
    ## unlist() makes names unique by adding indices - we probably don't want them
    ## glmmTMB parameters will never end with numeric values ...
    names(uu) <- gsub("[0-9]+$","",names(uu))
    return(uu)
}
```

**Comment by bbolker** [comment]
I have a basic fix for this in the `map_summary_fix` branch.

- [ ] write tests
- [ ] stress-test: other situations with mapping, particularly where *all* of the elements in a given parameter are mapped?
- [ ] add printing of Tweedie power (and/or more generic additional shape parameters?) to summary
- [ ] combine new util (`get_pars`) with map-restoring machinery in `vcov.glmmTMB` ? or `getParameters` ?
