### ISSUE TITLE
|| syntax is broken

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#689]
```r
library(glmmTMB)
data("sleepstudy", package="lme4")
glmmTMB(Reaction ~ 1 + (Days || Subject), sleepstudy)
## Error in mapply(parFun, covCode, blksize, blkrank, SIMPLIFY = FALSE) : 
##   zero-length inputs cannot be mixed with those of non-zero length
```

This is probably a side effect of the changes to implement rank-reduced models? Not sure how `||` is handled at the moment, but it would probably be best to make it an exact synonym (i.e., semantic replacement/transformation) for `diag()`, i.e. `(a||b)` gets automatically transformed to `diag(a|b)` before any further processing ...

**Comment by mebrooks** [comment]
I just came across this when looking at #686. I'll admit that I don't actually know what `||`is supposed to become. I've never found "nested" `(1|x/y)`syntax useful, so I was prejudiced against this new one. I tried to look it up, but it isn't on the [GLMM FAQ page](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#model-specification). Should this be added there?

**Comment by bbolker** [comment]
Interesting that it's not in the GLMM FAQ - I agree that it would be good to add it for completeness, although actually it's *not* frequently asked about in my experience - I guess people either read the `lmer` docs (below) or learn about it from somewhere like Barr (2013)'s "keep it maximal" paper.

> Two  vertical bars (‘||’) can be used to specify multiple uncorrelated random effects for the same grouping variable.
 (Because of the way it is implemented, the ‘||’-syntax _works only for design matrices containing numeric (continuous) predictors_; to fit models with independent categorical effects, see ‘dummy’ or the ‘lmer_alt’ function from the ‘afex’ package.)

As mentioned above, in glmmTMB `f || g` is a synonym for `diag(f|g)`.

**Comment by bbolker** [comment]
Addressed by https://github.com/glmmTMB/glmmTMB/pull/736

**Comment by bbolker** [comment]
fixed by https://github.com/glmmTMB/glmmTMB/pull/736
