### ISSUE TITLE
odd error from str() applied to sdreport 

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#692]
This might belong in a TMB venue, but: if `sdr` is an `sdreport` object

```
class(sdr)
## [1] "sdreport"
str(sdr)
## List of 10
## Error in match.arg(what, opts) : 
##   'arg' should be one of “Estimate”, “Std. Error”
```

Obviously `str()` (a built-in R command) is somehow trying to access some component of `sdr` in a way it doesn't like ...?

**Comment by mmaechler** [comment]
hmm... I'm pretty sure `str()` will be relying on either `format()` or `print()`  and they give the error -- as  you know -- showing `traceback()` wd have told more.   Otherwise, how do I get the `sdr` object?

**Comment by kaskr** [comment]
@bbolker I can't reproduce this problem:

```r
example(glmmTMB)
str(m1$sdr)
```

```
List of 10
 $ value          : num(0) 
 $ sd             : num(0) 
 $ cov            : logi[0 , 0 ] 
 $ par.fixed      : Named num [1:5] 0.0879 1.1419 1.1393 -1.7361 -1.2728
  ..- attr(*, "names")= chr [1:5] "beta" "beta" "betazi" "betazi" ...
 $ cov.fixed      : num [1:5, 1:5] 0.0542 -0.0533 0.0347 -0.0337 -0.0445 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:5] "beta" "beta" "betazi" "betazi" ...
  .. ..$ : chr [1:5] "beta" "beta" "betazi" "betazi" ...
 $ pdHess         : logi TRUE
 $ gradient.fixed : num [1:5] -0.000102 -0.000209 -0.000199 -0.000121 0.000055
 $ par.random     : Named num [1:23] -0.00215 0.08188 0.03693 0.42098 0.14053 ...
  ..- attr(*, "names")= chr [1:23] "b" "b" "b" "b" ...
 $ diag.cov.random: num [1:23] 0.0181 0.0186 0.0217 0.0167 0.0188 ...
 $ env            :<environment: 0x55e24a362fb8> 
 - attr(*, "class")= chr "sdreport"
```

**Comment by bbolker** [comment]
Hmmm.

Here's my `traceback()` for @kaskr's example:

```r
traceback()
8: stop(gettextf("'arg' should be one of %s", paste(dQuote(choices), 
       collapse = ", ")), domain = NA)
7: match.arg(what, opts)
6: as.list.sdreport(X)
5: as.list(X)
4: vapply(object, typeof, "")
3: "promise" %in% (oTypes <- vapply(object, typeof, ""))
2: str.default(m1$sdr)
1: str(m1$sdr)
```

So we can get there faster via `TMB:::as.list(sdreport(m1$obj))`. Will keep digging (TMB 1.7.20, R-devel SVN 80240). 

Fails in particular [here](https://github.com/kaskr/adcomp/blob/master/TMB/R/sdreport.R#L503); it looks like calling `TMB:::as.list.sdreport()` without specifying `what` fails ... ? 

Stopping for now.

**Comment by bbolker** [comment]
More specifically:

```r
vapply(TMB::sdreport(m1$obj), typeof, "")
```

which first appears in [this R commit 4 months ago](https://github.com/wch/r-source/commit/586c888744b67db63b84cf6637e4e294534cdc28) (SVN 79833)

As far as I can tell it would be nice if `as.list.sdreport()` returned something sensible when `what` is not specified ... ?  (Even returning NULL might be OK ...)

**Comment by mmaechler** [comment]
> More specifically:
> 
> ```r
> vapply(TMB::sdreport(m1$obj), typeof, "")
> ```

> As far as I can tell it would be nice if `as.list.sdreport()` returned something sensible when `what` is not specified ... ? (Even returning NULL might be OK ...)

Definitely:   `is.list(.)` is TRUE;  hence  `str(.)`   must really be allowed to ask for `typeof(.)` of each list component via `vapply()`.
If something like that fails, I claim the  class has not been properly implemented...

**Comment by bbolker** [comment]
OK, I think this should be migrated to TMB. @kaskr, do you agree?

**Comment by kaskr** [comment]
Seems reasonable.
