### ISSUE TITLE
I got warning and cannot run glmmtmb but the same dataset works for function zeroinfl

### ISSUE THREAD

**Issue by nichalala** [glmmTMB/glmmTMB#693]
I want to run Spatial zero-inflated negative binomial regression model. So I planned to use run spatial correlation from glmtmb package but I found problems:

When running with function zeroinfl, the model works fine

zinbz <- zeroinfl(driver~zone+pop+market+depstore+religious+med+edu+res+conv+busstop+busline+rail+pier+transit+dist_sta+RL_motorway+RL_trunk+RL_primary+RL_secondary+RL_tertiary+RL_residential+RL_track+RL_footway+RL_livingstreet|pop+market+religious+med+edu+res+conv+busstop+busline+RL_motorway+RL_trunk+RL_primary+RL_secondary+RL_tertiary+RL_residential+RL_track+RL_footway+RL_livingstreet, data=wingrid, dist="negbin")

but when running with glmmTMB, I got warning:
Warning messages:
1: In fitTMB(TMBStruc) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
2: In fitTMB(TMBStruc) :
  Model convergence problem; function evaluation limit reached without convergence (9). See vignette('troubleshooting')

here is my code:

zinb_glmm <- glmmTMB(driver~zone+pop+market+depstore+religious+med+edu+res+conv+busstop+busline+rail+pier+transit+dist_sta+RL_motorway+RL_trunk+RL_primary+RL_secondary+RL_tertiary+RL_residential+RL_track+RL_footway+RL_livingstreet+(1|null), zi=~pop+market+religious+med+edu+res+conv+busstop+busline+RL_motorway+RL_trunk+RL_primary+RL_secondary+RL_tertiary+RL_residential+RL_track+RL_footway+RL_livingstreet, data=wingrid, family=nbinom2)

wingrid is my data
null is column with value of 1 for all rows

What should I do?

**Comment by mebrooks** [comment]
This question would be better for R-sig-mixed. See [where to ask questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions).

Your model is probably too complicated. You might not need the zero-inflation part. First I would say try it without the `zi` model and then check residuals with [DHARMa](https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html).

You could get some guidance if you copy and paste `vignette('troubleshooting')` into your R console.

**Comment by mebrooks** [comment]
Also, I just noticed "null is column with value of 1 for all rows". This random effect doesn't make sense. Seek help.
