### ISSUE TITLE
Matrix Incompatibility

### ISSUE THREAD

**Issue by delucalab** [glmmTMB/glmmTMB#694]
I am a fairly new RStudio using Version 1.2.5033 on macOS Mojave. I've tried to install and load the glmmTMB package with the following code:

install.packages("glmmTMB") 
library(glmmTMB)

I then receive the following error:

Warning message:
In checkMatrixPackageVersion() : Package version inconsistency detected.
TMB was built with Matrix version 1.3.2
Current Matrix version is 1.3.3
Please re-install 'TMB' from source using install.packages('TMB', type = 'source') or ask CRAN for a binary version of 'TMB' matching CRAN's 'Matrix' package

I've tried following the recommendation to install from source and get the following error:

clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/waldmanad/Library/R/3.6/library/Matrix/include" -I"/Users/waldmanad/Library/R/3.6/library/RcppEigen/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c external_metis.c -o external_metis.o
clang: error: unsupported option '-fopenmp'
make: *** [external_metis.o] Error 1
ERROR: compilation failed for package ‘TMB’
* removing ‘/Users/waldmanad/Library/R/3.6/library/TMB’
* restoring previous ‘/Users/waldmanad/Library/R/3.6/library/TMB’
Warning in install.packages :
  installation of package ‘TMB’ had non-zero exit status

Any help you can provide would be much appreciated.

**Comment by bbolker** [comment]
Any luck/update on this?

**Comment by delucalab** [comment]
So sorry for the delay, I just tried using:

install.packages("TMB", repos="https://glmmTMB.github.io/glmmTMB/repos")

I then got the following error:

Warning in install.packages :
  package ‘TMB’ is not available (for R version 3.6.3)
Warning in install.packages :
  unable to access index for repository https://glmmTMB.github.io/glmmTMB/repos/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://glmmTMB.github.io/glmmTMB/repos/bin/macosx/el-capitan/contrib/3.6/PACKAGES'

However, I think I've had success with the following:

while (!require("checkpoint")) install.packages("checkpoint")
bd <- as.character(asDateBuilt(packageDescription("TMB",fields="Built")))
oldrepo <- getOption("repos")
setSnapshot(bd)
install.packages("Matrix")
options(repos=oldrepo)
install.packages("glmmTMB")
library(glmmTMB)

**Comment by bbolker** [comment]
Glad it worked out. I should have specified that I only built the binaries for R version 4.0 (version 4.0.0 was released over a year ago, which makes version 3.6.3 "old" in R terms). I have built the binaries for *Windows* version 3.6.3, but r-hub (the publicly available binary-building resource) doesn't offer support for version 3.6.3 under MacOS ...
