### ISSUE TITLE
problems caused by link/inverse link during prediction

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#696]
Right now we are always returning predictions on the response scale (`mu`), then transforming to the link scale if requested.

This causes problems if, for example, we have a fairly extreme prediction on the `cloglog` scale (e.g. 3.99). Especially given the relatively naive inverse-link function we are using (`1-exp(-exp(eta))`, in contrast to `make.link("cloglog")$linkinv` [which uses `pmax(pmin(-expm1(-exp(eta)), 1 - .Machine$double.eps), .Machine$double.eps)`, this overflows to 1.000 on the probability scale.

We should probably do one or the both of the following:

- modify the cloglog link to be 'clamped' within (0,1) as in `make.link("cloglog")$linkinv` (this would require using something from `CppAD` and/or putting it inside an atomic function so that we can do the hard truncation?)
- modify `glmmTMB.cpp` to return `eta_predict` as well as `mu_predict` and use it instead? (Is it that easy?)

An example from John Maindonald: using [ffly.csv](https://github.com/glmmTMB/glmmTMB/files/6525594/ffly.csv):

```r
## ffly <- read.csv('https://github.com/jhmaindonald/dataR/files/6521483/ffly.csv')
## write.csv(ffly,"ffly.csv", row.names=FALSE)
ffly <- read.csv("ffly.csv")
ffly$obs <- factor(ffly$obs)

form1 <- cbind(Dead,Live)~0+trtGp/TrtTime+(1|obs)+(1|trtGpRep)

library(glmmTMB)
ObsTMB.cll <- glmmTMB(form1,
                      family=binomial(link="cloglog"), data=ffly)
(p0 <- predict(ObsTMB.cll, re.form=NA))[61:65]
p1 <- predict(ObsTMB.cll, re.form=NA,type="response")
1-p1[61:65]
X <- model.matrix(~0+trtGp/TrtTime, data=ffly)
## compute by hand
pp <- c(X %*% fixef(ObsTMB.cll)$cond)
pp[61:65]
1.0-make.link("cloglog")$linkinv(pp[61:65])
```

**Comment by jhmaindonald** [comment]
> We should probably do one or the both of the following:
> 
>   1)  modify the cloglog link to be 'clamped' within (0,1) as in make.link("cloglog")$linkinv (this would require using something from CppAD and/or putting it inside an atomic function so that we can do the hard truncation?)
>    2) modify glmmTMB.cpp to return eta_predict as well as mu_predict and use it instead? (Is it that easy?)

Re 2), it did occur to me that the issue might be that eta_predict is being calculated from mu_predict, but thought it unlikely to be that simple.  I'd judge that both change 2) is certainly needed.  On 1), is mu_predict not currently thus constrained?

**Comment by bbolker** [comment]
I implemented both of these changes: see the linked PR

**Comment by bbolker** [comment]
PR is merged; **not** clamping due to feedback that this represents papering over a crack rather than solving a problem. (See discussion [here](https://github.com/glmmTMB/glmmTMB/pull/697#issuecomment-847737592))
