### ISSUE TITLE
Does the dispersion parameter of the beta regression means the inverse of the precision parameter in glmmTMB package?

### ISSUE THREAD

**Issue by Tahsin1990** [glmmTMB/glmmTMB#700]
Hi! By using glmmTMB package for the beta distributed generalized linear mixed model, we have got dispersion parameter. Does this dispersion parameter means the inverse of the precision parameter? Is the dispersion parameter for fixed or constant precision? When should we assume for varying precision/dispersion? Is there any code for varying precision or dispersion for beta distributed generalized linear mixed model in glmmTMB package? Thanks.

**Comment by mebrooks** [comment]
You're sort of right. `?family_glmmTMB` says 
"Beta distribution: parameterization of Ferrari and Cribari-Neto (2004) and the betareg package (Cribari-Neto and Zeileis 2010); V=mu*(1-mu)/(phi+1)"
So a larger value of phi leads to a smaller variance.


The default is that the parameter is constant, but you can let the dispersion parameter very by using the `dispformula`. When you should do that is a larger topic.

This question would be more appropriate for the [R-sig-mixed list](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions). Please direct further questions there.

```
library(glmmTMB)
#Simulate data
simfun0 <- function(beta=c(-0.05,.001),
                   sd.re=5,
                   ngrp=100,nobs=200,
                   invlink=exp) {
    x <- rnorm(nobs)
    f <- factor(rep(1:ngrp,nobs/ngrp))
    u <- rnorm(ngrp,sd=sd.re)
    eta <- beta[1]+beta[2]*x+u[f]
    mu <- invlink(eta)
    return(data.frame(x,f,mu))
}
set.seed(101)
nobs <- 2000; eps <- 1e-6; phi <- 0.1
dd0 <- simfun0(nobs=nobs,sd.re=0.1,invlink=plogis)
y1 <- with(dd0,rbeta(nobs,shape1=mu/phi,shape2=(1-mu)/phi))

phi <- 0.2
y2 <- with(dd0,rbeta(nobs, shape1=mu/phi,shape2=(1-mu)/phi))

dd1 <- data.frame(dd0,y=pmin(1-eps,pmax(eps,y1)), d="A")
dd2 <- data.frame(dd0,y=pmin(1-eps,pmax(eps,y2)), d="B")

dd <- rbind(dd1, dd2)

summary(dd)

#Fit the model
m1 <- glmmTMB(y~x+(1|f), disp = ~d, family=beta_family(), data=dd)

summary(m1)
```
Then to get back the values of phi used in the simulation I do
```
> 1/exp(fixef(m1)$disp[1])
(Intercept) 
  0.1046172 
> 1/exp(sum(fixef(m1)$disp))
[1] 0.1985131
```
but this only works in this case; other code would need to be written for other cases.

**Comment by Tahsin1990** [comment]
Thanks a lot!
