### ISSUE TITLE
How can I understand that I should include which variable for varying dispersion beta distributed generalized linear mixed model using glmmTMB?

### ISSUE THREAD

**Issue by Tahsin1990** [glmmTMB/glmmTMB#701]
I am struggling for the varying dispersion beta regression using glmmTMB. I did the Breusch-Pagan Test for checking heteroscedasticity for my model. As, the p-value is smaller than 0.05, so heterodasticity is present. So, I have to use beta glmm for varying dispersion. Further, I need to know which variable should I include for varying dispersion model. To know this, I followed a procedure. For example, my response variable is y, independent variable is x1,x2 and x3 and there is random effect for study id. At first, I run beta glmm for varying dispersion only for y and x1. Then, I did the Breusch-Pagan Test for checking heteroscedasticity. If the p value is smaller than 0.05, so there is heteroscadsticity. In this case, I added x1 variable in my dispersion model. Similarly, I run beta glmm for y and x2, and then perform the Breusch-Pagan test. If the result shows homoscedasticity, then I didn't include x2 covariate for the dispersion model. Again, I did the same thing for y and x3. If the result implies heteroscedasticity, then I added x3 covariate for my dispersion model. 

Finally, this will be like :
m1.f <- glmmTMB(y~  x1+x2+x3+(1|study_id), data=mydata, ziformula= ~1,dispformula = ~x1+x3, family=beta_family() )
summary(m1.f)

Is my procedure correct?

Should we comment on only conditional mean model?

Thanks.

**Comment by mebrooks** [comment]
Crossposted on R-sig-mixed. It belongs over there.

**Comment by Tahsin1990** [comment]
Thanks for letting me know.
