### ISSUE TITLE
Interpretation of residual plot using DHARMA package for mixed model in glmmTMB package

### ISSUE THREAD

**Issue by Tahsin1990** [glmmTMB/glmmTMB#705]
Hi,

I am struggling to interpret the residual plots from the Dharma package. If we find a red line in residual plot,does it mean there is heteroscedasticity in the model for the predictor variables? If the solid line matches with the dashed line, can we say there is no heteroscedasticity? I have attached some residual plots here to understand heteroscedasticity of the model.  In the first plot, quantile deviation are detected by the red line, so there is heteroscedasticity in the model. This is for the model which includes all covariates. Then I created the residual plot for one by one covariate to know which predictors are responsible for variable dispersion. The 2nd and 3rd plots are for just one predictor. In the 2nd plot, three solid lines are red and there exhibits a clear deviation from the dashed line. So, there is heteroscedasticity in the model for that predictor. The 3rd plot is box plot.The distribution for each factor level should be uniformly distributed, so the box should go from 0.25 to 0.75, with the median line at 0.5 (within-group ). As the two box plots are red and it shows deviation of median line from 0.5, so there is heteroscedasticity in the model for the predictor. The 4th plot shows less deviation. Can we say this is better? I need your expert suggestions and also please refer me to any article where I find a clear explanation of heteroscedasticity checking by residual plot using DHARMA for glmmTMB . I am also not sure if this is right place for this question. If not, please refer me any other place where I can know about this. Many thanks.
![Rplot1](https://user-images.githubusercontent.com/83094821/120565063-80b32900-c3c9-11eb-8b2d-16e80e3d69ce.png)
![Rplot 2](https://user-images.githubusercontent.com/83094821/120565080-890b6400-c3c9-11eb-8bcc-edf8ba3e38a6.png)
![Rplot 3](https://user-images.githubusercontent.com/83094821/120565094-91fc3580-c3c9-11eb-97cd-10ac2fff7dee.png)
![Rplot 4](https://user-images.githubusercontent.com/83094821/120565111-99bbda00-c3c9-11eb-8267-4dfc142f3bb5.png)

Kindest regards,

Tahsin

**Comment by bbolker** [comment]
Please do not cross-post to the r-sig-mixed-models list and here. I'm going to close this, as I think the list is a better venue based on [this guidance](https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions)

**Comment by Tahsin1990** [comment]
Dear Dr Bolker,

Thanks for informing me. I saw that my email was not accepted in
r-sig-mixed model list because of its length. That's why I posted it in
glmmTMB package.I am sorry for my mistake.

**Comment by bbolker** [comment]
No problem (I had to manually approve it on the list because of its length).
