### ISSUE TITLE
Customize maximum number of cores/threads at install of the package?

### ISSUE THREAD

**Issue by yukio-takeuchi** [glmmTMB/glmmTMB#709]
As pointed [here](https://github.com/kaskr/adcomp/issues/303#issuecomment-566449181), if more than 48 cores be used with TMB, it needs to insert 
```
#define CPPAD_MAX_NUM_THREADS 128
```
right before
```
#include <TMB.hpp>
```
of cpp file

For HPC node equipped with 2 AMD EPYC7742 cpus with 128 cores in total in my office, I installed from local clone of this repo with glmmTMB.cpp edited as described above.

Although I understand that it is very rare case, is it possible to add an option to change the value of CPPAD_MAX_NUM_THREADS when glmmTMB is installed or to insert a line
```
#define CPPAD_MAX_NUM_THREADS 128
```
right before
```
#include <TMB.hpp>
```
of glmmTMB.cpp?

**Comment by bbolker** [comment]
This seems hard to do without setting up some fairly complex `configure` machinery: feels like most people who want to do computing at this scale would probably be savvy enough to do the workaround/hack you described (especially if we document it).

On the other hand ... @kaskr, what are the potential downsides/dangers to bumping up the default max number of threads ... ?

**Comment by yukio-takeuchi** [comment]
I found slightly smarter way to change maximum number of cores to be used by installing glmmTMB as
```
withr::with_makevars(c(PKG_CPPFLAGS="-DCPPAD_MAX_NUM_THREADS=128"),{
devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
 },assignment="+="
)
```
This is inspired by [](https://cran.r-project.org/web/packages/httpuv/readme/README.html)

It seemed that this trick also works to install glmmTMB from cran.

**Comment by bbolker** [comment]
added to README
