### ISSUE TITLE
rr covstruct fails with parallelization

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#710]
```shell
echo "options(glmmTMB.cores=2L); source('test-rr.R')" | R --slave
```

Gives

```
── Failure (???): rr model fit ─────────────────────────────────────────────────
as.numeric(logLik(spider_p1)) not equal to c(-736.0022).
1/1 mismatches
[1] -611 - -736 == 125
```

I didn't realize until now that the way rr covstruct is implemented violates the assumption of parallel accumulation.

**Some thoughts on how to fix it**

Short term:

- Set number of threads to `1` if `cc_covstruct` is present in the formula.

Long term:

- Skip all explicit parallelization from glmmTMB.cpp (remove the `PARALLEL_REGION`) and use the upcoming completely automatic parallelization in TMB.

In addition we should routinely run the glmmTMB test suite as

```shell
echo "options(glmmTMB.cores=2L); source('AAAtest-all.R')" | R --slave
```

**Comment by bbolker** [comment]
Resolved by #712

**Comment by bbolker** [comment]
hi, @kaskr, could we revisit this issue?  Is it possible/reasonably straightforward to overcome this limitation with the current version of `TMB`?  Alternatively, would there be a straightforward to conditionally (for `rr`-containing terms only) enable `PARALLEL_REGION` for the random effects computation (`allterms_nll`), leaving `PARALLEL_REGION` always enabled for the conditional likelihood loop?

**Comment by kaskr** [comment]
The help page `?TMB::openmp` mentions the new experimental option `autopar=TRUE`. It ignores all the `PARALLEL_REGION` stuff and splits the computational graph automatically.

There is no easy way to *manually* (e.g. by tweaking the `PARALLEL_REGION` macro) perform a valid parallel split for the `rr_covstruct` because all conditionally independent terms depend on the the `rr` random effects.

**Comment by bbolker** [comment]
Superseded by #1051.
