### ISSUE TITLE
Windows OpenMP crash

### ISSUE THREAD

**Issue by kaskr** [glmmTMB/glmmTMB#714]
I suggest we continue Windows OpenMP discussion in this new issue (rather than #647).

Summary:

- `make test` fails `tweedie` and `rr_covstruct` tests when glmmTMB is compiled with OpenMP on Windows.
- Setting `TMB::openmp()` to `1` before running `test-families.R` doesn't help.
- Problem observed for both versions (new/old) of the tool chain.
- gdb backtrace shows the crash is triggered by TMB's tweedie when calling `R_chk_calloc` indicating a thread safety issue with this allocator (but then why doesn't it solve the problem to set nthreads=1 (?)...).

**Comment by bbolker** [comment]
Does the presence of information about a gdb backtrace indicate that you succeeded in setting up a Windows test platform that displays the problem?

If so, can you re-create a more minimal version using the [tweedie example that @mebrooks referenced in the other thread](https://kaskr.github.io/adcomp/tweedie_8cpp-example.html#a2), and showing that it fails/succeeds based on whether OpenMP is enabled or not?

**Comment by bbolker** [comment]
Digging a little bit more, I have a guess that the problem *might* be the Calloc/Free calls in [tweedie_logW](https://github.com/kaskr/adcomp/blob/b380fe8e78d16aba38d755ad4efbea3139d92212/TMB/inst/include/tiny_ad/tweedie/tweedie.cpp#L61-L74).

- I'm clueless about how allocation/freeing is supposed to happen in a thread-safe way under TMB (I see stuff in the code base called `thread_alloc`, but don't know how it's supposed to be used. Maybe the problem and/or solution will be obvious to someone who does more of this stuff.
- running under `valgrind` might be informative
- [web search on "calloc free openmp thread-safe"](https://duckduckgo.com/?t=ffab&q=calloc+free+openmp+thread-safe)

**Comment by kaskr** [comment]
@bbolker I now have access to a windows terminal server (thanks to hints from @mebrooks ) and can re-produce the problems.

It was a surprise to me that R remaps `calloc` to something called `R_chk_calloc`. In my experience, whenever there's a `R_chk_` in a function name it normally signifies 'not thread safe'... :) Without trying to understand this further I made a simple experiment to avoid the (calloc/free) allocation pattern of dtweedie. In this branch:
https://github.com/kaskr/adcomp/tree/tweedie_fix
That fixes the tweedie test on Windows. In addition it gives a small performance improvement on Linux so I'm tempted to use this allocation pattern in other TMB special functions as well.

However, there's one more surprise. It seems like Windows completely ignores setting the number of threads via `TMB::openmp()`. That explains why the `test-rr.R` fails (even with the recent fix here: https://github.com/glmmTMB/glmmTMB/pull/712). It also explains why `TMB::openmp(1)` didn't solve the Tweedie calloc problem in the first place...

**Comment by bbolker** [comment]
Just curious: do you know why putting `openmp()` within `glmmTMB` would make it work when it doesn't work coming from `TMB` ... ?

**Comment by kaskr** [comment]
@bbolker I don't really *know* but my tests indicated the following platform difference Linux/Windows:

- Linux: `openmp()` accesses the same global variable across DLLs `TMB::openmp() == glmmTMB::openmp()`
- Windows: `openmp()` accesses a global variable specific for the DLL of which it is compiled/linked. `TMB::openmp() != glmmTMB::openmp()`
