### ISSUE TITLE
CRAN issues

### ISSUE THREAD

**Issue by florianhartig** [glmmTMB/glmmTMB#722]
Hi guys,

I received CRAN warnings that glmmTMB will be removed from CRAN within 3 days, and DHARMa with it - what's the status on this issue and did you receiving the CRAN emails?

Best,
Florian

**Comment by mebrooks** [comment]
Yes. I'm aware. I hope that if we can resolve #721, that will be the last problem. I'm running checks now.

**Comment by florianhartig** [comment]
OK, thanks for the update! F

**Comment by bbolker** [comment]
Closing as duplicate of #721
