### ISSUE TITLE
Warning in the object or only stdout

### ISSUE THREAD

**Issue by bri2020** [glmmTMB/glmmTMB#725]
Hi, I have a basic question. Is a warning only given when running the model in the stdout (e.g. Model convergence problem; false convergence (8). See vignette('troubleshooting') )- or can I also find this information in the glmmTMB-object. How can I see this afterwards?
Thanks a lot,
Best wishes
Britta Meyer

**Comment by mebrooks** [comment]
If your fitted model is named "`model`" then there is `model$fit$convergence`

0 indicates successful convergence. Other integers are documented with the optimizer (nlminb by default).

Also, see https://github.com/glmmTMB/glmmTMB#where-to-ask-questions
