### ISSUE TITLE
glmmTMB removed from the CRAN

### ISSUE THREAD

**Issue by Generalized** [glmmTMB/glmmTMB#728]
Dear Authors, I just wanted to check something in the vignette, but found a message, that the package is removed from CRAN.
Do you plan to return to the CRAN, or should be this package considered as non-maintained in the future?

And, if so, do you have any plans, to add the residual covariance structures to the lme4 or create a new package (like the glmmTMB) in the future, which enables both covariance specifications?

```
Package ‘glmmTMB’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2021-07-10 as repeated problems were not corrected in time.
A summary of the most recent check results can be obtained from the check results archive.
Please use the canonical form https://CRAN.R-project.org/package=glmmTMB to link to this page.
```
https://cran.r-project.org/web/packages/glmmTMB/

**Comment by bbolker** [comment]
We are working to restore glmmTMB to CRAN.

**Comment by bbolker** [comment]
Submitted to CRAN, fingers crossed.
