### ISSUE TITLE
Predict (model) results in p <- ncol(X)) == ncol(Y) is not TRUE when using random intercept

### ISSUE THREAD

**Issue by ajw11** [glmmTMB/glmmTMB#731]
I am trying to find the fitted values for a negative binomial hurdle model with a random intercept (on the zero-inflated part).  When I drop the random intercept it works fine, but when I add it back in I get the error "p <- ncol(X)) == ncol(Y) is not TRUE."  Is there a known issue with this?

**Comment by bbolker** [comment]
Possible, but it doesn't ring a bell ([searching issues doesn't find anything either](https://github.com/glmmTMB/glmmTMB/issues?q=is%3Aissue+ncol%28X%29+ncol%28Y%29+TRUE). Could we have a reproducible example please?

**Comment by ajw11** [comment]
I don't have the code available right now, but the model portion (m1) is essentially what you have written.  Since it works without the random intercept, I'm going to try making the random effect a factor as you have and will let you know if that fixes it.

**Comment by bbolker** [comment]
I can't replicate this when making `f` a character variable instead of a factor, either:

```
m3 <- update(m1, data = transform(dd, f = as.character(f)))
fitted(m3)
```

works fine.

If you can generate a reproducible example we would be interested in seeing it ...

**Comment by bbolker** [comment]
any further updates on this?  If there's a problem (even one with a workaround) we'd like to fix it ...

**Comment by ajw11** [comment]
I was able to get around the error by redefining the variables in my original data frame, then rerunning the model with these redefined variables. For example:

y<-  df$'response'
x1<- df$'variable 1'
x2<- df$'variable 2'
x3<- df$'variable 3'
re<- df$'random effect'

dd<-data.frame(y,x1,x2,x3,re)

m1 <- glmmTMB(y ~ x1 +x2 + x3 , data = dd, zi = ~ x1+x2+x3 + (1|re),  family = truncated_nbinom2)

fitted(m1)

There was probably an issue with my original data frame but I don't know exactly what it was.

**Comment by bbolker** [comment]
It would be great to have a reproducible example, but without one we can't really do any more with this.  It doesn't really shock me that variables with spaces in their names could be a problem, but so far I can't come up with an example.  Do you still have the original data set?

This doesn't reproduce the problem:

```
dd <- data.frame(response=rep(1:5, length.out = 100),
                 `variable 1` = rnorm(100),
                 `variable 2` = rnorm(100),
                 `variable 3` = rnorm(100),
                 `random effect` = factor(rep(1:10, length.out = 100)),
                 check.names = FALSE)
m0 <- glmmTMB(response ~ `variable 1` + `variable 2` + `variable 3` ,
              data = dd,
              zi = ~ `variable 1` + `variable 2` + `variable 3` + (1|`random effect`),
              family = truncated_nbinom2)
fitted(m0)
```

**Comment by bbolker** [comment]
PS does [this SO post](https://stackoverflow.com/questions/38663394/p-ncolx-ncoly-is-not-true-error-in-glmer) help at all?

**Comment by bbolker** [comment]
If I set the random effect to `(1|1)` I can get 

> Error in KhatriRao(sm, t(mm)) : (p <- ncol(X)) == ncol(Y) is not TRUE

but so far I haven't found any non-contrived way to make that happen.  Are you somehow generating your formula programmatically ???

**Comment by ajw11** [comment]
No that post wasn't how I had originally coded it. the random effect was of the form (1|df$'random effect'). I'm unable to provide the original data set unfortunately, it's not on my computer. I don't understand your last question about generating the formula programmatically, can you elaborate?

**Comment by bbolker** [comment]
OK, I can replicate this, but **only** with an old version of the package (1.0.2.1, superseded by a new version about a month ago) and **only** when specifying the random effect with `dd$'random effect'`, **which is generally considered bad practice** (I've added a note to that effect to the `?glmmTMB` page). (You might be able to replicate it with the current version of glmmTMB if you try get predictions with the `newdata` argument specified.)

```r
m0 <- glmmTMB(response ~ `variable 1` + `variable 2` + `variable 3` ,
              data = dd,
              zi = ~ `variable 1` + `variable 2` + `variable 3` + (1|dd$`random effect`),
              family = truncated_nbinom2)
```

**Comment by bbolker** [comment]
Warnings added in new branch/PR for use of `$` in formulas and skipping the `data` argument ... as well as a comment in the docs

**Comment by ajw11** [comment]
Thank for your help!
