### ISSUE TITLE
Misplaced `PARALLEL_REGION` in template

### ISSUE THREAD

**Issue by jaganmn** [glmmTMB/glmmTMB#733]
I suspect that computation of random effect likelihood terms is not being parallelized _at all_ in `glmmTMB.cpp`, which may help explain the less-than-anticipated speed-up reported in #620. I hope that someone more familiar with TMB internals can assess my reasoning.

`glmmTMB.cpp` contains these lines, introduced in #652:

```cpp
PARALLEL_REGION jnll += allterms_nll(b, theta, terms, this->do_simulate);
PARALLEL_REGION jnll += allterms_nll(bzi, thetazi, termszi, this->do_simulate)
```

where `PARALLEL_REGION` is a macro defined in `tmb_core.hpp`:

```cpp
#define TMB_OBJECTIVE_PTR                                               \
this
#define PARALLEL_REGION                                                 \
if( TMB_OBJECTIVE_PTR -> parallel_region() )
``` 

where `parallel_region` is a member function of the `objective_function` class, also defined in `tmb_core.hpp`:

```cpp
bool parallel_region(){            /* Is this the selected parallel region ? */
    bool ans;
    if(current_parallel_region<0 || selected_parallel_region<0)return true; /* Serial mode */
    ans = (selected_parallel_region==current_parallel_region) && (!parallel_ignore_statements);
    current_parallel_region++;
    if(max_parallel_regions>0)current_parallel_region=current_parallel_region % max_parallel_regions;
    return ans;
}
```

I grasp from the above that the entire expression `allterms_nll(b, theta, terms, this->do_simulate)`, including every iteration of every loop enclosed in `allterms_nll`, is being evaluated in one thread. I tested this by modifying the `linreg_parallel` example from TMB (see files in zip archive [here](https://github.com/glmmTMB/glmmTMB/files/6858527/parallel.zip)).

`parallel1.cpp` does `PARALLEL_REGION nll += func_returning_nll_term_sum(args)`, imitating the two lines from `glmmTMB.cpp`, while `parallel2.cpp` does `func_modifying_nll_by_reference(nll, this, args)`.

Here are the results of `TMB::benchmark(obj, n = 1000L, cores = 1:8)` for each template:

```r
> res[["parallel1"]]
#                      ncores
#                           1     2     3     4     5     6     7     8
#   template.likelihood 2.446 2.455 2.654 2.500 2.493 2.513 2.500 2.636
#   template.gradient   6.163 6.325 6.388 6.422 6.395 6.444 6.373 6.535
# attr(,"class")
# [1] "parallelBenchmark"

> res[["parallel2"]]
#                      ncores
#                           1     2     3     4     5     6     7     8
#   template.likelihood 2.432 1.420 1.005 0.756 0.853 0.714 0.636 0.553
#   template.gradient   6.192 3.172 2.317 1.733 2.148 2.026 1.760 1.559
# attr(,"class")
# [1] "parallelBenchmark"
```

which suggests that the first implementation does not permit any speed-up regardless of the number of threads used. The second implementation remedies the issue, and could be useful in `glmmTMB.cpp`.

Note that `glmmTMB` _does_ seem to parallelize observation likelihood computation correctly, which might explain why #620 reported _some_ speed-up with multiple threads, rather than none.

**Comment by kaskr** [comment]
@jaganmn Your reasoning is correct. The `all_terms` stuff is not really parallelized. Parallelization in glmmTMB targets the observation likelihood only.

In the future we are aiming for a completely automatic parallel split that wont have these issues.
