### ISSUE TITLE
Hessian problem for truncated distributions?

### ISSUE THREAD

**Issue by ldharder** [glmmTMB/glmmTMB#734]
I have encountered a problem with truncated distributions (both Poisson and Conway-Maxwell-Poisson) that I suspect is associated with the Hessian matrix.  I provide the following data to illustrate this problem.

[Truncated compois problem.xlsx](https://github.com/glmmTMB/glmmTMB/files/6874470/Truncated.compois.problem.xlsx)

The data represent the number of mates (mates) for multiple plants (ID) from six populations (pop). Plants belong to either of two morphs (morph).  Populations are treated as fixed, so the analysis involves a generalized linear model.  Interest focuses on plants with at least some mates (hence the truncated distribution) and the distribution of mates is under-dispersed compared to a Poisson distribution (hence interest in the Conway-Maxwell-Poisson distribution).

The problematic analysis is 
```
data$pop <- as.factor(data$pop)
data$morph <- as.factor(data$morph)
options(contrasts = c("contr.sum","contr.poly")) 
trunc_compois <- glmmTMB(mates ~ pop*morph, family='truncated_compois', data=data)
summary(trunc_compois)
```

which results (without warnings) in 

```
Conditional model:
            Estimate Std. Error z value Pr(>|z|)
(Intercept)   -1.098    600.338  -0.002    0.999
pop1           2.464    600.338   0.004    0.997
pop2          -8.288   3001.692  -0.003    0.998
pop3           1.441    600.338   0.002    0.998
pop4           1.758    600.338   0.003    0.998
pop5           1.171    600.339   0.002    0.998
morph1        -1.422    600.338  -0.002    0.998
pop1:morph1    1.089    600.338   0.002    0.999
pop2:morph1   -7.675   3001.692  -0.003    0.998
pop3:morph1    1.358    600.338   0.002    0.998
pop4:morph1    1.558    600.338   0.003    0.998
pop5:morph1    1.905    600.339   0.003    0.997
```

The problem is evident in the disproportionately large standard errors for the parameter estimates.

This problem is associated with the lack of variation in mate number for the L-morph plants in population ELS, all of which mated with 1 other plant.  Altering the mate number of one of these plants (ELS11) from 1 to 2 (represented in `altmates`) leads to more proportional standard errors:

```
alttrunc_compois <- glmmTMB(altmates ~ pop*morph, family='truncated_compois', data=data)
summary(alttrunc_compois)

Conditional model:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  0.37900    0.15769   2.403   0.0162 *  
pop1         0.98796    0.19465   5.076 3.86e-07 ***
pop2        -0.91290    0.47828  -1.909   0.0563 .  
pop3        -0.03367    0.18841  -0.179   0.8582    
pop4         0.28296    0.19762   1.432   0.1522    
pop5        -0.30342    0.28898  -1.050   0.2937    
morph1       0.05231    0.12564   0.416   0.6771    
pop1:morph1 -0.38541    0.18234  -2.114   0.0345 *  
pop2:morph1 -0.30100    0.47394  -0.635   0.5254    
pop3:morph1 -0.11683    0.18879  -0.619   0.5360    
pop4:morph1  0.08345    0.19621   0.425   0.6706    
pop5:morph1  0.43009    0.28973   1.484   0.1377 
```

That this problem is specifically related to truncated distributions is demonstrated by fitting the compois distribution (rather than truncated_compois), which does not estimate inflated standard errors:

```
compois <- glmmTMB(mates ~ pop*morph, family='compois', data=data)
summary(compois)

Conditional model:
             Estimate Std. Error z value Pr(>|z|)    
(Intercept)  0.704959   0.058058  12.142  < 2e-16 ***
pop1         0.696720   0.101779   6.845 7.63e-12 ***
pop2        -0.526613   0.196506  -2.680  0.00736 ** 
pop3        -0.075118   0.094498  -0.795  0.42666    
pop4         0.120172   0.105126   1.143  0.25299    
pop5        -0.168852   0.130489  -1.294  0.19567    
morph1      -0.003177   0.058058  -0.055  0.95636    
pop1:morph1 -0.299890   0.101779  -2.946  0.00321 ** 
pop2:morph1 -0.175151   0.196506  -0.891  0.37275    
pop3:morph1 -0.031956   0.094498  -0.338  0.73524    
pop4:morph1  0.094337   0.105126   0.897  0.36952    
pop5:morph1  0.220835   0.130489   1.692  0.09058 .  
```

Parallel differences are evident between the standard and truncated Poisson distributions, indicating that the problem applies more generally.

Is this issue an inherent feature of analyzing truncated discrete distributions, or does it signal a problem with the implementation of truncated distributions in `glmmTMB`?

Thanks for considering this issue.

**Comment by bbolker** [comment]
Strongly suspect that this is a problem of **complete separation**; do a web search for that or **Hauck-Donner effect**.

**Comment by bbolker** [comment]
This seems to be a peculiarity of truncated distributions that I don't fully understand/can't explain in a heuristic way yet.  I posted some of my explorations [here](https://gist.github.com/bbolker/210cc090db7184dfa5e45be1ee1c2e03).

**Comment by ldharder** [comment]
Thanks for digging into this problem.  Your analogy with solely 0 observations for a category in a Poisson analysis makes sense.

Does your update concerning the use anova() (Anova()?) reflect concern about single-parameter (i.e., 1 df) tests?  For example, the test for morph in the example seems to suffer from the general problem, as represented by the summary () test for parameter morph1 in the provided example.

Unless you intend to include regularization in glmmTMB soon, I will investigate the contrast approach that you suggest.  

(I appreciate your personal comment.)

Thanks again.

**Comment by bbolker** [comment]
I explored the inferential possibilities a little bit [here](https://gist.github.com/bbolker/00de1e4dfdf0cf7ff56ecc451a8d09e2). Closing now unless there is another question ...
