### ISSUE TITLE
Answering general questions about treatment effect 

### ISSUE THREAD

**Issue by InkaMarei** [glmmTMB/glmmTMB#735]
I have a field study with insects were we evaluate whether a fungicide has an effect (negative effect) on the insect number in the fields. I have several replicates per field and the experiment is a time series over 43 days.  My model looks like this: 

myModel <- glmmTMB(NumberBees~  Treatment*poly(Day,2)+
                   (1|Plot/Replicate),data=dat,REML=T, family=gaussian(link = "identity"))

Treatment is :(TRUE or FALSE) and Day is a numeric variable from -1 to 43. 

I am wondering how to answer these two questions. 
- Does treatment have an effect, considering days-1 to 43 together?
- Does treatment have an effect at any day of the experiment?

I now answer the second question with:
summary(glht(Test3, emm(pairwise~~Treatment|DAT, at=list(DAT=c(-1:43)))))          

I use glht as I can choose to only look at adverse effect of treatment with alternative="greater"

Is this correct, or should I rather use emtrends, because I have an interaction between a factor and a continuous variable. I am insecure here, because I believe, that I only want to compare the marginal means at specific days, rather than their slopes. 

Regarding the second question I want two answer, I wonder whether I simply take the p-value of Treatment from the summary(myModel) output or whether I should focus on the comparison of the slopes via emtrends and concomitant pairs() function.

**Comment by bbolker** [comment]
Please send this to `r-sig-mixed-models@r-project.org`; it's more appropriate there (see ["where to ask"](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions).  (Please subscribe to the mailing list before posting; you can find the subscription page by web-searching.)
