### ISSUE TITLE
error dowloading glmmTMB

### ISSUE THREAD

**Issue by NinaSchaefer** [glmmTMB/glmmTMB#739]
HI everyone,

I also got troubles downloading the package and get the following error:
........
Documents/R/win-library/3.6/RcppEigen/include"     -fopenmp   -O2 -Wall  -mtune=generic -Wall -pedantic -fdiagnostics-color=always -c glmmTMB.cpp -o glmmTMB.o
   In file included from glmmTMB.cpp:3:0:
   distrib.h: In function 'double glmmtmb::rtruncated_poisson(int, double)':
   distrib.h:88:12: error: 'range_error' is not a member of 'std'
         throw std::range_error("non-positive mu in k-truncated-poisson simulator\n");
               ^
   distrib.h:90:12: error: 'range_error' is not a member of 'std'
         throw std::range_error("negative k in k-truncated-poisson simulator\n");
               ^
   distrib.h: In function 'double glmmtmb::rtruncated_nbinom(double, int, double)':
   distrib.h:126:15: error: 'range_error' is not a member of 'std'
            throw std::range_error("non-positive size in k-truncated-neg-bin simulator\n");
                  ^
   distrib.h:128:15: error: 'range_error' is not a member of 'std'
            throw std::range_error("non-positive mu in k-truncated-neg-bin simulator\n");
                  ^
   distrib.h:130:15: error: 'range_error' is not a member of 'std'
            throw std::range_error("negative k in k-truncated-neg-bin simulator\n");
                  ^
   make: *** [C:/PROGRA~1/R/R-36~1.1/etc/x64/Makeconf:215: glmmTMB.o] Error 1
   ERROR: compilation failed for package 'glmmTMB'
-  removing 'C:/Users/NINASC~1/AppData/Local/Temp/RtmpKc3xrx/Rinst43346e61455/glmmTMB'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'glmmTMB' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E>          throw std::range_error("non-positive mu in k-truncated-neg-bin simulator\n");
E>                ^
E> distrib.h:130:15: error: 'range_error' is not a member of 'std'
E>          throw std::range_error("negative k in k-truncated-neg-bin simulator\n");
E>                ^
E> make: *** [C:/PROGRA~1/R/R-36~1.1/etc/x64/Makeconf:215: glmmTMB.o] Error 1
E> ERROR: compilation failed for package 'glmmTMB'
E> * removing 'C:/Users/NINASC~1/AppData/Local/Temp/RtmpKc3xrx/Rinst43346e61455/glmmTMB'
E>       -----------------------------------
E> ERROR: package installation failed
In addition: Warning messages:
1: In i.p(...) : installation of package ‘Rcpp’ had non-zero exit status
2: In i.p(...) : installation of package ‘lme4’ had non-zero exit status
> 

I'd appreciate any suggestions on how to resolve this :)

Cheers,
Nina

**Comment by bbolker** [comment]
I haven't seen this one before.

- it looks like you have a fairly old version of R (your packages library is in "3.6", which suggests that's  your R version); any chance of upgrading?
- can we have more detail on your OS, e.g. output of `sessionInfo()`, and if possible your compiler?
- any chance you could install a binary version (e.g. from CRAN) rather than installing from source?

**Comment by NinaSchaefer** [comment]
Thanks @bbolker. 
I am upgrading everything right now and give it another go. Will let you know how I go :)

**Comment by NinaSchaefer** [comment]
hi @bbolker. After updating I just received the Matrix error which I managed to resolve according to your suggestions on that error.
I had updated my R recently, but turned out it had not done it properly.
Thank you for checking on this and for your help!
