### ISSUE TITLE
Attempt to set an attribute on NULL

### ISSUE THREAD

**Issue by tuncbkose** [glmmTMB/glmmTMB#740]
Hi! I encountered an issue where my `glmmTMB` call constantly gave the following error:
```
Error in names(respCol) <- names(fr)[respCol] : 
  attempt to set an attribute on NULL
```
Upon looking at the source code, I noticed that that `respCol` is set by a lookup by "response". Thinking my column named "response" might be interfering, I removed it, but the error persists.

**Comment by mebrooks** [comment]
Can you give any more information? ideally a reproducible example? 

I unsuccessfully tried to reproduce the "response" issue from the pre-edited version as follows"

```
d2 <- transform(Salamanders, "response"=count)

m1 <- glmmTMB(count ~ mined + (1|site),
  zi=~mined,
  family=poisson, data=Salamanders)
  
m2 <- glmmTMB(response ~ mined + (1|site),
  zi=~mined,
  family=poisson, data=d2)
```

**Comment by tuncbkose** [comment]
I am not sure how to give a reprex because my dataset is very big and I cannot replicate the issue with a dummy dataset. In trying to debug it myself looking at the source code, I noticed that
`fr <- eval(mf,envir=environment(formula),enclos=parent.frame())`
is a list that has an entry named "response", but at the line the error is occuring
`terms(fr)` returns some collection of numbers, without any obvious named attributes. I am not clear on what `terms` is supposed to do, so it is possible I missed something.

In any case, I know this information isn't too helpful, so feel free to close the issue.

**Comment by bbolker** [comment]
Debugging remotely is tough, but try this:

- set `options(error = recover)`
- run the code that triggers the error
- select the correct frame (this is the tricky bit, you probably want to be within the top-level `glmmTMB` call
- `print(respCol)`
- `print(names(fr))`
- `str(fr)`

(Note that the response column isn't being set to "response"; it's being set to the "response" *attribute* of `terms(fr)`)

**Comment by bbolker** [comment]
Any chance of more information, or a reproducible example?

**Comment by bbolker** [comment]
Closing in the absence of a reproducible example or other information that would allow us to move forward ...

**Comment by edgar45328** [comment]
Hi there!
I have encountered this problem with my MixSiar.
If Brian or someone can tell me what it is about? my 'discrimination' file is even correct I guess.

Error in load_discr_data(mixsiar$discr_filename, mixsiar$mix) : 
  *** Error: Discrimination mean column names mislabeled.
    Should be 'Mean' + iso_names from mix data file, e.g. 'Meand13C' if
    mix$iso_names = 'd13C'. Please ensure headings in discr data file match
    this format and try again.
