### ISSUE TITLE
Unable to install glmmTMB on MacOS

### ISSUE THREAD

**Issue by Ele86** [glmmTMB/glmmTMB#741]
I tried to install glmmTMB in R (version 3.6.3) but I got the following error.
```
* installing *source* package ‘glmmTMB’ ...
** package ‘glmmTMB’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/username/Library/R/3.6/library/TMB/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c glmmTMB.cpp -o glmmTMB.o
clang: error: unsupported option '-fopenmp'
make: *** [glmmTMB.o] Error 1
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Users/username/Library/R/3.6/library/glmmTMB’
Warning in install.packages :
  installation of package ‘glmmTMB’ had non-zero exit status
```
Could you please help me to solve this?
Thanks.

**Comment by marcoplebani85** [comment]
Hello, I'm also using R 3.6.3, on MacOS Sierra. I failed to install `glmmTMB` from CRAN:

```
> install.packages('glmmTMB')
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘glmmTMB’
Do you want to attempt to install these from sources? (Yes/no/cancel) y
installing the source package ‘glmmTMB’

trying URL 'https://cloud.r-project.org/src/contrib/glmmTMB_1.1.2.tar.gz'
Content type 'application/x-gzip' length 3626562 bytes (3.5 MB)
==================================================
downloaded 3.5 MB

The downloaded source packages are in
	‘/private/var/folders/p3/4nbtfxfs4mb858cgg_3861400000gn/T/RtmpJO4R1o/downloaded_packages’
Warning message:
In install.packages("glmmTMB") :
  installation of package ‘glmmTMB’ had non-zero exit status
Error in loadNamespace(name) : there is no package called ‘glmmTMB’
Execution halted
```
I haven't seen `glmmTMB` on CRAN for some time, but until recently I could install it from github without issues. I tried installing it from github just now and failed:

```
> devtools::install_github("glmmTMB/glmmTMB/glmmTMB")
Downloading GitHub repo glmmTMB/glmmTMB@HEAD
✔  checking for file ‘/private/var/folders/p3/4nbtfxfs4mb858cgg_3861400000gn/T/RtmpJO4R1o/remotes2ea5ec30273/glmmTMB-glmmTMB-fa9323b/glmmTMB/DESCRIPTION’ ...
   ERROR: package installation failed
Error: Failed to install 'glmmTMB' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> * installing *source* package ‘glmmTMB’ ...
E> ** using staged installation
E> ** libs
E> clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/TMB/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -Wall -pedantic -c glmmTMB.cpp -o glmmTMB.o
E> clang: error: unsupported option '-fopenmp'
E> make: *** [glmmTMB.o] Error 1
E> ERROR: compilation failed for package ‘glmmTMB’
E> * removing ‘/private/var/folders/p3/4nbtfxfs4mb858cgg_3861400000gn/T/RtmpSM1y1h/Rinst35775a927a5/glmmTMB’
E>       -----------------------------------
E> ERROR: package installation failed
 ERROR: package installation failed
```

**Comment by marcoplebani85** [comment]
@Ele86 For the moment I was able to reinstall `glmmTMB` version 1.1.1 from [MRAN](https://mran.microsoft.com/package/glmmTMB) using:
`install.packages('glmmTMB', repos='https://mran.microsoft.com/snapshot/2021-07-07/')`

**Comment by marcoplebani85** [comment]
It looks like recent versions of glmmTMB can't be installed on R 3.6.3 at the moment. Unfortunately, Apple computers with MacOS Sierra or older cannot update to R 4.1. I updated the MacOS to Mojave so that I could update R to version 4.1. Now I see glmmTMB in the CRAN list of binary packages again, and I could install glmmTMB version 1.1.1 from CRAN without issues.

**Comment by bbolker** [comment]
The README file for this repository suggests these [tips](https://github.com/Rdatatable/data.table/wiki/Installation#openmp-enabled-compiler-for-mac) for enabling OpenMP on older versions of MacOS. This sort of thing is typically a moving target, and I don't know if those tips work any more. If someone with R 3.6.3 installed on MacOS wants to build a binary we can post it to the repository here.

**Comment by Ele86** [comment]
Hi, thanks a lot for your comments.
Indeed, with R version 3.6.3 I could not install glmmTMB. So I updated R, and with the new version (4.1.0) I was able to install it.
My MacOS is Big Sur version 11.4.

**Comment by bbolker** [comment]
I'm going to close this for now. I think that in  theory it *should* be possible to install glmmTMB on R 3.6.x under MacOS, but since the people who participated in the thread have worked around the problem by updating R, and in the absence of resources (a test platform and/or someone sufficiently interested and knowledgeable to dig in and try the various potential solutions), I don't think we can tackle this at this time. Happy to re-open if someone wants to make it a priority.
