### ISSUE TITLE
confint function not loaded

### ISSUE THREAD

**Issue by t-davidson** [glmmTMB/glmmTMB#742]
I cannot find the `confint` function after loading the glmmTMB package.

I can open the help file in RStudio using `?glmmTMB::confint.glmmTMB` but `confint` is not in the functions loaded by the package. I have tried both CRAN and the latest version from Github (glmmTMB 1.1.2.2).

![Screen Shot 2021-08-07 at 9 13 44 PM](https://user-images.githubusercontent.com/11861697/128617626-ee7cee9f-fc0b-4a52-8329-202c48f5b526.png)

I updated all packages and restarted R several times to no avail.

My computer is running MacOS Big Sur 11.2.3.

**Comment by bbolker** [comment]
Did you figure this out?  The `confint()` function is a generic function defined in the `stats` package.  The `confint.glmmTMB` method is private, so you can only look at the source code via `glmmTMB:::confint.glmmTMB`.

**Comment by t-davidson** [comment]
Yes, managed to resolve the issue. I found it quite unintuitive though, perhaps it would be prudent to mention this more clearly in the documentation.

**Comment by bbolker** [comment]
Well, this is sort of a tricky thing, as it's more a "feature" of R than anything specific having to do with the glmmTMB package. It's true that `confint` is not a function loaded by the package, but `?confint` finds the main help page for `stats::confint` just fine, `find("confint")` prints "package:stats".  I think the (possibly incorrect) assumption is that R users will already know how methods work, and that calling `foo(obj)` on an object called `obj` that has class "bar" invokes the (possibly hidden) S3 method `foo.bar()` (S4 methods are *much* harder to trace, in my opinion ...). Can you say a little bit more about the context of what you were doing/trying to do so we can (hopefully) improve the documentation?

**Comment by bbolker** [comment]
As an experienced R user it would feel redundant to me to document the fact that the `confint()` generic function lives in the `stats` package namespace rather than the `glmmTMB` namespace. The help page begins with 

> S3 method for class 'glmmTMB';   confint(...)

I'm going to close this, but I'd be happy to reopen it if there are concrete suggestions for how to improve the docs.
