### ISSUE TITLE
Using glmmTMB with mediation package

### ISSUE THREAD

**Issue by Siromujin** [glmmTMB/glmmTMB#743]
Hi! I have a mediation model where the outcome needs to be modeled with negative binomial distribution. Is there anyway I can use glmmTMB with the mediation package? 
When I tried, it produced this error 

> Error in rmvnorm(sims, mean = MModel.coef, sigma = MModel.var.cov) : sigma must be a symmetric matrix

Thank you very much!

**Comment by mebrooks** [comment]
I think we need more information, but from briefly looking at the mediation documentation, I'm guessing you would not use both packages together. You should write to R-sig-mixed (see [where to ask questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions)) and explain a bit about your data and what type of model you want to fit to it.
