### ISSUE TITLE
predict(x, re.form = ~0) doesn't work when RE variances are fixed by hand

### ISSUE THREAD

**Issue by florianhartig** [glmmTMB/glmmTMB#746]
Hi guys,

I realise it's an exotic issue, but a DHARMa user wants to check a model where parts of the RE variances were fixed by hand, which fails because population-level estimates don't work in this case.
 
Context at https://github.com/florianhartig/DHARMa/issues/303, reproducible example https://github.com/florianhartig/DHARMa/blob/master/Code/DHARMaIssues/303.R

**Comment by bbolker** [comment]
Recent versions of `glmmTMB` allow `map` and `start` parameters to be specified in-line, in which case `predict` (and presumably the downstream DHARMa methods) will work:

```r
fit2B <- glmmTMB(observedResponse ~ Environment1 + (1|group) + (1|ID), family=binomial(), data=testData,
                 start = list(theta = c(log(1e3),0)),
                 map = list(theta = factor(c(NA,1))))
predict(fit2B, re.form = ~0)                              
```

Similar models are discussed in https://github.com/glmmTMB/glmmTMB/issues/744

In this example I've hard-coded the number of parameters/position of the fixed parameter; may be working on easier/improved wrappers for these kinds of models (which will presumably be increasing rapidly in popularity).

**Comment by florianhartig** [comment]
Hi Ben,

thanks for that - this works in the sense that it doesn't create an error, however, I'm not sure if the re.form = ~0 is actually active in this case.

When I run the DHARMa residuals, using the above model creates a noticeable pattern, while "normal" model where everything is fit does not (see updated example https://github.com/florianhartig/DHARMa/blob/master/Code/DHARMaIssues/303.R). This type of diagonal pattern is typical for having predictions conditional on fitted REs on the x axis. 

To be clear: in the model above, all parameters should be fitted, except for the one RE variance, right? We would expect a good fit of the model, wouldn't we?

**Comment by bbolker** [comment]
Hmm, OK, will take a look ...

**Comment by bbolker** [comment]
Hmm.  I'm still not sure what's going on (I haven't looked at the updated example yet), but 

```r
p1 <- predict(fit2B, re.form = ~0)                             
p2 <- drop(getME(fit2B, "X") %*% fixef(fit2B)$cond)
all.equal(p1,unname(p2), tolerance=0) ## TRUE
```
suggests that we are indeed predicting without the random effects ... ?  
Even more directly:

```r
beta <- fixef(fit2B)$cond
p3 <- beta[1] + beta[2]*testData$Environment1
all.equal(p1,p3, tolerance=0)  ## TRUE
```

**Comment by bbolker** [comment]
I think this **might** be a peculiarity of the model, we might want to engage the authors of the corresponding paper to see if they've thought about it?  The intercept is unidentifiable, I thought that might be a problem, but removing it didn't seem to make a difference.

Here's what I've looked at so far. I thought I would look at the model with (unrestricted, fixed, no) random effects × prediction (with, w/o) random effects (having established upstream that no-RE prediction appears to work as expected). Using simple non-DHARMa residuals to try to focus/avoid extra moving parts.

```
## full/unrestricted model
fit2C <- glmmTMB(observedResponse ~ Environment1 + (1|group) + (1|ID),
                 family=binomial(), data=testData)

fit2E <- glmmTMB(observedResponse ~ Environment1, family=binomial(), data=testData)

get_res <- function(fit) {
    pp <- data.frame(rbind(testData, testData),
                     type=rep(c("no RE", "full RE"), each = nrow(testData)),
                     .pred = c(predict(fit, re.form = ~0, type = "response"),
                               predict(fit, type = "response")))
    pp <- transform(pp,
                    .resid = observedResponse - .pred)
    return(pp)
}
dd <- dplyr::bind_rows(list(fixed_RE=get_res(fit2B),
                      full_RE=get_res(fit2C),
                      no_RE = get_res(fit2E)),
                 .id = "model")

library(ggplot2); theme_set(theme_bw())
ggplot(dd, aes(.resid, .pred)) + geom_smooth() + geom_point() +
    facet_grid(model~type)
ggsave("dharma303.png")  
```

![dharma303](https://user-images.githubusercontent.com/78918/130120970-423c2e0b-6b02-4158-b9f4-5cd40e005f76.png)

**Comment by florianhartig** [comment]
Hi Ben,

sorry, I think I can't follow. What's your conclusion from this?

Florian

**Comment by florianhartig** [comment]
OK, never mind, I think I have understood what the problem is:

a) predict(x, re.form = ~0) works as expected

b) however, as the simulate function in glmmTMB does not (yet) include any re.form arguments (that right, isn't it?), we are re-simulating REs with a var of 10E3, which doesn't fit to the data and seems to create the residual pattern I have observed.

So, while it would be preferable to have a simulate function which can condition on the REs, this doesn't seem to be a but any more, as glmmTMB behaves as documented, so I will close the issue here and move the discussion how to deal with this back to https://github.com/florianhartig/DHARMa/issues/303.

Thanks for your help!

**Comment by florianhartig** [comment]
Sure, why not. I'll open a new issue.
