### ISSUE TITLE
Memory allocation fail in function 'MakeADGradObject' 

### ISSUE THREAD

**Issue by jenifav** [glmmTMB/glmmTMB#750]
Dataset is large 659,404 observations.  This is the model, run in a RStudio Pro server:

```r
nb.trunc <- glmmTMB(PVLS ~ as.numeric(agecat)*sex*country  + offset(log(CURR)) + (1 | facilityuid), 
                    zi = ~ 0,  disp= ~as.numeric(agecat) + sex + country, family=truncated_nbinom2, dta,
                    control=glmmTMBControl(optimizer=optim, optArgs=list(method="BFGS")))
```

It runs fine, takes a few days to complete. But when I run a summary on the object (large glmmTMB object with 7 elements and 39MB) I get:

> Error in retape(set.defaults = FALSE) : 
  Memory allocation fail in function 'MakeADGradObject'

Thanks@

**Comment by bbolker** [comment]
If you have a lot of countries it might be worth trying `sparseX=c(cond=TRUE, disp = TRUE)`. Could we see the results of `traceback()` after the error occurs?

**Comment by jenifav** [comment]
Ben, I will check in the morning, thanks for responding!  I have most of
the sub-Saharan countries in the dataset, which is why it's so huge.

**Comment by jenifav** [comment]
traceback() gives:

7: retape(set.defaults = FALSE)
6: f(par, order = 0, type = "double")
5: x$obj$env$report(x$fit$parfull)
4: VarCorr.glmmTMB(object)
3: VarCorr(object)
2: summary.glmmTMB(nb.trunc2)
1: summary(nb.trunc2)

**Comment by jenifav** [comment]
Oh, and there are 44 countries.  Not all of sub-Sahara but a lot.

**Comment by bbolker** [comment]
@kaskr could probably say in more detail, but focusing just on the size of the model matrix:

- a dense model matrix with `n` rows and `p` predictors will require `n*p*8` bytes: `as.numeric(agecat)*sex*country` means `p=176` (I think).
- a sparse model matrix with `e` non-zero elements will require much less than that (depends on how the indexing is done, but proportional to the number of non-zero elements rather than the dimensions. In the case below, it is `e*(4+8) + p`

```r
dd <- expand.grid(agecat=1:2, sex=factor(1:2), country=factor(1:44), rep=1:1000)
 nrow(dd)
## [1] 176000
m <- model.matrix(~agecat*sex*country, dd)
ncol(m)
## [1] 176
format(object.size(m), "Mb")
## [1] "247.1 Mb"
(176e3*176*8)/1e6
## [1] 247.808
m2 <- Matrix::sparse.model.matrix(~agecat*sex*country, dd)
format(object.size(m2), "Mb")
## [1] "22.7 Mb"
```

This problem is about 1/3 the size of yours, but there's a 10-fold decrease in the memory needed for the model matrix. This is not the only way that memory is used, but it's very low-hanging fruit/room for improvement.

**Comment by jenifav** [comment]
Forgive my ignorance, is there something for me to do for improvement? You
probably just told me but I'm not understanding.

**Comment by bbolker** [comment]
No problem. If you can try re-running your model with the added argument `sparseX=c(cond=TRUE, disp = TRUE)` ... (for more rapid experimentation, you could take a (say) 10% random subset of your data and run models with and without the `sparseX=` argument, using the `peakRAM` package to see how memory usage is affected, e.g. something **approximately** like:

```r
set.seed(101)
nn <- nrow(dta)
keep_vals <- sample(seq(n), size = round(0.1*n), replace=FALSE)
dta_small <- dta[keep_vals,]
library(peakRAM); library(glmmTMB)
p1 <- peakRAM(m1 <- glmmTMB(..., data=dta_small))  ## ... is replaced with full model above
p1s <- peakRAM(s1 <- summary(m1))
p2 <- peakRAM(m2 <- update(m1, sparseX=c(cond=TRUE, disp = TRUE))
p2s <- peakRAM(s2 <- summary(m2))
```

You won't get the error with the smaller data subset, of course, but the experiments should run a lot faster and it should be possible to get a sense of how much sparsity would help.

**Comment by jenifav** [comment]
Ok, I understand!  I'll get back to you. The model with the full data takes
a few days so, not knowing what will happen, I'll get back to you ASAP.
Thanks!

**Comment by bbolker** [comment]
Hopefully the 10% model will only take a few hours.  If you have multiple cores available you might experiment with `control = glmmTMBControl(parallel = 4L)` (that's 4 cores - you could try more, although parallelization also has memory consequences ...)

**Comment by jenifav** [comment]
I'll give it a shot!

**Comment by jenifav** [comment]
Sorry, Ben, I will likely get to this next week.  The holiday weekend meant
some last minute things that needed doing RIGHT NOW came up.  But this is
still important to me.  Thanks for your help and patience!

**Comment by bbolker** [comment]
Let us know how it goes.

**Comment by jenifav** [comment]
OK, so I ran this:

set.seed(1011)
nn <- nrow(dta)
keep_vals <- sample(seq(nn), size = round(0.1*nn), replace=FALSE)
dta_small <- dta[keep_vals,]
library(peakRAM); library(glmmTMB)
p1 <- peakRAM(m1 <- glmmTMB(PVLS ~ as.numeric(agecat)*sex*volume + volume*country +as.numeric(agecat)*country + sex*country + offset(log(CURR)) + (1 | facilityuid), 
                            zi = ~ 0,  disp= ~as.numeric(agecat) + sex + country + volume, family=truncated_nbinom2, dta_small,
                            control=glmmTMBControl(optimizer=optim, parallel = 4L,
                                                   optArgs=list(method="BFGS"))))
p1s <- peakRAM(s1 <- summary(m1))
p2 <- peakRAM(m2 <- update(m1, sparseX=c(cond=TRUE, disp = TRUE)))
p2s <- peakRAM(s2 <- summary(m2))

```
> p1
                                                                                                                                                                                                                                                                                                 Function_Call
1 m1<-glmmTMB(PVLS~as.numeric(agecat)*sex*volume+volume*country+as.numeric(agecat)*country+sex*country+offset(log(CURR))+(1|facilityuid),zi=~0,disp=~as.numeric(agecat)+sex+country+volume,family=truncated_nbinom2,dta_small,control=glmmTMBControl(optimizer=optim,parallel=4L,optArgs=list(method="BFGS")))
  Elapsed_Time_sec Total_RAM_Used_MiB Peak_RAM_Used_MiB
1          1102.52               44.6             770.8
> p1s
    Function_Call Elapsed_Time_sec Total_RAM_Used_MiB Peak_RAM_Used_MiB
1 s1<-summary(m1)            0.179               -0.1              12.4
> p2
                                  Function_Call Elapsed_Time_sec Total_RAM_Used_MiB Peak_RAM_Used_MiB
1 m2<-update(m1,sparseX=c(cond=TRUE,disp=TRUE))          1098.23               22.2             799.1
> p2s
    Function_Call Elapsed_Time_sec Total_RAM_Used_MiB Peak_RAM_Used_MiB
1 s2<-summary(m2)            0.162                0.1              12.4
```

**Comment by bbolker** [comment]
Hmm, not sure what to make of this: based on what's above, there doesn't seem to be much difference between the sparse and non-sparse runs.  If you have the computational resources handy, I would probably start a run with the `sparseX` stuff enabled on the full data set, to see if it runs ... in the meantime I might start ramping up the example above to larger fractions of the data set to see how it scales. (I'm not entirely sure that `peakRAM` accurately captures memory that's used by TMB - that might be handled outside of R's memory management. The other thing to do is to keep an eye on an external system monitor to see how the memory allocation changes over the course of each of these runs.  (What OS are you using?)

**Comment by jenifav** [comment]
Hi Ben,

I ran it on the full dataset starting yesterday so I will check it on
Monday.  As for OS, it's my work's RStudio Pro server, so it's some kind of
Linux.  But I am probably restricted on some of the background metrics.

Thanks!

**Comment by jenifav** [comment]
So, I ran the same model on the full dataset:




```
p3 <- peakRAM(m1 <- glmmTMB(PVLS ~ as.numeric(agecat)*sex*volume + volume*country +as.numeric(agecat)*country + sex*country + offset(log(CURR)) + (1 | facilityuid), 
                            zi = ~ 0,  disp= ~as.numeric(agecat) + sex + country + volume, family=truncated_nbinom2, dta,
                            control=glmmTMBControl(optimizer=optim, parallel = 4L,
                                                   optArgs=list(method="BFGS"))),
                            sparseX=c(cond=TRUE, disp = TRUE))
> p3
                                                                                                                                                                                                                                                                                           Function_Call
1 m1<-glmmTMB(PVLS~as.numeric(agecat)*sex*volume+volume*country+as.numeric(agecat)*country+sex*country+offset(log(CURR))+(1|facilityuid),zi=~0,disp=~as.numeric(agecat)+sex+country+volume,family=truncated_nbinom2,dta,control=glmmTMBControl(optimizer=optim,parallel=4L,optArgs=list(method="BFGS")))
2                                                                                                                                                                                                                                                                                 c(cond=TRUE,disp=TRUE)
  Elapsed_Time_sec Total_RAM_Used_MiB Peak_RAM_Used_MiB
1         11854.89              460.9            2052.9
2             0.00                0.0               0.0

> p3s <- peakRAM(s1 <- summary(m1))
> p3s
    Function_Call Elapsed_Time_sec Total_RAM_Used_MiB Peak_RAM_Used_MiB
1 s1<-summary(m1)            1.043                  0              27.3

```

The funny thing is the first time I ran p3s <- peakRAM(s1 <- summary(m1)) I got this error:

Error in retape(set.defaults = FALSE) : 
  Memory allocation fail in function 'MakeADGradObject'
Timing stopped at: 424.8 155.9 25.58

But I ran it again and it completed with the above result.  So, perhaps this is a server "glitch"?  It does seem to run smoother and faster with these options.

**Comment by bbolker** [comment]
So did you succeed in getting an answer? If so, I'll close this.  (I can't speak for all of the details of memory allocation and release on an RStudio server, but if you're running close to the limit I wouldn't be surprised if things got a bit unpredictable ...)

**Comment by jenifav** [comment]
Sorry Ben, I didn't.  I have a ticket request out to the server admins about it.  I would say go ahead and close this.  You gave me some useful functions and I thank you for that.

**Comment by bbolker** [comment]
OK.  My last point is that using `parallel = 4` will incur a tradeoff between speed & memory; if you use `parallel = 1` and `sparseX`, the fit will be slower but should be the most memory-efficient.
