### ISSUE TITLE
update Readme.md

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#764]
I'm really struggling to get my new laptop set up, so I don't have time right now to fix this, but wanted to document it. Along the way, I discovered that this link is broken https://www.rstudio.com/products/rpackages/devtools/. 
Also, the `devtools::dr_devtools()` function doesn't seem to work.
```
> library(devtools)
Loading required package: usethis
> dr_devtools()
Error in dr_devtools() : could not find function "dr_devtools"
> devtools:::dr_devtools()
Error: object 'dr_devtools' not found
```

**Comment by bbolker** [comment]
I think this is all done.
