### ISSUE TITLE
emmeans support: recover_data needs to use component 

### ISSUE THREAD

**Issue by rvlenth** [glmmTMB/glmmTMB#780]
This was reported on the **emmeans** issues page: at https://github.com/rvlenth/emmeans/issues/328. When using `emmeans` and `component` is other than the default, we don't necessarily obtain the needed data to build the reference grid. That is because the `recover_data` method needs to know which component also. It is simple to fix. Simply add that argument and pass it in the call to `terms()`:
```
recover_data.glmmTMB <- function (object, component = "cond", ...) 
{
    fcall <- getCall(object)
    if (!requireNamespace("emmeans")) 
        stop("please install (if necessary) and load the emmeans package")
    emmeans::recover_data(fcall, delete.response(terms(object, component = component)), 
        attr(model.frame(object), "na.action"), ...)
}
```
I could create a PR for this (and will do so if you wish), but it seems simpler to just let you make these changes.

**Comment by bbolker** [comment]
Will close once PR is merged ...
