### ISSUE TITLE
Problems getting model residuals with non significant deviation 

### ISSUE THREAD

**Issue by shannonfinn8** [glmmTMB/glmmTMB#783]
Hello,

This is my first time working with glmmTMB, so apologies in advance if my questions seem somewhat basic.

I am currently working with a dataset where my response is bear energetic expenditure (value ranges from 163- 539, with data heavily skewed to the left) at given hourly locations. I have six fixed effects (both numeric and categorical) and one random effect (Bear ID), My dataset is quite large with >77,000 points among 28 individual animals. I have attached a screen grab here of a section from my data. 

I have tried out a number of different model types ( poisson without random effects, poisson with random effects, nbinom1 and nbinom2), however my DHARMa residuals remain significantly deviated for every model (see attached). What am I doing wrong here or what other model type should I be using to get a better fit with this kind of data?

I would appreciate any help or advice

Thank you
![DHARMa residual_binomial1](https://user-images.githubusercontent.com/88739986/151072615-9ae5490f-bc04-446f-8ec5-ddce9c73a09d.png)
![sample_data](https://user-images.githubusercontent.com/88739986/151072622-09b41ff5-f6a5-46e1-96c9-a2a5b6b993e0.jpg)
![HIST](https://user-images.githubusercontent.com/88739986/151072642-c2cc7ffa-6546-4367-a8b4-206890a201be.png)

**Comment by bbolker** [comment]
This is a more appropriate question for CrossValidated or the r-sig-mixed-models mailing list (see [here](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions)), but some *very* brief diagnosis/advice:

 I doubt that count-response models (Poisson, nbinom) make sense for your data anyway.  My first try would definitely be a log-response model, i.e. `log(energy) ~ [predictors]`.  That may or may not be enough to fix your model; my next step would be to look at the `DHARMa` vignette, especially the section on "Detecting missing predictors or wrong functional assumptions".

**Comment by shannonfinn8** [comment]
I forgot to mention that log transformation does not change the data much or model fit.

Thank you for your assistance 
Best
