### ISSUE TITLE
Estimate Discrepancy Between 2 Complementary Models

### ISSUE THREAD

**Issue by jjohnston123** [glmmTMB/glmmTMB#785]
I am running into a bit of an issue and am unsure whether it is due to a bug or a lack of background knowledge. I have data on the presence of lesions of 2 types (inflammatory or non-inflammatory) in 3 different locations. I have run 2 different logistic mixed models:

Example 1: Lesion presence is the response variable with predictors of location and lesion type with a random effect of subject ID.

[Example 1.csv](https://github.com/glmmTMB/glmmTMB/files/8019085/Example.1.csv)

example1<-read.csv("Example 1.csv",header=T)
as.factor(example1$ID)->example1$ID
as.factor(example1$Location)->example1$Location
as.factor(example1$LesionType)->example1$LesionType
as.factor(example1$LesionPresence)->example1$LesionPresence

model.example1<-glmmTMB(LesionPresence ~ Location*LesionType + (1 | ID), data=example1, family="binomial")

emmeans.example1<-emmeans(model.example1, ~Location*LesionType, type="response")

 Location LesionType  prob     SE  df lower.CL upper.CL
 0        0          0.838 0.0447 365    0.731    0.908
 1        0          0.712 0.0557 365    0.592    0.809
 2        0          0.750 0.0600 365    0.615    0.849
 0        1          0.603 0.0593 365    0.483    0.712
 1        1          0.667 0.0580 365    0.545    0.770
 2        1          0.654 0.0660 365    0.516    0.770

Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 

Example 2: Treating inflammatory vs non-inflammatory as a mutually exclusive binary categories with location as a predictor and a random effect of subject ID.

[Example 2.csv](https://github.com/glmmTMB/glmmTMB/files/8019082/Example.2.csv)

example2<-read.csv("Example 2.csv",header=T)
as.factor(example2$ID)->example2$ID
as.factor(example2$Location)->example2$Location
as.factor(example2$Inflammatory)->example2$Inflammatory

model.example2<-glmmTMB(Inflammatory ~ Location + (1 | ID), data=example2, family="binomial")

emmeans.example2<-emmeans(model.example2, ~Location, type="response")

 Location  prob     SE  df lower.CL upper.CL
 0        0.891 0.0493 182    0.750    0.957
 1        0.767 0.0711 182    0.600    0.879
 2        0.802 0.0715 182    0.625    0.908

Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 

The csv data inputs (attached) for example 1 and example 2 have the same arithmetic means for inflammatory lesions in the 3 different locations. However, the emmeans outputs for example 1 but not example 2 equals these arithmetic means. I was expecting both models to produce the same estimates. I've also noticed that if I remove the random effect for example 1, nothing changes. However, if I remove the random effect for example 2, then the estimated means for inflammatory lesions across both examples are equal.

Any insight into where I may be going wrong?

**Comment by bbolker** [comment]
without going into too much detail, it probably has to do with bias adjustment: see https://cran.r-project.org/web/packages/emmeans/vignettes/transformations.html#bias-adj .  Please follow up on `r-sig-mixed-models@r-project.org` or CrossValidated (see https://github.com/glmmTMB/glmmTMB#where-to-ask-questions ) ...
