### ISSUE TITLE
Memory allocation fail in function 'MakeADGradObject'

### ISSUE THREAD

**Issue by lararof** [glmmTMB/glmmTMB#802]
Hello!

I've been trying to run a model:
```
glm1<- glmmTMB(abundance ~ as.factor(year) + (point | transect), data=d, family=nbinom2(link="log"),
                    control = glmmTMBControl(optCtrl = list(iter.max=1e3,eval.max=1e3),profile=TRUE, parallel = 1),
                    sparseX=c(cond=TRUE, disp = TRUE)) 
```

but I'm always having the same error:

> Error in retape_adgrad(lazy = TRUE) : 
>   Memory allocation fail in function 'MakeADGradObject'

I added the `sparseX=c(cond=TRUE, disp = TRUE)`  and `parallel=1` after reading the other issue opened for this mistake but it's still not working.

I don't really have that much data. My table has less than 5000 lines and only 4 columns. I have 8 years, 640 points and 64 transects. I'm counting abundance of one species, so they are always discrete values and not very high. 

I've tried to run the model in two different computers but it's still not working. I'm doing this in Rstudio version 4.1.2.

My traceback() is:
```
9: retape_adgrad(lazy = TRUE)
8: retape(set.defaults = TRUE)
7: MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg, 
       profile = "beta", silent = !verbose, DLL = "glmmTMB")
6: eval(substitute(expr), data, enclos = parent.frame())
5: eval(substitute(expr), data, enclos = parent.frame())
4: with.default(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg, 
       random = randomArg, profile = "beta", silent = !verbose, 
       DLL = "glmmTMB"))
3: with(TMBStruc, MakeADFun(data.tmb, parameters, map = mapArg, 
       random = randomArg, profile = "beta", silent = !verbose, 
       DLL = "glmmTMB"))
2: fitTMB(TMBStruc)
1: glmmTMB(formule, data = d, family = nbinom2(link = "log"), control = glmmTMBControl(optCtrl = list(iter.max = 1000, 
       eval.max = 1000), profile = TRUE, parallel = 1), sparseX = c(cond = TRUE, 
       disp = TRUE))
```

I was wondering if since the last open issue on this problem maybe someone would have a clue of how I can fix this error and have some results?

Thank you so much!

**Comment by bbolker** [comment]
the `(point | transect)` term in your model looks potentially problematic; if `point` is a factor, then this will mean the model is trying to estimate a 640 x 640 covariance matrix.

Can you try running with `doFit = FALSE` and post the output of `str(glm1$data.tmb)` ?

**Comment by bbolker** [comment]
closing this in the absence of actionable information ....
