### ISSUE TITLE
issue when fitting tweedie distribution with the new version of glmmTMB 

### ISSUE THREAD

**Issue by KarinePrince** [glmmTMB/glmmTMB#811]
Hi,

I had to update my version of glmmTMB, and after that the versions of TMB and Matrix package to have glmmTMB  running!). Now that these package dependencies issues seem to be fixed, I now have this Error message showing up:
```
Error in MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg,  : 
  Link not implemented!
```
the model I am running is the following (and was running perfectly before I updated all these packages...)

> trenddensite.glmm <- glmmTMB(densité ~ annee_sc + Secteur + (1|Num_sitefi), family = tweedie, data= zerofilldata_cheveche.df)

I guess it says that tweedie link is not implemented in this new package version, isn't?

Thanks in advance for your help!

**Comment by mebrooks** [comment]
We definitely kept the tweedie distribution, so I'm not sure why that's happening. Could you try restarting R and then running this code?
```
library(glmmTMB)
library(tweedie)

nobs = 100; phi = 2; p = 1.7
set.seed(101)
x = exp(runif(nobs, 1, 2))
m = -1.5; b = 10
mu = exp(m*log(x)+b)
y = rtweedie(nobs, mu=mu, phi=phi, power=p)
dat=data.frame(x=x, y=y)

twm = glmmTMB(y ~ log(x), family=tweedie, data=dat)
summary(twm)
```
Do you get the same error?

**Comment by KarinePrince** [comment]
I get this error message for glmmTMB
`Warning messages:
1: package ‘glmmTMB’ was built under R version 4.1.2 
2: In checkDepPackageVersion(dep_pkg = "TMB") :
  Package version inconsistency detected.
glmmTMB was built with TMB version 1.8.0
Current TMB version is 1.8.1
Please re-install glmmTMB from source or restore original ‘TMB’ package (see '?reinstalling' for more information)`

**Comment by KarinePrince** [comment]
ok. I think I may have found the remaining issue after updating the package...
I got this new error message when loading the different packages requested to run all the models (glm and glmm) in my code:
```
library(statmod)

Attaching package: ‘statmod’

The following object is masked from ‘package:glmmTMB’:

    tweedie
```

So I restarted R, and loaded only _glmmTMB_ to specifically run my glmmTMB model, and it seems to finally work... until the next update ;-)

Thanks for you help!

**Comment by bbolker** [comment]
Is this a common enough problem that we want to re-open/write a warning? It shouldn't be too hard to detect, e.g. somewhere around [here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R#L268) (`if (family$family == "Tweedie") ...`) (looks like `statmod` uses uppercase T - or (`if (find("tweedie")[1] == "package:statmod") [and not `link %in% names(.valid_link)` ...]
