### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Tulasgit** [glmmTMB/glmmTMB#822]
Hi,

I keep getting this message when I try to install the package. I tried many things written online but didn't help.

clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/TMB/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp -fPIC  -Wall -g -O2  -c glmmTMB.cpp -o glmmTMB.o
clang: error: unsupported option '-fopenmp'
make: *** [glmmTMB.o] Error 1
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/glmmTMB’
Warning in install.packages :
  installation of package ‘glmmTMB’ had non-zero exit status

What should I do?

**Comment by bbolker** [comment]
Please see https://glmmtmb.github.io/glmmTMB/#macos-compilation-issues=

>    If you get errors about unsupported option '-fopenmp' you need to turn off OpenMP compilation by adding the line SHLIB_OPENMP_CFLAGS= to your ~/.R/Makevars file. If you’ve already done step #1 this file will already exist; use a text editor to add the line above. Otherwise, you need to create it.

> After updating your compilers (if necessary) and turning off OpenMP compilation, re-try the installation from source.

Is there any particular reason you're (apparently) using R version 3.6, which is quite old at this point?

**Comment by bbolker** [comment]
Did you try the suggested fix? I'm going to close this for now, but will re-open if you come back with further related questions.
