### ISSUE TITLE
glmmTMB fails on OS X

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#823]
I have an error from CRAN checks in one of my packages:
https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/insight-00check.html

This occurs on
> using R version 4.2.0 (2022-04-22)
> using platform: aarch64-apple-darwin20 (64-bit)
> using session charset: UTF-8

and I believe this is a _glmmTMB_ issue.

The error:

```
checking tests ... [27s/38s] ERROR
  Running ‘spelling.R’ [0s/0s]
  Running ‘testthat.R’ [27s/38s]
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Error in `.Call("getParameterOrder", data, parameters, new.env(), NULL,
      PACKAGE = DLL)`: Incorrect number of arguments (4), expecting 3 for 'getParameterOrder'
  Backtrace:
      ▆
   1. └─glmmTMB::glmmTMB(...) at test-glmmTMB.R:24:2
   2. └─glmmTMB::fitTMB(TMBStruc)
   3. ├─base::with(...)
   4. └─base::with.default(...)
   5. └─base::eval(substitute(expr), data, enclos = parent.frame())
   6. └─base::eval(substitute(expr), data, enclos = parent.frame())
   7. └─TMB::MakeADFun(...)
  
  [ FAIL 5 | WARN 1 | SKIP 14 | PASS 2025 ]
  Error: Test failures
  Execution halted
checking for unstated d
```

The failing example:

```r
library(glmmTMB)
data("fish")
m1 <- glmmTMB(
  count ~ child + camper + (1 | persons),
  ziformula = ~ child + camper + (1 | persons),
  data = fish,
  family = truncated_poisson()
)
```

**Comment by bbolker** [comment]
This is a typical glmmTMB/TMB/Matrix binary stack incompatibility problem, I think.  I assume it happens because TMB has been updated to a new version. This means we need to push a new version of glmmTMB as soon as possible ... @mebrooks @kaskr  ? cf. https://github.com/glmmTMB/glmmTMB/issues/794 ; https://github.com/glmmTMB/glmmTMB/issues/651 ; etc.

I see that `broom.mixed` is also failing.

**Comment by kaskr** [comment]
Nothing to do with the recent update of TMB - this is a CRAN issue and it must have been there for a while:

```
Package version inconsistency detected.
    glmmTMB was built with TMB version 1.7.22
    Current TMB version is 1.8.1
```

**Comment by mebrooks** [comment]
I have time to work on this tomorrow (Wednesday).

**Comment by bbolker** [comment]
@kaskr I admit I'm confused, but there's definitely something strange, and I think new, going on with CRAN checks (as I mentioned, [broom.mixed is failing with the same error](https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/broom.mixed-00check.html)). I don't understand how this could happen, but I do think it's new. Maybe updating TMB triggers a re-check but the packages aren't up to date yet?? (I see that the MacOS binaries for TMB are still on 1.8.1 ...)

In any case, there will just be increasing amounts of fallout from stuff like this, and from users who are getting errors, so we should go ahead and push a new `glmmTMB` to (hopefully) resolve this issue.

**Comment by strengejacke** [comment]
Will this issue appear every now and then in the future as well, or can this be "permanently" resolved? If not, is there a way to skip tests under certain conditions? (like: checking available package versions of TMB and glmmTMB)?

**Comment by bbolker** [comment]
Not quite sure what the question is here. As mentioned somewhere else, there is an `up2date()` function that will update previously fitted `glmmTMB` objects to make them work with a newly installed version of TMB ...

There is also an exported `checkPackageDepVersion()` utility.

**Comment by bbolker** [comment]
Bump.  Is there anything more we can do here?
