### ISSUE TITLE
add ordered-beta family

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#835]
This [post](https://www.robertkubinec.com/post/limited_dvs/) gives a nice formulation for an ordered-beta family that handles zeros and ones by censoring:

![image](https://user-images.githubusercontent.com/78918/177602877-a7bdf19b-60d6-4b00-93be-a998959d38f9.png)

I'm not sure why we use the link function $g()$ rather than the CDF of the beta for the censoring calculations, but we could adjust that if we wanted.

The only part of this that's awkward at all is the fact that we need to pass the cutpoint parameters $k_1$, $k_2$ to TMB (as 'data', not as parameters - I can't see any use case in which we would want to optimize these values). We could abuse the `size` data-value for this, since it is otherwise only used in the binomial family, but maybe we should add another `extra_parms` vector in the data? Would that break backward compatibility more than abusing `size`?

**Comment by mebrooks** [comment]
I like the idea of `extra_parms` since it would be more readable and extendable for other things that could come up. Since they aren't exactly parameters in the TMB sense, maybe it would be better to call it something like `extra_vals`. If the default value is `NULL`, then would that break backward compatibility?

**Comment by bbolker** [comment]
This issue is addressed by https://github.com/glmmTMB/glmmTMB/pull/867 . We don't really need any `extra_parms`, we can put it in `thetaf`.  Unlike a censored model (which this *isn't*), the cutpoints k1 and k2 are estimated parameters, not a priori specified values (and, there is no problem with differentiability to worry about).
