### ISSUE TITLE
lme4::bootMer (no longer?) works for glmmTMB

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#836]
``` r
library(glmmTMB)

m1 <- glmmTMB(
  count ~ mined + (1 | site),
  zi =  ~ mined,
  family = poisson,
  data = Salamanders
)

boot_fun <- function(model) {
  lme4::fixef(model)[[1]]
}

lme4::bootMer(m1, boot_fun)
#> Error in eval(expr, p): trying to get slot "call" from an object (class "glmmTMB") that is not an S4 object
```

<sup>Created on 2022-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We got a feedback from a user who said that bootstrapping using `parameters::bootstrap_parameters()` worked with _glmmTMB_ before, but now no longer works. From what I found out, the issue seems to be `bootMer()` (see reprex). Is there anything that has changed, or didn't this work before anyway?

**Comment by koenvanbenthem** [comment]
Dear Daniel,

this seems to have been fixed in the current github version of lme4, if you
install that, it should work again.

see commit:
https://github.com/lme4/lme4/commit/43a4c49071c54806e17eda2ef93a7eb8a80aba36

Best,

Koen

Op do 7 jul. 2022 om 09:15 schreef Daniel ***@***.***>:

**Comment by bbolker** [comment]
Just submitted a new version of lme4 to CRAN, should fix this.
