### ISSUE TITLE
NOBOUND option to unbound covariance parameter estimates?

### ISSUE THREAD

**Issue by SchmidtPaul** [glmmTMB/glmmTMB#840]
Does `glmmTMB()` have an option similar to [NOBOUND in SAS](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.3/statug/statug_mixed_syntax11.htm#statug.mixed.parmsstmt_nobound), which *"requests the removal of boundary constraints on covariance parameters. For example, variance components have a default lower boundary constraint of 0, and the NOBOUND option allows their estimates to be negative."*?

**Comment by bbolker** [comment]
No.

The variance parameters are fitted on a log-standard-deviation scale.  There is no option to change this. If you *really* wanted to you could hack the code to change the fitting scale, but it would be a lot of work.

(In `lme4` the variances are fitted on an unlogged scale, and it would be possible in principle to try the optimization without the bounds, but Doug Bates [author of `lme4`] has always maintained that this wouldn't make any sense ...)

A negative variance estimate is impossible; in cases where the best fit variance appears to be negative, this can usually be translated into an equivalent case of a compound symmetric structure with negative correlations. (I have thought about figuring this out/writing it up but have never gotten around to it.)
