### ISSUE TITLE
Differences in estimation between R 4.2.1 and R devel (on Windows 11)

### ISSUE THREAD

**Issue by strengejacke** [glmmTMB/glmmTMB#848]
Here are two model, where results slightly differ between current R and R devel (version from today)_

```r
library(glmmTMB)
library(lme4)
data(cake)
set.seed(123)
m1 <- suppressWarnings(glmmTMB(angle ~ temperature + (temperature | recipe) + (temperature | replicate), data = cake))
m3 <- suppressWarnings(glmmTMB(angle ~ temperature + (temperature | recipe), data = cake))
```

(download: [glmmTMB.zip](https://github.com/glmmTMB/glmmTMB/files/9392515/glmmTMB.zip))

The differences (both in fixed and random effects coefficients) are not large, but I just wanted to point out anyway, just in case this is something that could or should be fixed. You can see the differences from the `summary()`, but also random effects coefficients and their confidence intervals slightly differ (e.g., for some parameters, CIs could be estimated under R devel, but not under R 4.2.1):

```r
library(glmmTMB)
load("glmmTMB.RData")
confint(m1_r421, "theta_")
confint(m1_redevel, "theta_")
```

**Comment by strengejacke** [comment]
This _might_ be related to having categorical random slopes, because I found no differences between R 4.2.1 and R devel for these two models:

```r
data(sleepstudy)
set.seed(123)
sleepstudy$Months <- sample(1:4, nrow(sleepstudy), TRUE)

set.seed(123)
m2 <- glmmTMB(Reaction ~ Days + (Days | Subject), data = sleepstudy)
m5 <- suppressWarnings(glmmTMB(Reaction ~ Days + (Days + Months | Subject), data = sleepstudy))
```

**Comment by bbolker** [comment]
@mebrooks @kaskr does anyone feel like digging into this ... ??

**Comment by mmaechler** [comment]
Note that particularly model `m1` is very unstable, in other words largely over-parametrized, .. very very different BTW than the model that was fit with `lmer()` in the example of  `help(cake)`.
For a largely over-parametrized model as this (where  a `lmer()` fit duly warns about singularities),
it does make sense that you see differences in the fit between platforms, R versions, ... dada ..

I'd propose to close this as not relevant. Only sensible models which *can* be stable should be required to give results that are very close.

**Comment by mmaechler** [comment]
Apropos:  I've preached numerous times that people who just wrap warnings  with `suppressWarnings()`  should be punished ..  ;-)

**Comment by bbolker** [comment]
OK with me. It occurs to me one could set up a (tedious) `git bisect` on a Github repo of R (Winston Chang's or another) where each step re-built R, ran the code, and compared it to the 4.2.1 results ... but I'm willing to decide that we don't have time and energy for that.

**Comment by strengejacke** [comment]
Yes, that's fair enough. I wasn't seeking for a particular solution to this issue, I just realized this when writing tests - I tested against results from `summary()`, and these tests pass on one system, but fail on another. And I thought about reporting it in case you can pull something useful out of this related to finding possible bugs.

@mmaechler That said, the examples are over-parameterized for the particular reason that we wanted to test different outputs of random effects (including curious edge cases), and hence also the warning was expected. We suppressed it to not mess up the output from our tests with (in this case) "irrelevant" messages and warnings. :-) I would never suppress any alert from functions you wrote ;-)
