### ISSUE TITLE
Non-positive-definite Hessian matrix and factor variables

### ISSUE THREAD

**Issue by harD2** [glmmTMB/glmmTMB#849]
I am trying to run a simple zero-inflated model (resp ~ ordered(disease_activity)). Disease activity is measured subjectively on a 5-point scale, but non-zeroes only occur after the first activity level. 

I get the model convergence error and based on your troubleshooting guide, I think the problem is that my lowest-level activity contains only zero observation (per troubleshooting guide, I think this statement applies here: "when complete separation occurs in a binomial model: some categories in the model contain proportions that are either all 0 or all 1"). 

If I run a model with resp ~ unclass(disease_activity), then I am able to fit what appears to be a reasonable model, where I can see a relationship between response and disease activity. Is this a reasonable workaround? I can't find any suggestions in the troubleshooting file for this issue.

**Comment by bbolker** [comment]
This might be better for r-sig-mixed-models@r-project.org, but ...

Your problem does sound like complete separation. If you `unclass(disease_activity)`, you are treating disease activity as *integer-valued*, which is not necessarily what you want - that will assume that levels are equally spaced. This is sometimes an acceptable shortcut, but has a lot of potential problems (i.e. floor/ceiling effects, nonlinearity/unequal spacing, etc.). The more principled solution is to *regularize* the model. There is (still!!) no way to do this in glmmTMB (#387) but you can achieve this effect in `GLMMadaptive` (frequentist), or in pretty much any Bayesian machine (`blme`/`rstanarm`/`brms`/`MCMCglmm`)

- [package comparison](https://docs.google.com/spreadsheets/d/19itelYaVW0U0gtNtRfqh76ZGt1awlamNcJwT71u_5Uk/edit#gid=1836440275) (there is a "regularization" feature column but not much listed)
- [reddit thread](https://www.reddit.com/r/rstats/comments/obim0k/mixed_models_with_regularization/) (not too much additional information here, but for completeness)


My reproducible example below doesn't actually give a non-pos-def Hessian, but exhibits the usual pathologies of complete separation (large parameter estimates, ridiculous Wald SEs [see "Hauck-Donner effect"])

```r
> set.seed(101)
> dd <- data.frame(d = ordered(rep(1:5, each = 10)))
> library(glmmTMB)
> dd$resp <- ifelse(dd$d=="1", 0, rbinom(50, size = 1, prob = 0.5))
> m1 <- glmmTMB(resp ~ d, data = dd, family = binomial)
> m1
Formula:          resp ~ d
Data: dd
      AIC       BIC    logLik  df.resid 
 62.59799  72.15810 -26.29899        45 

Number of obs: 50

Fixed Effects:

Conditional model:
(Intercept)          d.L          d.Q          d.C          d^4  
     -4.515       13.205      -12.499        7.243       -2.456  
> with(dd, table(d, resp))
   resp
d    0  1
  1 10  0
  2  4  6
  3  4  6
  4  6  4
  5  7  3
> summary(m1)
 Family: binomial  ( logit )
Formula:          resp ~ d
Data: dd

     AIC      BIC   logLik deviance df.resid 
    62.6     72.2    -26.3     52.6       45 


Conditional model:
             Estimate Std. Error z value Pr(>|z|)
(Intercept)    -4.515   4043.388  -0.001    0.999
d.L            13.205  12786.316   0.001    0.999
d.Q           -12.499  10806.409  -0.001    0.999
d.C             7.243   6393.158   0.001    0.999
d^4            -2.456   2416.387  -0.001    0.999
> class(unclass(dd$d))
[1] "integer"
```

**Comment by harD2** [comment]
Okay, thanks very much for the clarification and suggestions. In my research context, I think it would be safe to assume linearity but I will see if I can manage to get these more nuanced approaches working instead.

**Comment by bbolker** [comment]
FWIW, this works now with the `priors` branch:

```r
set.seed(101)
dd <- data.frame(d = ordered(rep(1:5, each = 10)))
library(glmmTMB)
dd$resp <- ifelse(dd$d=="1", 0, rbinom(50, size = 1, prob = 0.5))
m1 <- glmmTMB(resp ~ d, data = dd, family = binomial, prior = data.frame(prior = "normal(0,3)", class = "beta"))
```
