### ISSUE TITLE
[Feature Request] A guide on what random-effects covariance structure to use

### ISSUE THREAD

**Issue by DexterGlass** [glmmTMB/glmmTMB#856]

**Comment by bbolker** [comment]
I appreciate the need, but I'm afraid this is way too broad a request; this would be more of a book chapter ... and I'm not aware of a great resource I can point you to. (There is some discussion of correlation/covariance structures  in the `MCMCglmm` course notes https://mran.microsoft.com/snapshot/2018-08-24/web/packages/MCMCglmm/vignettes/CourseNotes.pdf , and some discussion in Pinheiro and Bates's book ...)  Feel free to ask on `r-sig-mixed-models@r-project.org` or CrossValidated; it would definitely help to have a more specific example ... (see also https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions )
