### ISSUE TITLE
how does AICtab() define the number of parameters in AIC?

### ISSUE THREAD

**Issue by DexterGlass** [glmmTMB/glmmTMB#857]
2k*-2ln(L)=AIC. What is k?

The df(Residual) is the sample size minus the number of parameters being estimated, so it becomes df(Residual) = n - (k+1) or df(Residual) = n - k - 1. It's often easier just to use subtraction once you know the total and the regression degrees of freedom

If k*=df(residual). What is n and what is k?

https://cran.r-project.org/web/packages/glmmTMB/vignettes/miscEx.html

**Comment by bbolker** [comment]
As is fairly standard in mixed models, the number of observations is defined as the number of non-`NA` observations (this is after incomplete cases are dropped - TBH I'm not sure what the `!is.na()` is needed for), and `k` is defined as the total number of *top-level* parameters (i.e. parameters controlling fixed effects and the (co)variances of random effects -- not including the `b` vector of random effect deviations).

See https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#can-i-use-aic-for-mixed-models-how-do-i-count-the-number-of-degrees-of-freedom-for-a-random-effect for more information/references.

```r
> glmmTMB:::nobs.glmmTMB
function (object, ...) 
sum(!is.na(object$obj$env$data$yobs))
> glmmTMB:::df.residual.glmmTMB
function (object, ...) 
{
    nobs(object) - length(object$fit$par)
}
```
