### ISSUE TITLE
There is no function to extract the lag-dependent covariance matrix of the random effects or the residual of random-effects or fitted-values of the random-effects [feature-request]

### ISSUE THREAD

**Issue by DexterGlass** [glmmTMB/glmmTMB#859]

**Comment by DexterGlass** [comment]
(m1 <- glmmTMB(count ~ mined + (1|site),
  zi=~mined,
  family=poisson, data=Salamanders))
summary(m1)
vcov(m1)

Conditional model:
            (Intercept)     minedno
(Intercept)  0.05423294 -0.05327991
minedno     -0.05327991  0.06058959

Zero-inflation model:
               zi~(Intercept)  zi~minedno
zi~(Intercept)     0.05526613 -0.05455748
zi~minedno        -0.05455748  0.06864418

I was looking for the time-dependent variance-covariance matrix of the random-effects rather than how the random-intercept and random-slope co-vary.

**Comment by bbolker** [comment]
- This model doesn't have random slopes, just a random intercept.
- There is no time-dependence in the random effects in this model.
- There are no correlations among any of the random effects in this model (by assumption). glmmTMB doesn't have an easy way for you to extract the full covariance matrix of the random effects, but if it did you would see that it's diagonal ... There will only be correlations among the random effects for *vector-valued* random effects, i.e. a random effect term with something other than `1` on the left-hand side of the bar in the RE term ...

I really think that these questions would be better handled on `r-sig-mixed-models@r-project.org`, and with **more context** for what you're trying to do ...
