### ISSUE TITLE
ranef applied to tweedie or t_family models

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#870]
If we use `ranef` on a model without random effects, with `family =tweedie` or `t_family`, then it gives this error:
```
Error in ss[rownames(ss) == "b", "Std. Error"] : 
  no 'dimnames' attribute for array
In addition: Warning message:
In summary.sdreport(object$sdr, "random") :
  no or empty summary selected via 'select = %s'"random"
```

I'm not sure if this is a recent change. I came across this while trying `confint` with these types of models. It happens there because `confint` calls `ranef` on every model, even if it doesn't have random effects.

```
set.seed(101)
dd <- data.frame(y = 3 + 5*rt(1000, df = 10))
m1 <- glmmTMB(y ~ 1, family = t_family, data = dd)
ranef(m1)
```

```
library(glmmTMB)
library(tweedie)
nobs = 100; phi = 2; p = 1.7
set.seed(101)
x = exp(runif(nobs, 1, 2))
m = -1.5; b = 10
mu = exp(m*log(x)+b)
y = rtweedie(nobs, mu=mu, phi=phi, power=p)
dat=data.frame(x=x, y=y)
twm = glmmTMB(y ~ log(x), family=tweedie, data=dat)
ranef(twm)
```

**Comment by mebrooks** [comment]
I like the second option (change "thetaf" to something else globally) because my first guess will probably always be that code objects named "theta" have to do with random effects.

**Comment by bbolker** [comment]
@kaskr added this variable initially (for Tweedie).  Maybe call it `betas` (for "shape") or `betap` (for power)? Not sure what the "f" was supposed to denote ... The other potential can of worms -- do we ever imagine wanting to build linear sub-models for these terms (e.g. have different shape parameters according to a factor)? In general that seems ambitious, but you never know ...

I used `thetaf(0)` and `thetaf(1)` for the two cut-point parameters in `ordbetareg`. If we want the design to accommodate linear submodels, then we would need to have a different name for each parameter of a family (i.e. `beta` = location, `betad` = scale, `betas` = shape, `betas2`? = fourth family-specific parameter ...)

**Comment by kaskr** [comment]
@bbolker The 'f' was chosen to signify *family* specific. Feel free to change to whatever you prefer.

**Comment by bbolker** [comment]
changing to `psi`.

**Comment by bbolker** [comment]
Hmmm.  Changing the name works (I think), **but** will break backward compatibility in two ways: 

* stored glmmTMB objects will need to be updated (I think I can hack `up2date` to fix this ...)
* code that explicitly sets starting values for `thetaf` will break

I think the first is the bigger problem, but I think I can fix it by modifying `up2date` ...
