### ISSUE TITLE
Ordered beta regression: "Error in fitTMB(TMBStruc) :    negative log-likelihood is NaN at starting parameter values"

### ISSUE THREAD

**Issue by cmrnp** [glmmTMB/glmmTMB#883]
Hi,

Filing an issue as discussed on Mastodon last week: https://fosstodon.org/@cameronpat/109384912045096958

I get the negative log-likelihood is NaN error with almost every dataset I try to fit an ordered beta model to, using glmmTMB 1.1.5, R 4.2.2, Windows 10 64-bit.

I have a reprex here; it could probably be made even simpler: https://gist.github.com/cmrnp/bcccec7b0c6bd042ac45674fa05db15d

That produces an error for me every time I run it, I guess if you want to be truly reproducible I can confirm that set.seed(42) gives the error. If you omit the random effect, I still get an error, but this time it's "some elements of gradient are NaN at starting parameter values".

Let me know if I can help chase this down at all.

Cheers,

Cam

**Comment by bbolker** [comment]
I pushed a fix to https://github.com/glmmTMB/glmmTMB/tree/ordbeta_start_fix (still have to add tests).  Let me know if either the workaround or the updated branch (`remotes::install_github("glmmTMB/glmmTMB/glmmTMB@ordbeta_start_fix")`) work for you?

**Comment by cmrnp** [comment]
Thanks!!! That fixes it, to the extent that the model now converges. 

For my 'real' data, the fixed effect point estimates agree with ordbetareg::ordbetareg() to one decimal place but the standard errors are very different - some of the glmmTMB SEs are close to half the SEs from ordbetareg. Some of the random effect estimates are quite different too, which may be related. I have permission to share this data with you (but not publicly), let me know if you'd like to see it.

**Comment by bbolker** [comment]
Great. I think I would like to see it. 
Some possible reasons for differences in uncertainty:

* a bug of some sort (seems somewhat unlikely since the same machinery is used here for computing SEs as in all other, better-tested glmmTMB families, but always a possibility)
* glmmTMB is reporting Wald SEs, brms is presumably reporting the posterior standard deviations. Comparing profile likelihood confidence intervals (`confint(., method = "profile")` or `method = "uniroot"`) to `ordbetareg`/`brms` credible intervals might be closer.
* effects of priors
* conditional (Wald/profile) vs integrated (marginal posterior) uncertainty assessment

**Comment by cmrnp** [comment]
I suspect it's either point 2 or point 4 in your list above, although the difference in random effect variances gave me some hesitance.

I tried profile likelihood CIs and... the NaN errors are back!

```
> confint(m_ordbeta_glmmtmb, method = "profile")
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': missing values in object
In addition: Warning message:
In nlminb(start, newfn, newgr, control = control) :
  NA/NaN function evaluation
```

**Comment by bbolker** [comment]
Annoying but not shocking.  Profile CIs are under-exercised/tested.  I'll see what I can do (after I get a less-fun task accomplished).

**Comment by bbolker** [comment]
Are the NaN errors there for the tiny reprex or for your real data?  For the tiny reprex, I think the data set is too small so the Wald estimates are terrible so the whole thing falls apart.  Working through the Pew data example [here](https://github.com/glmmTMB/glmmTMB/blob/ordbeta_start_fix/misc/ordbeta.R), the profile looks OK ...

**Comment by bbolker** [comment]
The tiny reprex was failing because profile CIs are unbounded below for theta (RE variance) parameters. I've made profile CIs more robust, so that the tiny reprex also works (reports NA when the CIs are unbounded below ... could report `-Inf` instead but that would require more logic). Try again?

**Comment by bbolker** [comment]
Any luck on this? I would take a look at data if you send it ...

**Comment by bbolker** [comment]
I'm going to assume this is resolved, can reopen if necessary.
