### ISSUE TITLE
Degrees of freedom used by emmeans after fitting a model in glmmTMB

### ISSUE THREAD

**Issue by davidatkaritane** [glmmTMB/glmmTMB#893]
I recently noticed that emmeans uses the residual degrees of freedom when calculating a confidence interval after fitting a glm in glmmTMB, even when there is no dispersion parameter (and hence only fixed effects).

This differs from standard practice, where the degress of freedom would be set to Inf, as happens when emmeans is used after fitting such a model with glm(.).

I can understand why one might want to do this (a bit more conservatism in the interval, to allow for the fact that df=Inf is justified by asymptotics), but I thought I should check what the glmmTMB team had in mind when they chose this option.

I contacted Russell Lenth, who maintains emmeans, and he suggested I discuss it with the glmmTMB team.

**Comment by bbolker** [comment]
Can you provide a reproducible example? The behaviour you're describing isn't immediately obvious, at least with the current development/master branch on GitHub.

```
library(glmmTMB)
library(emmeans)
salamander1 <- up2date(readRDS(system.file("example_files","salamander1.rds",package="glmmTMB")))
confint(emmeans(salamander1, ~ mined))
```
```
 mined emmean     SE  df asymp.LCL asymp.UCL
 yes   0.0879 0.2329 Inf    -0.369     0.544
 no    1.2298 0.0909 Inf     1.052     1.408
```
```
> packageVersion("emmeans")
[1] ‘1.8.4.1’
> packageVersion("glmmTMB")
[1] ‘1.1.5.9000’
> 
```

**Comment by davidatkaritane** [comment]
My apologies - I should have done that first time...

```
library(emmeans)
library(glmmTMB)

n<-10
a<-1
b<-1

x<-1:n
mu<-exp(a+b*x)
y<-rpois(n,mu)
d<-data.frame(y=y,x=x)

m1<-glm(y~x,family=poisson,data=d)
emmeans(m1,~x)
```

```
   x emmean      SE  df asymp.LCL asymp.UCL
 5.5    6.5 0.01369 Inf     6.473     6.526

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```

Thus df=Inf after using glm

```
m2<-glmmTMB(y~x,family=poisson,data=d)
emmeans(m2,~x)
```

```
   x emmean      SE df lower.CL upper.CL
 5.5    6.5 0.01369  8    6.468    6.531

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```
Thus df=residual df after using glmmTMB

```
packageVersion("emmeans")
[1] ‘1.8.4.1’

packageVersion("glmmTMB")
[1] ‘1.1.5’
```

**Comment by bbolker** [comment]
Hmm.  I didn't think this had changed, but maybe @rvlenth fixed it along with some recent updates.  Can you try `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")` and see what you get?  (If it indeed changes we should note this in the NEWS file for the development version ...)

**Comment by davidatkaritane** [comment]
The installation failed for some reason (details below)

```
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'glmmTMB'
* removing 'C:/Users/david/OneDrive/Documents/R/win-library/4.1/glmmTMB'
Warning messages:
1: In missing_devel_warning(pkgdir) :
  Package glmmTMB has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools (https://cran.r-project.org/bin/windows/Rtools/).Then use the pkgbuild package, or make sure that Rtools in the PATH.
2: In i.p(...) :
  installation of package ‘C:/Users/david/AppData/Local/Temp/RtmpUpsE09/file1d0858bcc1f/glmmTMB_1.1.5.9000.tar.gz’ had non-zero exit status
```

**Comment by bbolker** [comment]
In order to install a development version you need to have compiler tools installed: see [here](https://cran.r-project.org/bin/windows/Rtools/). (In the meantime I'll work on building/pushing an updated Windows binary to our repository, but that will take a little while ...)

**Comment by rvlenth** [comment]
I didn't *consciously* change the df in my recent pull request, but that might have slipped in inadvertently somehow.

Trying the example (which is not completely reproducible because we don't know the random-number seed):
```
> set.seed(2023.0222)  # makes this reprodicible
> library(emmeans)
> library(glmmTMB)
> 
> n<-10
> a<-1
> b<-1
> 
> x<-1:n
> mu<-exp(a+b*x)
> y<-rpois(n,mu)
> d<-data.frame(y=y,x=x)
> m2<-glmmTMB(y~x,family=poisson,data=d)
> emmeans(m2,~x)
   x emmean     SE  df asymp.LCL asymp.UCL
 5.5  6.498 0.0137 Inf     6.472     6.525

Results are given on the log (not the response) scale. 
Confidence level used: 0.95

> packageVersion("glmmTMB")
[1] ‘1.1.5.9000’
```
... I *do* get `Inf` d.f., fwiw. This is using the version I installed from source yesterday.

**Comment by bbolker** [comment]
Confirming that using a fresh CRAN install of 1.1.5 does give df=8 rather than df=Inf.  I think I will go ahead and document this in the NEWS file and consider this issue resolved ...

**Comment by davidatkaritane** [comment]
All good now, after `remotes::install_github("glmmTMB/glmmTMB/glmmTMB")` (I already had RTools 4.2 installed but had to re-install it to make this work).

```
set.seed(2023.0222) 
library(emmeans)
library(glmmTMB)

n<-10
a<-1
b<-1

x<-1:n
mu<-exp(a+b*x)
y<-rpois(n,mu)
d<-data.frame(y=y,x=x)

m1<-glm(y~x,family=poisson,data=d)
emmeans(m1,~x)

```
```
   x emmean     SE  df asymp.LCL asymp.UCL
 5.5  6.498 0.0137 Inf     6.472     6.525

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 

```
```
m2<-glmmTMB(y~x,family=poisson,data=d)
emmeans(m2,~x)
```
```
   x emmean     SE  df asymp.LCL asymp.UCL
 5.5  6.498 0.0137 Inf     6.472     6.525

Results are given on the log (not the response) scale. 
Confidence level used: 0.95 
```

```
packageVersion("emmeans")
[1] ‘1.8.4.1’
packageVersion("glmmTMB")
[1] ‘1.1.5.9000’
```

I also get df=Inf after glmmTMB now :-)
