### ISSUE TITLE
Multiple membership

### ISSUE THREAD

**Issue by clairerichardsRN** [glmmTMB/glmmTMB#898]
I am wondering if it is possible to add/have a way to include multiple membership in glmmTMB. I can see the wrapper is only for lme4 but I have a zero-inflated negative binomial model that I need glmmTMB for: [Multi member](https://jvparidon.github.io/lmerMultiMember/)

**Comment by bbolker** [comment]
I think this could possibly be hacked in the same way as here: https://bbolker.github.io/mixedmodels-misc/notes/multimember.html (which is the same technique as used in the linked package, the package is just smoother/nicer to use), especially with the `doOptim=FALSE` option, but will have to find time to take a look ...

* set up model with a dummy random effect
* hack the model data appropriately to substitute the modified `Z` matrix
* optimize
* ? construct fitted model object ?

**Comment by bbolker** [comment]
I've modified glmmTMB a little bit for convenience to make the "hacking" version of this reasonably straightforward.  Search for "glmmTMB" in [this document](https://bbolker.github.io/mixedmodels-misc/notes/multimember.html) (you'll need to run the first few chunks to set up the simulated example and construct the membership matrix ...)

**Comment by bbolker** [comment]
@clairerichardsRN , does my previous comment/link address your problem?
