### ISSUE TITLE
In this recent vignette....

### ISSUE THREAD

**Issue by clairerichardsRN** [glmmTMB/glmmTMB#901]
I've been looking at this [vignette](https://cran.r-project.org/web/packages/glmmTMB/vignettes/sim.html) because I have a similar zero-inflated model with an offset, and I'm confused about why the negperchick is calculated with the simulation results rather than comparing sibling negotiation between the original and simulated data. I'm wondering is it ok to just compare the sibling negotiation?

**Comment by bbolker** [comment]
Sure.  I would say that we compared negotiations per chick, rather than per brood, because the original study was interested in chick-level behaviour (unconfounded by variation in brood size).

**Comment by clairerichardsRN** [comment]
@bbolker , I think what is confusing to me about this, and likely due to my lack of understanding of how offsets work, is how the response from the simulation does not appear to take into account the offset and so the response is not the rate, even though that's the intention of my regression. I notice that with ggeffects, the offset is taken into consideration, but if I don't think it still is if I set type="simulate"
