### ISSUE TITLE
ZI to model the logit of probability of being non-zeros

### ISSUE THREAD

**Issue by wsdlk** [glmmTMB/glmmTMB#904]
I am working on zero-inflated Poisson data. My understanding is "zi" formula models the logit of the probability of being the latent "0" group.  I am wondering if there is a setting to reverse the order of the latent "0" and "1" group so that  "zi" formula models the logit of the probability of being the latent "1" group (outcome is not 0). The interpretation of the coefficients from the logistic part would be more natural in my case.
Or is it valid to change the sign of the output of the logistic part for interpretation purposes?

**Comment by bbolker** [comment]
It is absolutely valid to change the sign of the 'zi' coefficients for interpretation. It's so easy that I wouldn't consider it worth implementing a polarity-switching argument unless someone were paying me to develop glmmTMB :-)
