### ISSUE TITLE
Installing glmmTMB

### ISSUE THREAD

**Issue by sculpin99** [glmmTMB/glmmTMB#916]
Thanks kindly in advance. I used glmmTMB successfully for some time, but now do have an issue calling summary() and/or using broom.mixed to extract components from a previously created glmmTMB model object. 
 (I have not made the code reproducible as I don't think it applies: this issue would exist with any glmmTMB model object regardless of specifics):

```
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
#have also tried installing the binary via
#install.packages(glmmTMB)
#and the source via
#install.packages(glmmTMB, type = 'source')

mod <- readRDS('mod.Rds')
mod
#Formula: case ~ (1 | t_step) + elevation...
#Error in .Call("MakeDoubleFunObject", data, parameters, reportenv, PACKAGE = DLL) : 
#Incorrect number of arguments (3), expecting 4 for 'MakeDoubleFunObject'

class(mod)
#[1] "glmmTMB"

#_________________________________________________________________________________________________________
sessionInfo()
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/Anchorage
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmTMB_1.1.7.9000

loaded via a namespace (and not attached):
 [1] crayon_1.5.2        nlme_3.1-162        cli_3.6.1           processx_3.8.1      minqa_1.2.5         prettyunits_1.1.1  
 [7] TMB_1.9.4           rprojroot_2.0.3     pkgbuild_1.4.1      ps_1.7.5            lme4_1.1-33         grid_4.3.0         
[13] MASS_7.3-58.4       numDeriv_2016.8-1.1 compiler_4.3.0      Rcpp_1.0.10         rstudioapi_0.14     lattice_0.21-8     
[19] nloptr_2.0.3        R6_2.5.1            curl_5.0.1          splines_4.3.0       callr_3.7.3         Matrix_1.5-4.1     
[25] tools_4.3.0         boot_1.3-28.1       remotes_2.4.2       desc_1.4.2         
```

**Comment by bbolker** [comment]
See if the `up2date` function does what you need ...

**Comment by sculpin99** [comment]
No, it yields:
`Error in TMB::MakeADFun(data, parameters, map = map, random = random,  : 
  A map factor length must equal parameter length`

**Comment by bbolker** [comment]
Can you post a link to your `mod.Rds` file?

**Comment by sculpin99** [comment]
I will try to figure that out, bear with me here...

**Comment by bbolker** [comment]
OK. (Note I'm also about to leave work so won't be responding instantaneously either.)

**Comment by sculpin99** [comment]
I tried to upload to github, but my model objects are all > 200 MB. Thanks for trying to help. I'll figure it out by Monday

**Comment by sculpin99** [comment]
Here's a link, sorry it's so big, all my saved model objects are about this size:
https://drop.state.ak.us/drop/pickup.php?claimID=u27xRQRFsJZ8sRpX&claimPasscode=r8h7STJ25eyfcJg3  
Thanks kindly for your quick reply today, greatly appreciated. Have a pleasant weekend.

**Comment by sculpin99** [comment]
> Can you post a link to your `mod.Rds` file? (Does this happen with _all_ stored glmmTMB fits, i.e. including freshly made ones, or just with fits that were created with previous versions of the package and then stored?)

I haven't worked on these in a while, so I have no fresh ones. If the new version of glmmTMB is functioning for me, I will attempt to run a 'fresh' model when I get back to work. Thanks heaps.

**Comment by bbolker** [comment]
There's a discrepancy in the stored model between the `map` and the `parameters` component. It's possible to work around this (see below), but it's fussy - I'm a little bit puzzled how this discrepancy could have arisen in the first place/how previous versions of `glmmTMB` could have accepted it (it's *possible* that an earlier version of `TMB`, the underlying platform, would silently accept this ... but, as shown below, some kinds of mismatches lead to segmentation faults ...) Were you fitting this model with the variance fixed à la Muff et al 2020?  

A few tangential notes:
- for Muff et al.'s approach, you don't need to do the two-phase stuff any more (first fit with `doFit = FALSE`, then adjust the `map` component, then optimize) - the `map` argument can be set directly in the `glmmTMB` call
- you've got a lot of terms of the form `(1|id) + (0 + a|id) + (0 + b|id) + ...` You can specify these more compactly as `diag(1 + a + b + ... | id)` or `(1 + a + b + ... || id)` (although it shouldn't make any difference)

```r
x <- readRDS("glmmTMB_GH916_mod.Rds")
## retrieve environment of underlying TMB object
ee <- x$obj$env

## find mismatch
length(maptheta <- ee$map$theta)  ## 9
length(partheta <- ee$parameters$theta)  ## 8

library(glmmTMB)
try(up2date(x))
## Error in TMB::MakeADFun(data, parameters, map = map, random = random,  : 
##   A map factor length must equal parameter length

## check original call
x$call
## how many random effects terms are there?
##  equal to length of theta [because each term is a scalar/one-parameter effect]
length(lme4::findbars(x$call$formula))  ## 9
## initially tried, incorrectly, to *shorten* parameters$theta instead of lengthening map$theta
if (FALSE) {
    ee$map$theta <- factor(ee$map$theta[1:8])
    x2 <- up2date(x)  ## uh-oh, crash
}
## lots of acrobatics to create an extended version of parameters$theta
##  with all of the correct structures attached
aa <- attributes(ee$parameters$theta)
aa <- aa[setdiff(names(aa), c("dim", "dimnames"))]
th <- array(c(ee$parameters$theta, 0), dim = 9L,
            dimnames = list(1:9))
for (nm in names(aa)) {
    attr(th, nm) <- aa[[nm]]
}
## compare (only differences should be lengths of some components)
waldo::compare(ee$parameters$theta, th)
## reset internal value
ee$parameters$theta <- th
x2 <- up2date(x)
print(x2)
```

```
Formula:          case ~ (1 | dr_step) + ln_sl + cos_ta + closed_decay_100_s +  
    not_closed_decay_100_s + elevation_s + slope_s + slope_sq +  
    thinned + unthinned + unharv_noncomm + (0 + closed_decay_100_s |  
    deerID) + (0 + not_closed_decay_100_s | deerID) + (0 + slope_s |  
    deerID) + (0 + slope_sq | deerID) + (0 + elevation_s | deerID) +  
    (0 + thinned | deerID) + (0 + unthinned | deerID) + (0 +  
    unharv_noncomm | deerID)
Data: season_data
      AIC       BIC    logLik  df.resid 
 908521.4  908731.6 -454241.7    471659 
Random-effects (co)variances:

Conditional model:
 Groups   Name                   Std.Dev.
 dr_step  (Intercept)            1.0000  
 deerID   closed_decay_100_s     0.2247  
 deerID.1 not_closed_decay_100_s 0.2904  
 deerID.2 slope_s                0.3000  
 deerID.3 slope_sq               0.1886  
 deerID.4 elevation_s            1.9098  
 deerID.5 thinned                0.3816  
 deerID.6 unthinned              0.5830  
 deerID.7 unharv_noncomm         0.2534  

Number of obs: 471678 / Conditional model: dr_step, 47859; deerID, 60

Fixed Effects:

Conditional model:
           (Intercept)                   ln_sl                  cos_ta  
            -24.572117                0.027264               -0.105067  
    closed_decay_100_s  not_closed_decay_100_s             elevation_s  
             -0.060565                0.063240               -0.720558  
               slope_s                slope_sq                 thinned  
              0.056240               -0.163494                0.010526  
             unthinned          unharv_noncomm  
              0.125821                0.002685  
```

Muff, Stefanie, Johannes Signer, and John Fieberg. “Accounting for Individual-Specific Variation in Habitat-Selection Studies: Efficient Estimation of Mixed-Effects Models Using Bayesian or Frequentist Computation.” Journal of Animal Ecology 89, no. 1 (2020): 80–92. https://doi.org/10.1111/1365-2656.13087.

**Comment by sculpin99** [comment]
Thanks kindly Ben for taking the time!
Yes, this was set up in accordance with Muff et al. 2020.
Those are much more compact model specs, I will follow one of those forms in the future.
Thanks again, I'll let you know how it goes!
Dave.

**Comment by bbolker** [comment]
Feel free to close this if everything works out for you. I still don't understand how the stored fit came to exist (my best guess is that you had a mismatch in parameters/map that was somehow tolerated in an earlier version of TMB and now throws an error, although that seems unlikely ...)  - but we might never know.

**Comment by sculpin99** [comment]
Thanks heaps for the assistance, I did close the issue.
________________________________
