### ISSUE TITLE
`predict(..., re.form = NA)` still seems to want random factors

### ISSUE THREAD

**Issue by rvlenth** [glmmTMB/glmmTMB#923]
A user reported a problem using `emmeans()` in a complicated model with `component = "response"`, and I traced it down to a `predict()` line in `emm_basis.glmmTMB()`. Here's a reprex:
``` r
library(glmmTMB)
mod0 <- glmmTMB(count ~ mined*spp + (1|site), zi = ~mined*spp, 
                family = nbinom2 , data = Salamanders)
## Warning in fitTMB(TMBStruc): Model convergence problem; singular convergence
## (7). See vignette('troubleshooting')

grid <- structure(list(mined = structure(c(1L, 2L, 1L, 2L, 1L, 2L), 
                                         levels = c("yes", "no"), class = "factor"), 
                       spp = structure(c(1L, 1L, 2L, 2L, 3L, 
                                         3L), levels = c("GP", "PR", "DM", "EC-A", "EC-L", "DES-L", "DF"
                                         ), class = "factor")), row.names = c(NA, 6L), class = "data.frame")

predict(mod0, newdata = grid, type = "response", 
        re.form = NA, se.fit = TRUE, cov.fit = TRUE)
## Error in eval(predvars, data, env): object 'site' not found

packageVersion("glmmTMB")
## [1] '1.1.7'


```
<sup>Created on 2023-07-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Apparently, even though I specified `re.form = NA`, it is still expecting the random factor `site` to still be in `grid`.

Another particularly odd aspect of this bug is that for this particular example, this error does not occur with `emmeans()`,
even though `emm_basis.glmmTMB` makes the same `predict()` call:
``` r
library(emmeans)
emmeans(mod0, ~ spp|mined, component = "response", 
        at = list(spp = c("GP", "PR", "DM")))
## mined = yes:
##  spp emmean     SE  df asymp.LCL asymp.UCL
##  GP  0.0341 0.0380 Inf   -0.0403     0.109
##  PR  0.0959 0.0613 Inf   -0.0243     0.216
##  DM  0.3876 0.1506 Inf    0.0926     0.683
## 
## mined = no:
##  spp emmean     SE  df asymp.LCL asymp.UCL
##  GP  2.1806 0.3769 Inf    1.4418     2.919
##  PR  0.4240 0.1421 Inf    0.1455     0.703
##  DM  2.4118 0.4236 Inf    1.5815     3.242
## 
## Confidence level used: 0.95
```
For my user's more complicated model (which has several random effects) , however, the `emmeans()` call fails.

*Note: My initial posting had some typos. This corrected one will make more sense.*

**Comment by bbolker** [comment]
This should be resolved in https://github.com/glmmTMB/glmmTMB/pull/924 . Try it out (with `remotes::install_github("glmmTMB/glmmTMB/glmmTMB@reform_pred_NA")`) ?

**Comment by rvlenth** [comment]
Many thanks. This works as well for the example I mentioned.
