### ISSUE TITLE
prepare version 1.1.8 for CRAN

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#925]
I don't feel strongly about this, but we should at least consider posting a new version to CRAN before July 21 (July 21 - Aug 7 is CRAN's summer break)?

- we could pull in the `lognorm_dist` and (!!) `mgcv_smooths` PRs (the latter is perhaps a little undercooked, but we would get more feedback/visibility if it were on CRAN ...)
- there's a fairly lightweight improvement (allowing pop-level prediction with `newdata` without explicitly adding the variables that are needed for the random-effects terms) [here](https://github.com/glmmTMB/glmmTMB/pull/924)

In a perfect world, we would get a new `TMB` version posted to CRAN (@kaskr ...) first, *then* post the new `glmmTMB`, which would prevent all of the warning messages about the binary stack (`Matrix → TMB → glmmTMB`) being out of sync ...

I'm not sure we need to do much to prepare other than bump version number/run checks including reverse-dep checks/make sure NEWS is appropriately updated ... ? It is probably *not* worth trying to squeeze in any new features/bug fixes though.

**Comment by kaskr** [comment]
A new TMB version (1.9.5) was submitted today.

**Comment by bbolker** [comment]
@mebrooks do you want to go for it, or wait?

**Comment by mebrooks** [comment]
Yes, I should be able to do this tomorrow.

**Comment by mebrooks** [comment]
There's a problem that shows up when I do `R CMD check --as-cran` and when I test on [Winbuilder](https://win-builder.r-project.org/0qW8kZZ4J5zj/00check.log), but now when I do `make test`. 
```
══ Failed ══════════════════════════════════════════════════════════════════════
  ── 1. Failure ('test-methods.R:653:5'): bad inversion in vcov ──────────────────
  all(is.na(vcov(m)$cond)) is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
```
I don't have much energy left today. So I will probably pick this up in the morning.

**Comment by mebrooks** [comment]
The error didn't show up on [R 4.2.3](https://win-builder.r-project.org/45k4ZVq0mfSk/00check.log), but it did on the later versions.

**Comment by mebrooks** [comment]
I have too much other work to do right now, so I'm not going to be able to get this done before the break. We can have it ready by the time they get back.

**Comment by bbolker** [comment]
understood/no problem.

**Comment by bbolker** [comment]
I've added windows and macos binaries to the repository, so if people are desperate to avoid TMB warnings we can tell them to try installing from there ...

**Comment by bbolker** [comment]
I added an  `if (getRVersion() >= "4.3.0")` clause that apparently makes things happier on GitHub actions, at least for the default check (running the "all OS" check now ...).  It would be nice to figure out exactly where this is and isn't failing; I don't think it's that important (and it would be a huge pain) to figure out exactly why an unstable fit was giving `NA` values (non-pos-def Hessians) on some platforms and not on others, but it's nice not to skip tests more than necessary ...

**Comment by mebrooks** [comment]
I'm going to try to find time to work on this next week.

**Comment by mebrooks** [comment]
The same as above, there's an error on the current version of R run on Windows, but I can't replicate it on my Mac and I'm away from my Windows computer for the next 2 weeks. @bbolker, you marked this as an unreliable test in the commit last month. Do you have any better ideas?

```
══ Failed ══════════════════════════════════════════════════════════════════════
  ── 1. Failure ('test-methods.R:655:9'): bad inversion in vcov ──────────────────
  all(is.na(vcov(m)$cond)) is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
  
  ══ DONE ════════════════════════════════════════════════════════════════════════
 ```

**Comment by bbolker** [comment]
Bump ... I don't think we should let this one example hold up the entire release (although I admit I have no good way to mark this as "we should get back to this someday", other than opening a separate issue that we will never deal with :-( )

I think it would be a good idea to

- merge https://github.com/glmmTMB/glmmTMB/pull/947 (even though as I say there, `diagnose()` could still be hardened a little bit more ...)
- make sure `NEWS` is updated with anything we've done. (Does anyone have good strategies for updating NEWS in branches? I often hesitate because I know it's likely to create merge conflicts ...) `simulate_new()` is a new function that deserves to be documented ...

**Comment by mebrooks** [comment]
> The same as above, there's an error on the current version of R run on Windows, but I can't replicate it on my Mac and I'm away from my Windows computer for the next 2 weeks. @bbolker, you marked this as an unreliable test in the commit last month. Do you have any better ideas?
> 
> ```
> ══ Failed ══════════════════════════════════════════════════════════════════════
>   ── 1. Failure ('test-methods.R:655:9'): bad inversion in vcov ──────────────────
>   all(is.na(vcov(m)$cond)) is not TRUE
>   
>   `actual`:   FALSE
>   `expected`: TRUE 
>   
>   ══ DONE ════════════════════════════════════════════════════════════════════════
> ```

Should we temporarily remove this test?  It still shows up on [R version 4.3.1](https://win-builder.r-project.org/2UzX49L2N95m) and [R Under development](https://win-builder.r-project.org/lkU638HA3Bgo).

**Comment by mebrooks** [comment]
Ok. I made the change directly on the master branch and am testing on WinBuilder again.

**Comment by mebrooks** [comment]
It passes tests on WIndows now. In reference to the list above, I see that you put `simulate_new` in the news file, so we're ready for CRAN, right?

**Comment by bbolker** [comment]
Go for it ... (in other news, our downloads badge is now reporting 1 million downloads ...)

**Comment by mebrooks** [comment]
We almost passed, but got this note

> Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: Rd \usage sections, Result: NOTE
 Documented arguments not in \usage in documentation object 'VarCorr.glmmTMB':
   'extra'

 > Documented arguments not in \usage in documentation object 'expandDoubleVert':
   'a'

 > Documented arguments not in \usage in documentation object 'mkTMBStruc':
   'zioffset' 'doffset'

 

> Functions with \usage entries need to have the appropriate \alias
>  entries, and all their arguments documented.
>  The \usage entries must correspond to syntactically valid R code.
>  See chapter 'Writing R documentation files' in the 'Writing R
>  Extensions' manual.

**Comment by bbolker** [comment]
I think I've fixed these (I guess the CRAN doc checks are improving ...) I removed the unused `doffset` and `zioffset` args from `mkTMBStruc` - I think these have to be specified by a `+offset()` term in the corresponding formulas ... ?

**Comment by mebrooks** [comment]
It was accepted just now and should be out soon. Yay!

**Comment by bbolker** [comment]
Ugh, we have a [check failure under macos-x86_64](https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/glmmTMB-00check.html), in the same place as the check was failing on Windows (because a model that was *supposed* to have an uninvertible Hessian actually has an invertible one ...)

```
Running the tests in ‘tests/AAAtest-all.R’ failed.
Last 13 lines of output:
  ══ Failed ══════════════════════════════════════════════════════════════════════
  ── 1. Failure ('test-methods.R:656:9'): bad inversion in vcov ──────────────────
  all(is.na(vcov(m)$cond)) is not TRUE
  
  `actual`: FALSE
  `expected`: TRUE
  ```

I don't know if we should push a patched version with `skip_on_os("mac", arch = "x86_64")` added?

**Comment by bbolker** [comment]
And now the [checks as of 14 October](https://cran.r-project.org/web/checks/check_results_glmmTMB.html) **aren't** failing any more ... ??  (Cross-ref to https://github.com/glmmTMB/glmmTMB/commit/243639e012f10b9c92f86b3725216a2b6ee346e0 )
