### ISSUE TITLE
Map factor must equal parameter length

### ISSUE THREAD

**Issue by elianemccarthy** [glmmTMB/glmmTMB#934]
I would like to use this code to run a glmmTMB with a large fixed variance, as described in Muff et al. (2019): 

#defining model
TMBStruc1 <- glmmTMB(case_ ~ -1 + veg_class + fire_class + (1|step_id_) + (0 + veg_class|id) + (0 + fire_class|id), family=poisson, data=datsambar_fire_steps, doFit = FALSE)

#fixing variance
TMBStruc1$parameters$theta[1] = log(1e3)
TMBStruc1$mapArg = list(theta = factor(c(NA, 1:2)))

#running model
glmmTMB:::fitTMB(TMBStruc1)

But I get this error and the model does not run:
Error in MakeADFun(data.tmb, parameters, map = mapArg, random = randomArg,  :
  A map factor length must equal parameter length

Could you please explain what this error means. Many thanks in advance.

**Comment by mebrooks** [comment]
`TMBStruc1$mapArg = list(theta = factor(c(NA, 1:2)))` assumes that there are 3 random effect coefficients, which makes sense if `veg_class` and `fire_class` were continuous, but not if they're factors. If you fit the model normally, how many coefficients are shown in  `VarCorr(TMBStruc1)`? This should be the length of theta.

Please see [advice on where to ask questions](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions).

**Comment by bbolker** [comment]
For what it's worth you can do this more compactly/in one step:

```r
TMBStruc1 <- glmmTMB(case_ ~ -1 + veg_class + fire_class + (1|step_id_) + diag (0 + veg_class+fire_class|id) ,
    family=poisson, 
    data=datsambar_fire_steps,
    map = list(theta = factor(c(NA, 1:nf))),
    start = list(theta = c(log(1e3), rep(0, nf)))
)
```

where `nf` is the correct value ...
