### ISSUE TITLE
Model convergence issues with null model and reduced model, but not with full model

### ISSUE THREAD

**Issue by MCP95** [glmmTMB/glmmTMB#940]
Hi there, 

I am trying to fit a full and a null model to my data in order to perform a full-null-model comparison and it seems like my full model does converge whereas the null model and another reduced model do not. 
As I was able to fit the full model to the data I don't have a good feeling to change the model structure based on the convergence issues with the null model. 
Does anyone have an idea why it could be that I have convergence issues with the simple but not the more complex model?

## Full model

```r
glmmTMB (proportion_looking_time ~ condition * z.trial.nr +
                                                   (1 + condition.code + z.trial.nr|| participant) + 
                                                   (1 | video.id), 
                                                 family=beta_family,
                                                 data=xdata)


Summary: 

Family: beta  ( logit )
Formula:          proportion_looking_time ~ condition * z.trial.nr + (1 + condition.code +  
    z.trial.nr || participant) + (1 | video.id)
Data: xdata

     AIC      BIC   logLik deviance df.resid 
   -64.9    -36.8     41.4    -82.9      158 

Random effects:

Conditional model:
 Groups      Name           Variance  Std.Dev.  Corr      
 participant (Intercept)    1.877e-01 4.333e-01           
             condition.code 4.387e-09 6.623e-05 0.00      
             z.trial.nr     4.113e-12 2.028e-06 0.00 0.00 
 video.id    (Intercept)    9.949e-15 9.974e-08           
Number of obs: 167, groups:  participant, 48; video.id, 8

Dispersion parameter for beta family (): 4.82 

Conditional model:
                         Estimate Std. Error z value Pr(>|z|)    
(Intercept)              -0.84550    0.12007  -7.042  1.9e-12 ***
conditioninco             0.25928    0.13352   1.942   0.0522 .  
z.trial.nr               -0.10040    0.09936  -1.010   0.3123    
conditioninco:z.trial.nr -0.19005    0.14223  -1.336   0.1815    

Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

## Null Model: 

```r
glmmTMB (proportion_looking_time ~ z.trial.nr +
                                                    (1 + condition.code + z.trial.nr || participant) + 
                                                    (1 |video.id), 
                                                  family=beta_family,
                                                  data=xdata)

Warning message:
In fitTMB(TMBStruc) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
```

## Reduced Model

```r
glmmTMB (proportion_looking_time ~ condition + z.trial.nr +
                                                   (1 + condition.code + z.trial.nr || participant) + 
                                                   (1 |video.id), 
                                                 family=beta_family,
                                                 data=xdata)

Warning message:
In fitTMB(TMBStruc) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
```

If you need any more information, please let me know. I am happy about any suggestion! 
Thank you!

**Comment by bbolker** [comment]
Sorry to take so long to respond. In the first (full) model, it's clear that your model is mostly singular: the variances for all but the participant intercept term (first row of the random effects output) are tiny.   It's not clear why `glmmTMB` still succeeds in getting a positive-definite Hessian, but I would strongly consider simplifying the random-effects terms to *only* `(1|participant)` before proceeding.

You can use calls like `update(full_model, . ~ . - cocondition:z.trial.nr)` or  `update(full_model, . ~ . - condition - condition:z.trial.nr)`  to get the simplified models.

If you still have non-pos-def warnings after simplifying the random effects, please (1) run `diagnose()` on the fitted model and see if it helps and (2) post your question to [Cross Validated](https://stats.stackexchange.com) or `r-sig-mixed-models@r-project.org`, as this is really a question about how to proceed with modeling than (IMO) pointing out a bug or infelicity in `glmmTMB` (see https://glmmtmb.github.io/glmmTMB/#where-to-ask-questions)

**Comment by MCP95** [comment]
Hi!

thank you very much for your reply! I will try to run the model as you suggested and apply your solutions. Sorry for posting the question in the wrong pository! 

Best,
Maria
