### ISSUE TITLE
PartialMatch Warnings

### ISSUE THREAD

**Issue by LGraz** [glmmTMB/glmmTMB#949]
Thanks for this nice project.

in the source code you seem to use partial matching at several places.

## To reproduce run:
```r
options(warnPartialMatchArgs = TRUE)
options(warnPartialMatchAttr = TRUE)
options(warnPartialMatchDollar = TRUE)
example(glmmTMB)   # gives many warnings

options(warnPartialMatchArgs = FALSE)
options(warnPartialMatchAttr = FALSE)
options(warnPartialMatchDollar = FALSE)
example(glmmTMB)  # no warnings
```

Please tell me if you wish me to fix this with (my first open source) PR.

**Comment by bbolker** [comment]
Sure, that would be great! (I'm a little surprised that CRAN hasn't yelled at us about this before ...)

**Comment by LGraz** [comment]
In the end, I decided not to fix this, since it seems to be a rather common issue with CRAN packages. 

Apparently, one is not supposed to turn these warnings on :)
