### ISSUE TITLE
Gaussian dispformula specification with SD vs variance

### ISSUE THREAD

**Issue by bwiernik** [glmmTMB/glmmTMB#955]
Is there any way to fit the linear model in `dispformula` to `log(sqrt(V))` rather than `log(V)`? The immediate practical interest is in comparing results with other packages that specify Gaussian dispersion in terms of sigma rather than sigma^2.

If not, would you be open to a PR added a `gaussian2()` family that uses an SD dispersion specification rather than a variance dispersion specificiation?

**Comment by ASKurz** [comment]
Yes please.

**Comment by bbolker** [comment]
This was discussed somewhere recently, but I can't find it (@mebrooks, @kaskr, do you remember?).  I think that this would be automatically handled by changing the internal specification, which (IIRC) is *different* for Gaussian than for any of the other distributions, to be more consistent with the other distributions. The only reasons *not* to do this (again, IIRC) are

* breaking backward compatibility (I don't know whether it would be useful to add an option for back-compatibility somewhere?)
* "Chesterton's fence", i.e. trying to understand/remember what the original reason was for parameterizing the Gaussian differently from the other distributions/families ...

I would personally prefer to make this change than to add another family.

**Comment by mebrooks** [comment]
We were discussing it on the `lognorm_dist` branch, but I think the discussion may have disappeared when we merged and deleted the branch (slightly annoying GitHub behavior). The things I know that would be broken are a test and a teaching video that use something similar to [this example](https://github.com/glmmTMB/glmmTMB/blob/bd625cad51392fee7086b6c832c6bfdd8a9114d4/glmmTMB/R/glmmTMB.R#L1037). I think @skaug is currently using the teaching video in a private class now and then we plan to share them openly. So I'd need to re-record the video (at DTU instead of UiB), but I don't mind doing that in early 2024.

**Comment by bwiernik** [comment]
Here is that discussion https://github.com/glmmTMB/glmmTMB/pull/921

**Comment by bwiernik** [comment]
The only thing that comes to mind regarding why the variance might have been chosen is that the base `gaussian()` family specifies `variance` as a unit vector with length equal to `length(mean)`

**Comment by bbolker** [comment]
@kaskr @skaug @mebrooks should I go ahead and make a branch that does this?

**Comment by mebrooks** [comment]
I'm OK with the change if everyone else is. Any other opinions? @mmaechler ?

**Comment by bbolker** [comment]
Starting working on this [here](https://github.com/glmmTMB/glmmTMB/tree/reparam_gauss_family).  The basic implementation is done, but I (or someone!) has to work through the remainder of the test breakage, write a NEWS entry, etc ...

**Comment by bbolker** [comment]
Remaining issues (at least):

* weird problems when retrieving/updating `fm_ar1` from stored models (first element of `theta` changes ... ???)
* still need to check/understand logic of Pearson residuals for Gaussian models. Why should response == Pearson for Gaussian? (has to do with whether we are dividing by scaled or unscaled variance function ... ?? to match glm/lm we do have to divide by unscaled variance function ...)

**Comment by ASKurz** [comment]
Loving this progress

**Comment by bwiernik** [comment]
Using version number to keep `up2date()` idempotent is a great idea.

**Comment by bbolker** [comment]
pulled in f6f0d98fb

**Comment by bbolker** [comment]
closed ...

**Comment by bwiernik** [comment]
Thanks for doing this! This is great!
