### ISSUE TITLE
dispformula = ~ 0 for more families

### ISSUE THREAD

**Issue by hrlai** [glmmTMB/glmmTMB#957]
Hi there, not sure if an issue like this had been raised before, but I was playing around with the covariance structure on non-Gaussian data following https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html 

Say we are dealing with count data with the negative binomial, how would we get the following model to work? When I do something like
```
fit.gau <- glmmTMB(y ~ gau(times + 0 | group), data=dat1, dispformula=~0, family = "nbinom2")
```
I get the message :-(
```
Error in mkTMBStruc(formula, ziformula, dispformula, combForm, mf, fr,  : 
  ~0 dispersion not implemented for ‘nbinom2’ family
```

Is this something on the to-do list for the foreseeable future...? I'd really like to leverage more on the covariance capability of `glmmTMB`!

**Comment by bbolker** [comment]
What are you trying to achieve with `dispformula = ~ 0` ?  You can't really have a "pure" (spatial or temporal) autoregressive model with anything other than a Gaussian response.  If you get rid of `dispformula = ~0`, you'll get latent Gaussian autocorrelation on the log scale, with negative binomial variation overlaid. (You could also choose a Poisson conditional distribution, which would give you something like a Poisson-logNormal latent model ...)

**Comment by bbolker** [comment]
Any further comment on this?  Otherwise, I may close it (you can request that it be re-opened if you like ...)

**Comment by hrlai** [comment]
Feel free to close it for now. I’m digesting your quick tips here and was going to comment further using simulated data, but ran out of time. If I manage to get back to it, will follow up :) On 29 Oct 2023, at 14:58, Ben Bolker ***@***.***> wrote:﻿
Any further comment on this?  Otherwise, I may close it (you can request that it be re-opened if you like ...)
