### ISSUE TITLE
Installing glmmTMB in docker

### ISSUE THREAD

**Issue by yshao-amplify** [glmmTMB/glmmTMB#960]
Hello!

I've been unsuccessful in trying to install glmmTMB in a docker container on CentOS7 on R 4.2.2
`RUN Rscript -e "install.packages('glmmTMB', type='source')"`. 

I was able to load `lme4` without issue. 

But when I install glmmTMB, it first gives a number of Eigen warnings, like this:

> /opt/R/4.2.2/lib/R/library/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h:537:19:   required from ‘Eigen::PlainObjectBase<Derived>::PlainObjectBase(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Product<Eigen::Matrix<double, 2, 8, 0, 2, 8>, Eigen::Matrix<double, 8, 1, 0, 8, 1>, 0>; Derived = Eigen::Matrix<double, 2, 1>]’
> /opt/R/4.2.2/lib/R/library/RcppEigen/include/Eigen/src/Core/Matrix.h:377:29:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::Product<Eigen::Matrix<double, 2, 8, 0, 2, 8>, Eigen::Matrix<double, 8, 1, 0, 8, 1>, 0>; _Scalar = double; int _Rows = 2; int _Cols = 1; int _Options = 0; int _MaxRows = 2; int _MaxCols = 1]’
> /opt/R/4.2.2/lib/R/library/TMB/include/tiny_ad/atomic.hpp:30:1:   required from ‘void atomic::bessel_kOp<order, ninput, noutput, mask>::reverse(TMBad::ReverseArgs<Type>&) [with Type = double; int order = 3; int ninput = 2; int noutput = 8; long int mask = 9]’
> /opt/R/4.2.2/lib/R/library/TMB/include/TMBad/global.hpp:1721:28:   required from ‘void TMBad::global::AddForwardMarkReverseMark<OperatorBase>::reverse(TMBad::ReverseArgs<Type>&) [with Type = double; OperatorBase = TMBad::global::AddIncrementDecrement<TMBad::global::AddDependencies<TMBad::global::AddInputSizeOutputSize<atomic::bessel_kOp<3, 2, 8, 9> > > >]’
> /opt/R/4.2.2/lib/R/library/TMB/include/TMBad/global.hpp:2134:47:   required from ‘void TMBad::global::Complete<OperatorBase>::reverse(TMBad::ReverseArgs<double>&) [with OperatorBase = atomic::bessel_kOp<3, 2, 8, 9>]’
> glmmTMB.cpp:941:1:   required from here
> /opt/R/4.2.2/lib/R/library/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(2) double}’ [-Wignored-attributes]

then aborted with this error after a few minutes:
```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [glmmTMB.o] Error 4
ERROR: compilation failed for package ‘glmmTMB’
* removing ‘/opt/R/4.2.2/lib/R/library/glmmTMB’

The downloaded source packages are in
	‘/tmp/RtmpmIn8tb/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("glmmTMB") :
  installation of package ‘glmmTMB’ had non-zero exit status
```

appreciate any thoughts!

**Comment by bbolker** [comment]
I don't know -- my only initial thought is that if you add a `~/.R/Makevars` file containing (at least) the line `CXXFLAGS += -Wno-ignored-attributes`, that will suppress a whole lot of chaff to make it easier to see the real errors ...

Can you see if it's possible to install and run the examples of the `TMB` package in your container, so that we can see if the problem is `glmmTMB`-specific?  i.e. something like

```
RUN Rscript -e "install.packages('TMB', type='source')"
RUN Rscript -e "TMB::runExample(all=TRUE)"
```

?

**Comment by yshao-amplify** [comment]
@bbolker TMB installs fine and the runExample also works.

**Comment by bbolker** [comment]
OK (too bad - I was hoping to get away with kicking the problem over to the TMB folks).  Can you please set up your `~/.R/Makevars` file to suppress unnecessary warnings and then copy/paste (or attach a text file, I think GitHub will let you do that?) the *complete* error output from the installation attempt? (@kaskr, I may need help here ...)

**Comment by kaskr** [comment]
I seem to remember that `g++: internal compiler error: Killed (program cc1plus)` may happen when gcc runs out of memory? Perhaps try increasing the limit?

**Comment by yshao-amplify** [comment]
I increased the memory and it worked! Thank you.
