### ISSUE TITLE
SD of the random intercept for beta glmmtmb

### ISSUE THREAD

**Issue by Franelizabethgalvez** [glmmTMB/glmmTMB#963]
I am trying to understand the SD of the random intercept of my summary of this beta adjusted logit model. 

```
Family: beta  ( logit )
Formula:          FvFm ~ hora * temperatura + (1 | Experimento)
Data: d

AIC      BIC   logLik deviance df.resid 
  -730.4   -711.2    371.2   -742.4      174 

Random effects:
Conditional model:
  Groups      Name        Variance Std.Dev.
Experimento (Intercept) 0.0099   0.0995  
Number of obs: 180, groups:  Experimento, 5

Dispersion parameter for beta family ():  262 

Conditional model:
                                      Estimate Std. Error z value Pr(>|z|)   
                 (Intercept)    0.26960    0.04821    5.59 2.24e-08 ***
                          hora4    0.03181    0.02627    1.21   0.2260    
           temperatura20   0.05626    0.02630    2.14   0.0324 * 
hora4:temperatura20 -1.44971    0.03859  -37.56  < 2e-16 ***
```

If I invert this SD (0.0995), I get 0.524, a value that is very close to the mean of all the experiments (0.57). The difference is 0.046, indicating that the heterogeneity between the experiments is quite small. Was this interpretation correct? any suggestions are welcome, 
Thank you!!!

**Comment by bbolker** [comment]
Hi @Franelizabethgalvez,

I'm not sure what you mean by "inverting" the SD: it looks like you are computing `plogis(SD)`, which is actually not meaningful in this case (to convert a SD from the linear predictor/link scale to the data/response scale you actually need to multiply by the derivative of the inverse link function ...).  Therefore, I think any match between `plogis(SD)` and some other value is coincidental.  To interpret heterogeneity, you should compare the magnitude of the SD to the magnitude of the fixed-effect coefficients. It looks like your predictor variables are categorical/factor, so we could make a statement like "on the log-odds scale the SD of the difference in the intercept between experiments is approximately 0.1, which is small relative to the magnitude of the interaction term (-1.4) but large relative to the magnitude of the main effects (~ 0.05)".

Statistical/interpretation questions are better suited for the `r-sig-mixed-models@r-project.org` mailing list or [Cross Validated](https://stats.stackexchange.com) (see https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions), so I'm going to close this issue, but please feel free to follow up in one of those venues.

**Comment by Franelizabethgalvez** [comment]
@bbolker thank you again for your time!!
