### ISSUE TITLE
Using cbind vs. weights specification for proportion gives different r-square in model results

### ISSUE THREAD

**Issue by milkweedgirl** [glmmTMB/glmmTMB#966]
I recently ran 2 models comparing the results of using cbind to specify my binomial  versus using the weights argument to specify proportion and found a huge difference in the r square between the 2 models. As I thought these were equivalent what is causing this difference and which result should I trust? It seems that maybe using cbind is not appropriate in glmmTMB based on other reports?

For reference the propgerm is equivalent to germ_2022 (# germinated seeds ) divided by n or number planted (25). For weights- "total"= 25 for each observation. 

```
red <- glmmTMB(propgerm ~ sdm + cage + soilcat + gapcat + rh_diff + temp_diff
              + cage:soilcat + cage:gapcat + soilcat:gapcat
              + gapcat: temp_diff+  (1|site/plotID), family=binomial, 
              weights = total, data = data)

red2 <- glmmTMB(cbind(germ_2022,total-germ_2022) ~ sdm + cage + soilcat + gapcat
    + rh_diff + temp_diff+ cage:soilcat + cage:gapcat + soilcat:gapcat
          + gapcat: temp_diff+  (1|site/plotID), family=binomial, data = data)

r.squaredGLMM(red)
r.squaredGLMM(red2)
```

For my red model the variance explained using the Mumin package is 42% whereas the cbind method gives me 94% (conditional)! This is a pretty big difference!

**Comment by bbolker** [comment]
I don't know.  I can confirm that these are different in a reproducible example, but I think I would attribute this to/blame this on whatever the `MuMIn` package is doing to compute the R^2 ...

```r
library(glmmTMB)
library(MuMIn)

data("cbpp", package = "lme4")
m1 <- glmmTMB(cbind(incidence, size - incidence) ~ period + (1|herd),
              family = binomial, data = cbpp)
m2 <- update(m1, incidence/size ~ ., weights = size)
stopifnot(all.equal(fixef(m1), fixef(m2)))
stopifnot(all.equal(logLik(m1), logLik(m2)))

r.squaredGLMM(m1)

                  R2m       R2c
theoretical 0.3538875 0.7760638
delta       0.2633137 0.5774385

r.squaredGLMM(m2)

r.squaredGLMM(m2)
                   R2m        R2c
theoretical 0.08541602 0.18731456
delta       0.03799099 0.08331301
```

**Comment by milkweedgirl** [comment]
Thanks for the speedy response Ben! Would you caution against using Mumin package then to calculate R2 for glmmTMB and stick with the performance method for cbind models?

**Comment by bbolker** [comment]
That sounds right, although it would also be good to contact the package maintainer (`maintainer("MuMIn")`) and point them to this issue (the [CRAN page for this package](https://cran.r-project.org/package=MuMIn) doesn't specify a particular bug-reporting venue ...)

**Comment by milkweedgirl** [comment]
I am just looking for some follow-up verification on R2 but is the R2 value reported for a binomial glmm pseudo-R2? Also are these values reported accurate if your model has zero inflation (specified with ziformula=~1)?

**Comment by bbolker** [comment]
Please ask these questions in a `performance` package venue, e.g. https://github.com/easystats/performance/issues, if [this write-up](https://easystats.github.io/performance/#r-squared) doesn't answer your questions ...

**Comment by k-barton** [comment]
According to [Nakagawa et al. (2017)](https://doi.org/10.1098/rsif.2017.0213), the observation-level variance used in R2GLMM for the binomial distribution is `1 / (n*p(1 – p))`, where `p` is the proportion of successes and `n` is the number of trials. MuMIn's `r.squaredGLMM` (mistakenly) assumes 'n = 1' when the response is a proportion and takes `n` as the mean of row sums of `y` when the response is a matrix of counts, which is consistent with the Nakagawa et al's formula. It appears that `performance::r2_nakagawa` assumes `n = 1` in all cases.
