### ISSUE TITLE
compois family not finishing

### ISSUE THREAD

**Issue by Phome95** [glmmTMB/glmmTMB#967]
Hello,

I am attempting to fit a conway-maxwell poisson glmm as my previous genpois and poisson models were underdispersed, however even after around 12 hours the model does not finish it's fit. I saw that another user had a similar issue :https://stats.stackexchange.com/questions/450377/issues-with-conway-maxwell-poisson-family-in-glmmtmb

Granted my dataset is quite large at 45,000 rows in my dataframe, but with 16gb RAM I thought I would be ok, could it be a problem with the compois family?

thanks for your help!

**Comment by bbolker** [comment]
There's really not much specific that we can do here.  The generic advice: you could try

* parallelizing (set `option(glmmTMB.cores = <ncores>)` or run with `control = glmmTMBControl(parallel = <ncores>)`
* use `genpois` or quasi-likelihood instead

As always, it would be worth benchmarking with some smaller subsets of your data to get an estimate of how long it would take (e.g. if you project that the full data set will take 20 hours to fit, that might be worth it ... at least to compare COM-Poisson fits with quasi-likelihood/genpois to see if a quicker method would be acceptable ...

**Comment by bbolker** [comment]
I [answered the CV question](https://stats.stackexchange.com/a/632836/2126); in that case, their data were actually overdispersed, which is a worst-case scenario for COM-Poisson fitting speed.  In addition to parallelization (illustrated in my answer), you can also get some idea of how the fitting is going by specifying `verbose = TRUE` and/or 
`control = glmmTMBControl(optCtrl = list(trace = 1))` (the output from the latter is less detailed but, I find, more useful: `verbose=TRUE` gives you lots of information about the *internal* computation steps used by `TMB`).

I'm going to close this issue, but feel free to re-open if you want to continue the conversation.

**Comment by Phome95** [comment]
Thank you, I will give that a go and report back

**Comment by Phome95** [comment]
Is it possibly due to the number of levels within my dataset? My data is looking at roads as groups (6600) with n=45000
