### ISSUE TITLE
Models won't converge under new glmmTMB version but did under the old one

### ISSUE THREAD

**Issue by btojenniferborder** [glmmTMB/glmmTMB#968]
HI, I had some models which were running fine up until about September this year. However, I recently tried to re-run them, as I had comments back from reviewers on a paper using the models. The models now would not run and gave the error:  

Error in fitTMB(TMBStruc) : negative log-likelihood is NaN at starting parameter values

Following some instructions I found online here: https://stackoverflow.com/questions/77466641/error-in-fittmbtmbstruc-negative-log-likelihood-is-nan-at-starting-parameter

I tried re-instaling glmmTMB and using: tools::package_dependencies("Matrix", which = "LinkingTo", reverse = TRUE)[[1L]]

Now the models run but won't converge:

Warning messages:
1: In (function (start, objective, gradient = NULL, hessian = NULL,  :
  NA/NaN function evaluation
2: In finalizeTMB(TMBStruc, obj, fit, h, data.tmb.old) :
  Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
3: In finalizeTMB(TMBStruc, obj, fit, h, data.tmb.old) :
  Model convergence problem; false convergence (8). See vignette('troubleshooting'), help('diagnose')

I don't know which version of glmmTMB I had before the update now, but it was probably 1.1.6 or 1.1.5. Do you knwo which version of that and matrix I would need to make my models converge as they used to? It's tricky as I'm doing copmments for a paper and so I don't want to change the models as they worked in the version I had reviewed.

Thanks!

**Comment by bbolker** [comment]
I'm not sure how much we're going to be able to help.  You could experiment with the [groundhog package](https://groundhogr.com/) to work with earlier versions of packages (I don't know how far back it goes, but it's worth a try). Another thing you could try would be to use a different optimizer (see the example in the `?glmmTMBControl` help page) ...

**Comment by btojenniferborder** [comment]
Thanks for the reply. I've now found the version of glmmTMB I originally used that the models converge in, it's 1.1.3. Just out of interest, were there any big changes to the way the covariance matrices were calculated or anything after that. I'm just wondering why in other versions they don't converge. I have a gau covariance structure to account for spatial autocorrelation which seems to cause the convergence issues.

**Comment by bbolker** [comment]
No, there weren't any big changes that I'm aware of.  It's surprisingly easy for *small* changes in many different parts of the machinery (OS, compiler, code, etc.) to tip a given model from converging to non-converging, and tracking down the details can be **extremely** time consuming.  Looking at the [NEWS file](https://cran.r-project.org/web/packages/glmmTMB/news.html), this is the only *documented* change that seems to be a potential cause (from version 1.1.5):

> glmmTMB has switched to using a different (newer, under active development) autodifferentiation library under the hood (from CppAD to TMBad). This is likely to lead to small changes in estimates, including tipping marginally stable computations to instability or vice versa (e.g. presence or absence of convergence warnings, positive-definite Hessian warnings, NaN values of standard errors, etc.) You can revert to using the older autodiff engine by commenting out the line PKG_CPPFLAGS = -DTMBAD_FRAMEWORK in src/Makevars and reinstalling the package (make sure to delete .o/.so files from the src directory first if installing from the package directory, as the Makefile doesn't recognize know that this change requires recompilation). 

If you were curious you could see if this was the culprit (it would require downloading the source tarball, making the change described above, and re-installing from source ...)

(It's always *possible* that we made some other small change that would have slightly modified the computational machinery, and forgotten to document it, but this definitely seems like the most likely culprit ...)

I'm going to close this, although you can re-open if you feel the need to follow up.
