### ISSUE TITLE
Missing data handling in glmmTMB

### ISSUE THREAD

**Issue by bwalsh10** [glmmTMB/glmmTMB#971]
I am running a series of models using glmmTMB package (binomial and truncated negative binomial). I understand that the default handling of missing data is listwise deletion, but I was wondering if there is any way to implement full information maximum likelihood?

**Comment by bbolker** [comment]
Not easily.  I know roughly what FIML is, but I've never looked into how it's implemented - I wouldn't even know where to start.  I'm sure it's feasible in principle (the underlying engine of glmmTMB can compute essentially any objective function with continuous derivatives), but it would only happen if someone was interested in doing the (presumably very considerable) amount of work to implement it.  I would be happy to help such a person with technical advice ...

In the absence of FIML, I would suggest that you could try multiple imputation (e.g. via the `mice` package), which is less computationally efficient but has the advantage of being a "wrapper" method, meaning that it can be used on top; for example, [this page](https://github.com/amices/mice/issues/219) shows an example of `mice` being used with `glmmTMB`.
