### ISSUE TITLE
compois lambda and nu parameters

### ISSUE THREAD

**Issue by JWilson2021** [glmmTMB/glmmTMB#972]
How would one go about estimating `lambda` and `nu` parameters from a `glmmTMB` model with a `compois` family? From what I've been reading, there isn't an easy way to do it by hand. The COMPoissonReg package does this via the `link` prediction type ([see here](https://cran.r-project.org/web/packages/COMPoissonReg/vignettes/vignette.pdf), bottom of page 20), but I need to use a random variable, and was really hoping to stick with `glmmTMB`.
This question was raised [on SO](https://stackoverflow.com/questions/76625373/how-to-extract-lambda-and-nu-parameters-from-glmmtmb-conway-maxwell-poisson-regr) a few months ago, with no answers...

**Comment by mebrooks** [comment]
I answered over on SO since there was more context and that's a more [appropriate place to ask](https://github.com/glmmTMB/glmmTMB#where-to-ask-questions) this type of question.
