### ISSUE TITLE
Help needed fitting a general latent variable model in glmmTMB

### ISSUE THREAD

**Issue by Max-Muehlenhaupt** [glmmTMB/glmmTMB#984]
Hi,
I am trying to fit a model similar to the one presented in this vignette: https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html#reduced-rank as I was suggested to do this by a statistician.

The data I have is area under the curve following spectrometry analysis of toad toxin secretions. 15 different compounds have been identified in the secretions of all toads and I would like to find out if there are differences in the composition of the secretions (i.e., more of a specific toad toxin) in the secretions of toads from specific locations (4 different locations). I have formatted my data set into long format.

```
> head(toxins)
# A tibble: 6 × 6
  Toad_ID Location  Sex    log10SVL Toxin  Area
  <chr>   <chr>     <chr>     <dbl> <chr> <dbl>
1 CU195   Cape_Town female     1.93 TT7    494.
2 CU195   Cape_Town female     1.93 TT8    192.
3 CU195   Cape_Town female     1.93 TT9   1100.
4 CU195   Cape_Town female     1.93 TT10   544.
5 CU195   Cape_Town female     1.93 TT12   305.
6 CU195   Cape_Town female     1.93 TT14  1167.
> str(toxins)
tibble [600 × 6] (S3: tbl_df/tbl/data.frame)
 $ Toad_ID : chr [1:600] "CU195" "CU195" "CU195" "CU195" ...
 $ Location: chr [1:600] "Cape_Town" "Cape_Town" "Cape_Town" "Cape_Town" ...
 $ Sex     : chr [1:600] "female" "female" "female" "female" ...
 $ log10SVL: num [1:600] 1.93 1.93 1.93 1.93 1.93 ...
 $ Toxin   : chr [1:600] "TT7" "TT8" "TT9" "TT10" ...
 $ Area    : num [1:600] 494 192 1100 544 305 ...
```

So far, I've been log(x+1) transforming my y variable to fit a glmm with gaussian family:

```
fit_g1a <- glmmTMB(log(Area+1) ~ Location * Sex + 
                   rr(Location |Toxin, d = 2) + rr(Toxin|Toad_ID, d = 2),
                 data = toxins)
```
I'm especially interested in the `Location |Toxin` term to see if specific toxins occur in higher amounts in toads of specific locations.
After some model selection based on AIC, I decided on this model:

```
fit_g2c <- glmmTMB(log(Area+1) ~ Location + Sex + 
                     rr(Location |Toxin, d = 4) + rr(Toxin|Toad_ID, d = 2),
                   data = toxins)
```

The fixed effect of Location is controlling for general differences in area under the curve between locations (it seems that toads from the first location have generally more toxin than from the other locations and therefore the area under the curve from the spectrometry is generally higher for toads from this location. The Sex fixed effect checks for general differences between the sexes.  The random intercept of Toad_ID controls for inter-dependence, the random slope for Toxin accounts for the correlations among Toxins. Lastly, we have the Location |Toxin random effect which is supposed to tell me which toxins occur more prominent in which locations. Using anova() determined that a model with the Location |Toxin term is providing a significantly better fit than a model without the term. However, when I want to see which specific toxins are more prominent in which locations using
`ranef(fit_g2c) and plot_model(fit_g2c, type = "re", show.values = TRUE)`, I see that the estimates for my fourth location are very small:
```
$Toxin
     (Intercept) LocationMauritius LocationReunion LocationCape_Town
TT10  -0.9671358         0.6877188      1.47336824      1.205429e-06
TT12  -0.4091168         0.4425725     -1.32286924      5.852014e-06
TT14  -0.7891181        -0.7838166      1.01857989     -1.541306e-07
TT16   0.4410460        -0.4826110     -0.50307829     -2.788336e-06
TT18  -0.2660568        -1.1611358     -0.03094444     -3.073159e-06
TT19   1.1873699        -0.2000598     -0.46025354     -2.741581e-07
TT20   1.1835372         0.2719932      0.40175692     -7.958919e-08
TT22   1.8972002         0.5311096      0.79150775      2.277659e-06
TT23  -0.8726360        -0.8476109     -1.73618011      3.216233e-06
TT24  -0.1601007        -2.2621117      0.73948689     -4.943835e-06
TT25   0.5144228         0.2036495     -0.69332780     -1.714787e-06
TT26   1.1307610         0.8049135      0.37142541     -2.392636e-06
TT7   -0.8814806         0.4381274     -0.43754205      6.684454e-07
TT8   -1.8193548         1.2714524      0.65175510     -1.639845e-06
TT9   -0.1890797         1.0857231     -0.26372446      3.840653e-06
```
I find this suspicious as it would suggest that all toxins are evenly distributed in this location which is certainly not the case from looking at the raw data (some toxins make up to 42 % of the entire toxin composition). I have tried using different values for "d" but it did not change the result. 
What could cause this issue? Should i be using a different model formula?

All help is very much appreciated!

Thanks,
Max

**Comment by bbolker** [comment]
This is a reasonable question but I think it belongs on `r-sig-mixed-models@r-project.org` or [Cross Validated](https://stats.stackexchange.com); see ["Where to ask questions"](https://github.com/glmmTMB/glmmTMB/blob/master/README.md#where-to-ask-questions) on the README.

That said, I'm having a little bit of trouble getting my head around a `Location | Toxin` random effect: if you want to allow for variation in toxins across locations, and account for correlations in the toxin assemblage, wouldn't you use `Toxin | Location` ?  (I'm not saying you're wrong, just that I'm having trouble understanding how your formulation would work ...)

Please follow up in one of the venues suggested ...
