### ISSUE TITLE
Error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by santoshbs** [glmmTMB/glmmTMB#993]
I get this error when I add ar1(0+ time_dummy|id), where time_dummy = factor(time). 

Not sure how to interpret this message.

```
> m = glmmTMB(
+   y ~ time + (1|id) + ar1(0 + time_dummy | id),
+   data = df)

Warning in attributes(.Data) <- c(attributes(.Data), attrib) :
  NAs introduced by coercion to integer range

Error in h(simpleError(msg, call)) (r_v1.R#467): error in evaluating the argument 'x' in selecting a method for function 't': missing value where TRUE/FALSE needed
Show stack trace
```

It works fine when using the following though:

```
m= glmmTMB(
  y ~ time + (1 + time|id),
  data = df)

```

**Comment by bbolker** [comment]
I'm having a hard time reproducing this.  With the example below I get various convergence warnings, but no errors.  Can we have a reproducible example? What is `str(df)`?  What do you get from running `traceback()` after you get the error?

```r
library(glmmTMB)
dd <- expand.grid(time = 1:20, id = factor(1:20))
dd$time_dummy <- factor(dd$time)
dd$y <- simulate_new(~time + (1|id) + ar1(0 + factor(time)|id),
                     seed = 101,
                     newdata = dd,
                     newparams = list(beta = c(2,1),
                                      theta = rep(0,3),
                                      sigma = 1))[[1]]
m = glmmTMB(
   y ~ time + (1|id) + ar1(0 + time_dummy | id),
   data = dd)

m = glmmTMB(
   y ~ time + (1|id) + (1 + time | id),
   data = dd)
```

**Comment by bbolker** [comment]
PS the warning 

> Warning in attributes(.Data) <- c(attributes(.Data), attrib) :
  NAs introduced by coercion to integer range

suggests that you are somehow have very large values somewhere in your data, but I haven't been able to reproduce that particular warning e.g. by making `time = as.numeric(.Machine$integer.max) + 1:20`  (that gives me a different set of warnings/problems).

**Comment by santoshbs** [comment]
@bbolker - Many thanks for your kind response and help. 

It is so weird that I cannot reproduce the warning now. I tried all day yesterday with the same data and code. It runs without any warnings. Not sure what is happening. I hope it was one off case.
