### ISSUE TITLE
Is it possible to use simulate() with ordbeta models in glmmTMB?

### ISSUE THREAD

**Issue by C-Crowther** [glmmTMB/glmmTMB#994]
Hi, 
I'm building an ordered beta regression model in glmmTMB (thanks for implementing this feature btw). I noticed that the simulate() function produces data points that are identical to the real data every time I try to simulate a model with the ordbeta family. 

Here is a simplified version of my code. Simulate works when family='gaussian' but not when family='ordbeta'.

```
#Testing model simulation for the ordbeta family in glmmTMB

#Packages
library(glmmTMB)
set.seed(101)

#Create data
Vec <- c(rep(0, 25), rep(1, 25), runif(50, min=0, max=1))
Y <-sample(Vec)
X <- sample(LETTERS[1:2],100,replace = TRUE)

df <- data.frame(X,Y)

# Ordbeta model
mod.1 <- glmmTMB(Y ~ X, family = "ordbeta",  data = df)
#Simulate data
df$Sim1 <- unlist(simulate(mod.1))

#Gaussian model
mod.2 <- glmmTMB(Y ~ X,  family="gaussian", data = df)
#Simulate data
df$Sim2 <- unlist(simulate(mod.2))
```

Have I made a mistake or is it not possible to use simulate() with ordbeta models in glmmTMB?

I also noticed the same issue that @AustinNash001 encountered (https://github.com/florianhartig/DHARMa/issues/390). simulateResiduals from DHARMa always produces simulated residuals that perfectly fit the predicted values.

E.g.
```
library(DHARMa)
plot(simulateResiduals(mod.1, n = 1000))
```
 
I wonder if this is happens because simulate() replicates the real data when family=ordbeta?

Thanks!

**Comment by bbolker** [comment]
Hmm, I don't know. There is a SIMULATE block defined for this model family ([here](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L687-L701)); we'll have to have a look and see what's going on.

**Comment by C-Crowther** [comment]
Updating R and glmmTMB fixed the issue, thanks very much for the suggestion. Sorry for bothering you with something I definitely should have checked!
