### ISSUE TITLE
glmmTMB does not have function Anova.glmmTMB

### ISSUE THREAD

**Issue by ornithmmoyer** [glmmTMB/glmmTMB#996]
I'm trying to use the published function Anova.glmmTMB, but it does not appear to be present in the v1.1.8 I have downloaded. 

If I run:
lsf.str("package:glmmTMB")
addForm : function (...)  
addForm0 : function (f1, f2)  
beta_family : function (link = "logit")  
betabinomial : function (link = "logit")  

You can see Anova.glmmTMB is not present. I have also tried to add it manually using the source code, but several functions within that function are also missing, including fixef.

**Comment by bbolker** [comment]
`Anova.glmmTMB` is an S3 method whose definition is exported, but the function itself is not. This is true of other S3 methods such as `fixef`.

The general definition of the `Anova` method is in the `car` package, so you may to have that package loaded before you can use it.
In general, me
thods that are not exported aren't supposed to be used by end-users, although you can access them via (e.g. `glmmTMB:::Anova.glmmTMB`.

If you say e.g.

```r
methods("fixef")
[1] fixef.glmmTMB* fixef.lme*     fixef.lmList*  fixef.lmList4* fixef.merMod* 
```
you'll see stars by any methods that are not exported from their namespaces (see `?methods`).

If you can say more specifically what you're trying to accomplish, we can try to help.

**Comment by bbolker** [comment]
In the absence of any further feedback/questions, I'm closing this. Feel free to clarify your question/use-case (i.e., what are you trying to do?) and re-open.
